### ISSUE TITLE
To-fix:TIGER delta 2014

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#100]
The latest [TIGER 2014]() from the US census has lots of new roads that are not currently mapped on OSM. A difference(delta) of OSM and TIGER 2014 road geometries have been processed and loaded in to-fix for manual review.

**Improve the OSM road network of the USA using missing roads and names from TIGER 2014**
Task: [TO-FIX Tiger delta](http://osmlab.github.io/to-fix/?error=unconnected_major#/task/tigerdelta)

- Missing roads
- Misaligned roads
- Missing road names
- [Incorrectly tagged highways](http://wiki.openstreetmap.org/wiki/TIGER_fixup#Wrong_highway_classifications)
- For a full list of TIGER issues, check the [wiki](http://wiki.openstreetmap.org/wiki/TIGER_fixup)

**Sources**
- TIGER 2014 imagery layer `tms:http://{switch:a,b,c}.tiles.mapbox.com/v4/enf.e0b8291e/{zoom}/{x}/{y}.png?access_token=pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJhNVlHd29ZIn0.ti6wATGDWOmCnCYen-Ip7Q`
- Bing
- Mapbox Satellite

**To-fix instructions**
- Once an area has been improved on OSM, mark the issue as `Fixed` to remove it from the queue
- If you feel the area is unclear and would like a different issue, hit `Skip`
- If the issue was incorrectly marked as an error, hit `Not an error` to remove it from the queue

**Warning**
- TIGER data is not always accurate. There are many instances of non existent roads which need to be verified on imagery first. If in doubt, skip the issue.

**Timeline**
- As of June 2015, we have close to 70,000 issues to update. Expected completion at the rate of 20000 issues/week is 20 July 2015.
![screenshot 2015-06-29 16 33 25](https://cloud.githubusercontent.com/assets/126868/8406712/9d279f10-1e7c-11e5-8704-eec78a51916f.png)

**Working Groups**
- [Mapbox data team Peru+India](http://wiki.openstreetmap.org/wiki/Mapbox#Mapbox_Data_Team) @mapbox/team-data

**Comment by ruthmaben** [comment]
Sharing few observations while working on [ TO-FIX Tiger delta](http://osmlab.github.io/to-fix/?error=deadendoneway#/task/tigerdelta)

I am coming across a lot of tasks which are already fixed (I am saving them as fixed).

**Like this**
![screen shot 2015-06-30 at 11 18 12 am](https://cloud.githubusercontent.com/assets/10308123/8425587/cbb24bb6-1f24-11e5-95cc-2d86d18855a3.png)

![screen shot 2015-06-30 at 12 26 43 pm](https://cloud.githubusercontent.com/assets/10308123/8425592/d40f138e-1f24-11e5-8bf6-2edc90d5b522.png)

![screen shot 2015-06-30 at 12 27 56 pm](https://cloud.githubusercontent.com/assets/10308123/8425595/da44e760-1f24-11e5-8e16-aae1df4d8cc4.png)

![screen shot 2015-06-30 at 12 31 14 pm](https://cloud.githubusercontent.com/assets/10308123/8425600/deca831c-1f24-11e5-92cd-865aad112b42.png)

![screen shot 2015-06-30 at 1 01 53 pm](https://cloud.githubusercontent.com/assets/10308123/8425897/41479022-1f28-11e5-9928-a419ef6188a4.png)


cc: @planemad @aaronlidman @mapbox/team-data

**Comment by planemad** [comment]
@ruthmaben This might be because we usually fix all missing roads in an area, more than what was originally highlighted in to-fix.

Not really seeing this as an immediate problem, but its useful to think about how we could remove such issues from the queue. @aaronlidman do you think it is worthwhile to refresh this data every week?

**Comment by planemad** [comment]
**Progress Update**
In one week, @mapbox/team-data  have hit close to 25,000 issues which is amazing progress :rocket: If we keep this up we're all set to reach the finish line on this batch of tiger-delta tasks by **20th July**. 
![screenshot 2015-07-06 15 30 29](https://cloud.githubusercontent.com/assets/126868/8519973/0651a0ea-23f4-11e5-8f95-46104c6c6260.png)

Lets keep our foot on the pedal and run this out!
![](http://media.giphy.com/media/eyDQMSLsPR09a/giphy.gif)

**Comment by planemad** [comment]
**Complete**
Fantastic work @mapbox/team-data 
Team Peru took this right to the finish line on Friday, one week ahead of schedule!

**Comment by planemad** [comment]
@aaronlidman can you point me to instructions on how to load up the next batch of tasks into to-fix?
The CSV file for NY tiger-delata is [here](https://www.dropbox.com/s/zaxlod83f88hnyv/tiger-difference-ny-geohacker.csv?dl=0)

**Comment by shvrm** [comment]
Awesome @mapbox/team-data!

**Comment by samely** [comment]
### Tiger Data Updated
Tiger data was updated so there are 20 250 issues.
![image](https://cloud.githubusercontent.com/assets/10425629/9307338/b0cf81e6-44c3-11e5-8ccd-fe996db9b87c.png)

### Progress Update
In about 10 days we have hit 11 982 issues and if we continue like this we are going to finish all issues in TIGER before **August 21**.
![image](https://cloud.githubusercontent.com/assets/10425629/9307477/5cedde14-44c4-11e5-8e8b-c6fb16f5cfce.png)

**Comment by Rub21** [comment]
@mapbox/india-office @mapbox/peru-office : Yesterday We've finished  20,250 items from Tiger task.
![screenshot from 2015-08-18 08 58 23](https://cloud.githubusercontent.com/assets/1152236/9331910/8c8ddb56-4587-11e5-9a3c-97f36a681ecc.png)

For today 08/18/2015 I've added 37,710 items in Tiger Task. 
![screenshot from 2015-08-18 08 56 43](https://cloud.githubusercontent.com/assets/1152236/9331940/b713c4bc-4587-11e5-9101-b5df7e8258cf.png)

Happy Mapping everyone :+1: 

cc. @lxbarth

**Comment by samely** [comment]
@mapbox/peru-office : 
Tiger task is done! In 4 and a half days we have hit 37,710 issues of this task.

![image](https://cloud.githubusercontent.com/assets/10425629/9478205/02d4f254-4b3c-11e5-8e15-9659afd4ff34.png)

Congratulations Ayacucho team! :dart: 
cc. @lxbarth

**Comment by lxbarth** [comment]
So amazing!
