### ISSUE TITLE
Tracing Routes

### ISSUE THREAD

**Issue by Hedaja** [mapbox/mapping#102]
Nice guide so far
I noticed one thing. I'm not happy with the first picture about tracing with the right amount of detail: https://camo.githubusercontent.com/ada5abee6a5ac0a6d47f329b14b50726fbfbd10a/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f32683333313432513138317030373143314f31342f53637265656e25323053686f74253230323031352d30312d30342532306174253230382e33322e3337253230504d2e706e67
For me the last (recommended) level of details is to rough in the turn. I think the middle and the right picture combined would make the best accuracy. Nodes on straights only if there are any changes and more detailed in turn.

cheers Christian

**Comment by planemad** [comment]
Thanks for the feedback @Hedaja will try an improved visual for this.

**Comment by Hedaja** [comment]
Seems like nothing changed in the meantime :(

**Comment by planemad** [comment]
@Hedaja do you want to create a graphic that we can use to replace the one in the guide?

**Comment by Hedaja** [comment]
If you show me the curve you used I could create an replacement for the 3rd image. Otherwise it would be I could make make a completely new one

**Comment by planemad** [comment]
Feel free to make a new one, there is no reason to use the same curve :)

**Comment by Hedaja** [comment]
This is the form that I would recommend. Same order as yours just with small changes to the right most picture. No nodes on straight parts and more detailed in curves.
The first is a full size image and the second one is scaled to the size you used so far.

Cheers
Christian

![mapbox guide big](https://cloud.githubusercontent.com/assets/693781/10158378/f3a4b3fc-6691-11e5-9738-58ad86a5a525.png)
![mapbox guide original](https://cloud.githubusercontent.com/assets/693781/10158377/f3a4507e-6691-11e5-819f-11fd16acdd02.png)

**Comment by planemad** [comment]
@Hedaja awesome! Updated https://github.com/mapbox/mapping/wiki/How-to-map-X
