### ISSUE TITLE
To-fix: Highway intersects Water

### ISSUE THREAD

**Issue by shvrm** [mapbox/mapping#103]
**Task** http://osmlab.github.io/to-fix/?error=unconnected_major#/task/highwayriverbank

Highways intersecting water polygons indicates issues where:
- Road crosses a water body without a tag specifying the crossing (missing bridges, culvert, fords or layers)
- Outdated water polygons from old imagery that overlaps with new roads
- Bad imports with misplaced water polygons

**Sources**
* Bing
* Mapbox Satellite

**Working Groups**
- [Mapbox data team India](http://wiki.openstreetmap.org/wiki/Mapbox#Mapbox_Data_Team) @mapbox/team-data   during 20-31 July

**Timeline**
- As of July 21, 2015 - there were a total of 215,719 issues requiring review.
![screen shot 2015-07-21 at 10 57 04 pm](https://cloud.githubusercontent.com/assets/8562256/8807779/47f1d43e-2ffc-11e5-8efe-be2365d24966.png)
- This is an ongoing secondary task and the estimated completion is 6 months with community and Mapbox involvement

#### Instructions
- Focus will be on making definite fixes to roads or water geometries that can be verified from imagery
- Skip issues involving imported map data that does not match with satellite imagery

#### Map Features
Familiarize yourself with the following map features and tags:
- [bridge](http://wiki.openstreetmap.org/wiki/Key:bridge)
- [tunnel](http://wiki.openstreetmap.org/wiki/Key:tunnel) and [culvert](http://wiki.openstreetmap.org/wiki/Tag:tunnel%3Dculvert)
- [layer](http://wiki.openstreetmap.org/wiki/Key:layer)
- [pier](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dpier)
- [ford](http://wiki.openstreetmap.org/wiki/Key:ford)
- [ice road](http://wiki.openstreetmap.org/wiki/Key:ice_road)

#### Resources
- https://github.com/mapbox/mapping/wiki/Working-with-To-fix

**Comment by lxbarth** [comment]
@shvrm @ruthmaben @planemad - are yuo guys running an in person training for this?

**Comment by shvrm** [comment]
@lxbarth - on Monday, when we started this task, we gathered as a team while working on issues, and also pulled up issues on the big screen to discuss as a team and find a solution. 

@planemad - I know we talk briefly yesterday about priority of this task. It would nonetheless be good to gather and go through this to-fix task and do a in-person training this morning.

**Comment by planemad** [comment]
@lxbarth @shvrm @ruthmaben 
We don't really know what to expect with these tasks out of the ordinary till we start working on it and issues are surfaced from the team. I think the most important thing for the team to know is what issues should be ignored that we won't fix. Lets start documenting that here.

**Comment by lxbarth** [comment]
> We don't really know what to expect with these tasks out of the ordinary till we start working on it and issues are surfaced from the team.

Exactly. That's why we should be starting such task with a very small team of experienced mappers first to scope it out well.

**Comment by ramyaragupathy** [comment]
Per voice with @mapbox/india-office, we are only dealing with adding bridges, culverts, fords and other alignment work. Problem points touching the lake imports are to be marked as `not an error`. General understanding is that import data is not to be deleted.

**Comment by planemad** [comment]
**Weekly progress**
![screenshot 2015-08-03 10 23 28](https://cloud.githubusercontent.com/assets/126868/9031050/bd6c832c-39c9-11e5-88e2-3b9d3c31b94c.png)
- 7 members from the India data team @mapbox/team-data fixed 3,027 issues in 3 days
- Expected timeline at current speed is 2 months
- There are many issues involving imported misplaced water polygons and waterways that the team decided not to touch. These need to be filtered out.

**Comment by pratikyadav** [comment]
Highway intersects Water task is on a hold for now.

Closing here.
