### ISSUE TITLE
To-fix: Crossing highways

### ISSUE THREAD

**Issue by Rub21** [mapbox/mapping#104]
### Objective

Review and repair highway intersections that are not connected to a node.
### Tasks

**Tasks below are updating everyday from Monday to Friday with the latest errors in OpenStreetMap**
- Major: http://osmlab.github.io/to-fix/#/task/crossingmajorhighways
- Minor: http://osmlab.github.io/to-fix/#/task/crossingminorhighways
#### Changeset comment

```
Adding junction nodes or bridges to overlapping highways using #to-fix https://github.com/mapbox/mapping/issues/104
```
### Coverage

All countries in this list: https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt
### Tools for edition
- If using iD editor, work with [To-Fix web](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)
- If using JOSM, work with [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin)
- Configure your [JOSM-Shortcuts](https://github.com/mapbox/mapping/wiki/JOSM-Shortcuts), particularly `Merge Nodes = M` and `Join Node to Way = J`.
### Instructions
- Connect _level_ intersections of two highways with a node where they are not connected. This excludes bridges and tunnels. Confirm an intersection is level from satellite imagery.
- According to the satellite imagery, add `bridge=yes` and `layer=*` or `tunnel=yes` and `layer=-1`.
- If editing in an actively mapped area, add a note instead of making a fix.
- If satellite imagery isn't clear click on not an error of to-fix
## Common issues

![image](https://cloud.githubusercontent.com/assets/1152236/8833519/bda5b60a-3074-11e5-9342-4648a011f97d.png)
_Add `layer=1` to the bridge_

![image1](https://cloud.githubusercontent.com/assets/1152236/8806362/f2d9f496-2f9b-11e5-8f97-83f73cff4b12.png)
_Join the node to the road_

![image2](https://cloud.githubusercontent.com/assets/1152236/8834208/93750bd4-3078-11e5-9e19-47003b9bb005.png)
_Add `tunnel=yes` and `layer`=-1_

![image3](https://cloud.githubusercontent.com/assets/1152236/8806289/985f6fb4-2f9b-11e5-9c2e-78e72159b239.png)
_Add a node to connect both roads_
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
## Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data @lxbarth @aaronlidman

**Comment by Andygol** [comment]
@mapbox/peru-office 
I working on Hyderabad - fixing huge amount of errors so you may avoid it in tofix tasks
https://github.com/mapbox/data/issues/1215
![screenshot 2015-07-14 15 02 22](https://cloud.githubusercontent.com/assets/126868/8670548/a9aa9894-2a3b-11e5-83ab-878103ee5d10.png)
https://www.openstreetmap.org/#map=12/17.4135/78.5365

**Comment by samely** [comment]
Today @mapbox/peru-office is starting to work in this task.

![image](https://cloud.githubusercontent.com/assets/10425629/9477886/28df7d7c-4b3a-11e5-8500-48a155485827.png)
Happy mapping :rocket:
cc. @lxbarth

**Comment by samely** [comment]
@Rub21 has updated issues in this task, so we the status is: 

![image](https://cloud.githubusercontent.com/assets/10425629/10591687/25ee2302-767d-11e5-8015-902be9767a6f.png)

**Comment by Rub21** [comment]
### Updates 

We've added  76,182  issues on 03/08/2016, the detection was made using [osmlint](https://github.com/osmlab/osmlint).

**Comment by Rub21** [comment]
# Update 28/03/2016
-  Added errors `76,182`  for major highways around the world. 
-  Source : osmlint
-  To-fix task: http://osmlab.github.io/to-fix/#/stats/crossingmajorhighways

**Comment by samely** [comment]
Well done team! :rocket: :rocket: :rocket:
![image](https://cloud.githubusercontent.com/assets/10425629/14221936/80cbfcf6-f830-11e5-88fe-00dc0340f713.png)

**Comment by shvrm** [comment]
Great work guys! :boom:

**Comment by ruthmaben** [comment]
Nice work :clap:  @mapbox/peru-office!

**Comment by pratikyadav** [comment]
Great work team 🚀 
Closing here.

**Comment by Rub21** [comment]
### Osmlint for the error detection
https://github.com/osmlab/osmlint/tree/master/validators/crossingHighways

**Comment by calfarome** [comment]
##### [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways) issues from 06/20/2016 - 06/24/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 61  | 0 |
Tuesday 21st, June  | 95 | 54 |
Wednesday 22nd, June | 10 | 4 |
Thursday 23rd, June | 38 | 7 |
Friday 24th, June | 129 | 52 |
**Total** | -- | **117** | 

##### [Crossing minor highways](http://osmlab.github.io/to-fix/#/task/crossingminorhighways) issues from 06/20/2016 - 06/24/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 66  | 0 |
Tuesday 21st, June  | 123 | 68 |
Wednesday 22nd, June | 28 | 12 |
Thursday 23rd, June | 45 | 18 |
Friday 24th, June | 1311 | 942 |
**Total** | -- | **1040** |

**Comment by RichRico** [comment]
##### Progress [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways) issues from 06/27/2016 - 07/01/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 127 | 76 |
Tuesday 21st, June  | 32 | 13 |
Wednesday 22nd, June | 45 | 13 |
Thursday 23rd, June | 25 | 0 |
Friday 24th, June | 24 | 19 |
**Total** | -- | **121** | 

##### Progress [Crossing minor highways](http://osmlab.github.io/to-fix/#/task/crossingminorhighways) issues from 06/27/2016 - 07/01/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 282  | 215 |
Tuesday 21st, June  | 38 | 21 |
Wednesday 22nd, June | 37 | 21 |
Thursday 23rd, June | 21 | 0 |
Friday 24th, June | 143 | 66 |
**Total** | -- | **323** |

**Comment by karitotp** [comment]
##### Progress [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways) issues from 07/04/2016 - 07/08/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 04th, July | 135 |71 |
Tuesday 05th, July  |36  |19  |
Wednesday 06th, July | 81 |30 |
Thursday 07th, July |45  |45 |
Friday 08th, July | 43 |23  |
**Total** | -- | **188** | 

##### Progress [Crossing minor highways](http://osmlab.github.io/to-fix/#/task/crossingminorhighways) issues from 07/04/2016 - 07/08/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 04th, July | 167 |0 |
Tuesday 05th, July  | 109 |71  |
Wednesday 06th, July | 96 |14 |
Thursday 07th, July | 27 |27 |
Friday 08th, July |64  |34  |
**Total** | -- | **146** |

**Comment by dannykath** [comment]
##### Progress [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways) issues from 07/11/2016 - 07/14/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July | 23 |23 |
Tuesday 12th, July  | 68 |68  |
Wednesday 13th, July | 34 |3 |
|**Total** | -- | **94** | 

##### Progress [Crossing minor highways](http://osmlab.github.io/to-fix/#/task/crossingminorhighways) issues from 07/11/2016 - 07/14/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July | 3020 |-- |
Tuesday 12th, July  | 3107 |2119  |
Wednesday 13th, July | 2118 |-- |
|**Total** | -- | **2119** |

**Comment by luiswalter** [comment]
##### Progress [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways) issues from 07/18/2016 - 07/22/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 18th, July | 61 |26 |
Wednesday 20th, July | 152 |95 |
Thursday 21th, July | 45 |25 |
|**Total** | -- | **146** | 

##### Progress [Crossing minor highways](http://osmlab.github.io/to-fix/#/task/crossingminorhighways) issues from 07/18/2016 - 07/22/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 18th, July | 16,955 | 13,470 |
Tuesday 20th, July  | 3,485 | 2,523  |
|**Total** | -- | **15,993** |

**Comment by samely** [comment]
##### Progress [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways) issues from 07/18/2016 - 07/22/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 18th, July | 100 | 0 |
Tuesday 20th, July | 106 |59 |
Wednesday 21th, July | 86 |86 |
|**Total** | -- | **145** |

**Comment by RichRico** [comment]
##### Progress [Crossing minor highways](http://osmlab.github.io/to-fix/#/task/crossingminorhighways) issues from 07/18/2016 - 07/22/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 18th, June | 18967  | 13470 |
Tuesday 19th, June  | 3007 | 2423 |
Wednesday 20th, June | 247 | 0 |
Thursday 21st, June | 265 | 0 |
Friday 22nd, June | 314 | 0 |
**Total** | -- | **15993* |

**Comment by RichRico** [comment]
##### Progress [Crossing minor highways](http://osmlab.github.io/to-fix/#/task/crossingminorhighways) issues from 07/25/2016 - 07/27/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 18th, June | 409  | 158 |
Tuesday 19th, June  | 190 | 28 |
Wednesday 20th, June | 54 | 0 |
**Total** | **653** | **186** |

**Comment by samely** [comment]
####  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways) issues from 08/01/2016 - 08/05/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 1st, July | 173 | 0 |
Tuesday 2nd, July  | 39 | 12 |
Wednesday 3th, July | 1810 | 0 [obs.](http://forum.openstreetmap.org/viewtopic.php?id=55220) |
Thursday 4th, August | 123 | 0 |
Friday 5th, August | 135| 64 |
**Total** | -- | **76** |

**Comment by RichRico** [comment]
##### Progress [Crossing minor highways](http://osmlab.github.io/to-fix/#/task/crossingminorhighways) issues from 08/08/2016 - 08/12/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 8th, August | 58 | 0 |
Tuesday 9th, August  | 136 | 68 |
Wednesday 10th, August | 95 | 24 |
Thursday 11th, August | 37 | 27 |
Friday 12th, August | 35 | 15 |
**Total** | -- | **134** |

**Comment by samely** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)  issues from 08/15/2016 - 08/19/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 15th, August | 88 | 56 |
Tuesday 16th, August  | 38 | 0 |
Wednesday 17th, August | 69 | 0 |
Thursday 18th, August | 113 |49 |
Friday 19th, August | 68 | 32 |
**Total** | -- | **137** |

**Comment by samely** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)  issues from 08/22/2016 - 08/26/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 22th, August | 48 | 20 |
Tuesday 23th, August  | 89 | 49 |
Wednesday 24th, August | 96 | 15 |
Thursday 25th, August | 52 |0 |
Friday 26th, August | 82 | 35 |
**Total** | -- | **119*

**Comment by samely** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)  issues from 08/29/2016 - 09/02/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 29th, August | 167 |36 |
Tuesday 30th, August  | 46 | 20 |
Wednesday 31th, August | 88 | 46 |
**Total** | -- | **102**

**Comment by samely** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)  issues from 09/05/2016 - 09/09/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 5th, August | 107 | 65 |
Tuesday 6th, August  | 30 | 18 |
Wednesday 7th, August | 70 | 0 |
Thursday 8th, August | 109 | 0 |
Friday 9th, August | 83| 45 |
**Total** | -- | **128**

**Comment by samely** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)  issues from 09/12/2016 - 09/16/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 12th, August | 160  | 76  |
Tuesday 13th, August  | 76  | 40  |
Wednesday 14th, August | 42 | 0 |
Thursday 15th, August | 80 | 30 |
Friday 16th, August | 50| 31 |
**Total** | -- | **178**

**Comment by RichRico** [comment]
##### Progress  [Crossing minor highways](http://osmlab.github.io/to-fix/#/task/crossingminorhighways)  issues from 09/19/2016 - 09/23/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 19th, August | 111 | 70 |
Tuesday 20th, August  | 838 | 0 |
Wednesday 21st, August | 792 | 0 |
Thursday 22nd, August | 191 | 134 |
Friday 23rd, August | 12515 | 7764 |
**Total** | **** | **7968** |

**Comment by ediyes** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways) issues from 10/24/2016 - 10/28/2016

Date | N° detected error | Total Fixed 
---|---|---
Tuesday 25th, October| 444|73|
Wednesday 26th, October| 339| 143 |
Thursday 27th, October| 143 |1|
Friday 28th, October| 130| 64|
**Total** | -- | **281** |

**Comment by RichRico** [comment]
##### Progress  [Crossing minor highways](http://osmlab.github.io/to-fix/#/task/crossingminorhighways)  issues from 10/31/2016 - 11/04/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 31th, August | 155 | 76 |
Tuesday 01th, August  | -- | -- |
Wednesday 02nd, August | 103 | 0 |
Thursday 03rd, August | 59 | 11 |
Friday 04th, August | -- | -- |
**Total** | **** | **87** |

**Comment by samely** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)  issues from 09/01/2017 - 13/01/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 09th, August | 275|  |
| Tuesday 10th, August | 275 |  |
| Wednesday 11th, August | 357 | 72 |
| Thursday 12th, August | 152 | 2 |
| Friday 13th, August | 148 | 53 |
| **Total** | -- | **127** |

**Comment by samely** [comment]
Last and this week I found many crossing issues due to some changesets made by [Gã Trùm](https://www.openstreetmap.org/user/G%C3%A3%20Tr%C3%B9m), some of his edits look good, however, doesn't match with satellite imagery (I even looked at google map to be sure), also he has been editing with iD and is a new mapper. I've already left changeset comments last week but there is no reply. Not sure if I should revert them, what do you think @krishnanammala?
Those are the changeset that I've found:
- https://osmcha.mapbox.com/45018140/
- https://osmcha.mapbox.com/45018760/
- https://osmcha.mapbox.com/45017622/
- https://osmcha.mapbox.com/45017983/
- https://osmcha.mapbox.com/45017616/
- https://osmcha.mapbox.com/45192060/

cc. @Rub21

**Comment by samely** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)  issues from 16/01/2017 - 20/01/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 16th, January | 216| 111 |
| Tuesday 17th, January| 74 | 38 |
| Wednesday 18th, January| 38 | 1 |
| Thursday 19th, January| 0 | 0 |
| Friday 20th, January| 304 | 109 |
| **Total** | -- | **259** |

Obs.
- I found those features in Poland that are based on proposal tags: [#1](https://www.openstreetmap.org/way/467429675#map=19/51.75597/19.43374), [#2](https://www.openstreetmap.org/way/467427839#map=18/51.75650/19.43535), [#3](https://www.openstreetmap.org/way/462407626#map=16/51.7569/19.4343) and more around this area.
- I also found some [deleted highways](https://www.openstreetmap.org/changeset/45313118).

**Comment by ediyes** [comment]
##### Progress  [Crossing minor highways](https://osmlab.github.io/to-fix/#/task/crossingminorhighwaysldazu) issues from 01/23/2017 - 01/27/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 23rd January|117|57|
Wednesday 25th January|298|120
Thursday 26th January|373|215
**Total** | -- | **392** |

**Comment by ediyes** [comment]
##### Progress  [Crossing minor highways](https://osmlab.github.io/to-fix/#/task/crossingminorhighwaysldazu) issues from 01/30/2017 - 02/03/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 30th January|1099|237|
Tuesday 31st January|634|282|
Wednesday 01st February|706|70
Thursday 2nd February|240|85
**Total** | -- | **674** |

**Comment by RichRico** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways) issues from 02/06/2017 - 02/10/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday|615|55
Tuesday |605|74|

**Total** | -- | **129** |

**Comment by ridixcr** [comment]
##### Progress  [Crossing minor highways](https://osmlab.github.io/to-fix/#/task/crossingminorhighwaysldazu) issues from issues from 02/13/2017 - 02/17/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Wednesday 15th February :point_left:(No detected)|0|0
Thursday 16th February |0|0
Friday 17th February |516|107
**Total** | -- | **107** |

**Comment by RichRico** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways) issues from 02/20/2017 - 02/24/2017

Date | N° detected error | Total Fixed 
---|---|---
Monday 20th February|454|79
Tuesday 21th February|365|7
Wednesday 22nd February |310|75
Thursday 23th February|--|--
Friday 24th February|257|73
**Total** | -- | **234** |

**Comment by ridixcr** [comment]
##### Progress  [Crossing minor highways](https://osmlab.github.io/to-fix/#/task/crossingminorhighwaysldazu) issues from 02/27/2017 - 03/03/2017

Date | N° detected error | Total Fixed 
---|---|---
Monday 27th February|178|74
Tuesday 28th February|261|20
Wednesday 1st March |231|0
Thursday 2nd March |276|172
Friday 3rd March |121|89
**Total** | -- | **355** |

**Comment by ridixcr** [comment]
##### Progress  [Crossing minor highways](https://osmlab.github.io/to-fix/#/task/crossingminorhighwaysldazu) issues from 03/06/2017 - 03/10/2017

Date | N° detected error | Total Fixed 
---|---|---
Monday 06th March|131|91
Tuesday 07th March|72|0
Wednesday 08th March |72|0
Thursday 09th March |72|56
Friday 10th March |108|97
**Total** | -- | **244** |

**Comment by ridixcr** [comment]
##### Progress  [Crossing minor highways](https://osmlab.github.io/to-fix/#/task/crossingminorhighwaysldazu) issues from 03/13/2017 - 03/17/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Wednesday 15th March |258|157
Friday 17th March |167|120
**Total** | -- | **277** |

**Comment by RichRico** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways) issues from 03/27/2017- 03/31/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Wednesday 15th March |553|56
Tuesday 28th March |282|81
**Total** | -- | **81** |

**Comment by RichRico** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways) issues from 04/03/2017- 04/07/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 3th April |11|9
Tuesday 4th April |9|0
Wednesday 5th April |2 |1 
Friday 7th | 2|1
**Total** | -- | **11** |

**Comment by RichRico** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)  from 04/17/2017 - 04/21/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 17th April |46 |6 
Tuesday 18th April|10|5
Wednesday 19th April|2 |0 
--| **Total**|**11**

**Comment by RichRico** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)  from 04/24/2017 - 04/28/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 24th April |112 |10 
--| **Total**|**10**

**Comment by RichRico** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)  from 04/24/2017 - 04/28/2017

Date| Detected Issues | Fixed Issues
---|----|---
Tuesday 2nd May | 373| 174
Wednesday 3rd May | 76|56
Friday 5th May |42 |32
--| **Total**|**262**

**Comment by RichRico** [comment]
##### Progress  [Crossing major highways](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)  from 05/08/2017 - 05/12/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 8th May |26 |11
Tuesday 9th May | 11| 7
Thursday 11th May|21 |6
Friday 12th May |6563 |24
--| **Total**|**48**
