### ISSUE TITLE
To-fix: Unconnected highways

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#105]
### Objective

Connect roads that are motorable and end near another road but not connected to it. This could be because of:
- User error in creating proper junction for ways (fixable)
- User error in tracing the full road till the junction (fixable)
- Incomplete tracing because road connection not visible in imagery (requires survey)
- No road connection because of a wall or barrier (ignore)
### Tasks

To-Fix issues:
-  Major: http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways
-  Minor: http://osmlab.github.io/to-fix/#/stats/unconnectedminorhighways
### Team

For now, only team @mapbox/peru-office  will work on this challenge.
#### Changeset comment

```
Connecting motorable roads using #to-fix https://github.com/mapbox/mapping/issues/105
```
### Coverage

All countries in this list: https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt
### Tools
- If using iD editor, work with [To-Fix web](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)
- If using JOSM, work with [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin)\- Use `join` tool (Shortcut: `J`)
- Use `merge` tool (Shortcut: `M`)
### Instructions
- Join disconnected roads and junctions verifiable from satellite imagery
- Do not make connections where there is a possibility of a fence or barrier in between the roads
- If editing in a actively mapped area, add a note instead of making a fix
- Check object history (`ctrl + H`) to understand why the previous user did not make a connection
### Common issues
- You can select these nodes and merge them(m)
  ![imagen 1](https://cloud.githubusercontent.com/assets/10425629/8985611/e3ca6ec8-369d-11e5-8c0b-350e67f9b749.png)

_Select the nodes and merge them_

![imagen 2](https://cloud.githubusercontent.com/assets/10425629/8985652/0a2eb9de-369e-11e5-8621-72255117efd8.png)
_Select the node and join it to the road_
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
### Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data

**Comment by lxbarth** [comment]
@samely - is this batch of unconnected major limited to a particular geographic area?

In the past, many unconnected major issues included residential roads, could we fix this?

What's the source for this task?

**Comment by samely** [comment]
@lxbarth 
It's not limited to an specific area. 
![image](https://cloud.githubusercontent.com/assets/10425629/9009358/34d5b16a-3766-11e5-8245-82441a283bdf.png)

I didn't specify the kind of road for this task because while I was working on this I could see residential, primary, secondary, tertiary, service, track and path roads, so I thought it wasn't necessary to specified them.

I don't understand about the source, but Ruben told me it is ´unconnected´.

**Comment by Rub21** [comment]
@lxbarth @samely :

>  is this batch of unconnected major limited to a particular geographic area?

There are items for whole world .

![image](https://cloud.githubusercontent.com/assets/1152236/9014583/e96c729a-3788-11e5-8123-06db9585b00d.png)


> In the past, many unconnected major issues included residential roads, could we fix this?


The task contain all roads but mostly of items include residential roads.


> What's the source for this task?

According https://github.com/osmlab/to-fix/blob/gh-pages/src/data/tasks.json#L3-L5, `unconnected major` has as source `unconnected`, it come from https://github.com/osmlab/csv-err

**Comment by Rub21** [comment]
@mapbox/india-office @mapbox/peru-office :

We've finished [unconnected major task](http://osmlab.github.io/to-fix/#/stats/unconnected_major), @samely @ediyes @abel801 @RichRico @calfarome @dannykath @karitotp  @luisalanya  spent 17 hours to completed 26,079 items. 

**Stats**

###  To-fix number of item `edited`, `fixed`, `skip`, `not an error`

![image](https://cloud.githubusercontent.com/assets/1152236/9042989/f5d24ce8-39d7-11e5-8703-9c3e09a4a28b.png)


### OpenStreetMap number of objects modified and number of changeset

![image](https://cloud.githubusercontent.com/assets/1152236/9042969/d1aa028e-39d7-11e5-9094-2d45e59e209e.png)


From `26,079`all items on  [unconnected major task](http://osmlab.github.io/to-fix/#/stats/unconnected_major) we did `11,640` changeset in OpenStreetmap,   and around `14,439`  was fixed  by other users or was  not an error issues on map.

**Comment by talllguy** [comment]
Keep up the great work!

**Comment by lxbarth** [comment]
@Rub21 - this is a great summary. How do we track master tickets like this one? Should we do a label and close them? cc @planemad 

Is "mapping" a good name for the label?

Looking for a simple way to look at all pending and finished mapping project's we're on.

**Comment by planemad** [comment]
`project` `task` ?

**Comment by planemad** [comment]
Loaded the latest unconnected data into http://geohacker.in/unconnected-tiger/ and found many issues on motorways(purple circles) that are [over 3 months old](https://www.openstreetmap.org/node/3536529906)

@Rub21 i'm having a feeling these were not loaded into to-fix for some reason. Any ideas why they are still broken?

**Comment by planemad** [comment]
**Task Updated**
- 09/08: Task refreshed with 5771 open issues. Does not include JP or GB.

**Comment by ramyaragupathy** [comment]
Here is something I came across in unconnected major task, where the problem point is indicated in Antractica. Two things noticeable here,
 1. Location information in to-fix is shown as Ceduna, Australia while it is actually Antarctica
 2. There is no data in the indicated problem point except for a coastline
![screenshot 2015-09-08 18 16 54](https://cloud.githubusercontent.com/assets/12103383/9735141/3522a1aa-5656-11e5-906d-73a8d422b297.png)

CC @planemad @geohacker @aaronlidman @Rub21

**Comment by jinalfoflia** [comment]
This is something that I came across while doing this task. I found this issue where there is a barrier between the roads.
![pg](https://cloud.githubusercontent.com/assets/4470913/9761936/8b8dcf16-571d-11e5-88a0-c15d8dfc1549.png)
Thus these roads weren't connected and were showing up as an issue. To fix this, I have connected the roads and added a `barrier=yes` tag to the node connecting them.
![screen shot 2015-09-09 at 5 54 52 pm](https://cloud.githubusercontent.com/assets/4470913/9761984/ebc47fc4-571d-11e5-9e3a-9d8fdc0367c5.png)

**Comment by planemad** [comment]
We have a data disaster in Nukus, Uzbekistan that requires a separate cleanup effort. Avoid fixing errors in this area.

More details: http://www.openstreetmap.org/user/PlaneMad/diary/35762

cc @mapbox/team-data

**Comment by ruthmaben** [comment]
Task completed!  :boom: :rocket: 

![screen shot 2015-09-11 at 7 40 15 pm](https://cloud.githubusercontent.com/assets/10308123/9816870/378ab05e-58bd-11e5-81c8-55f823a8ff90.png)

cc: @mapbox/team-data

**Comment by Andygol** [comment]
@planemad 
Yesterday I faced with bunch of error in Nukus and spent all day cleaning them.

In my opinion errors arose unintentionally. Most likely they occurred after a failed uploading.

I hoped that I fixed most of them

**Comment by Andygol** [comment]
Here left some issues with *Duplicate ways* and *Unconnected major*
![image](https://cloud.githubusercontent.com/assets/369696/9831853/fdb2bfb2-596f-11e5-8b4e-c94435801fd0.png)

**Comment by planemad** [comment]
**Task Updated**
- 09/14: 4,889 issues added from OSM inspector

**Comment by Rub21** [comment]
### Task Updated
![image](https://cloud.githubusercontent.com/assets/1152236/13365387/b4e07dc2-dca2-11e5-8f3b-4a725812c766.png)

01/26/2016: 35,218 issues added from OSMLINT

**Comment by lxbarth** [comment]
@Rub21 - do we literally have more unconnected major issues now than we had [6 months ago](https://github.com/mapbox/mapping/issues/105)?

**Comment by Rub21** [comment]
@lxbarth ,

> do we literally have more unconnected major issues now than we had 6 months ago?

Yes, I think it is because We are considering [this classification](https://github.com/osmlab/osmlint/blob/dev/validators/nodeEndingNearHighway/map.js#L15-L27) as unconnected major issues, in the past was not clear which roads were considered as major issues.

For unconnected minor we are considering [this classification](https://github.com/osmlab/osmlint/blob/dev/validators/nodeEndingNearHighway/map.js#L29-L31),  why not  track, footway, path? because there are many false positive on these case, let's focus on main roads first. 

cc. @aaronlidman

**Comment by lxbarth** [comment]
@Rub21 @planemad @maning - I think this classification is out of whack ^ what makes more sense in my mind is:

1. unconnected major roads = tertiary and up
2. unconnected minor roads = service, residential, unclassified
3. unconnected paths = path, cycleway, footway

This would allow us to prioritize 1, 2 and 3 differently by periodic revisits and geographic regions in a meaningful way.

**Comment by Rub21** [comment]
@lxbarth 
>unconnected major roads = tertiary and up
unconnected minor roads = service, residential, unclassified
unconnected paths = path, cycleway, footway

it looks fine. 

I will make some modifications in osmlint to support this and then update here.

**Comment by Rub21** [comment]
### Task Updated

According this [classification](https://github.com/osmlab/osmlint/blob/dev/validators/nodeEndingNearHighway/map.js#L13-L24) , We've added 2,546 issues on  01/29/2016

**Comment by ruthmaben** [comment]
Nice work @mapbox/peru-office!

**Comment by chtnha** [comment]
Great work @mapbox/peru-office. Proud of you guys :muscle:

**Comment by jothirnadh** [comment]
Wow! Superb work guys :rocket: :fire:

**Comment by abhisheksaikia** [comment]
Super work @mapbox/peru-office :muscle: :rocket:

**Comment by mikelmaron** [comment]
Solid!

**Comment by Rub21** [comment]
### Task Updated 03/02/2016

I've added 1,698 issues, These issues are for entire world. 
source: osmint-nodeendingnearhighway.

http://osmlab.github.io/to-fix/#/stats/unconnectedmajor

**Comment by samely** [comment]
Task completed!  :boom: :rocket: Great team!! :boom: :rocket:

![image](https://cloud.githubusercontent.com/assets/10425629/13505802/de159a06-e148-11e5-9fa2-cc44915f4462.png)

**Comment by Rub21** [comment]
### Task Updated 03/10/2016

I've added 349 issues for entire world. 
source: osmint-nodeendingnearhighway.

http://osmlab.github.io/to-fix/#/stats/unconnectedmajor

**Comment by samely** [comment]
Task completed!  :boom: :rocket: Well done team!! :boom: :rocket:

![image](https://cloud.githubusercontent.com/assets/10425629/13678978/75bebf2e-e6bf-11e5-9aa3-c352f3acc799.png)

**Comment by calfarome** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 06/20/2016 - 06/24/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 5  | 0 |
Tuesday 21st, June  | 10 | 6 |
Wednesday 22nd, June | 3| 3 |
Thursday 23rd, June | 3| 3 |
Friday 24th, June | 15|  12|
**Total** | -- | **24** | 

##### [Unconnected minor highways](http://osmlab.github.io/to-fix/#/task/unconnectedminorhighways) issues from 06/20/2016 - 06/24/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 66  | 0 |
Tuesday 21st, June  | 131 | 90 |
Wednesday 22nd, June | 45 | 32|
Thursday 23rd, June | 36 | 24 |
Friday 24th, June | 113 | 92 |
**Total** | -- | **238** |

**Comment by RichRico** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 06/27/2016 - 07/01/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 12  | 12 |
Tuesday 21st, June  | 8 | 6 |
Wednesday 22nd, June | 3| 3 |
Thursday 23rd, June | 3| 0 |
Friday 24th, June | 3 | 3 |
**Total** | -- | **24** | 

##### [Unconnected minor highways](http://osmlab.github.io/to-fix/#/task/unconnectedminorhighways) issues from 06/27/2016 - 07/01/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 157 | 87 |
Tuesday 21st, June  | 71 | 51 |
Wednesday 22nd, June | 48 | 33 |
Thursday 23rd, June | 33 | 0 |
Friday 24th, June | 102 | 78 |
**Total** | -- | **249** |

**Comment by karitotp** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 07/04/2016 - 07/08/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 04th, July | 64 |17 |
Tuesday 05th, July  | 6 | 5 |
Wednesday 06th, July | 8 | 3 |
Thursday 07th, July |12  |0  |
Friday 08th, July | 9 | 4 |
**Total** | -- | **29** | 

##### [Unconnected minor highways](http://osmlab.github.io/to-fix/#/task/unconnectedminorhighways) issues from 07/04/2016 - 07/08/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 04th, July | 237 |177 |
Tuesday 05th, July  | 64 | 30 |
Wednesday 06th, July | 53 | 28 |
Thursday 07th, July | 32 | 0 |
Friday 08th, July | 70 |41  |
**Total** | -- | **276** |

**Comment by dannykath** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 07/11/2016 - 07/14/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July | 24 |19 |
Tuesday 12th, July  | 7 |5  |
Wednesday 13th, July | 5 | -- |
Thursday 14th, July | 3 | 1 |
**Total** | -- | **25** | 

##### [Unconnected minor highways](http://osmlab.github.io/to-fix/#/task/unconnectedminorhighways) issues from 07/11/2016 - 07/14/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July | 214 |3 |
Tuesday 12th, July  | 273 |12  |
Wednesday 13th, July | 274 |206  |
Thursday 14th, July | 101 |  |
**Total** | -- | **221** |

**Comment by luiswalter** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 07/18/2016 - 07/22/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 18th, July | 5 | 4 |
Tuesday 19th, July  | 16 | 8 |
Wednesday 20th, July | 6 | 3 |
Thursday 21th, July | 13 | 10 |
Friday 22th, July | 3 | 3 |
**Total** | -- | **28** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 07/25/2016 - 07/29/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 25th, July | 13|5 |
Tuesday 26th, July  | 5 |3  |
Wednesday 27th, July | 5 | 1 |
Thursday 28th, July | 4 | -- |
Friday 29th, July | 10 | -- |
**Total** | -- | **9** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 08/01/2016 - 08/05/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 1st, August |13  | 5 |
Tuesday 2nd, August | 6 | 3 |
Wednesday 3rd, August | 25 | 0  |
Thursday 4th, August | 7 | 6 |
Friday 5th, August | 4 | 4 |
**Total** | -- | **18** |

**Comment by Yurasi** [comment]
##### [Island minor highways](http://osmlab.github.io/to-fix/#/task/islandsminorhighways) issues from 07/12/2016 - 07/14/2016
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 12th, July  | 754 | 74 |
Wednesday 13th, July | 504 | 171 |
Thursday 14th, July | 250 | 62 |
**Total** | -- | **307** | 

##### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/task/missingonewaysmotorwaylink) issues from 07/11/2016 - 07/14/2016
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 12th, July  | 12 |11  |
Wednesday 13th, July | 2 |0  |
Thursday 14th, July | 0 | 0 |
**Total** | -- | **11** |

**Comment by Yurasi** [comment]
##### [Island minor highways](http://osmlab.github.io/to-fix/#/task/islandsminorhighways) issues from 07/18/2016 - 07/22/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 1st, August |104  | 27 |
Tuesday 12th, July  | 49 | 25 |
Wednesday 13th, July | -- | -- |
Thursday 14th, July | 18 | 11 |
Friday 5th, August | 26 | 20 |
**Total** | -- | **83** | 

##### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/task/missingonewaysmotorwaylink) issues from 07/18/2016 - 07/22/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 1st, August |6  | 6 |
Tuesday 12th, July  | 6 |0  |
Wednesday 13th, July | 0 |0  |
Thursday 14th, July | 0 | 0 |
Friday 5th, August | 0 | 0 |
**Total** | -- | **6** |

**Comment by ridixcr** [comment]
##### [Unconnected minor highways](https://osmlab.github.io/to-fix/#/stats/unconnectedminorhighways) issues from 07/25/2016 - 07/29/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 25th, July | 438|317 |
Tuesday 26th, July  | 61 |0  |
Wednesday 27th, July | 121 | 0 |
**Total** | -- | **317** | 

##### [Overlapping minor highways](https://osmlab.github.io/to-fix/#/stats/overlappingminorhighways) issues from 07/25/2016 - 07/29/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 25th, July | 210|0 |
Tuesday 26th, July  | 221 |0  |
Wednesday 27th, July | 251 | 0 |
**Total** | -- | **0** |

**Comment by Yurasi** [comment]
##### [Island minor highways](http://osmlab.github.io/to-fix/#/task/islandsminorhighways) issues from 07/26/2016 - 07/27/2016
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 26th, July  | 30 | 26 |
Wednesday 27th, July | 15 | 9 |
**Total** | -- | **35** | 

##### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/task/missingonewaysmotorwaylink) issues from 07/26/2016 - 07/27/2016
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 26th, July  | 0 | 0 |
Wednesday 27th, July | 0 | 0 |
**Total** | -- | **0** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 08/08/2016 - 08/12/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 1st, August |13  | 5 |
Tuesday 2nd, August | 6 | 3 |
Wednesday 3rd, August | 25 | 0  |
Thursday 4th, August | 7 | 6 |
Friday 5th, August | 4 | 4 |
**Total** | -- | **18** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 08/15/2016 - 08/19/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 15th, August |5| 3|
Tuesday 16th, August | 4 | 1 |
Wednesday 17th, August | 1 | 1  |
Thursday 18th, August | 3 | 0 |
Friday 19th, August | 8 | 3 |
**Total** | -- | **29** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 08/22/2016 - 08/26/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 22nd, August |13| 9|
Tuesday 23rd, August | 3 | 2 |
Wednesday 24th, August | 7 | 1  |
Thursday 25th, August | 5 | 2 |
Friday 26th, August | 1 | 1 |
**Total** | -- | **15** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 08/29/2016 - 08/31/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 29th, August |9| 8|
Tuesday 30th, August | 9 | 7 |
Wednesday 31th, August | 3 | 1  |
**Total** | -- | **16** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 09/05/2016 - 09/09/2016

Date | N° detected error | Total Fixed 
---|---|---|
Monday 5th, September |21|13|
Tuesday 6th, September | 4 |1|
Wednesday 7th, September | 4 | 3 |
Thursday 8th, September | 4 | 1 |
Friday 9th, September | 1 | 1 |
**Total** | -- | **19** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from  09/12/2016 - 09/16/2016

Date | N° detected error | Total Fixed 
---|---|---|
Monday 12th, September|15|12|
Tuesday 13th, September| 4 |1|
Thursday 15th, September| 2 | 2 |
Friday 16th, September| 9 | 7 |
**Total** | -- | **22** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from  09/19/2016 - 09/23/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 19th, September|14|9|
Tuesday 20th, September| 12|6|
Wednesday 21st, September| 10| 3 |
Thursday 22nd, September| 4|2|
Friday 23rd, September| 282| 223 |
**Total** | -- | **243** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 10/24/2016 - 10/28/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 24th, October|121|78|
Tuesday 25th, October| 9|7|
Wednesday 26th, October| 7| 2 |
Thursday 27th, October| 2 |1|
Friday 28th, October| 18| 15|
**Total** | -- | **98** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 10/31/2016 - 11/04/2016

Date | N° detected error | Total Fixed 
---|---|---
Thursday 3rd, November| 23 |16|
Friday 4th, November| 21| 2|
**Total** | -- | **18** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](http://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) issues from 11/07/2016 - 11/11/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 7th, November|18|10|
Tuesday 8th, November| 10 | 6 |
Wednesday 9th, November| 6 | 0 |
Thursday 10th, November| 18 | 13 |
Friday 11th, November| 17| 17|
**Total** | -- | **46** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](https://osmlab.github.io/to-fix/#/stats/unconnectedmajorhighwaysfy) issues from 01/09/2017 - 01/13/2017
Date | N° detected error | Total Fixed 
---|---|---
Monday 09th, January |19|16| 
Tuesday 10th|14|1|
Wednesday 11th , January |11|9 
Thursday 12th, January |16|12
Friday 13th, January|8|2
**Total** | -- | **40** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](https://osmlab.github.io/to-fix/#/stats/unconnectedmajorhighwaysfy)issues from issues from 16/01/2017 - 20/01/2017
The user [Imp_GL](https://www.openstreetmap.org/user/Imp_GL) fixed the issues :point_down:

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Wednesday 18th, January| 20 |17  |
| Thursday 19th, January| 32| 7 |
| Friday 20th, January| 29 |9  |
| **Total** | -- | **33** |

**Comment by ediyes** [comment]
##### [Unconnected minor highways](https://osmlab.github.io/to-fix/#/stats/unconnectedminorhighways) issues from 01/23/2017 - 01/27/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 23rd January|117|57|
Wednesday 25th January|298|120
Thursday 26th January|373|215
**Total** | -- | **392** |

**Comment by ediyes** [comment]
##### [Unconnected major highways](https://osmlab.github.io/to-fix/#/stats/unconnectedmajorhighwaysfy) issues from 01/30/2017 - 02/03/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 30th January|177|75|
Tuesday 31st January|29|18|
Wednesday 01st February|19|1
Thursday 2nd February|32|18
**Total** | -- | **112** |

**Comment by samely** [comment]
##### [Unconnected minor highways](https://osmlab.github.io/to-fix/#/stats/unconnectedminorhighways) issues from 02/06/2017 - 02/07/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 30th January|572|370|
Tuesday 31st January|144|96|
**Total** | -- | **466** |

**Comment by Yurasi** [comment]
##### [Unconnected major highways](https://osmlab.github.io/to-fix/#/stats/unconnectedmajorhighwaysfy)  Progress  issues from 13/02/2017 - 17/02/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 13th February|207|--
Tuesday 14th February|150|46
Wednesday 15th February :point_left:(No detected)|0|0
Thursday 16th February |04|01
Friday 17th February |16|10
**Total** | **--** | **57** |

**Comment by samely** [comment]
##### [Unconnected minor highways](https://osmlab.github.io/to-fix/#/stats/unconnectedminorhighways) issues from 02/20/2017 - 02/24/2017
Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 20th February|166|99|
Tuesday 21st February|97|39|
Wednesday 22nd February|64|39
Friday 24th February|297|152
**Total** | -- | **329** |

**Comment by Yurasi** [comment]
##### [Unconnected major highways](https://osmlab.github.io/to-fix/#/stats/unconnectedmajorhighwaysfy) Progress issues from 02/27/2017 - 03/03/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 27th February|48|24
Tuesday 28th February :point_left:(No detected)|00|00
Wednesday 1st March |25|19
Thursday 2nd March |17|13
Friday 3rd March |12|05
**Total** | **--** | **61** |

**Comment by Yurasi** [comment]
##### [Unconnected major highways](https://osmlab.github.io/to-fix/#/stats/unconnectedmajorhighwaysfy) Progress issues from 03/06/2017 - 03/10/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 06th March|38|19
Tuesday 07th March|06|02
Wednesday 08th March |15|10
Thursday 09th March |11|03
Friday 10th March |27|17
**Total** | **--** | **51** |

**Comment by Yurasi** [comment]
##### [Unconnected major highways](https://osmlab.github.io/to-fix/#/stats/unconnectedmajorhighwaysfy) Progress issues from 03/13/2017 and 03/17/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 13th March|35|25
Friday 17th March |24|18
**Total** | **--** | **43** |

**Comment by Yurasi** [comment]
##### [Unconnected major highways](https://osmlab.github.io/to-fix/#/stats/unconnectedmajorhighwaysfy) Progress issues on 03/21/2017 

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Tuesday 21th March |80|64
**Total** | **80** | **64** |

**Comment by Yurasi** [comment]
##### [Unconnected major highways](https://osmlab.github.io/to-fix/#/stats/unconnectedmajorhighwaysfy) Progress issues from 03/29/2017 to 03/30/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Wednesday 29th March |04|03
Thursday 30th March |00|00
**Total** | **04** | **03** |

**Comment by Yurasi** [comment]
##### [Unconnected major highways](https://osmlab.github.io/to-fix/#/task/unconnectedmajorhighways) Progress issues on 05/12/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Friday 12th May |468|31
**Total** | **--** | **31** |
