### ISSUE TITLE
To-fix: Unconnected minor Highways

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#106]
### Objective

To-Fix issue: http://osmlab.github.io/to-fix/#/task/unconnectedminorhighways

Review and repair highways which have another road end near them. They have to be intersected by a node.

Total number of issues: `47,382`

![image](https://cloud.githubusercontent.com/assets/10425629/9016276/63b6576c-3795-11e5-95de-7032d8346384.png)

## Team

For now, only team @mapbox/peru-office  will work on this challenge.

### Source

osmi

### Tools

- Use the [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin) instead of ToFix directly
- Configure your [JOSM-Shortcuts](https://github.com/mapbox/mapping/wiki/JOSM-Shortcuts), particularly `Merge Nodes = M` and `Join Node to Way = J`.

### Instructions

*Node near a highway*

![image](https://cloud.githubusercontent.com/assets/10425629/9016317/cdd5e0f4-3795-11e5-8ea9-9d2151915431.png)

- Connect  the node to the highway.
- Before editing, confirm an intersection is level from satellite imagery.
- Make sure there's no a wall, a grid or an area between the highways.

## Common issues

- [imagen 1](https://cloud.githubusercontent.com/assets/10425629/9016341/0df3dd6c-3796-11e5-945d-027cd6ee7b43.png)
- [imagen 2](https://cloud.githubusercontent.com/assets/10425629/9016427/b1454960-3796-11e5-8d6f-d8c13916dc20.png)

## Training

We've had a training in Ayacucho on Friday.

## Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data @lxbarth @aaronlidman

**Comment by Rub21** [comment]
### Task Updated
![image](https://cloud.githubusercontent.com/assets/1152236/13365445/0f97874c-dca3-11e5-947b-a18df305c351.png)


01/26/2016: 77,352 issues added from OSMLINT

**Comment by Rub21** [comment]
### Task Updated

According the follow [classification](https://github.com/osmlab/osmlint/blob/dev/validators/nodeEndingNearHighway/map.js#L25-L31)

``` js
 var minorRoads = {
    'unclassified': true,
    'residential': true,
    'living_street': true,
    'service': true,
    'road': true
  };
```
We've added 102,196 issues on  01/29/2016

**Comment by samely** [comment]
Part of just one [ticket](https://github.com/mapbox/mapping/issues/105). Closing.
