### ISSUE TITLE
To-fix: Kinks

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#107]
### Objective

Kinks issues are motorable roads that have nodes which make impossible angles on the road. 
## Tasks

**The below tasks are updating everyday from Monday to Friday with the latest errors in OpenStreetMap**
-  Major highways: http://osmlab.github.io/to-fix/#/task/impossibleangle
-  Minor highways: http://osmlab.github.io/to-fix/#/task/kinksminorhighways
#### Changeset comment

```
Aligning and fixing impossible angles in highway using #to-fix https://github.com/mapbox/mapping/issues/107
```
### Coverage

All countries in this list: https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt
### Tools for edition
- If using iD editor, work with [To-Fix web](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)
- Use `Merge Nodes = M` and `Join Node to Way = J`.
- GPS Layer `http://{switch:a,b,c}.gps-tile.openstreetmap.org/lines/{z}/{x}/{y}.png`
### Instructions
- If intersecting with the starting or ending point, split the way  according to satellite imagery.
- If intersecting with by a middle node, disengage the last one and reshape the way.
- If editing in an actively mapped area, add a note instead of making a fix.
- If satellite imagery isn't clear click on `not an error` of to-fix
### Common issues

![image](https://cloud.githubusercontent.com/assets/5991158/9045885/778eeebc-39ec-11e5-89d9-4002569a39c8.jpg)
_Delete irrelevant node_

![image](https://cloud.githubusercontent.com/assets/5991158/9045888/77925408-39ec-11e5-94fd-7261cd6d7227.jpg)
_Align the road if it's necessary and where there are GPS traces_

![image](https://cloud.githubusercontent.com/assets/10425629/18391178/bb390fda-7672-11e6-83a3-49952dc596fe.png)
_Split the way into two segments for each direction_

![image](https://cloud.githubusercontent.com/assets/10425629/18455208/392fc1de-790e-11e6-80d2-5b009565c68c.png)
_Not an error_
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
### Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data @lxbarth @aaronlidman

**Comment by pratikyadav** [comment]
![screen shot 2015-11-26 at 3 32 40 pm](https://cloud.githubusercontent.com/assets/12744420/11420266/fdd1b75a-9452-11e5-8e90-856e106c5ef2.png)


@planemad  good to close here?

**Comment by pratikyadav** [comment]
Done here. Nice work team.

**Comment by calfarome** [comment]
### Updates 

We've added  9,532  issues on 12/04/2016, the detection was made using [osmlint](https://github.com/osmlab/osmlint).

**Comment by calfarome** [comment]
##### [Kinks mayor highways](http://osmlab.github.io/to-fix/#/task/impossibleangle) issues from 06/20/2016 - 06/24/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 10  | 0 |
Tuesday 21st, June  | 31 | 15 |
Wednesday 22nd, June | 0| 0 |
Thursday 23rd, June | 16| 8 |
Friday 24th, June | 32 |  20|
**Total** | -- | **43** | 

##### [Kinks minor highways](http://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 06/20/2016 - 06/24/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 0  | 0 |
Tuesday 21st, June  | 0 | 0 |
Wednesday 22nd, June | 0 | 0 |
Thursday 23rd, June | 0| 0 |
Friday 24th, June | 374 | 318 |
**Total** | -- | **318** |

**Comment by RichRico** [comment]
##### [Kinks mayor highways](http://osmlab.github.io/to-fix/#/task/impossibleangle) issues from 06/27/2016 - 07/01/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 39  | 0 |
Tuesday 21st, June  | 15 | 27 |
Wednesday 22nd, June | 31 | 6 |
Thursday 23rd, June | 24 | 0 |
Friday 24th, June | 25 | 17 |
**Total** | -- | **50** | 

##### [Kinks minor highways](http://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 06/27/2016 - 07/01/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 30  | 0 |
Tuesday 21st, June  | 37 | 11 |
Wednesday 22nd, June | 7  | 22 |
Thursday 23rd, June | 6 | 0 |
Friday 24th, June | 44 | 38 |
**Total** | -- | **71** |

**Comment by karitotp** [comment]
##### [Kinks mayor highways](http://osmlab.github.io/to-fix/#/task/impossibleangle) issues from 07/04/2016 - 07/08/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 04th, July | 18 | 0 |
Tuesday 05th, July  |1  |0  |
Wednesday 06th, July | 8 | 3 |
Thursday 07th, July | 7 | 7 |
Friday 08th, July | 1 | 0 |
**Total** | -- | **10** | 

##### [Kinks minor highways](http://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 07/04/2016 - 07/08/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 04th, July | 23 |0 |
Tuesday 05th, July  | 14 | 1 |
Wednesday 06th, July |14  |11  |
Thursday 07th, July | 7 | 7 |
Friday 08th, July | 10 | 1 |
**Total** | -- | **20** |

**Comment by dannykath** [comment]
##### [Kinks mayor highways](http://osmlab.github.io/to-fix/#/task/impossibleangle) issues from 07/11/2016 - 07/14/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July | 16 |-- |
Wednesday 13th, July | 22 |13  |
Thursday 14th, July | 11 | -- |
**Total** | -- | **13** | 

##### [Kinks minor highways](http://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 07/11/2016 - 07/14/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July |26  |21 |
Tuesday 12th, July  | 21 | 13 |
Wednesday 13th, July | 14 |1  |
Thursday 14th, July | 29 |20  |
**Total** | -- | **65** |

**Comment by luiswalter** [comment]
##### [Kinks mayor highways](http://osmlab.github.io/to-fix/#/task/impossibleangle) issues from 07/18/2016 - 07/22/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 18th, July | 4 | 4 |
**Total** | -- | **4** | 

##### [Kinks minor highways](http://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 07/18/2016 - 07/22/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 18th, July | 32  |20 |
Tuesday 19th, July  | 20 | 14 |
Thursday 21th, July | 24 | 12 |
Friday 22th, July | 4 | 4 |
**Total** | -- | **65** |

**Comment by karitotp** [comment]
##### [Kinks minor highways](http://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 07/25/2016 - 07/29/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 25th, July | 26  | 20 |
Tuesday 26th, July  | 14 | 10 |
**Total** | -- | **30** |

**Comment by karitotp** [comment]
##### [Kinks minor highways](http://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 08/01/2016 - 08/05/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 01th, August | 49 |19 |
Tuesday 02th, August  | 11 | 9 |
Wednesday 03th, August |2852  | -- |
Thursday 04th, August | 18 | 14 |
Friday 05th, August | 13 | 10 |
**Total** | -- | **52** |

**Comment by karitotp** [comment]
##### [Kinks minor highways](http://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 08/08/2016 - 08/12/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 08th, August | 28 |0 |
Tuesday 09th, August  | 45 | 24 |
Wednesday 10th, August | 18 | 12 |
Thursday 11th, August | 10 | 5 |
Friday 12th, August | 24 | 12 |
**Total** | -- | **53** |

**Comment by karitotp** [comment]
##### [Kinks minor highways](http://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 08/15/2016 - 08/19/2016
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 16th, August  | 33 | 22 |
Wednesday 17th, August | 12 | 9 |
Thursday 18th, August | 11 | 7 |
Friday 19th, August | 6 | 4 |
**Total** | -- | **42** |

**Comment by karitotp** [comment]
##### [Kinks minor highways](http://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 08/22/2016 - 08/26/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 22nd, August |13 | 9 |
Tuesday 23rd, August  | 25 | 14 |
Wednesday 24th, August | 11 | 9 |
Thursday 25th, August | 14 | 8 |
Friday 26th, August | 7 | 6 |
**Total** | -- | **46** |

**Comment by karitotp** [comment]
##### [Kinks minor highways](http://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 08/29/2016 - 08/31/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 29th, August |30 | 21 |
Tuesday 30th, August  | 25 | 18 |
Wednesday 31th, August | 8 | 6 |
**Total** | -- | **45** |

**Comment by luiswalter** [comment]
##### [Kinks major  highways](https://osmlab.github.io/to-fix/#/task/impossibleangle) issues from 09/05/2016 - 09/09/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 05th, September |48| 17 |
Wednesday 07th, September | 15 | 11 |
Friday 09th, September |8374 | 7716 | 					
**Total** | -- | **7744** |

**Comment by andrewguertin** [comment]
[This loop](https://overpass-api.de/achavi/?changeset=42040424) was apparently detected as a kink and a mapper "fixed" it, even though the previous geometry matched reality much better. 

I'm not very familiar with the to-fix tool. Can it be improved (either through better UI or through better problem detection) to not encourage users to make changes like this?

**Comment by samely** [comment]
Hi @andrewguertin. 
Thanks for notifying us about this issue. Just so you know it's not about to-fix itself, but about detection.
However, we cannot stop detecting this kind of geometries because sometimes we found loops that shouldn't be loops. Every task in to-fix needs human analysis, and also we have this guide to help mappers on how fixing common issues. 

You are totally right, geometry before the change matches better than the new one and should be marked as a `not an error`, so we consider  adding these case to the **common issues** part. Thanks for helping us to improve the guide.

**Comment by andrewguertin** [comment]
@samely Thanks!

I realized that this and [another edit](https://overpass-api.de/achavi/?changeset=42112148) that showed up in my area recently have something in common: they were both loops that came straight from TIGER. Whenever TIGER had a loop at the end of a road like this, it imported the loop as a separate way.

Hopefully that can make the common issues part a little more specific and easier to deal with.

**Comment by RicoElectrico** [comment]
Hi, just thinking aloud, are fixes like this necessary? http://www.openstreetmap.org/changeset/42179258

Now, I understand why it tripped the validator, but on the other hand it wouldn't make any difference for routers, as they split the road graph at junctions anyway. Should it be not-an-error instead?

**Comment by Rub21** [comment]
Hi @RicoElectrico, thank you for looking into this issue.

I think there some differences in the rendered map style, e.g. the name of the roads doesn't look good in a triangle form. On the other hand, splitting the road into segments is more accepted,  most of this kind of situations are mapped on divided segments since we can add easier  turn-lanes, turn- restriction or  other features corresponding to the road segment.

**Comment by RicoElectrico** [comment]
You're right. I didn't think about the labeling problem, sure it's easier to split them than implement additional logic. OsmAnd suffers from wacky text wrapping in particular.

**Comment by karitotp** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 09/12/2016 - 09/16/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 12th, September |15, 922|637|
Tuesday 13th, September |15, 216|49|
Wednesday 14th, September | 15, 170|166 |
Thursday 15th, September|14, 963|5, 809|
Friday 16th, September |6, 449| 443| 					
**Total** | -- | **7, 104** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 09/19/2016 - 09/23/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 19th, September |5, 777 |3, 768 |
Tuesday 20th, September |78|59|
Wednesday 21st, September |36  |10 |
Thursday 22nd, September| 43| 34|
Friday 23rd, September |3, 096| 104| 					
**Total** | -- | **3, 975** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 10/24/2016 - 10/28/2016
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 25th, October |3,364|2,601|
Wednesday 26th, October |80  |61 |
Friday 28th, October |64|41| 					
**Total** | -- | **2,703** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 10/31/2016 - 11/04/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 31st, October |60|43|
Wednesday 2nd, November|47|26|
Thursday 3rd, Nomvember| 27|4 |
Friday 4th, November |28|18| 					
**Total** | -- | **91** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 11/07/2016 - 11/11/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 07th, November |59|44|
Tuesday 08th, November|36|24|
Thursday 09th, Nomvember| 43|18 |
Friday 10th, November |47|16| 					
**Total** | -- | **102** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighways) issues from 11/14/2016 - 11/18/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 14th, November |70|54|				
**Total** | -- | **54** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw) issues from 11/21/2016 - 11/25/2016
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 22nd, November |7446|19|				
**Total** | -- | **19** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw) issues from 11/28/2016 - 12/02/2016
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 29th, November |7,101|37|	
Wednesday 30th, November |6,733|31|
Thursday 01st, December |6,610|54|
Friday 02nd, December |6,300|8|			
**Total** | -- | **130** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw) issues from 12/05/2016 - 12/09/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 05th, December |6,294|40|
Tuesday 06th, December |904|86|	
Wednesday 07th, December |762|66|
Friday 09th, December |681|39|			
**Total** | -- | **231** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw) issues from 01/02/2017 - 01/06/2017
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 03rd, January |101|59|			
**Total** | -- | **59** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw) issues from 01/09/2017 - 01/13/2017
Date | N° detected error | Total Fixed 
---|---|---
Monday 09th, January |31|23 
Wednesday 11th , January |19|2 
Thursday 12th, January |33|27
**Total** | -- | **52** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw) issues from 01/16/2017 - 01/20/2017
Date | N° detected error | Total Fixed 
---|---|---
Monday 16th, January |47|30 
Tuesday 17th , January |30|11 
Thursday 19th, January |21|10
Friday 20th, January |11|4
**Total** | -- | **55** |

**Comment by calfarome** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw) issues from   from 23/01/2017 - 27/01/2017

Date | N° detected error | Total Fixed 
---|---|---
Monday 23th, January |0|0| 
Tuesday 24th,January |0|0|
Wednesday 25th , January |108|27
Thursday 26th, January |78|21
Friday 27th, January|0|0
**Total** | -- | **48** |

**Comment by ridixcr** [comment]
##### [Kinks major highways](http://osmlab.github.io/to-fix/#/task/impossibleangle) issues from   from 30/01/2017 - 03/02/2017

Date | N° detected error | Total Fixed 
---|---|---
Monday 30th January|95|59|
Tuesday 31st January|38|22|
Wednesday 01st February|23|2
Thursday 2nd February|23|0
Friday 3nd February|42|23
**Total** | -- | **106** |

**Comment by calfarome** [comment]
##### [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw) issues from 06/02/2017 - 10/02/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 06th February|151|34
Tuesday 07th Frebruary |40|25
--| **Total**|**59**

**Comment by ridixcr** [comment]
##### [Kinks major highways](http://osmlab.github.io/to-fix/#/task/impossibleangle) issues from 13/02/2017 - 17/02/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 13th February|11|11
Tuesday 14th February|02|02
Wednesday 15th February :point_left:(No detected)|0|0
Thursday 16th February |14|09
Friday 17th February |11|11
**Total** | **38** | **33** |

**Comment by calfarome** [comment]
#####  Progress [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw)  from 02/20/2017 - 02/24/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 20th February|167|46
Tuesday 21th February|94|37
Wednesday 22th February|10|4
Friday 24th February|45|16
--| **Total**|**103**

**Comment by ridixcr** [comment]
##### [Kinks major highways](http://osmlab.github.io/to-fix/#/task/impossibleangle) issues from issues from 02/27/2017 - 03/03/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 27th February|20|15
Tuesday 28th February|15|2
Wednesday 1st March |50|0
Thursday 2nd March |58|14
Friday 3rd March |14|0
**Total** | -- | **31** |

**Comment by ridixcr** [comment]
##### [Kinks major highways](http://osmlab.github.io/to-fix/#/task/impossibleangle) issues from  03/06/2017 - 03/10/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 06th March|20|11
Tuesday 07th March|12|0
Wednesday 08th March |12|0
Thursday 09th March |12|5
Friday 10th March |12|8
**Total** | -- | **24** |

**Comment by ridixcr** [comment]
##### [Kinks major highways](http://osmlab.github.io/to-fix/#/task/impossibleangle) issues from  03/13/2017 - 03/17/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 13th March|14|12
Wednesday 15th March |11|0
Friday 17th March |10|4
**Total** | -- | **16** |

**Comment by calfarome** [comment]
#####  Progress [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw)  from 03/20/2017 - 03/24/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Tuesday 21th March |75|43
Thursday 23th March |41|26
**Total** | -- | **69** |

**Comment by RichRico** [comment]
#####  Progress [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw)  from 04/17/2017 - 04/21/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 17th April |11 |3 
Tuesday 18th April|1|1
Wednesday 19th April|2 |0 
Friday 21th April|8 |5 
--| **Total**|**9**

**Comment by RichRico** [comment]
#####  Progress [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw)  from 04/24/2017 - 04/28/2017

Date| Detected Issues | Fixed Issues
---|----|---
Thursday 27th April|57 |7 
--| **Total**|**7**

**Comment by calfarome** [comment]
#####  Progress [Kinks minor  highways](https://osmlab.github.io/to-fix/#/task/kinksminorhighwaysjzw)  from 05/02/2017 - 05/05/2017

Date| Detected Issues | Fixed Issues
---|----|---
Tuesday 02th May|169|38
Wednesday 03th May|135 |81
Friday 05th May|10 |7
--| **Total**|**126**
