### ISSUE TITLE
Idea: Unconnected walkways / footways / paths / etc

### ISSUE THREAD

**Issue by talllguy** [mapbox/mapping#108]
:bulb: Idea for a new task...

I like these unconnected tasks team Mapbox is working on! I think one for pedestrian / cycle ways that are unconnected would be helpful for exercise routing. Often, mappers stop drawing the path or sidewalk where it ends on the imagery. Perhaps we can find these in the same way we're finding other types of roads.

**Comment by planemad** [comment]
@talllguy we have unconnected paths, walkways, tracks and footpaths in the [unconnected minor](http://osmlab.github.io/to-fix/?error=unconnected_major#/task/unconnected_minor1) task which currently has 47,000 issues. We should be hitting this sometime later in the month.

**Comment by talllguy** [comment]
@planemad Excellent, thanks!

**Comment by aaronlidman** [comment]
:+1: I agree! We took a look at paths/walkways/cycleways before and found there were tens of millions of issues to fix. I'm sure it's something we'll get to again when we find a better way of prioritizing which areas we're fixing. Until then we decided to focus on highways.
