### ISSUE TITLE
Task Manager: Hyderabad cleanup validation

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#109]
There has been some careless edits in Hyderabad that introduced a major number of connectivity issues. The user responsible has started cleaning up the mess, but validations of the cleanup remains.

**Task** http://tasks.openstreetmap.in/project/28

**Sources**
* Bing

**Working Groups**
- [Mapbox data team India](http://wiki.openstreetmap.org/wiki/Mapbox#Mapbox_Data_Team) @mapbox/team-data   From August 3

**Timeline**
- August 3-7 as and when tasks are ready to validate.

#### Instructions
- Validate that the user has cleaned up the data according the tasking manager instructions.
- Visually check for incorrect connections or overlapping ways that was not fixed using the JOSM validator. Fix them before validating the task.

#### Resources
- https://github.com/mapbox/mapping/wiki/Working-with-To-fix

**Comment by lxbarth** [comment]
@planemad  -

- At what point do we just roll back bad edits?
- After working on this today, do you have a sense of how much time it will take us to fix this issue?
- Is the user in question continuing to create bad edits?

**Comment by planemad** [comment]
@lxbarth 
- The user has been cleaning up the areas and fixing his bad edits with two more people
- Our team have been validating their work and so far are seeing that they have done a very good job of cleanup. There are some stray validation issues that require manual fixing, but I would estiimate over 95% of the connectivity issues have been fixed
- The user has stopped creating new map data after @geohacker and I had a call with him and guided him on how to do the cleanup. We dont know yet what his future plans are after the cleanup is complete.

**Comment by planemad** [comment]
**Progress**
- The users responsible for the broken data have progressed well on the cleanup tasks and the Mapbox data team has been validating the changes
- The progress has been very good and we are now down to 325 unconnected points on minor residential roads compared with the original 25,000 issues
![screenshot 2015-08-11 12 25 26](https://cloud.githubusercontent.com/assets/126868/9191954/6f4bdde4-4024-11e5-8721-349c1ab076b4.png)
- We have discovered a possible bug in JOSM validator where warning for certain unconnected ways do not show up. Ticket filed [here](https://josm.openstreetmap.de/ticket/11778). Few unconnected issues will remain due to this.

Nice work @mapbox/india-office !

**Comment by planemad** [comment]
Done here!
