### ISSUE TITLE
Task Manager: Indian capital cities road network

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#110]
Improving the OSM road network of state capitals in India using satellite imagery.
- Missing roads
- Misaligned roads
- Retagging roads based on [OSM India road tagging guidelines](http://wiki.openstreetmap.org/wiki/India:Tags/Highway)

**Tasks**
- [Ranchi](http://tasks.openstreetmap.in/project/29)

**Sources:**
- Bing
- Mapbox Satellite

**Timeline**
- This is an ongoing map improvement exercise to improve [OSM coverage in india](https://gist.github.com/geohacker/09854032b22656603a93#file-olacabs-md). There is no fixed timeline for completion.

**Working Groups**
- None

**Comment by bhargavpanth** [comment]
Classification of roads : How and in what pre-text do I tag a road that is branching off from a tertiary road? I am not really able to tell which road is a primary road and which is a tertiary road in Ranchi.

**Comment by planemad** [comment]
@bhargavpanth the easiest way to decide on road classification is to guess the ratio of non local/local traffic on a road. A residential road has purely local traffic going to building on that road. An unclassified road has mostly residential, but some non local traffic, and at the other end you would have a trunk road with mostly non local traffic.

When in doubt go by this simple scheme:
- `tertiary` for major roads with heavy traffic
- `unclassified` for roads connecting neighborhoods with major roads
- `residential` for roads inside neighborhoods

**Comment by pratikyadav** [comment]
![screen shot 2015-11-30 at 6 17 27 pm](https://cloud.githubusercontent.com/assets/12744420/11471913/a711d73a-978e-11e5-9462-c3c1dff4d170.png)


11% of the task completed(and validated) covering the inner city area. We have user [Rajkumarmishra](http://tasks.openstreetmap.in/user/Rajkumarmishra) making projects on tasking manager for improving road network in Indian cities.

cc @planemad

**Comment by pratikyadav** [comment]
http://tasks.openstreetmap.in/
Ongoing tasks on many Indian major cities^. 
A good place to move these task's discussion will be https://github.com/osm-in 

No immediate actions here. Closing.
