### ISSUE TITLE
Map Roulette: Missing US level crossings

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#111]
**Task** http://maproulette.org/#t=fix-railway-crossings/

Many railway level crossings from the [FRA](https://en.wikipedia.org/wiki/Federal_Railroad_Administration) are not tagged on OSM:
- There is already a level crossing tagged at the location (fixed)
- The road and rail data was imported and the level crossing was not tagged (fixable)
- Users forgot to tag the level crossing (fixable)
- Location does not coincide with a crossing (fixable if a clear crossing is visible nearby)
- No road and rail junction is visible on imagery (requires survey/cannot fix)
- There is no railway line in the area (ignore/not an error)
- There is a railway bridge or tunnel visible in the imagery (ignore/not an error)
- The railway line is `abandoned` or `disused` (ignore/not an error)
- Level crossing junction with a snowmobile track (ignore/not an error)

**Task coverage**
- USA

**Map features**
- http://wiki.openstreetmap.org/wiki/Tag:railway%3Dlevel_crossing

**Mapping source**
- Bing
- Mapbox Satellite

**Timeline**
-  08/05: 17470 Issues remaning
- @mapbox/india-office  will work on this challenge from 5 August to compare the workflow speed against to-fix
- 08/11: India team will pause on this for HOT https://github.com/mapbox/mapping/issues/112

**Setup**
- By default map roulette will load data in the same layer in JOSM. You will need to reconfigure remote control to download objects in a new layer. Update: JOSM still loads data in the same layer after reconfiguration.

**Instructions**
- Make an intersection node between the roads and railway tracks at the location and tag the junctions with `railway=level_crossing`

![untitled](https://cloud.githubusercontent.com/assets/126868/9081055/d21f10e2-3b76-11e5-81d6-087b486aac20.gif)

**Tips and tricks**
- You can copy an existing level crossing node to your clipboard, and just use the paste tags (cmd+shift+v) to instantly add the same tags to another selected node

#### Resources
- https://github.com/mapbox/mapping/wiki

cc. @mapbox/team-data @lxbarth

**Comment by ramyaragupathy** [comment]
Issues from the first 30 tasks I picked:
##### Areas with no data
![screenshot 2015-08-05 14 28 03](https://cloud.githubusercontent.com/assets/12103383/9081942/4ef5d536-3b7e-11e5-82ef-80495ba24884.png)
##### Problem points far from the actual railway lane
![screenshot 2015-08-05 14 30 19](https://cloud.githubusercontent.com/assets/12103383/9081996/92f440ce-3b7e-11e5-9abe-602bc61380ba.png)

**Comment by srividyacb** [comment]
The error place downloads in the same layer and not to different layer.

**Comment by jinalfoflia** [comment]
#### Issues for first 20 tasks I picked

- Every 8/10 tasks are already fixed

- As @ramyaragupathy mentioned
> Problem points far from the actual railway lane

![screen shot 2015-08-05 at 2 26 12 pm](https://cloud.githubusercontent.com/assets/4470913/9082124/7464c196-3b7f-11e5-81f9-89b0aea1b964.png)

**Comment by planemad** [comment]
Thanks @jinalfoflia and @ramyaragupathy , have added these use cases in the lead.

**Comment by pratikyadav** [comment]
I ran into a few places where the intersection nodes were exactly overlapping each other but not merged. Also a few places where `railway=level_crossing' was present but the intersection point was not merged.

I guess it will be a good practice to check for these intersection nodes.

**Comment by jinalfoflia** [comment]
In certain cases, the area/issue which http://maproulette.org/ shows before editing in JOSM, changes after the `edit in JOSM` button is clicked. Per voice with @ramyaragupathy, She also faced a similar issue and ignored as a browser error.

![maproulette](https://cloud.githubusercontent.com/assets/4470913/9083460/fc45f230-3b87-11e5-868d-c27fac0de622.gif)

**Comment by ramyaragupathy** [comment]
@jinalfoflia I am able to reproduce the issue, whenever i try to edit using shortcut `r`
![screenshot 2015-08-05 15 53 35](https://cloud.githubusercontent.com/assets/12103383/9083714/2db9a314-3b8a-11e5-850e-0e2c07e7680f.png)

**Comment by planemad** [comment]
**Progress**
- In 1 week, 30% of the open tasks were fixed by the community and 7 members of the data team. Currently there are 12280 issues remaining. 
- Expected completion: 2 weeks.

**Comment by planemad** [comment]
**Progress**
- Last week, 4620 issues were fixed by the community and 7 members of the data team. Currently there are 7660 issues remaining. 
- Expected completion: 21 August

**Comment by mvexel** [comment]
thanks for your participation, everyone! 
As for https://github.com/mapbox/mapping/issues/111#issuecomment-127947573 - if you could file this on the MR repo issue page that would be great - thank you! https://github.com/osmlab/maproulette/issues

**Comment by mvexel** [comment]
Also note that there are ~60k more to go after this one :dancers:

**Comment by ramyaragupathy** [comment]
>As for https://github.com/mapbox/mapping/issues/111#issuecomment-127947573 - if you could file this on the MR repo issue page that would be great - thank you! https://github.com/osmlab/maproulette/issues

done @mvexel. https://github.com/osmlab/maproulette/issues/347

**Comment by planemad** [comment]
@mapbox/india-office will pause on this task to work on #113

**Comment by pratikyadav** [comment]
Still on hold here. Closing for now.
