### ISSUE TITLE
HOT: Myanmar floods

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#112]
There has been severe flooding in Myanmar over the last week and the number of affected people is nearing 1 million and a death toll of 100 according to [latest reports](http://www.channelnewsasia.com/news/asiapacific/myanmar-flood-death-toll/2040634.html).

**Task** http://tasks.hotosm.org/project/1154

@mapbox/team-data is well experienced with HOT tasks after our [Nepal response](). We should jump in to offer our resources to this time critical task at the earliest.

- Validate completed tasks first
- Only after validation is complete work on incomplete blocks
- Follow instructions on tasking manager very carefully. Do strict with validation, especially building accuracy

**Task coverage**
- Flood affected villages in Myanmar

**Mapping source**
- Bing
- Mapbox Satellite

**Timeline**
-  Starting August 11. 15% validated 

<img width="392" alt="screenshot 2015-08-11 19 26 19" src="https://cloud.githubusercontent.com/assets/126868/9199219/decbe3fa-405e-11e5-9373-8b3ddaa62360.png">
- @mapbox/team-data will work on this full time till Thursday with a daily progress summary

**Instructions**
- Detailed instruction in the tasking manager

**Tips**
- Use realign tool (w) to quickly improve existing ways
![untitled](https://cloud.githubusercontent.com/assets/126868/9199837/6a1c6dd2-4062-11e5-953e-ed65b51c8100.gif)
- While using the building tool (b), press (ctrl) to avoid snapping to nearby edges
![untitled](https://cloud.githubusercontent.com/assets/126868/9200359/1b2cabc6-4065-11e5-90b1-91215ee60ffe.gif)

**Comment by planemad** [comment]
UN maps for Myanmar now includes OSM data http://www.unitar.org/unosat/maps/MMR

**Comment by planemad** [comment]
**Update**
- 08/13: The task is complete as per available imagery. The areas that are incomplete and invalidated  have low resolution imagery where it is impossible to do further mapping
![screenshot 2015-08-13 10 12 36](https://cloud.githubusercontent.com/assets/126868/9242727/17057344-41a4-11e5-9025-9ae9d1a70422.png)
- Nice work @mapbox/team-data, will post a summary of our contributions that @ramyaragupathy is extracting via overpass.

**Comment by lxbarth** [comment]
@ramyaragupathy - have you posted the summary in the meantime?

**Comment by ramyaragupathy** [comment]
@lxbarth Here is a link to the [team edits in Myanmar](https://github.com/mapbox/data/issues/1304#issuecomment-130339820). Edit counts from the [osm-query](http://mapbox.github.io/osm-query/#) as follows:
![screenshot 2015-10-19 15 32 41](https://cloud.githubusercontent.com/assets/12103383/10574947/d0df1520-7676-11e5-8dab-a75d5ac9a454.png)
