### ISSUE TITLE
To-fix: Strava routing errors

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#114]
Continuing from #113, we have all the Strava routing errors loaded onto to-fix.

**Task** http://osmlab.github.io/to-fix/?error=unconnected_major#/task/strava

- Trace/realign missing roads and paths on the map using the Strava heatmap
- Add bicycle lanes and sidewalks to trunk roads where visible in imagery, else add notes to verify their existence

![screenshot 2015-08-26 10 50 31](https://cloud.githubusercontent.com/assets/126868/9486095/519eff02-4be0-11e5-9161-383fed96521f.png)

**Task coverage**
- USA

**Mapping source**
- Strava globalheat walking (Red) `http://globalheat.strava.com/tiles/walking/color5/{zoom}/{x}/{y}.png`
- Strava globalheat  cycling (Blue) `http://globalheat.strava.com/tiles/cycling/color3/{zoom}/{x}/{y}.png`
- Bing
- Mapbox Satellite

**Timeline**
-  Starting 08/25 @mapbox/india-office  will work on this full time with a weekly progress summary. Status: 0/2748 issues
- 09/01: 1022/2748

**Instructions**
- Use the [JOSM to-fix plugin](https://github.com/osmlab/josm-tofix-plugin) to load issues
- Activate the globalheat imagery to see where users have been walking/cycling
- Compare OSM data with Bing/Strava imagery to find missing areas to trace and tags to add
- Look into #113 for false positives

**Features**
- [highway=*](http://wiki.openstreetmap.org/wiki/Key:highway)
- [cycleway=*](http://wiki.openstreetmap.org/wiki/Key:cycleway)

**Tips**
- Use realign tool (w) to quickly improve existing ways
![untitled](https://cloud.githubusercontent.com/assets/126868/9199837/6a1c6dd2-4062-11e5-953e-ed65b51c8100.gif)
- Cycle lanes have special lane markings that look like a bicycle. Look for these marking near junctions with other roads.
![untitled](https://cloud.githubusercontent.com/assets/126868/9658203/41e83e58-5265-11e5-81ba-b8615f57953a.gif)

cc @mapbox/team-data

**Comment by srividyacb** [comment]
For places where there is high Strava activity in `railway=abondoned`, add `highway=path` as a subtag for railway line. 
![screenshot 2015-08-26 15 34 21](https://cloud.githubusercontent.com/assets/3423533/9490790/f0973954-4c07-11e5-9b51-d5ac7658db8c.png)

**Comment by planemad** [comment]
**Progress**
- 236/2,748 issues closed in one day with 8 member team
- Expected completion at current rate is 8-10 days

**Comment by talllguy** [comment]
Just wondering: if people are still doing the tasks on the strava site, will that impact the Data team?

**Comment by lxbarth** [comment]
> Just wondering: if people are still doing the tasks on the strava site, will that impact the Data team?

No. The chances on 'stepping on each other's toes' while editing are very low.

**Comment by planemad** [comment]
@mapbox/team-data today is our last day fixing Strava issues so that we can move onto the higher priority Japan fixup #116 . We've made some great progress and our target is to close 2,000 issues by today. Will post the final report when done.

**Comment by planemad** [comment]
Closing with Strava after a massive push to fix issues and reaching 75% completion. Team-blr will work on Japan road realignment from now.

![screen shot 2015-09-03 at 8 22 37 pm](https://cloud.githubusercontent.com/assets/126868/9661712/97e36d96-5279-11e5-9bf6-b8dc8ec592be.png)

**Next actions**
- @planemad post way/node stats for data added

**Comment by planemad** [comment]
**Complete**
- 09/07: team-blr closed all remaining Strava issues
<img width="790" alt="screenshot 2015-09-10 20 53 18" src="https://cloud.githubusercontent.com/assets/126868/9792527/2f9b0e44-57fe-11e5-9ca4-96f515b83d50.png">

**Next actions**
- [ ] @planemad send note to Strava to generate fresh issue list
