### ISSUE TITLE
Move finalized / ongoing projects from OSM wiki to Github

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapping#117]
Per chat:

Let's move http://wiki.openstreetmap.org/wiki/Mapbox#Ongoing_projects and http://wiki.openstreetmap.org/wiki/Mapbox#Finalized_projects to here.

Let's make a "Finalized projects" page on our Github wiki here under mapping/ and link from the OSM wiki to the Github wiki for finalized projects and from the OSM wiki to the github issue queue for ongoing projects.

@planemad said he'll run with this.

**Comment by planemad** [comment]
@lxbarth moved https://wiki.openstreetmap.org/wiki/Mapbox#Mapbox_Data_Team
