### ISSUE TITLE
To-fix: Looping

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#118]
**Task** http://osmlab.github.io/to-fix/#/stats/loopings

Looping issues are roads or building that have two joined nodes that make a self intersection.

**Task coverage**
- Global

**Mapping source**
- Bing
- Mapbox Satellite

**Timeline**
-  10 September issue count: 26,079

![image](https://cloud.githubusercontent.com/assets/10425629/9797058/dd68b0de-57be-11e5-88ac-cc568a929d0f.png)

- @mapbox/peru-office will work on this challenge from Thursday 10th of September. Team training was done and expected completion is 1 week.

**Instructions**
- Detach the nodes and then align the road or the building
- If editing in a actively mapped area, add a note instead of making a fix
- Check object history (ctrl+h) to understand why the previous user did not make a connection

**Tips and tricks**
- Use [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin) and read the [JOSM-Shortcuts](https://github.com/mapbox/mapping/wiki/JOSM-Shortcuts)

- If building is self intersected on a node, unglue (G) those nodes.
![image](https://cloud.githubusercontent.com/assets/10425629/9797682/26e7731e-57c2-11e5-8530-48302e8c123a.png)

-  If road is self intersected on a node, unglue (G) those nodes and then align the road.
![image](https://cloud.githubusercontent.com/assets/10425629/9797860/01a2369c-57c3-11e5-8841-911f2c6b1df8.png)

#### Resources
- https://github.com/mapbox/mapping/wiki/Working-with-To-fix

cc. @mapbox/team-data @lxbarth @aaronlidman

**Comment by pratikyadav** [comment]
Current status of this task is
![screen shot 2016-04-05 at 12 54 31 pm](https://cloud.githubusercontent.com/assets/12744420/14274215/9beb3b78-fb2d-11e5-9c9a-8f31e4533cec.png)

Closing for now as this is on hold.
