### ISSUE TITLE
Clean duplicate buildings - Indonesia

### ISSUE THREAD

**Issue by chtnha** [mapbox/mapping#119]
Tasking Manager Link - http://tasks.openstreetmap.in/project/37

**Task**
To clean (delete) all the duplicate buildings and to add `building = yes` tag for the untagged buildings. 

**Area covered** 
Parts of South Sulawesi (SN) state, Indonesia. 

**Sources**
Bing 
Mapbox Satellite

**Timeline**
This is an ongoing map improvement. 

**Working group**
None

*Three overlapped duplicate buildings*

![duplicates](https://cloud.githubusercontent.com/assets/6770741/9808658/d2ef68a8-587e-11e5-9b83-bff542e349b3.gif)

*Buildings without tag*

![withouttag](https://cloud.githubusercontent.com/assets/6770741/9808638/937969bc-587e-11e5-9390-88c3d8a892a8.gif)

**Comment by planemad** [comment]
@chtnha what is the status of the cleanup? If there is no further actions, lets close this.

**Comment by chtnha** [comment]
@planemad The task is done!! Need to validate.

**Comment by chtnha** [comment]
**Cleanup done** :100: 

#### Summery
 * By selecting the task, I ran validation (Shift+V) in JOSM and It cleared 95% of the errors and duplicated buildings. 
 *  For the untagged buildings I used JOSM filter (Windows > Filter). Two filtering query I passed to select all the untagged buildings at once.  They are 
       1. `untagged` and 
       2. `type:node`
 
![cleanup1](https://cloud.githubusercontent.com/assets/6770741/9954277/450ff75a-5e05-11e5-80d6-f5823bd148ea.gif)


![screen shot 2015-09-18 at 12 39 54 pm](https://cloud.githubusercontent.com/assets/6770741/9953933/aa777512-5e02-11e5-90fe-1243d356630c.png)


![screen shot 2015-09-18 at 12 41 22 pm](https://cloud.githubusercontent.com/assets/6770741/9953937/b1eea13a-5e02-11e5-848d-7cf45e8fd691.png)
