### ISSUE TITLE
Sidewalk tagging

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapping#121]
In cities like Washington DC and San Francisco you'll find many sidewalks mapped as `highway=footway` but without the secondary tag [`footway=sidewalk`](http://wiki.openstreetmap.org/wiki/Tag:footway%3Dsidewalk).

This means sidewalks can't be styled consistently different than footways:

![](https://s3.amazonaws.com/f.cl.ly/items/1A1U000C0K2k252y3L3q/screen_shot_2015-09-18_at_4.38.18_pm_720.png)

## Action

- Go through San Francisco and Washington DC and add a `footway=sidewalk` tag to existing sidewalks tagged as `highway=footway`.

Only apply `footway=sidewalk` tag where satellite imagery clearly confirms a sidewalk.

**Comment by nickidlugash** [comment]
@lxbarth @Andygol there are also footways tagged `footway=sidewalk` that look like they should probably have this tag *removed* (they are footways that are not alongside roads), e.g. all the footways on San Francisco State University's campus:

![screen shot 2015-09-18 at 5 37 42 pm](https://cloud.githubusercontent.com/assets/5607844/9971714/ff150c5a-5e2b-11e5-80d1-0055e259023e.png)

@lxbarth do you think this issue should be addressed now as well? Or just focus on adding `footway=sidewalk` tags for now?

**Comment by lxbarth** [comment]
Y, let's remove the sidewalk tag where a footway *clearly* is not a sidewalk.

**Comment by planemad** [comment]
- Use [Overpass](http://overpass-turbo.eu/s/by8) to lookup `highway=footway` in DC and SF and inspect ways parellel to highways
- Add missing `footway=sidewalk` or `footway=crossing` tags [where applicable](http://wiki.openstreetmap.org/wiki/Tag:footway%3Dcrossing)  ![](https://cloud.githubusercontent.com/assets/126868/9976616/5a3d0232-5f07-11e5-9ae5-4f635dd81e98.png)
- Remove `footway=sidewalk` tags from footways that are not sidewalks

@lxbarth :+1: ?

**Comment by planemad** [comment]
**Before** Footways (blue), sidewalks (black) and crossings (red):

![screenshot 2015-09-21 12 44 36](https://cloud.githubusercontent.com/assets/126868/9986843/06ce2fc8-605f-11e5-91ad-fbc011943418.png)
![Uploading Screenshot 2015-09-21 12.47.32.png…]()

**Comment by planemad** [comment]
@nickidlugash we have some grey areas like in [this case](http://overpass-turbo.eu/s/bzm) where its unclear if we should add the sidewalk/crossing tags. Does it look ok?

**Comment by jinalfoflia** [comment]
I came across this issue where a part of the footway is a `sidewalk` and the rest is a `footway` with `bicycle=yes`. I have added the `sidewalk` tag only that particular part and retained the other tags i.e. `bicycle=yes`

![sideway](https://cloud.githubusercontent.com/assets/4470913/9989485/601ca25a-6076-11e5-98fc-f6179605d999.gif)

[Here](https://www.openstreetmap.org/way/295482375/history#map=16/37.7649/-122.5008) is the link to the way.

**Comment by planemad** [comment]
The guideline we have been following for sidewalks is: if the footway is adjacent the road kerb its a sidewalk, but if there is a separation like a patch of grass it remains a footway.

![](http://wiki.openstreetmap.org/w/images/thumb/b/b9/Sidewalk_and_zebra-crossing.jpg/240px-Sidewalk_and_zebra-crossing.jpg)

In the US, a physical separation seems pretty common, so not sure if this is to be tagged as a sidewalk or not:
![screenshot 2015-09-21 17 03 11](https://cloud.githubusercontent.com/assets/126868/9991007/d79207f0-6083-11e5-9c45-d281af2302ad.png)
 cc @nickidlugash @ajashton

**Comment by srividyacb** [comment]
JOSM Filters used while adding add tags to footways in DC and SF
Sometimes using tags as separate filters or combinations may be helpful:

* Separate filters: `highway=footway` , `footway=sidewalk` and `footway=crossing`.
* Combination filters: `highway=footway | footway=sidewalk` and `highway=footway | footway=crossing` 



     ![screenshot 2015-09-21 18 19 43](https://cloud.githubusercontent.com/assets/3423533/9992111/5b43a35c-608d-11e5-8adc-504be1edfed2.png)

**Comment by srividyacb** [comment]
Nice work @jinalfoflia @chtnha @planemad 
After tagging screenshots: 
- Black : Footway with `footway=sidewalk` tag
- Red : Footway with `footway=crossing` tag

[![screenshot 2015-09-21 18 28 50](https://cloud.githubusercontent.com/assets/3423533/9992423/b08f4620-608f-11e5-8aab-3a601b419d9e.png)](http://overpass-turbo.eu/s/bzJ)
*DC*
[![screenshot 2015-09-21 18 35 41](https://cloud.githubusercontent.com/assets/3423533/9992422/b08e7434-608f-11e5-99f5-ba20ff9428de.png)](http://overpass-turbo.eu/s/bzL)
*SF*

**Comment by nickidlugash** [comment]
Great job, data team!

**Comment by planemad** [comment]
No further actions, closing for now
