### ISSUE TITLE
`highway=pedestrian` polygon obscures water body

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapping#122]
This pedestrian polygon covers up a pool because it doesn't have the shape of the pool cut out of it:

![screen shot 2015-09-21 at 7 54 37 pm](https://cloud.githubusercontent.com/assets/5607844/10008298/197d953c-609b-11e5-8b00-0f32271eacc2.png)

[Feature in osm](http://www.openstreetmap.org/edit#map=18/38.89416/-77.00781).

**Comment by srividyacb** [comment]
@nickidlugash 
Fixed the multipolygon 
![screenshot 2015-09-22 09 53 29](https://cloud.githubusercontent.com/assets/3423533/10010912/d69304c6-610f-11e5-99ee-6e1c080face9.png)

**Comment by nickidlugash** [comment]
@srividyacb thanks for working on this! Could you double-check the features inside the pedestrian area? From aerial imagery, it looks to me like:

![senate-pool](https://cloud.githubusercontent.com/assets/5607844/10057808/266c2e22-6210-11e5-9f3a-ece3540908c4.png)

**Comment by srividyacb** [comment]
oh Sorry!! I thought the center one is the grass cover and the surrounding is water. Now I have made the changes. Please check it.

![screenshot 2015-09-24 10 47 00](https://cloud.githubusercontent.com/assets/3423533/10065866/a8349842-62a9-11e5-8a55-a89ceda0c9cf.png)

**Comment by nickidlugash** [comment]
Thanks @srividyacb! This looks good. @ajashton made [2 minor changes to it](http://www.openstreetmap.org/changeset/34251327) – he changed the feature around the pool to be `landuse=grass` and made it a multipolygon.

**Comment by srividyacb** [comment]
Great :+1:
