### ISSUE TITLE
Task: Retagging Mobile Home Hamlets

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#123]
**Description**
Change `place=hamlet` tag to `landuse=residential`

**Coverage**
California, USA.

**Instructions**
* Draw a polygon where there is a Mobile Home Park, add `landuse=residential` tag and copy the node's name.
![screen shot 2015-10-01 at 11 57 12 am](https://cloud.githubusercontent.com/assets/58878/10226105/acdf03d4-6833-11e5-833f-6c69e2978bf6.png)
* Remove `place=hamlet` node.
* In actively mapped areas, add a note.

**Comment by SK53** [comment]
When doing this please subtag with something like residential=mobile_home_park. You will need to review taginfo for plausible tags.

**Comment by planemad** [comment]
Closing now, will revisit in future if required.
