### ISSUE TITLE
DC motorway no longer under construction

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapping#124]
http://www.openstreetmap.org/edit#map=17/38.87716/-76.98823

![screen shot 2015-10-08 at 8 29 19 pm](https://cloud.githubusercontent.com/assets/5607844/10383313/4d192254-6dfb-11e5-935d-b61a037b8513.png)

I added this note: http://www.openstreetmap.org/note/448249#map=17/38.87740/-76.98809&layers=N

I'm not sure yet how to update the road geometries. Need to find updated satellite imagery to trace? As a start perhaps we could just change the access tag for the roads that do connect.

@mikemorris, who takes this route out of the city, made these comments: 

> - The map makes it looks like there’s no route from 17th onto penn but there is, if I remember correctly.
> -  There’s a concrete barrier where it says “DC access road" *(this part looks correct)*

**Comment by ericfischer** [comment]
Seems like a GPS track would be ideal for getting the new road geometry.

**Comment by nickidlugash** [comment]
@ericfischer oh good idea, thanks!

**Comment by pratikyadav** [comment]
![dc](https://cloud.githubusercontent.com/assets/12744420/11440737/1f1e6916-952b-11e5-8c98-aa54c31d4e66.gif)

Could't find GPS track to correctly identify the geometry of the missing road. Also no mapillary imagery to help. Would be great if someone can do a ground survey as its difficult to identify correctly where the`moterway` meet other roads (a mapillary trip could also help). For now its difficult to address the issues without updated imagery.

**Comment by planemad** [comment]
@pratikyadav why not message an active mapper in the area?

**Comment by pratikyadav** [comment]
@planemad  I have send a message to an active local mapper for clarification on this.

http://www.openstreetmap.org/user/DavidYJackson

**Comment by mikemorris** [comment]
I can ground survey this (it's a few blocks from my where I live) if someone can point me in the right direction of good tools to do so.

**Comment by pratikyadav** [comment]
@mikemorris  https://github.com/mapbox/mapping/wiki/Useful%20OSM%20Resources#survey-tools

Field paper is good for foot survey.

**Comment by pratikyadav** [comment]
User David http://www.openstreetmap.org/user/DavidYJackson responded back 
> Thank you for emailing me about this. I made some edits to the area in question. Some of my edits are not being saved. This area is still incorrect. I will attempt to try some more.

OSM history shows that he made the necessory changes.
http://www.openstreetmap.org/history#map=16/38.8775/-76.9852

Good to close here.

**Comment by pratikyadav** [comment]
> Ok. I was able to fix this area. It took a while and many changes. It should be correct now. Please review.
David

@nickidlugash  @mikemorris  can you review the changes plz. I cannot verify without local knowledge. Thanks.
