### ISSUE TITLE
Japan OSM improvement validation

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#127]
Further to #120 we need a workflow to validate the cleanup process. The strategy of doing a multiple pass mapping already ensures more than one person maps in each block and verifies the previous pass.

In addition to this lets also do random validation checks for each task to make sure nothing has been missed out and flag the blocks to the last mapper for rework.

@jinalfoflia @ruthmaben can you start reviewing edits in Osaka http://tasks.openstreetmap.in/project/54 and Mito http://tasks.openstreetmap.in/project/49 today

- Validate 10 blocks at random in each task
- If pass2 is not complete - invalidate
- Else **unlock** with a comment `pass2 validated`
- Post your findings of validated/invalidated count and any other observations to improve our workflow.

cc @Rub21 @lxbarth

**Comment by ruthmaben** [comment]
@jinalfoflia and I have started working on this @planemad

**Comment by ruthmaben** [comment]
@planemad: We chose random blocks to validate on both the tasks and here are few observations:

[Overall Observations](https://gist.github.com/ruthmaben/e3c65b51caf0e60c2885):

| Overall Tasks | Validated | Invalidated | Error % |Accuracy% |
| -------- | ------------ | --------------- | ------------- | ------------ |
| 32  |    14 | 18 | 56.25 | 43.75 |


| Whole task | Validated | Invalidated |
| -------- | ------------ | --------------- | 
| 18 | 1 | 17 |

| Split task | Validated | Invalidated |
| -------- | ------------ | --------------- | 
| 14 | 13 | 1 |

| Osaka | Validated | Invalidated |
| -------- | ------------ | --------------- | 
| 10 | 0 | 10 |

| Mito | Validated | Invalidated |
| -------- | ------------ | --------------- | 
| 22 | 14 | 8 |

- Most of the Major highways and tertiary roads are not merged 
- Most of the tertiary and major highways not aligned
- Many roads with different sources but same parameters are not merged - these could have been merged by deleting the two sources and combining the other parameters.
- Roads are not consistently aligned, i.e. some parts of roads are well aligned and some are not.
- Some part of the road that continues in the other block  needs to be merged  -  in such cases roads can be merged and uploaded immediately in-order to avoid conflict.
-  Update precise comments - If  no primary or tertiary roads found, then it should be updated with appropriate comment saying that " no road network present", and then update on passes done.

 Multiple passes done by more than one person not verified properly before moving to next pass. Overall, seems like we are jumping to pass two without completion of pass one and while working on pass two, we are not cross checking the previous pass before we mark the task as done (considering that we are currently focusing only on pass 1 and 2).

It's observed that, tasks which are split or with partial imagery are traced well - This means probably we need to split all tasks before working on them to reduce errors.

cc: @lxbarth @Rub21

**Comment by planemad** [comment]
Nice work @ruthmaben @jinalfoflia . We have two valuable findings from this:

> It's observed that, tasks which are split or with partial imagery are traced well - This means probably we need to split all tasks before working on them to reduce errors.

This is great, and the numbers reflect this very strongly. This is hard to enforce from the software side, maybe we can have a guideline for every mapper: If a task takes more than 30 mins, split it.

> Multiple passes done by more than one person not verified properly before moving to next pass. Overall, seems like we are jumping to pass two without completion of pass one and while working on pass two, we are not cross checking the previous pass before we mark the task as done (considering that we are currently focusing only on pass 1 and 2).

This is worrying and shows that we definitely need a validation step after every pass. Because our multiple pass cleanup workflow is a hack around the limitations of the tasking manager, we need to put some thought on how to best do this.

The only realistic way I see to do this is to create separate projects for each pass that we do. This will be more in tune with the regular tasking manager workflow of mapping + validation, with the downside that it will multiply the number of projects and tracking them all will require some more effort.

cc @Rub21 @lxbarth

**Comment by maning** [comment]
> This means probably we need to split all tasks before working on them to reduce errors.

It seems like 1 zoom higher from the current tile/task size is the sweet spot.  It this is still unmanageable, we can split further.

> tasks using the smallest tile size, but it may result in more tasks than needed in remote areas

Agreed, we should avoid making very small /tile/task size. 

Also, I did a random check of the [evaluated geometries](https://gist.github.com/ruthmaben/e3c65b51caf0e60c2885), it seems that a lot of them were edited by other other mappers outside @mapbox/team-data. Perhaps we should also consciously review edits by other community members?

**Comment by planemad** [comment]
> It seems like 1 zoom higher from the current tile/task size is the sweet spot. It this is still unmanageable, we can split further.
There is no way to fine tune the size currently in the task manager. Is this something we should add as a feature?

> it seems that a lot of them were edited by other other mappers outside the team
Ok, this makes sense as they were using iD :scream:

**Comment by maning** [comment]
> There is no way to fine tune the size currently in the task manager. Is this something we should add as a feature?

We can add custom geojson file if needed.

**Comment by planemad** [comment]
No next actions
