### ISSUE TITLE
Add guide on Managing validation errors

### ISSUE THREAD

**Issue by mikelmaron** [mapbox/mapping#128]
Validation in JOSM is powerful, but the warnings can be a bit opaque, the UI to work through Validations is a bit futzy (ex. the process of select and zooming to problem), and tips for handling particular types of problems are needed. 

Let's start a guide on this topic in particular.

**Comment by maning** [comment]
Adding here previous docs related to validation for reference:
* http://wiki.openstreetmap.org/wiki/JOSM/Validator
* http://learnosm.org/en/coordination/review/#data-validation
* http://wiki.openstreetmap.org/wiki/OSM_Tasking_Manager/Validating_data

**Comment by maning** [comment]
Done: https://github.com/mapbox/mapping/wiki/Reviewing-your-edits#josm-validator
