### ISSUE TITLE
Minor fixes to guides

### ISSUE THREAD

**Issue by mikelmaron** [mapbox/mapping#129]
These are few minor fixes needed to guides, which I can't immediately handle being a Mac newbie

* [x] where is the best place to download java? included link doesn't have mac option. https://java.com/en/download/ or http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
* [x] in getting started,the screen for enabling remote control inconsistent button width with screenshots above. need new screenshot

**Comment by maning** [comment]
@mikelmaron , I updated the screenshots for the EN version for a more consistent UI.

**Comment by mikelmaron** [comment]
:boom:
