### ISSUE TITLE
Hurricane Patricia Activation

### ISSUE THREAD

**Issue by maning** [mapbox/mapping#131]
Stub ticket to coordinate @mapbox/team-data efforts on HOT Activation for Hurricane Patricia.

**Comment by lxbarth** [comment]
- @rub21 monitoring hot channels, team ayacucho ready to hop into action if HOT activates

**Comment by lxbarth** [comment]
@rub21 - per chat, pls get relevant INEGI data ready for tracin layer. @mike we should communicate availabilty well.

**Comment by lxbarth** [comment]
Cc @mikelmaron

**Comment by Rub21** [comment]
@lxbarth @mikelmaron @maning  I am jumping in that now.

**Comment by camillacaros** [comment]
@lxbarth @mikelmaron @maning @Rub21 I'm working on identifying and processing imagery from DG right now. Let me know if any other imagery comes through from INEGI or other that needs to be processed/vetted against what we already have available.

**Comment by rodowi** [comment]
awesome!

Guys we are grouping official datasets here: http://busca.datos.gob.mx/#/grupos/rmx
We already signed the authorization letter to OSMF for this datasets

If you need something on ODBL let me know and we add it to datos.gob.mx

**Comment by camillacaros** [comment]
We are currently processing good color, nearly cloudless imagery to z19 for the following extents to Mapbox Satellite, which is available to HOT for tracing. Imagery will be live in a few hours. 

The extents cover the immediate HOT activation region along the coast + 50km inland, and fills in a few extra areas that have been identified as having poor imagery coverage by HOT coordination group.

[![screen shot 2015-10-23 at 6 03 01 pm](https://cloud.githubusercontent.com/assets/3768909/10708080/161ba1e8-79b1-11e5-9b33-63860e70c9cc.png)](https://gist.github.com/camillacaros/0c75cdf555105605b403)

**Comment by Rub21** [comment]
@lxbarth @rodowi @mikelmaron @maning @camillacaros : I've made a  diff  [ map](https://a.tiles.mapbox.com/v4/ruben.npoa0pi8/page.html?access_token=pk.eyJ1IjoicnViZW4iLCJhIjoiYlBrdkpRWSJ9.JgDDxJkvDn3us36aGzR6vg#8/19.821/-99.841)  OSM vs RNC and  CGU , This is for whole Mexico,  you can find the missing roads an check out the offset , 
The link for JOSM and iD:
`https://a.tiles.mapbox.com/v4/ruben.f0f2a255/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoicnViZW4iLCJhIjoiYlBrdkpRWSJ9.JgDDxJkvDn3us36aGzR6vg`
![image](https://cloud.githubusercontent.com/assets/1152236/10711697/41a552d0-7a49-11e5-83ff-ad637d80c042.png)

**Comment by camillacaros** [comment]
Hi folks, I just checked in on imagery renders -- looks like all imagery has been processed. There may be some caching issues as final tiles roll in, but otherwise all should be there.

**Comment by maning** [comment]
@camillacaros and @Rub21!

**Comment by rodowi** [comment]
:+1: so awesome @Rub21! 

would be great to share this on the talk-mx list

**Comment by Rub21** [comment]
@rodowi , tienes razon, ahora mismo...

**Comment by gundersen** [comment]
@Rub21 @maning any plans to post a few before and after shots of the tracking work? Also, how many edits have been made as part of the activation? How maybe in the first 24 hours? cc @lxbarth - FYI talking to Re/code and might loop this work in, specifically in terms of our satellite imagery buy helping us make better data.

**Comment by maning** [comment]
![mx-hurricane](https://cloud.githubusercontent.com/assets/371666/10736196/a8dcaaf4-7c31-11e5-87f8-e5a7bfa0c0ad.gif)
_Data edits in the first 72 hours_

* 432 contributors mapped 5.6k miles of road + 72k buildings in 72hrs with substantial contributions from the @mapbox/team-data 
* Processed DG imagery to improved coverage over priority areas
* Analyzed INEGI road data to identify missing roads and road names in OSM data.
