### ISSUE TITLE
Afghan EQ HOT Activation

### ISSUE THREAD

**Issue by maning** [mapbox/mapping#132]
HOT Activated for [7.5 EQ over Afghanistan-Pakistan-India Region](http://wiki.openstreetmap.org/wiki/2015_Eastern_Afghanistan_Earthquake). @maning @shvrm @geohacker is coordinating with the HOT Activators via skype channel.

Current activities
- [x] Improve imagery coverage over affected areas. 
- [x] Setup priority areas for preparation of Tasking Manager projects.
- [x] Link with local contacts in the region for situation on the ground.
- [x] @mapbox/team-data To work on TM projects.

cc/ @camillacaros @lxbarth @gundersen @mikelmaron

**Comment by camillacaros** [comment]
@maning @lxbarth @gundersen @mikelmaron 

Imagery to z19 has been rendered for the entire Nangarhar province. [Coverage gist map.](https://gist.github.com/camillacaros/3bc2d9c0c040841cc4af)

I'm working on the next round of imagery to publish for priority cities farther to the North in Badakshan, and Takhar provinces now.

**Comment by Rub21** [comment]
@maning @lxbarth @gundersen @mikelmaron @camillacaros :

Mapbox Peru Office started  working since today in http://tasks.hotosm.org/project/1264, we are  focusing in the red area. 

![image](https://cloud.githubusercontent.com/assets/1152236/10772861/2424847c-7cc6-11e5-88cc-e31e9be381de.png)

**Comment by camillacaros** [comment]
Sounds great @Rub21 I've moved fwd with processing imagery for the following [area](https://gist.github.com/camillacaros/8f826e98cd8e2969bcd7), which covers that priority activation zone as well as the larger activation zone. Hi-res imagery is currently flowing into `mapbox.satellite` for this HOT activation region down to zoom 19 and is available to use for tracing. 

[<img width="786" alt="screen shot 2015-10-27 at 2 42 17 pm" src="https://cloud.githubusercontent.com/assets/3768909/10773524/1114a900-7cb9-11e5-887c-6c9e9f70e0f6.png">](https://gist.github.com/camillacaros/8f826e98cd8e2969bcd7)
*Please note this extent will not be fully processed for another few hours, but it is all in motion.*

cc @maning @lxbarth @gundersen @mikelmaron

**Comment by pratikyadav** [comment]
Seeing a lot of 2010 imported data from user - [afgroadsimport](https://www.openstreetmap.org/user/afgroadsimport). The source of this dataset is [Afghanistan Information Managment Service](http://www.aims.org.af/index.aspx).

There are 2 issues with these import-
1. Alignment - based on low resoultion imagery are thus are not aligned.
2. Missing connection- Overlaping nodes on each other but not merged.

![af](https://cloud.githubusercontent.com/assets/12744420/10781560/2bbf82a6-7d6e-11e5-9fba-16d9fa1b5d8f.gif)

cc @mapbox/team-data

**Comment by maning** [comment]
![roads_vs_rivers](https://cloud.githubusercontent.com/assets/353700/10781637/d5509a6c-7d6e-11e5-818f-dcb8d7b3cf88.gif)

Roads and dry river beds maybe confusing, use Mapbox Terrain or OpenCycleMap to compare.  Rivers in gullies. Roads/paths normally follow ridges. There are exceptions of course

**Comment by pratikyadav** [comment]
![screen shot 2015-10-28 at 3 48 35 pm](https://cloud.githubusercontent.com/assets/12744420/10785624/63af7fdc-7d8b-11e5-9c7b-11fe4a7967b4.png)


**Warning**
Make sure you don't get confused between canals and roads. Found some canals that looked like paved roads.

cc @mapbox/team-data

**Comment by maning** [comment]
## 2015-10-28

### Wins
:trophy: 10 @mapbox/india-office worked on [TM Project 1264](http://tasks.hotosm.org/project/1264)
:trophy: Imagery updates to fill-in gaps from Bing
:trophy: 22% done for [TM Project 1264](http://tasks.hotosm.org/project/1264) forcusing on Kunduz and Fayzabad priority areas

### Tracing issues

* Easy to trace residential areas.
* Difficult to differentiate dry riverbed over tracks https://github.com/mapbox/mapping/issues/132#issuecomment-151743203
* Fixing misaligned imported roads is taking time isolated settlements https://github.com/mapbox/mapping/issues/132#issuecomment-151741698
* Many isolated settlements particularly on the eastern section of Fayzabad

**Comment by ruthmaben** [comment]
![screenshot 2015-10-29 17 31 04](https://cloud.githubusercontent.com/assets/10308123/10817873/ffc9913c-7e62-11e5-971b-325d2e9bba21.png)

@mapbox/team-data - You may come across similar tags `building=yes`. Need to change this to `landuse=residential`

**Comment by maning** [comment]
## 2015-10-29

### Wins
:trophy: 12 @mapbox/india-office + @Andygol  worked on [TM Project 1264](http://tasks.hotosm.org/project/1264).
:trophy: 32% (+10% from yesterday) done for [TM Project 1264](http://tasks.hotosm.org/project/1264) focusing on Kunduz and Fayzabad priority areas.
:trophy: HOT Activators [processed Post-EQ imagery from Pleiades](https://lists.openstreetmap.org/pipermail/talk/2015-October/074614.html).  As agreed in skype, we keep this imagery for now, unless we get Post-EQ request.
:trophy: Nailing #ogpmapping!

![screen shot 2015-10-29 at 7 32 07 pm](https://cloud.githubusercontent.com/assets/353700/10820568/e8075096-7e73-11e5-912d-fa2431a058f0.png)


### Editing issues

*  Some [residential areas were tagged as buildings](https://github.com/mapbox/mapping/issues/132#issuecomment-152159028).

**Comment by maning** [comment]
Per voice with @planemad, we decided we will do validation focusing on checking consistency of road tagging.  This is to respond to the [request of the Activators](https://lists.openstreetmap.org/pipermail/hot/2015-November/010384.html).

@planemad Already made a visualization for [Nepal](https://api.mapbox.com/v4/planemad.5504651b/page.html?access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ#14/36.7106/68.8669).

Some of the @mapbox/team-data will do it this week.

**Comment by maning** [comment]
> validation focusing on checking consistency of road tagging. 

Done validating lower half of the TM project 1264.  Closing.
