### ISSUE TITLE
[SF Buildings] Menlo Park

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapping#135]
Prepare and lead a task to trace buildings in Menlo Park and around. Some of it is already traced.

![](https://www.evernote.com/shard/s210/sh/27bf2c7f-8b6a-414b-a2b7-3118d68594dc/cf215e79e8f341e2/res/414ff7a3-aed0-4af2-ad84-fb20dd2c38b1/skitch.png?resizeSmall&width=832)

http://www.openstreetmap.org/#map=13/37.4506/-122.1778

**Comment by ediyes** [comment]
@mapbox/team-data  The task manager for this ticket it: http://tasks.openstreetmap.us/project/11

**Comment by ediyes** [comment]
#### Done!!! @lxbarth 
![buildingmp](https://cloud.githubusercontent.com/assets/5991158/11579085/00a0f06c-99f9-11e5-8ba3-144a29ac3480.png)

**Buen trabajo chicos** :+1: 

cc @mapbox/team-data

**Comment by maning** [comment]
Awesome!!!

**Comment by ramyaragupathy** [comment]
Awesome work @mapbox/peru-office!  We ran a review of your edits today.

### Review Process

* In Overpass, download buildings edited by the user in Menlo Park. Open in JOSM.

```
[out:xml][timeout:25];
// fetch area “Menlo Park, USA” to search in
{{geocodeArea:Menlo Park, USA}}->.searchArea;
// gather results
(
  node(user:"RichRico")["building"](area.searchArea);
  way(user:"RichRico")["building"](area.searchArea);
  relation(user:"RichRico")["building"](area.searchArea);
);

out meta;
>;
out meta qt;
```

* In JOSM, click **Search**, add a new filter `user:username building`.  Add selected buildings in todo list.
* Visually inspect every building at >= z20.
* Fix errors if needed.
* Run JOSM validator for all selected buildings.
* Upload edits.


### Results

user | # of buildings reviewed | correction visual check | correction via JOSM Validator
--- | ---- | ---- | ----
ediyes | 2811 | improved geometry of 24 buildings | 0
calfarome | 498 | improved geometry of 4 buildings | 0
samely | 123| 0 | 0
karitotp | 502 | 1 missing building | 0
dannykath | 1224 |  improved geometry of 18 buildings| 0 
RichRico | 480 | 0 | 0


### Observations

This is not a 100% percent review, :but we think we covered enough number of samples to conclude **that your edits are AWESOME**! :clap: 
### Next steps
- [ ] Archive the TM project and close this ticket. 
- [ ] @lxbarth, should we review the [Mountain View](https://github.com/mapbox/mapping/issues/136) edits?
- [ ] Move to the next task of [tracing buildings to the rest of SF Peninsula](https://github.com/mapbox/mapping/issues/141).

### Other issues
* We think this review process is faster than validating each task in the TM manager. As a result of this process we are [proposing an enhancement to the Tasking Manager](https://github.com/hotosm/osm-tasking-manager2/issues/713) so others can use a similar workflow if they need to.
* In the next weekly peer review, lets exclude this project so as not to duplicate review efforts.


cc/ @geohacker @planemad @rub21 @lxbarth

**Comment by lxbarth** [comment]
Woah, nice work everyone!

>  @lxbarth, should we review the Mountain View edits?

yes please!
