### ISSUE TITLE
[SF Buildings] Mountain View

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapping#136]
Prepare and lead a task to trace buildings in Mountain View, Los Altos and around. Some of it is already traced. 

![](https://www.evernote.com/shard/s210/sh/1c15c016-61f6-4afe-b677-14ffdae55019/6726eebc56902427/res/6bd70c19-570a-4e23-a2f3-82593e470810/skitch.png?resizeSmall&width=832)

http://www.openstreetmap.org/#map=13/37.3828/-122.0870

**Comment by Rub21** [comment]
@mapbox/team-data  I've created task manager for this ticket. http://tasks.openstreetmap.us/project/9

@ediyes @luisalanya , ya pueden empezar con esta tarea :)

**Comment by karitotp** [comment]
Esta es la visualización de nuestro avance hasta el momento.

![visualizacion mountain view](https://cloud.githubusercontent.com/assets/11504548/11313291/c886a63a-8fa9-11e5-8e32-8526f1166d38.png)

cc. @lxbarth, @Rub21

**Comment by andreasviglakis** [comment]
wow!

**Comment by shvrm** [comment]
amazing guys @mapbox/peru-office

**Comment by planemad** [comment]
:rocket: crazy stuff!

**Comment by jothirnadh** [comment]
The colour combination is so attractive... amazing work @mapbox/peru-office

**Comment by ianshward** [comment]
:eyes: Nice work!!!  +1 on that color combo, it is spectacular.

**Comment by abhisheksaikia** [comment]
This is incredible stuff @mapbox/peru-office

**Comment by ruthmaben** [comment]
Nice work @mapbox/peru-office!

**Comment by oini** [comment]
Wow! Great work @mapbox/peru-office.

**Comment by bonniebogle** [comment]
Great work everyone, this is fantastic!

**Comment by ediyes** [comment]
Done!!!  :+1: 
![buildingmv](https://cloud.githubusercontent.com/assets/5991158/11492241/51085b46-97b8-11e5-9370-5e45af9c3ce3.png)

cc @lxbarth @Rub21

**Comment by lxbarth** [comment]
:boom: !!

**Comment by mikelmaron** [comment]
As someone who has spent a lot of time there, I can say, Mountain View has
never looked better!

**Comment by ramyaragupathy** [comment]
Here is an overview of the review work for Mountain View buildings.

**Team**: @abhisheksaikia @nikhilprabhakar @jothirnadh @ramyaragupathy

### Quality metrics

* In Overpass, download buildings edited by the user in Moutain view. Open in JOSM.

```
[out:xml][timeout:25];

{{geocodeArea:Los Altos, USA}}->.searchArea;
// gather results
(
  node(user:"RichRico")["building"](area.searchArea);
  way(user:"RichRico")["building"](area.searchArea);
  relation(user:"RichRico")["building"](area.searchArea);
);

out meta;
>;
out meta qt;
```

* In JOSM, click **Search**, add a new filter `user:username building`.  Add selected buildings in todo list.
* Visually inspect every building at >= z20.
* Fix errors if needed.
* Run JOSM validator for all selected buildings.
* Upload edits.




user | # of buildings reviewed | correction visual check | correction via JOSM Validator
--- | ---- | ---- | ----
ediyes |  4022 | 190 |0  |
calfarome | 1664 |29|0
samely | 1510 |  165 | 2
karitotp | 2045|37|0
dannykath | 98 | 15 | 3
RichRico | 1419 | 10 | 0
Luis36995 | 77 | 3|0

### Validating the completeness of the project

Also we reviewed the individual blocks in the TM to ensure the completeness of the project. 

### Observations


- In some cases there is an inconsistency in using Mapbox/Bing as the source. Parts of the task uses Bing and the rest uses Mapbox interchangeably. 

- Sometimes an entire bunch of buildings is missing in one of the imagery but it is clearly visible in the other source.

![change in images](https://cloud.githubusercontent.com/assets/8401827/11649450/1f2f11bc-9da5-11e5-9b70-26afa28c9ba7.gif) 

![mapbox bing 3](https://cloud.githubusercontent.com/assets/13744156/11625577/e65b23ce-9d01-11e5-8c50-76c25992d51a.gif)

- Also in some cases the outline of the buildings are entirely different in the two imagery

![mapbox bing](https://cloud.githubusercontent.com/assets/13744156/11625098/44946d5a-9cfe-11e5-826b-934512a19a69.gif)



In such cases the only option is to stick to the latest imagery. But the [Mapbox imagery seems to be missing metadata on capture date](https://github.com/mapbox/satellite/issues/1069), so we are not able to decide which image is the latest. For this validation process, we ran a history check of discrepant objects to decide the latest version.

### Recommendations

For the [SF peninsula building task](http://tasks.openstreetmap.us/project/12), it would be great if the team just sticks to Bing imagery as the source(this seems to be the latest in most places) and fall back to Mapbox imagery only in case of non-availability of Bing imagery.



cc/ @geohacker @planemad @rub21 @lxbarth

**Comment by lxbarth** [comment]
Awesome review post.

> In some cases there is an inconsistency in using Mapbox/Bing as the source. Parts of the task uses Bing and the rest uses Mapbox interchangeably.

@ramyaragupathy do you see a need to go back and review the accuracy of mapping in the cases where Mapbox imagery was used?

@ediyes - in which cases did the team use Mapbox versus Bing imagery?

**Comment by abhisheksaikia** [comment]
@lxbarth I think in this case we should wait for the satellite team to get back on [the ticket we raised for metadata information in Mapbox imagery](https://github.com/mapbox/satellite/issues/1069). 

> @ramyaragupathy do you see a need to go back and review the accuracy of mapping in the cases where Mapbox imagery was used?

At present there is no sure way to determine which among Bing and Mapbox has the more updated imagery as Mapbox is missing Metadata information. Until we have this information, we should hold on going back and reviewing the task.

**Comment by ramyaragupathy** [comment]
> Until we have this information, we should hold on going back and reviewing the task.

 :+1:  Also @lxbarth we don't have a log of places that used Mapbox imagery in the task.

**Comment by ediyes** [comment]
> @ediyes - in which cases did the team use Mapbox versus Bing imagery?

@lxbarth  todos utilizamos el Bing, pero habian edificios ya hechos en algunos lugares y para mejorarlo utilizamos la imagen de Mapbox cuando no existia el Bing.
