### ISSUE TITLE
Add feedback dialog to combine-highways script

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#137]
The [combine-highways](https://github.com/mapbox/mapping/tree/master/JOSM/scripts/combine-highways) JOSM script has been really useful to easily merge the large number of split roads in Japan. 

What would be nice to add is a dialog that display how many roads was combined so that the user knows the script worked as it should have. Currently there is no feedback to the user after running the script.

cc @Rub21

**Comment by Rub21** [comment]
@planemad thanks for feedback , I am  adding this on may to-do stuff

**Comment by Rub21** [comment]
done!, after run the script , it will give you a alert with summary of roads. 

![image](https://cloud.githubusercontent.com/assets/1152236/11225263/3753e3b2-8d47-11e5-9aa7-3291bb569c8c.png)
