### ISSUE TITLE
Highways: Improving coverage of road network in India

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#138]
As per the latest [OSM data metrics report](https://www.mapbox.com/data-platform/country/#india) India has one of the lowest highway coverage levels for a big country (apart from China). Lets collect resources that can help us identify the most important missing highways and map them.

**Next Steps**
- Discuss strategy on evaluating existing coverage and prioritize what to map
- Collect mapping resources

cc @mapbox/team-data

**Comment by shravan91** [comment]
Let me know how can I help @planemad. I can help in mapping as well as in collecting resources.

**Comment by planemad** [comment]
To start, we are collating the road length statistics per state for each class of road from various sources. This will help give a more granular coverage % and a better idea of whats missing where.

Contribute to the spreadsheet [here](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit?usp=sharing)

**Comment by planemad** [comment]
OSM road coverage statistics by state is now **[here](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit?pli=1#gid=1153498981&vpid=B2)**

Generated using [osm-coverage](https://github.com/mapbox/osm-coverage) tile reduce processor.

**Comment by mikelmaron** [comment]
Super cool. 

How is this best shared with the osm-in community, to start to address gaps? What about adapting the /data-platform/countries page for Indian states, on openstreetmap.in? How easy to add an overview map of completeness in all states? Could be a cool example for other communities to follow. Or we could think about how to add in more detail on the mapbox.com pages.

**Comment by planemad** [comment]
We're cleaning up our workflow documentation

@mikelmaron moving the conversation here https://github.com/mapbox/mapping/issues/142#issuecomment-160618405
