### ISSUE TITLE
[Mapillary] Improving Routing Information Using Mapillary Imagery [trial]

### ISSUE THREAD

**Issue by oini** [mapbox/mapping#139]
**Objective:** Mapillary images are a good source to verify and add information to OpenStreetMap. Our goal is to use [Mapillary](https://www.mapillary.com) street photos to improve the map data like turn-restrictions and speed limits.

**Point of contact:** @jinalfoflia

**Team:** @oini @aarthykc @jinalfoflia

#### Task Workflow [Trial in progress]

Here is the [**work-flow**](https://gist.github.com/jinalfoflia/88b2c3d0a49c54c4316d) that can be followed while using Mapillary to add data in OSM.

Here is an over-view of the work-flow:

**Imagery layer:** `tms:http://d2cd86j8eqns9s.cloudfront.net/tiles/{zoom}/{x}/{y}.png` (login to your Mapillary account  and go to `Preferences -> Display Settings -> Mapillary`).
(*This layer can be used to verify if Mapillary images are available for that particular area*)

Step 1: Pick a task from the tasking manager.
Step 2: Load the mapillary layer in JOSM
Step 3: Inspect images in Mapillary to find useful traffic information that can be added in OSM
Step 4: Inspect multiple images to be sure about the signs that is to be added.
Step 5: Use `turn restriction` plugin to add the turn-restrictions.

**Tools used:**

- [Mapillary plugin for JOSM](http://blog.mapillary.com/update/2015/06/25/josm-mapillary.html)
- [Turnrestrictions plugin for JOSM](http://wiki.openstreetmap.org/wiki/JOSM/Plugins/Turnrestrictions)
- [RoadSigns plugin for JOSM](http://wiki.openstreetmap.org/wiki/JOSM/Plugins/RoadSigns) 

**Map features that can be mapped:**

- [Turn restrictions](http://wiki.openstreetmap.org/wiki/Relation:restriction)
- [Speed limits](http://wiki.openstreetmap.org/wiki/Key:maxspeed) `maxspeed=X mph`
- Traffic signals `highway=traffic_signals`
- **Add note** for temporary barriers or access restrictions if image is less than a month old

For this purpose, we have come up with the [list of traffic symbols](https://gist.github.com/oini/f2f7e397f8b93a552489) that we shall be looking out for and how we will be adding the information to OSM.

**Changeset Comment:** `Adding traffic data using Mapillary (https://github.com/mapbox/mapping/issues/139)`
**Imagery:** `Bing and Mapillary`

--

**Other Resources :** 
- [Mapping Turn Lanes in OpenStreetMap] (https://www.mapbox.com/blog/turn-lanes-mapping/)
- [Diary post on using Mapillary images for mapping in OSM](https://www.openstreetmap.org/user/jinalfoflia/diary/)

--
#### Progress Milestones

**Week 1 [23 - 27 Nov' 15]:** The team did a trail run with the workflow and details are captured [here](https://github.com/mapbox/mapping/issues/139#issuecomment-160403278).

**Week 2 [ 30' Nov 15 to 4th Dec '15]:** The team worked in Boston area and all details are captured [here](https://github.com/mapbox/mapping/issues/139#issuecomment-162439043)

**Comment by jinalfoflia** [comment]
@aarthykc @oini and I worked in these areas on Thursday and Friday.

#### Thursday [26/Nov/2015]: [Washington DC](http://tasks.openstreetmap.in/project/60)

We put up a task in the [Tasking Manager](http://tasks.openstreetmap.in/project/60) with each block size of 0.16 square-km
Time taken: 1 hour 40 mins
Number of blocks covered : 19

*[Our Edits]( http://overpass-turbo.eu/s/cWG):*
- Number of turn restrictions added: [3](http://overpass-turbo.eu/s/cWM)
- Number of speed-limits added: [11](http://overpass-turbo.eu/s/cWN)
![screen shot 2015-11-26 at 6 45 27 pm](https://cloud.githubusercontent.com/assets/1933377/11423855/1e5a38b0-946e-11e5-9214-3cd24cd4d594.png)

--

#### Friday[27/NOV/2015]: [Boston](http://tasks.openstreetmap.in/project/61)

We put up a task in the [tasking manager](http://tasks.openstreetmap.in/project/61) with each block size of 0.25 square-km

Time taken : 1 hour
Number of blocks covered: 3
*[Our Edits]( http://overpass-turbo.eu/s/cZm):*
- Number of turn restrictions added: [6](http://overpass-turbo.eu/s/cZn)
- Number of speed-limits added: [2](http://overpass-turbo.eu/s/cZo)
![screen shot 2015-11-29 at 4 35 39 pm](https://cloud.githubusercontent.com/assets/4470913/11456708/56774fb2-96b7-11e5-8ed7-bf5137ae8c78.png)

/CC @planemad @shvrm

**Comment by jinalfoflia** [comment]
I have posted the [diary](https://www.openstreetmap.org/user/jinalfoflia/diary) in OSM about the current work-flow and posted these questions to the community:

While mapping, the team came across the following issues:

##### While mapping `turn restrictions`

- They are easily visible in the imagery and map but are leading to `splitting` of major roads and also leading to addition of multiple `relations`
- Is this something we need to follow while adding the turn restrictions or there is a better-way?

##### While mapping `speed-limits`

- It is difficult to identify the start and end point of the road to which the speed-limit should be applied.
- Is there a better way to add speed limits or any convention that is followed while adding them?

**Comment by jinalfoflia** [comment]
@oini and I did trial runs for mapping `turn-restrictions` using the [Mapillary fork of iD](http://mapillary.github.io/iD/).

#### Obsevartion

Feature | Mapillary plugin for JOSM | Mapillary fork of iD
------- | ------------------------- | --------------------
**Identifying type of Traffic Symbols** | Detects images with traffic signs in them but fails to display the type of traffic sign ![josm_mapillary](https://cloud.githubusercontent.com/assets/4470913/11524447/fcb77646-98f0-11e5-8fe8-9324f23f3455.png) | Detects images with traffic signs in them as well as displays the type of traffic sign ![screen shot 2015-12-02 at 12 25 02 pm](https://cloud.githubusercontent.com/assets/1933377/11524381/619cd110-98f0-11e5-86a1-c8a74133c268.png)
**Working with Mapillary images** | Extremely easy interface to navigate through images and zoom in and out of them ![mapi1](https://cloud.githubusercontent.com/assets/1933377/11524547/8c802386-98f1-11e5-8ac1-1bcba76514c9.gif) | Each image opens in the Mapillary site on a new tab in the browser and both iD and the Mapillary provides no provision to zoom in and out of images ![id_map](https://cloud.githubusercontent.com/assets/4470913/11499802/b69b86f4-984e-11e5-830c-dabb68188100.gif)
**Offset in GPX location of images** | None found so far | Noticed slight offset here: ![screen_shot_2015-12-01_at_5_48_01_pm](https://cloud.githubusercontent.com/assets/4470913/11524680/cdb4610e-98f2-11e5-8016-904f427f63fb.png)
**Working with Tasking Manager** | Very easy | Not possible
**Identifying already mapped traffic signs** | Traffic-Signals Map Paint Style makes it easier to view traffic information that has already been mapped | One needs to click on the respective roads to check for tags and relations
**Time required to map each sign(from detection to adding them)** | ~2 minutes | ~3-4 minutes

### Conclusion

- The time taken to map each turn-restriction is lesser in JOSM than in iD
- Inspecting the location of the sign requires most of the time
- The time taken to map an entire area is almost the same for both JOSM and iD
- We found using JOSM to be more convenient as it is easier to navigate through images and zoom in and out of them unlike iD where we need to shuffle multiple tabs for this purpose

/cc @shvrm @planemad @geohacker @maning

**Comment by jinalfoflia** [comment]
We're wrapped up adding turn restrictions in the [Boston area](http://tasks.openstreetmap.in/project/61). Here are the full statistics:

We have added [28 turn restrictions](http://overpass-turbo.eu/s/d80) and [2 speed limits](http://overpass-turbo.eu/s/cZo)

![screen shot 2015-12-07 at 11 04 15 am](https://cloud.githubusercontent.com/assets/4470913/11619888/d38d3838-9cd2-11e5-9fa2-d17c5b41c814.png)

#### Outcomes

- Time spent on mapping : 8 hours with approximately spending 3 minutes to map a single turn-restriction
- Over the course of time, time taken to complete a single block reduced drastically from **over an hour** to an average of **20 mins**.

### Next Action(s)

- The next city we should run out is Minneapolis + Saint Paul , using polished up [workflow](https://github.com/mapbox/mapping/issues/139#issue-118602203).

#### Minneapolis+ Saint Paul Overview: Adding Turn-Restrictions

- There are only [83 turn-restrictions](http://overpass-turbo.eu/s/d83)
- There is good [Mapillary coverage](http://www.mapillary.com/map/search/44.86769137383757/-93.02129177288266/8.649029718998765) in this area.
- Ideally we should be wrapping up this task by Thursday(10th of Dec). *Spending 3 hours on daily basis with a team of 3*
* **link to tasking manager for Minneapolis will updated soon**

/cc @mikelmaron @shvrm @oini @planemad @aarthykc @Andygol

**Comment by Andygol** [comment]
Useful to add `tms:http://d2cd86j8eqns9s.cloudfront.net/tiles/{zoom}/{x}/{y}.png` to **imagery** tab for the task 
![osm tasking manager - 2015-12-07 16-27-22](https://cloud.githubusercontent.com/assets/369696/11625259/8b953ada-9cff-11e5-92dc-1e3f5e77b0de.png)

**Comment by Andygol** [comment]
@jinalfoflia 
faced with 403 error while downloading mapillary layer :disappointed: 
![java openstreetmap editor 2015-12-07 16-54-03](https://cloud.githubusercontent.com/assets/369696/11625756/608a48ea-9d03-11e5-9ebb-78db050798d4.png)

do I need to login into mapillary account?
![preferences 2015-12-07 16-57-54](https://cloud.githubusercontent.com/assets/369696/11625820/cd36f36c-9d03-11e5-9091-0742f13651fa.png)

**Comment by jinalfoflia** [comment]
> do I need to login into mapillary account?

@Andygol, yes you need to log-in to your Mapillary account (`Preferences -> Display Settings -> Mapillary`). 
Also after downloading the data layer, if the imagery is not being displayed, you can Zoom-out and Zoom-in again.

**Comment by jinalfoflia** [comment]
We have decided to put the mapping of turn restrictions using Mapillary Imagery on hold. So as to refine the current workflow.

**Comment by jinalfoflia** [comment]
@pratikyadav and me started working with [Improve OSM](https://www.openstreetmap.org/user/mvexel/diary/37571) plugin to map turn-restrictions. We started mapping the turn-restrictions using the [web-interface](http://improve-osm.org/#12.2111800,-36.2988300,4/OPEN/true,1-0-0/true,1-0-0/true,1-0) as the usage of plugin in JOSM was resulting in JOSM crashing.
We have followed the same [work-flow](https://github.com/mapbox/mapping/issues/139#issue-118602203) as mentioned previously, except for the addition of one step.
- Improve OSM helps in detecting the probability of a turn-restriction being there at a particular place, thus eliminating the need for us to go through multiple images in Mapillary. Hence making this work-flow more efficient.

#### Observations:

Area: [Mountain view](http://improve-osm.org/#37.4020737,-122.0850563,13/OPEN/false,1-0-0/false,1-0-0/true,1-0)

- Total number of turn restrictions detected by Improve OSM: **16**
- Number of false positives: **4**  (Even though Mapillary imagery was available, the turn-restriction was not seen in the images)
       - Example: http://improve-osm.org/#37.4275870,-122.1444243,18/OPEN/false,1-0-0/false,1-0-0/true,1-0
- No mappilary imagery : **7** (Mapillary imagery was unavailable)
       - http://improve-osm.org/#37.5610147,-122.2730792,18/OPEN/false,1-0-0/false,1-0-0/true,1-0

- Already mapped: **3**
   -  The [lane](https://www.openstreetmap.org/way/24054673/history) is mapped with `Straight only` tag. So it adds upto the restriction (http://improve-osm.org/#37.5432758,-122.2893065,18/OPEN/false,1-0-0/false,1-0-0/true,1-0)
   - https://www.openstreetmap.org/way/129132246/history (http://improve-osm.org/#37.4534237,-122.1823347,18/OPEN/false,1-0-0/false,1-0-0/true,1-0)
   - http://improve-osm.org/#37.4433772,-122.1621537,18/OPEN/false,1-0-0/false,1-0-0/true,1-0

- Number of Turn restrictions mapped: **2** 
(https://www.openstreetmap.org/changeset/36934048)
- Number mapped, but not detected by the plugin : **1** (https://www.openstreetmap.org/changeset/36935047)

/cc @planemad @shvrm @maning

**Comment by lxbarth** [comment]
@jinalfoflia @pratikyadav - very interesting. How long did it take you to go through this work?

**Comment by jinalfoflia** [comment]
> @jinalfoflia @pratikyadav - very interesting. How long did it take you to go through this work?

@lxbarth: We spent approximately 4 hours to go through this work. (it includes the work we did on Thursday and Friday)

**Comment by jinalfoflia** [comment]
@gyllen is it possible to get an overlay of Mapillary images with the traffic symbols like it is in the iD editor? It would make identifying the turn-restrictions more convenient using JOSM.

cc @planemad @oini @lxbarth

**Comment by gyllen** [comment]
@jinalfoflia We have a vector tile layer for it, could you guys work with that?

**Comment by jinalfoflia** [comment]
@gyllen thank you for the heads up! This is something that we can use for the future projects.

**Comment by gyllen** [comment]
@jinalfoflia Just let me know when you need it and I will point you in the right direction.

**Comment by jinalfoflia** [comment]
@gyllen thank you! It would be great if you could point us to the vector layer.


/cc @planemad @oini @geohacker

**Comment by gyllen** [comment]
Here is an experimental URL `http://mapillary-vector.mapillary.io/tiles/{z}/{x}/{y}.mapbox?ors=key,l,package,value,validated,image_key,user,score,obj,rect`

Please note that this is currently alpha, and if you use it I expect feedback from you guys on how its working.

**Comment by jinalfoflia** [comment]
@gyllen this is great, thank you!

> Please note that this is currently alpha, and if you use it I expect feedback from you guys on how its working.

Sure thing!

**Comment by gyllen** [comment]
@jinalfoflia Let me know if this works for you.

**Comment by jinalfoflia** [comment]
Continuing this quest further in this [ticket](https://github.com/mapbox/mapping/issues/177). Closing this.

/cc @lxbarth @planemad @gyllen
