### ISSUE TITLE
[Highway Mapping India]: Improving the Expressways coverage in India

### ISSUE THREAD

**Issue by nikhilprabhakar** [mapbox/mapping#140]
**Objective:** Use the [statistics collected](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit?pli=1#gid=1997886170&vpid=A1) on the expressways from [wikipedia](https://en.wikipedia.org/wiki/Expressways_in_India) to add/improve the OSM coverage of motorways in India.

**Scope:** Review existing coverage of expressways in OSM and add/reclassify missing expressways.

**Team and Time estimate:** @jothirnadh @abhisheksaikia and @nikhilprabhakar will be working from Mapbox data team. Time to complete: 5hrs

**Data sources**
- https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit?pli=1#gid=1997886170&vpid=A1
- https://en.wikipedia.org/wiki/Expressways_in_India

**Brief mapping workflow:**
- Check each expressway in the list for any existing coverage in OSM
- If already mapped as `motorway` , mark in the spreadsheet
- If not mapped or tagged as motorway, locate terminal points based on expressway description and open online reference.
 - Correct the map data by adding/realigning/retagging portions of the expressway.

cc: @planemad @maning

**Comment by abhisheksaikia** [comment]
Here is the initial gist of the "Expressway Improvement":
https://gist.github.com/abhisheksaikia/8f8edcad882c341fecb4. We will be adding short gifs to this gist to develop it into a full fledged guide.
cc: @nikhilprabhakar @jothirnadh @maning @planemad need  :eyes: on this.

**Comment by lxbarth** [comment]
Prior art:

- http://roads.mapazonia.org/
- http://wiki.openstreetmap.org/wiki/WikiProject_Brazil/Brasil_250_Cidades
