### ISSUE TITLE
[Highway Mapping India]: Improving the Expressways and National Highways coverage in India

### ISSUE THREAD

**Issue by abhisheksaikia** [mapbox/mapping#142]
**Objective**: Improving the Expressways and national highways in India

**Focus Area**: India

**Team**: @jothirnadh, @nikhilprabhakar, @abhisheksaikia, @maning and @planemad

**Point of Contact**: @abhisheksaikia

**Duration**: To be updated

**Work-flow**:
* Checking the coverage of roads that connects all Indian towns/cities.
* Use [NGA](http://www.webcitation.org/getfile?fileid=95aeb9a62def8e568e554515b2272f42ca8b2bb2) data to [update the missing towns and villages in India](https://www.openstreetmap.org/user/Jothirnadh/diary/36793).
* Collect the statewise road coverage [statistics](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit#gid=0&vpid=A3) of India.
* Collect the statewise [osm coverage of Indian road networks](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit#gid=0&vpid=A3).
* Run a trial task on [mapping expressways in India](https://github.com/mapbox/mapping/issues/140).
* Create a trial run for National Highways.

**Sources**
- The statistics collected from all sources are [here](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit#gid=1997886170&vpid=A1)
- [NGA](http://www.webcitation.org/getfile?fileid=95aeb9a62def8e568e554515b2272f42ca8b2bb2) - For identifying the missing towns and cities in India.
- State's PWD website - Official road statistics for each states. 
- [Indiaenvironmentortal.org](http://www.indiaenvironmentportal.org.in/files/file/basic%20road%20statistics%20of%20india.pdf) - For road statistics where the official data is unavailable.
- [Wikipedia](https://en.wikipedia.org/wiki/Expressways_in_India) - Info on the highways in India

**Discussions**:

- General discussions on the Improvements on the Indian road network can be found [here](https://github.com/mapbox/mapping/issues/138).
- Discussion and up to date information on Improving the Expressways coverage in India can be found [here](https://github.com/mapbox/mapping/issues/140).

**Changeset comment**: Will be updated

**Source**: Bing/Mapbox
cc: @lxbarth @geohacker @pratikyadav @shvrm

**Comment by nikhilprabhakar** [comment]
Initially we collected the nationwide statistics with state-wise data in India using two main sources 
- The state PWD websites.
- The [Basic Road Statistics of India](http://www.indiaenvironmentportal.org.in/files/file/basic%20road%20statistics%20of%20india.pdf) document of the Ministry of Road Transport and Highways.

##### The observations for the collected [road statistics](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit#gid=1997886170&vpid=A1):

* There are discrepancies between the statistics between different official sources (eg. [the Gujarat Roads and Buildings Department](http://rnbgujarat.org/about-us/functions-and-back-ground.aspx) cites the total length of village roads as 21259 kilometres in length while the [Basic Road Statistics of India](http://www.indiaenvironmentportal.org.in/files/file/basic%20road%20statistics%20of%20india.pdf) document of the Ministry of Road Transport and Highways cites the total number of village roads as 51590 kilometres in total).

* The data sources are also outdated in most of the PWD websites dating back to 2007 and/or 2009. The most updated data available in the sources is for 2011.

* In case of conflicts between the length of roads and the time of the data collected, we have cited the statistics that is most recent and also the greater total road length.

* Union territories and some states have a severe lack of road statistics which was updated in the [spreadsheet](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit#gid=0).

* The MDR and ODR data is also very inconsistent in most of the sources and updation on MDR and ODR road lengths was done in the spreadsheet.

* The OSM community can constantly verify and update the data available in the spreadsheet along with any relevant sources for the data. Local OSM community can improve and collect the data of their individual states and accordingly update the [spreadsheet](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit#gid=0).

**Comment by jothirnadh** [comment]
**Updating the missing towns and villages in India**

* In India, there are  [~7935 major cities/towns](http://censusindia.gov.in/2011-prov-results/paper2/data_files/India2/1.%20Data%20Highlight.pdf) officially recogized by the [Government of India](http://censusindia.gov.in/) according to the 2011 cecsus, but in OSM, there are only 3352 (as of 2015-11-23) cities/towns mapped as place nodes.
* Analysed the freely available data sources to add the missing towns and villages in OSM.
* NGA provides WMS layer which can be overlaid on JOSM to aid mapping of missing towns and villages.
* The procedure is drafted as a [dairy post](https://www.openstreetmap.org/user/Jothirnadh/diary/36793) in OSM to encourage OSM community.

**Problems encountered**

* GNS record for India does not classify populated places according to administrative level (cities/towns/villages).
* NGA data is not upto-date data and it needs to be cross referenced with other sources before mapping.

**Comment by abhisheksaikia** [comment]
#### Expressway mapping in India [#140](https://github.com/mapbox/mapping/issues/140):
Our first step was to cross check the individual expressways against what was on OpenStreetMap to determine if they were already mapped, and identify missing [expressways](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit#gid=1997886170). 

**Approach**

1. Researched finite start and end points for each expressway by using [wikipedia](https://en.wikipedia.org/wiki/Expressways_in_India)
2. Retagged the expressways appropriately based on the above findings by splitting, merging, and adding relations.

**Challenges**

* Identifying finite start/end points for expressways: referred to [wikipedia](https://en.wikipedia.org/wiki/Expressways_in_India), and looking for entry and exit toll gates using satellite imagery.
* Multiple segments within expressway with different names: added `relations` to such road segments and added `name` tag.
* 'expressway' in name is not equal to actual 'expressway': express ways have `limited access`. Checked satellite imagery thoroughly to determine the road in question was actually an expressway.
* Under-construction/recently completed expressways: need to find more sources to accurately add this data to OpenStreetMap.

**Comment by planemad** [comment]
From https://github.com/mapbox/mapping/issues/138#issuecomment-160472887

> How is this best shared with the osm-in community, to start to address gaps? What about adapting the /data-platform/countries page for Indian states, on openstreetmap.in? How easy to add an overview map of completeness in all states? Could be a cool example for other communities to follow. Or we could think about how to add in more detail on the mapbox.com pages.

@mikelmaron what we need is resources that can help the community understand the data gap and help prioritize where effort is needed.

The  [osm-coverage](https://github.com/mapbox/osm-coverage) processor has been a great starting point to give a high level overview of data gaps, but will require more granular information to make it actionable for mappers.

From the progress we've had so far on researching the India data, a step by step approach to fill in data might be:
- Do basic data gap comparison and flag areas that need most improvement
- Improve place coverage: Add/correct cities and towns 
- Add missing motorways and trunk highways using official listings as reference
- Detect towns and cities that are not connected by a highway and add missing links
- Iterate for villages and lower order roads

**Comment by abhisheksaikia** [comment]
The table below states with the states with the lowest OSM national highway coverage in India:

State Name | National Highways(NH) | OSM Coverage (NH) | % Coverage
--- | --- | --- | ---
Jammu & Kashmir | 2,593.00 | 1683.543097 | 64.93
Manipur | 1,745.74 | 1186.800814 | 67.98
Himachal Pradesh | 2,622.48 | 1911.573839 | 72.89
Mizoram | 1,381.00 | 1044.835092 | 75.66
Nagaland | 1,150.09 | 888.4723057 | 77.25

Out of which, we will be using Manipur for the trial run and check the OSM coverage of the national highways in the state and map the missing National Highways.

**Comment by planemad** [comment]
@jothirnadh @abhisheksaikia @nikhilprabhakar going by the progress so far:
- Lets pick a small state with a large OSM coverage gap for trunk roads
- Make a listing of trunk roads in the state
- Validate each trunk road has been mapped correctly with proper route relations

**Comment by abhisheksaikia** [comment]
As a trial run I have looked into the national highway coverage in Arunachal Pradesh. 

**The workflow followed while doing the task**:
* Create a list of national highways in Arunachal Pradesh from a official source. In this case it is the [STATEWISE LENGTH OF NATIONAL HIGHWAYS IN INDIA 2014](http://morth.nic.in/showfile.asp?lid=366) published by the Ministry of Road Transport & Highways.
* Many of the highways in the source have been converged into an existing highway or renamed. In those cases the route of the highway was verified to determine it's present name.
* The starting and ending points in the route mentioned in the source are verified to determine whether the highway in question has been completely mapped.

The table listing the present status of national highways in Arunachal Pradesh and their status in OSM is [here](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit#gid=40504416&vpid=A1).

**Challenges**:

* The main challenge faced was to determine the national highways based on the current and the ould numbering system. The national highway numbering system is constantly changing which requires manual verification of all the highways.
* The starting and end points of the highways and whether the entire highway have been covered in OSM. In this case the 'route' information in the source helped in the start and end points of the highways.
 
**Observations**:
* Most of the new highways have been tagged as state highways as they have been recently converted. There is a need to update them defining proper route relations.

**Time Required**: 30 minutes-45 minutes (excluding mapping:may vary depending on the data present in OSM and also the amount of national highways in the state)

**Comment by jothirnadh** [comment]
As a trial run I analysed the National highway coverage of Manipur state. [Here](https://docs.google.com/spreadsheets/d/1rm4zHsGBruOa5QmulJSjnjM1HD2TAZSMo3OugfBl_1U/edit#gid=0&vpid=A1) is the list of National highways passing through Manipur according to [MORTH](http://morth.nic.in/showfile.asp?lid=366).

**Observations**
* Many of the towns in Manipur are not mapped which made it hard to identify the start and end points of the highways.
* 85% of the national highways are already mapped but they are assigned with different names than the names declared by [MORTH](http://morth.nic.in/).

**Comment by nikhilprabhakar** [comment]
As per the discussion we had with @planemad , we came up with a workflow for mapping the National highways in Manipur. The statistics are updated in the [spreadsheet](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit#gid=1428679349&vpid=A1)

**Time taken        :**  ~45 mins.
**Team members :** @jothirnadh @abhisheksaikia @nikhilprabhakar

##### Workflow :

- Checked whether a National Highway was already marked in OSM.
-  Searched for the cities or towns through which the National Highways are passing. If the city/town is not marked in OSM, we used [(Bhuvan (ISRO)](http://bhuvan.nrsc.gov.in/map/bhuvannew/bhuvan2d.php#) to compare and get the approximate location. 
- Used [MORTH](http://morth.nic.in/showfile.asp?lid=366) to get the starting and ending point of the National Highways.
- We added relations or Name or re-tagged the roads appropriately.


##### Challenges:

- It was difficult to determine the latest name for a National highway as the road names were changing from time to time.
- Getting the exact starting and ending points for a National highway was very difficult even with the data available from [MORTH](http://morth.nic.in/showfile.asp?lid=366) as some places/towns were not marked in OSM.

cc:/ @geohacker @shvrm @pratikyadav @maning

**Comment by nikhilprabhakar** [comment]
An overview of this whole mapping project has been published as a [OSM diary post](https://www.openstreetmap.org/user/nikhilprabhakar/diary/37448). 

cc:/  @jothirnadh @abhisheksaikia @geohacker @planemad @shvrm @maning

**Comment by abhisheksaikia** [comment]
As per voice with @geohacker  and @planemad the issue has been published in Talk-In and OSM India Forum.

cc:/ @nikhilprabhakar @jothirnadh @shvrm @maning

**Comment by mikelmaron** [comment]
Side note. Made an map based on India road completion by state
http://bl.ocks.org/mikelmaron/6035c33af4807149334f

* Exported CSV from https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit#gid=1428679349&vpid=A1
* Joined Natural Earth shapefile to CSV in QGIS (had to correct some names in spreadsheet)
* Created a new column with integer representation of completeness column. Saved as GeoJSON
* Uploaded data source to Studio
* Made a thematic map style in Studio https://www.mapbox.com/studio/styles/mikelmaron/cihwzxlmr00kp9nkp61406fkq/
* Modified [this example](https://www.mapbox.com/mapbox-gl-js/example/featuresat/) to display only name and percent complete, and posted as Gist.

**Comment by naveenpf** [comment]
Telagana and AP has to be separate. Then 171% on AP will be going.

**Comment by abhisheksaikia** [comment]
@naveenpf  we have used the [MORTH](http://morth.nic.in/showfile.asp?lid=366) data which was updated in 2014. The Telangana data is not present in this source. If you have any updated source with separate statistics for Andhra Pradesh and Telangana, can you please share it here? The [spreadsheet](https://docs.google.com/spreadsheets/d/1uYmQEyZqP2tMe1cJYJUVcNIhFPCdzETsBh1kaSCZplI/edit#gid=0) can then be updated.

**Comment by naveenpf** [comment]
@abhisheksaikia 

Below link has latest highways data. In this Telangana is separate. 
Very old NH numbers are retained, it is not updated. 
Recently notified NHs has only new numbers. 

http://morth.nic.in/index2.asp?slid=32&sublinkid=12&lang=1
Last Updated On: 07/08/2015 [as per the website]

Few more highways are notified in September and October 2015. 
For that data we to check gazette

August 25, 2015
http://egazette.nic.in/WriteReadData/2015/165603.pdf

September 2015
http://egazette.nic.in/WriteReadData/2015/166114.pdf
http://egazette.nic.in/WriteReadData/2015/166156.pdf

October 2015
http://egazette.nic.in/WriteReadData/2015/166203.pdf

**Comment by naveenpf** [comment]
@mikelmaron 
Can we update map ?
http://bl.ocks.org/mikelmaron/6035c33af4807149334f

For each state, NHs are given      network=IN:NH:TN [For Tamil Nadu State ]

http://wiki.openstreetmap.org/wiki/National_Highways_%28statewise%29

**Comment by mikelmaron** [comment]
@naveenpf I'd be happy to guide someone through the steps I outlined above, to update the data for the map

**Comment by jothirnadh** [comment]
Tracking the next actions of Highway mapping in the [OSM India Forum](http://forum.openstreetmap.org/viewtopic.php?id=17851). No further actions here. Closing it.

**Comment by sukhjitsehra** [comment]
Good Work
