### ISSUE TITLE
Retag quadrant routes in Pennsylvania, USA  from `ref` -> `ref:penndot`

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#149]
**Objective:** Retag the quadrant state routes in Pennsylvania according to the [OSM Wiki guidelines](http://wiki.openstreetmap.org/wiki/Pennsylvania/State_Route_Relations#Four_digit_routes)

Prior Tasks: *none*

<img width="570" alt="screenshot 2016-01-18 16 24 12" src="https://cloud.githubusercontent.com/assets/126868/12389633/f7b07e20-bdff-11e5-8cdb-91e8ccde1772.png">

**Project Area**: Pennsylvania State, USA
**Estimates**:

- Total incorrectly tagged ways in Pennsylvania: [6819](http://overpass-turbo.eu/s/dLg)
  - Routes tagged as `ref=SR ****` or `ref=SR****`: [6775](http://overpass-turbo.eu/s/dLm)
  - Routes tagged as `ref=Sr ****` or `ref=Sr****`: [44](http://overpass-turbo.eu/s/dLl)

- Incorrectly tagged ways in Pennsylvania excluding routes with no space: [3132](http://overpass-turbo.eu/s/dLh)
  - Routes tagged as `ref=SR ****`: [3123](http://overpass-turbo.eu/s/dLi)
  - Routes tagged as `ref=Sr ****`: [9](http://overpass-turbo.eu/s/dNY)

**Duration**: **1 day**
**Progress**: *Awaiting community review*

Team: @oini @planemad

#### Workflow:
1. Load overpass turbo link and run the query
2. Export the results into JOSM
3. In JOSM find objects with the filter `ref:sr`
4. Rename key for selected objects from `ref` to `ref:penndot`

#### Caution :exclamation: 
- Make sure the roads are within the PA state boundary, no other state roads are to be modified
- Only 4 digit routes are to be modified (1000 and above)

**Changeset Comment**: `Changing key of quadrant routes in PA which are not signposted from ref to ref:penndot as per OSM Wiki guidelines https://github.com/mapbox/mapping/issues/149`
**Source**: Bing

cc @mapbox/team-data @1ec5 @nickidlugash

**Comment by planemad** [comment]
Have created one trial changeset with the above process for 9 routes tagged `ref:Sr ****` https://www.openstreetmap.org/way/10700458

Verified each object for tag changes and results are as expected. 

**Next actions**
- @oini publish dairy post on this project inviting process review and feedback 
- @planemad to invite feedback from talk-us

**Comment by oini** [comment]
Published the diary post http://www.openstreetmap.org/user/oini/diary/37800

cc @planemad

**Comment by bhousel** [comment]
\o/

**Comment by planemad** [comment]
@oini based on the support in the diary and the lack of any objections over the 2 week period, lets go for this.

**Comment by nickidlugash** [comment]
This is going to be super helpful for our maps :heart_eyes_cat:

**Comment by oini** [comment]
This task is done. The outcome has been listed below.

### Outcome

Total routes re-tagged: [6787](http://overpass-turbo.eu/s/egt)

![screen shot 2016-02-05 at 6 58 55 pm](https://cloud.githubusercontent.com/assets/1933377/12847610/90248488-cc3a-11e5-9cdc-d1cfc8393ccf.png)

#### Breakdown of re-tagged routes:

- `ref=Sr ****` -> `ref:penndot=SR ****`: [35](http://www.openstreetmap.org/changeset/36995957)
- `ref=SR ****` -> `ref:penndot=SR ****`: [3151](http://www.openstreetmap.org/changeset/36997131)
    - This was a mass-edit and have been uploaded in one go
    - After the edit was done I noticed that in [29](http://overpass-turbo.eu/s/edw) of these routes `SR ****` was followed by a non-state route number like `T***` , `PA ***`, `Historic PA ***`
- `ref=SR****` -> `ref:penndot=SR****`: 3592
    - This edit was done in 7 parts, each changesest containing the following number of routes:
        - 32: In this case, `ref=SR****` was changed to `ref:penndot=SR ****` using the [TODO list plugin in JOSM](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/TODO_list). Since changing the rest 3560 routes in a similar way would have taken a very long time, from the next step only `ref` was changed to `ref:penndot` by mass modification and `SR****` was left as is
        - [474](http://www.openstreetmap.org/changeset/37013985)
        - [179](http://www.openstreetmap.org/changeset/37014074)
        - [325](http://www.openstreetmap.org/changeset/37014123)
        - [592](http://www.openstreetmap.org/changeset/37014248)
        - [1422](http://www.openstreetmap.org/changeset/37014365)
        - [568](http://www.openstreetmap.org/changeset/37014885)
    - Also this time I ensured none of the routes of the order of `SR` followed by a non-state route number were edited
- `ref:penndot=Sr` -> `ref:penndot=SR`: [9](http://www.openstreetmap.org/changeset/37015226)

### Note

- 1031 routes were found with the `penndot_ref` tag alongside the `ref` tag. Following the [OSM Wiki guidelines](http://wiki.openstreetmap.org/wiki/Pennsylvania/State_Route_Relations#Four_digit_routes), the `penndot_ref` tags were deleted for these routes
- For the below routes, we haven't changed the `ref` tag to `ref:penndot` as we're unsure of the correct tagging convention for these cases
    - [37](http://overpass-turbo.eu/s/eds) routes where `SR ****` is followed by a non-state route number like `T***` , `PA ***`, `Historic PA ***`
    - [79](http://overpass-turbo.eu/s/edB) routes where a non-state route number like `T***` , `PA ***`, `Historic PA ***` is followed by `SR ****`

### Next Action

- [ ] I shall post a follow-up diary-entry with the outcome of this task

cc @planemad

**Comment by rickmastfan67** [comment]
Problem with changeset 37014365. http://www.openstreetmap.org/changeset/37014365

3 nodes were changed that shouldn't have been since they are exit numbers, and not highway ref tags.

Might want to double check all of the changesets done for this and revert them if they are exit numbers.

**Comment by planemad** [comment]
@rickmastfan67 thanks for catching this. Can you verify if these are the nodes: http://overpass-turbo.eu/s/egw

**Comment by rickmastfan67** [comment]
@planemad I can verify all 4 of those nodes are exit number nodes.  I've even personally used the '[410650263](http://www.openstreetmap.org/node/410650263)' exit in the past.

As for the edge case link above, yes, motorway_link's can have their own quadrant route numbers.  Most of the time, they are numbered in the 8000's.  Here's a quick link to a picture from Google StreetView showing this as the case: https://goo.gl/maps/oKuWPYnBrYN2  So, pretty much anything that PennDOT maintains will get either a 'quadrant' ref, or a 'posted' ref as long as they are long enough to need one of those little white markers.

Also, in that edge case you linked, the 'ref:penndot=SR #' doesn't have the space between the 'SR' and the '#'.  Don't know how many cases of that need to be fixed so everything is the same.

**Comment by planemad** [comment]
@rickmastfan67 the regex catches all nodes with `ref:penndot` key irrespective of the value so its unlikely there are any more cases of the accidental retagging of exits.

Yes, there is a inconsistency in the space in the `SR` values. Its not something we can easily fix for now.

**Comment by oini** [comment]
@rickmastfan67 @planemad Reverted the `ref:penndot` tags on exit number nodes to `ref`. Here's the changeset: http://www.openstreetmap.org/changeset/37075782

**Comment by rickmastfan67** [comment]
Appears a few somehow got missed and weren't converted.

**Comment by oini** [comment]
@rickmastfan67 That is because we only targetted the routes with four digit route numbers that already had `SR` or `Sr` values in the `ref` key tag. 
On querying Overpass, we get a total of [174](http://overpass-turbo.eu/s/eDp) routes having `ref` tags with four digits in their values of which in [98](http://overpass-turbo.eu/s/eDr) routes, `PA` is present before the four digits. It would be of great help if you could suggest the right tagging scheme for these routes.

**Comment by rickmastfan67** [comment]
It's simple.  There are NO 4 digit posted routes in PA that should have 'PA' in the ref tag.  All those should be converted to the 'ref:penndot' tag.  Ways like [149263908](https://www.openstreetmap.org/way/149263908/) mentioned above, should be converted to 'ref:penndot', and have the 'PA' changed to 'SR'. (I find it interesting that the way I found doesn't show up in your 98 routes link.)  These type are cut and dry, and simple to make a quick and safe fix on.

For ways like [Way 264285966](https://www.openstreetmap.org/way/264285966), those need to be manually fixed on a case-by-case review (pretty much, if there is a ';' in the tag, ignore and maybe just add a note to the OSM database for somebody with more knowledge about the highway numbering scheme to double check it and possibly fix it.  I'm currently working on manually fixing the ways like this that show up in the '98' link you provided above.

**Comment by planemad** [comment]
Final diary post is out https://www.openstreetmap.org/user/oini/diary/38444

@rickmastfan67 many thanks for your inputs, going to close this now till we have something actionable for the team.

cc @oini
