### ISSUE TITLE
Turn-lanes and Turn-restriction don't match

### ISSUE THREAD

**Issue by Rub21** [mapbox/mapping#150]
We  found a particular case: 
There is a turn restriction https://www.openstreetmap.org/relation/5335445/history added by [diggernet](https://www.openstreetmap.org/user/diggernet) which is not match with the indication via road markings.

According the Turn-restriction relation, is not possible go from [Military West- way1](https://www.openstreetmap.org/way/393669696/history) to [1st Street-way2](https://www.openstreetmap.org/way/358264786/history). `restriction=no_left_turn`

According Turn-Lanes, the indication via road markings shown is possible go to left.
![image](https://cloud.githubusercontent.com/assets/1152236/12587700/78e9edcc-c423-11e5-9289-f4c7f5d457ca.png)

what solution can we give on this issues?

cc @Andygol @planemad @ediyes @mapbox/team-data

**Comment by lxbarth** [comment]
Want to get in touch with diggernet?

**Comment by Andygol** [comment]
@Rub21 I think there is a mistyping `no_left_turn` instead of `no_right_turn`. Since we have the extra lane for turn to the right we have to specify restriction for the intersection which denied right turn.

I propose to correct the wrong `left turn` restriction and inform `diggernet` about his mistyping.

@lxbarth what do you think?
<img width="631" alt="java openstreetmap editor 2016-02-05 14-37-54" src="https://cloud.githubusercontent.com/assets/369696/12846659/6e4951e6-cc16-11e5-84c3-5768077801fc.png">

**Comment by Andygol** [comment]
@Rub21 
Next turn restriction absolutely nonsense! It have to be removed! As the role is absolutely inappropriate. 

Way with `from` role have `oneway=yes` and  direction to the opposite side
<img width="501" alt="java openstreetmap editor 2016-02-05 14-54-14" src="https://cloud.githubusercontent.com/assets/369696/12846996/e39778f4-cc18-11e5-8d8e-e99f9515018f.png">

**Comment by lxbarth** [comment]
I wouldn't map a turn restriction in these instance at all. Not needed for informing a routing engine like OSRM. The shorter path won't ever lead through the "wrong" turn. cc @TheMarex ?

**Comment by TheMarex** [comment]
Turns into oneways against travel direction are implicitly forbidden anyway. No need to tag that . Turns _from_ oneways in opposite direction are not even checked sine they are never considered when generating the turns in OSRM (just not part of the graph model).

**Comment by planemad** [comment]
Nothing actionable for now.

**Comment by lxbarth** [comment]
> Nothing actionable for now.

Closing.
