### ISSUE TITLE
Clean up task for SF buildings

### ISSUE THREAD

**Issue by abhisheksaikia** [mapbox/mapping#152]
**Objective:** Cleanup previous building imports in SF peninsula.

![screen shot 2016-02-04 at 12 03 08 pm](https://cloud.githubusercontent.com/assets/13744156/12807908/1394d244-cb39-11e5-898c-48e1c5c77d30.png)

**Task Area:** ~48.22 sq.km
**Estimates:** ~56,000 buildings(~100 buildings per hour per person )
**Duration:** ~ one week
**Progress:**

**Team:** @mapbox/india-office and @mapbox/peru-office 

#### Mapping Sources
Source | Description|Quality|License 
---|---|---|---
Bing Imagery | Imagery | High | :white_check_mark: 

### Task
[Building tracing in San Francisco Peninsula - Import cleanup](http://tasks.openstreetmap.us/project/20)

#### Workflow:
1. Pick a task from the Tasking Manager.
2. Load the Bing satellite imagery to JOSM.
3. Install [JOSM Buildings Plugin](http://wiki.openstreetmap.org/wiki/JOSM/Plugins/BuildingsTools) for easy tracing.
4. Inspect the imagery to find the mis aligned buildings from previous imports and any missing buildings by using the Bing satellite imagery.
4. Improve alignment for existing buildings from previous imports with reference to the building footprint in the Bing imagery and also add any missing buildings

#### Issues to look out for:

Recent buildings like this [Apple Spaceship Campus](https://github.com/mapbox/mapping/issues/141#issuecomment-169813621) are absent in the Bing imagery which is outdated. These recent buildings should not be modified. 

#### Filters
Use the following [inverse filter](https://github.com/mapbox/mapping/issues/141#issuecomment-179182965) to highlight only buildings before January 2015: `timestamp:2005-12-31/2014-12-31 building`.

**Changeset Comment**: 
`Cleanup misaligned buildings https://github.com/mapbox/mapping/issues/152`

**Source**: Bing

**Comment by dannykath** [comment]
While working in Cupertino city I found some buildings that were out of phase and not orthogonalized with Bing neither Mapbox satellite imagery. Those buildings were imported, what should I do? I was aligning them with Bing satellite imagery. Is it right? or Should I revert my changesets?
https://www.openstreetmap.org/#map=20/37.31937884189635/-122.03850923433963
![ejemplo](https://cloud.githubusercontent.com/assets/8483644/12857946/08309130-cc1b-11e5-8ac3-9beef4d17bfa.png)
![ejemplo2](https://cloud.githubusercontent.com/assets/8483644/12857944/080cb6a2-cc1b-11e5-9877-d348b216cce2.png)
cc @abhisheksaikia , @planemad

**Comment by planemad** [comment]
@dannykath As per our initial workflow discussion we are not realigning buildings modified after 2015. Please use this inverse JOSM filter `timestamp:2005-12-31/2014-12-31 building` to only show the buildings that we will cleanup. It is ok to orthogonalize these buildings if to make them match actual geometry, but let us not move them.

cc @mapbox/team-data

**Comment by abhisheksaikia** [comment]
[Cleanup task](http://tasks.openstreetmap.us/project/20) is completed and validated. No further actions here. Closing it.
