### ISSUE TITLE
To-fix: Overlap Highways USA

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#154]
**Task** http://osmlab.github.io/to-fix/#/stats/overlaphighwaysus

Overlapping issues in motorable roads.
This could be because of:
- User error in creating proper junction for ways (fixable)
- User error in tracing the full road till the junction (fixable)
- Incomplete tracing because road connection not visible in imagery (requires survey)

**Task coverage**
- USA

**Mapping source**
- Bing
- Mapbox Satellite

**Timeline**
-  19 February issue count: 96

![image](https://cloud.githubusercontent.com/assets/10425629/13185618/279893e2-d710-11e5-9442-aba156a1ca1a.png)

- @mapbox/peru-office will work on this challenge from 19 February. Team training was done and expected completion is 1 day.

**Instructions**
- Merge tags and delete one of the overlapped roads.
- In some cases road need the tag `layer:`
- If editing in a actively mapped area, add a note instead of making a fix
- Check object history (ctrl+h) to understand why the previous user did the road.

**Tips and tricks**
- Use [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin) and read the [JOSM-Shortcuts](https://github.com/mapbox/mapping/wiki/JOSM-Shortcuts)

#### Resources
- https://github.com/mapbox/mapping/wiki/Working-with-To-fix

cc. @mapbox/team-data @lxbarth @aaronlidman

**Comment by samely** [comment]
Task completed!  :boom: :rocket: 
![image](https://cloud.githubusercontent.com/assets/10425629/13188436/93322a28-d71f-11e5-91dd-e34fea14f794.png)

cc: @mapbox/team-data

**Comment by Rub21** [comment]
I added more overlap issues for entire USA.
![image](https://cloud.githubusercontent.com/assets/1152236/13188558/22c6e67e-d720-11e5-9991-da6c19a38d3c.png)
