### ISSUE TITLE
Observations in Turn Lanes editions

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#155]
When we started editing turn lanes, we based on @Andygol's workshop.
But I found some issues that I consider unnecessary, that are taking our time. So we can improve it.

[@ediyes editions](https://www.dropbox.com/s/rngf51fngfg3jfo/ediyes.osm?dl=0): 
- Most of her editions was adding empty `turn:lanes:*` tag
![image](https://cloud.githubusercontent.com/assets/10425629/13290525/f34d4026-dae1-11e5-850e-56f736e6f235.png)

[@calfarome editions](https://www.dropbox.com/s/pidl822nq5aapsi/calfarome.osm?dl=0)
- Most of him editions was adding `placement:*` tag
![image](https://cloud.githubusercontent.com/assets/10425629/13295927/1e2ae80e-daf9-11e5-98b6-9dd9f6af24b0.png)

- Writing `turn:lanes=none|none` it's the same than `turn:lanes=|`
![image](https://cloud.githubusercontent.com/assets/10425629/13296051/a12bb7d8-daf9-11e5-921b-c79439ad49f1.png)

- Per voice with @Andygol, if the number of lanes of `turn:lanes:backward` and  `turn:lanes:forward` are equal, it's not necessary to add them. Just tag with `turn:lanes:*`

![image](https://cloud.githubusercontent.com/assets/10425629/13296322/1ec5c278-dafb-11e5-9bb3-cf9e6df0f15c.png)

- In this case, I think it's not necessary to add the `turn:lanes:backward=none|none` tag
![image](https://cloud.githubusercontent.com/assets/10425629/13296449/936e0540-dafb-11e5-85b6-a916a5cf0037.png)

What do you think @Andygol, @Rub21 , @lxbarth , @planemad ? 
@mapbox/team-data

**Comment by calfarome** [comment]
> Most of him editions was adding placement:* tag

- I add this tag according to this wiki:  [Placement of the OSM-way](http://wiki.openstreetmap.org/wiki/Proposed_features/placement#Current_status:_lane_count_decreases) and I thought that adding this tag would look more complete my work, but I made the respective consultation @Andygol  and tell me it was not necessary to add that tag, therefore in my last work we already do not add, but I still think my work is incomplete.
![08](https://cloud.githubusercontent.com/assets/10413117/13299747/85dde6ac-db0a-11e5-9039-b3cd80ae7ebe.gif)

The other observations were clarified in the comments the issues: [#144](https://github.com/mapbox/mapping/issues/144) and  [#153](https://github.com/mapbox/mapping/issues/153), therefore in our last work already do not commit these errors.

cc. @Andygol, @Rub21 , @lxbarth , @planemad , @samely

**Comment by Andygol** [comment]
@calfarome 
I am also try to add `placement` tag in case when IMHO it is needed. :+1:  -  https://github.com/mapbox/mapping/issues/153#issuecomment-188742948

**Comment by jothirnadh** [comment]
Apart from the `turn:lane=*` tag, adding rest of the tags is not our priority. Let us make this process really simple and prioritise on adding only `turn:lanes` tag. In my opinion adding `placement=*` or `lanes=*` tags are just redundant information at this point which might change in the future, but not right now.

@planemad your thoughts?

**Comment by jothirnadh** [comment]
Thanks for pointing out these scenarios of each user @samely.

> @ediyes => Most of her editions was adding empty `turn:lanes:*` tag

It is absolutely not necessary to add empty `turn:lanes:*` tag unless or until we see turn lane marking on the road. It is not wrong to add empty `turn:lanes:*` tag, but this will slow down our process of adding the actual turn lanes.

> @calfarome Most of him editions was adding `placement:*` tag

`placement:*` tag is used for visualization purpose. It is not at all necessary for routing. So you can skip adding the `placement:*` tag

> Per voice with @Andygol, if the number of lanes of `turn:lanes:backward` and `turn:lanes:forward` are equal, it's not necessary to add them. Just tag with `turn:lanes:*`

I did not clearly understand the context of this question. To my understanding we are supposed to tag the `turn:lane:forward:*` and `turn:lane:backward:*` separately when the way is bidirectional. We cannot replace these tags with the `turn:lane=*` tag

> In this case, I think it's not necessary to add the `turn:lanes:backward=none|none` tag 

Nope it is not necessary to add the `turn:lanes:backward=none|none` tag. Only add a tag when you find turn lanes marked on the road.

If I miss something please feel free to add more context here. What are your thoughts @planemad @Andygol and @abhisheksaikia

**Comment by Andygol** [comment]
@samely @jothirnadh 

> Per voice with @Andygol, if the number of lanes of `turn:lanes:backward` and `turn:lanes:forward` are equal, it's not necessary to add them. Just tag with `turn:lanes:*`

I feel that here is mistyping :point_up_2: 

This should be read as:  :point_down: 

> if the number of lanes of ~~`turn:lanes:backward` and `turn:lanes:forward`~~ `lanes:backward` and `lanes:forward`are equal, it's not necessary to add them. Just tag with `turn:lanes:*`

So for speed up the process we may omit `lanes:forward` and `backward:tagging` in this :point_up: cases but adding this tags will be useful for validation purpose. 

It would be nice to hear other opinions in this regard

**Comment by samely** [comment]
@Andygol 
You are right! It's a mistake. I meant:
> If `lanes:backward` and `lanes:forward` are equal, it's not necessary to add them. Just `lanes` tag.

That's because in your workshop you added `lanes` tag.

Finally, **I think we should add only `turn:lanes:*`**, I know we can add more tags to make the work complete, but as @jothirnadh said 
> This  slow down our process of adding the actual turn lanes.

**Comment by planemad** [comment]
Great discussion @samely @jothirnadh @Andygol @calfarome 

To summarize:
- The project focus is on turn lanes. So for completion we need correct addition of only `turn:lanes`, `turn:lanes:forward`, `turn:lanes:backward`. All other tags are extra information and not considered for project completion or validation.
- Only segments which have a turn lane needs to be tagged :point_up: . No turn lanes = no need for turn lane tag
- Adding `lane=` to help with style visualization and validation is ok, but not requirement for project completion. We can do lane mapping as a separate project for more efficient mapping and easier validation.
