### ISSUE TITLE
Unnecessary tags on nodes of buildings in Boscoreale, Italy 

### ISSUE THREAD

**Issue by chtnha** [mapbox/mapping#156]
@rclark reported many nodes tagged with `building=residential` in Italy. The edits were made by user [geopeppe](https://www.openstreetmap.org/user/geopeppe) and imported data from some other source which is not mentioned on his [changeset](https://www.openstreetmap.org/changeset/37431007).

**Details**
- Number of nodes with `building=residential` ~  44,036
- Number of way with the nodes ~  3,500

![screen shot 2016-02-26 at 12 01 47 pm](https://cloud.githubusercontent.com/assets/6770741/13345547/a1390194-dc85-11e5-8430-70984da27225.png)

_Affected nodes_
![screen shot 2016-02-26 at 12 12 22 pm](https://cloud.githubusercontent.com/assets/6770741/13345565/c5b078c2-dc85-11e5-9de3-806b7587cc49.png)

**Location**
The affected area is `Boscoreale`, Italy.
![screen shot 2016-02-26 at 12 17 10 pm](https://cloud.githubusercontent.com/assets/6770741/13345537/8d72ad9a-dc85-11e5-88c9-35840b07ecfc.png)

The user imported other data such as `length` and `area` of all buildings. 

![screen shot 2016-02-26 at 12 18 56 pm](https://cloud.githubusercontent.com/assets/6770741/13345706/f412c8ea-dc86-11e5-89e4-ae18ba2f1216.png)

**Proposed actions**
* Contact the user via private message, confirm if this is indeed an import.
* If its an import, remind the user to follow OSM' [Import Guidelines](http://wiki.openstreetmap.org/wiki/Import/Guidelines)
* If import process was followed, offer a cleanup to remove all `building=residential` tag on nodes of a building by using `type:node and building=residential` filter in JOSM.

**Who?**  I and @abhisheksaikia 
**Duration:** 1/2 hour

@maning @mikelmaron @planemad

**Comment by chtnha** [comment]
I have sent a message to the user in OSM. The cleanup is on hold till the user reply back to us.

**Comment by chtnha** [comment]
Italian translation: thanks for the comments, I made the cleaning and fixes I hope everything is ok

Hello

geopeppe



![screen shot 2016-02-26 at 4 20 50 pm](https://cloud.githubusercontent.com/assets/6770741/13350254/f8dda642-dca4-11e5-95a7-17e9c6e5d211.png)


Hope he cleans every unnecessary nodes. No next actions here.

**Comment by planemad** [comment]
@chtnha Can you review the fixes and close here?

**Comment by chtnha** [comment]
geopeppe fixed all the buildings. :100: 

![screen shot 2016-02-26 at 5 04 58 pm](https://cloud.githubusercontent.com/assets/6770741/13351243/4fd98cd0-dcab-11e5-98db-488d051290b9.png)


closing here.

**Comment by mikelmaron** [comment]
Reopening, there are more issues to address

* The building outlines are not individual buildings but clusters of buildings
* The source of the data is not clear
* There's no documentation of the import.

@chtnha please contact geopeppe again, asking about the issues above.

**Comment by chtnha** [comment]
I have sent a message to the user. I will post the reply here.

**Comment by chtnha** [comment]
There is comment left on the users' changeset. https://www.openstreetmap.org/changeset/37457576#map=14/40.7752/14.4825.

**Comment by pratikyadav** [comment]
There is still no reply back from the user.
His last edits are 3 months ago.

@chtnha  @planemad  should we report this to local-community? may be a quick diary entry?

**Comment by planemad** [comment]
@chtnha @pratikyadav 👍 lets close off with a diary and a mail to post to the local community.

**Comment by chtnha** [comment]
I will post a small diary and close this ticket by tomorrow.

**Comment by chtnha** [comment]
I have published a [short diary post](http://www.openstreetmap.org/user/Chetan_Gowda/diary) on this import. Closing here.
