### ISSUE TITLE
HOT: Fiji Activation - Cyclone Winston 

### ISSUE THREAD

**Issue by chtnha** [mapbox/mapping#157]
[Cyclone Winston](
https://en.wikipedia.org/wiki/Cyclone_Winston) hit Fiji on 20th of February, leaving at least 21 dead and destroying hundreds of homes. Winston made landfall on north of Viti Levu, the main island in the archipelago. From there it moved west, and the large storm narrowly avoided the capital city of Suva.  The government declared a state of emergency and imposed a 36-hour curfew for residents' safety.

**HOT task**: http://tasks.hotosm.org/project/1558

**Mapping source**

- **DG Imagery** : `tms[22]:http://hiu-maps.net/hot/1.0.0/rakiraki-19sep2014-flipped/{z}/{x}/{y}.png` 
- **Bing**

**Task coverage**

* Rakiraki Area

**Activities**

- [x] Map all buildings mainly and roads as needed. 
- [x] The main road types to be mapped are `residential`, `unclassified`, `track` and `path`. 

**Timeline**
Start date: February 29th. (73% Done and 11% Validated)

**Stats**
![screen shot 2016-02-29 at 11 38 14 am](https://cloud.githubusercontent.com/assets/6770741/13387070/03712f4e-ded9-11e5-856b-4f79ad33104b.png)

**Instructions**
* Detailed instructions are in the tasking manager.

**Tips**
- Use realign tool (w) to quickly improve existing ways
![untitled](https://cloud.githubusercontent.com/assets/126868/9199837/6a1c6dd2-4062-11e5-953e-ed65b51c8100.gif)
- While using the building tool (b), press (ctrl) to avoid snapping to nearby edges
![untitled](https://cloud.githubusercontent.com/assets/126868/9200359/1b2cabc6-4065-11e5-90b1-91215ee60ffe.gif) 

cc @mapbox/team-data @maning @planemad @mikelmaron

**Comment by chtnha** [comment]
**Updates from Monday (29 Feb)**

The team started to Map buildings/roads as needed for the task. Added some 1000+ buildings. 
![screen shot 2016-03-01 at 7 05 27 pm](https://cloud.githubusercontent.com/assets/6770741/13428462/a9f539ac-dfe0-11e5-8343-cd70c4553ef2.png)

**Updates from Tuesday (March 1)**

The team has validated task about 60%. Aligned most of the buildings and roads.  

![screen shot 2016-03-01 at 6 46 07 pm](https://cloud.githubusercontent.com/assets/6770741/13428481/c21b1c9a-dfe0-11e5-901c-137e7ecd8bdf.png)

**Comment by bgirardot** [comment]
Hi all, thank you very much for helping!
All the validation we can get would be great, we would like to wrap up the existing TM Projects, get out a data set and get to the lesser mapper areas.

**Comment by chtnha** [comment]
The task http://tasks.hotosm.org/project/1558 has been archived and closing this issue for now :100:
