### ISSUE TITLE
To-fix: Unconnected paths

### ISSUE THREAD

**Issue by RichRico** [mapbox/mapping#158]
### Objective
To-Fix issue: http://osmlab.github.io/to-fix/#/task/unconnectedpaths

Review and repair paths which have another road end near them. They have to be intersected by a node.

Total number of issues: 208,782
![screenshot from 2016-02-29 16 04 35](https://cloud.githubusercontent.com/assets/8484029/13408897/2a7a8db8-defe-11e5-85da-f64c39eaa9d9.png)

### Team

For now, only team @mapbox/peru-office will work on this challenge.
### Source

osmi
### Tools

- Use the Josm-tofix-plugin instead of ToFix directly
- Configure your JOSM-Shortcuts, particularly Merge Nodes = M and Join Node to Way = J.

### Instructions
*Node near a highway*
![image](https://cloud.githubusercontent.com/assets/10425629/9016317/cdd5e0f4-3795-11e5-8ea9-9d2151915431.png)

- Connect the node to the highway.
- Before editing, confirm an intersection is level from satellite imagery.
- Make sure there's no a wall, a grid or an area between the highways.

### Training

We've had a training in Ayacucho on Tuesday.

### Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data @lxbarth @aaronlidman

**Comment by Rub21** [comment]
close this for now, nobody is working on this task!
