### ISSUE TITLE
Add pin images in mapbox

### ISSUE THREAD

**Issue by Waseem-Jutt** [mapbox/mapping#160]
I want to add different pin images in mapbox. I used mapbox code

https://jsfiddle.net/sgybvxw1/1/

I changed mapbox loop
`for (var i = 0; i < addressPoints.length; i++) {
    var a = addressPoints[i];
    var title = a[2];
    var marker = L.marker(new L.LatLng(a[0], a[1]), {
        icon: L.mapbox.marker.icon({'marker-symbol': 'post', 'marker-color': '0044FF'}),
        title: title
    });
    marker.bindPopup(title);
    markers.addLayer(marker);
}`

with this
`for (var i = 0; i < addressPoints.length; i++) {
    var a = addressPoints[i];
    var title = a[2];
    var marker = L.marker(new L.LatLng(a[0], a[1]), {
      icon: L.mapbox.marker.icon({      
        "html": "<div class='pin'></div>",
        "iconUrl": "images/pins/food.png",
        "iconSize": [59, 84], // size of the icon
        "iconAnchor": [25, 25], // point of the icon which will correspond to marker's location
        "popupAnchor": [0, -25], // point from which the popup should open relative to the iconAnchor
        "className": "dot"    
      }),
      title: title
    });
    marker.bindPopup(title);
    markers.addLayer(marker);
}`

**Comment by planemad** [comment]
@Waseem-Jutt the best place to ask tech questions would be in [Mapbox Support](https://www.mapbox.com/contact/) or forums like stackoverflow where you have more developers with experience to help you out.

**Comment by Waseem-Jutt** [comment]
i already submit a question on stackoverflow http://stackoverflow.com/questions/35837792/add-pin-images-in-mapbox and alreay submit mail to Mapbox Support but no one solve this
