### ISSUE TITLE
Backport materials and illustrations to JOSM wiki?

### ISSUE THREAD

**Issue by d1g** [mapbox/mapping#162]
Hello Mapbox(ers)!

There a number of concerns why I'm suggesting this:
- josm wiki is integrated within JOSM editor (this is what user(s) see when they are offline)
- every JOSM user will have access to it (even they haven't heard about Mapbox company) Yet ;)
- it near to impossible to outperform JOSM developers in creating new tools vs keeping docs up to date; if we spread efforts we all loose
- this repository (mapbox/mapping) has no option for localization (little to no facilities for translation ATM)
- there no chance to re-explain interface in new tutoring materials [1](https://josm.openstreetmap.de/wiki/JOSM%20interface) [2](https://josm.openstreetmap.de/wiki/Help/ToggleDialogs) [3](https://josm.openstreetmap.de/wiki/Help/Dialog/LayerList) - even some pages still incomplete, there so many hours were put to them (no offense, but no way any company could repeat this)
##### examples
- https://github.com/mapbox/mapping/wiki/Getting%20started = https://josm.openstreetmap.de/wiki/Introduction
- https://github.com/mapbox/mapping/wiki/Sources = no alternative ATM
- https://github.com/mapbox/mapping/wiki/The%20OpenStreetMap%20Data%20Model = https://josm.openstreetmap.de/wiki/Help/Concepts/Object
- https://github.com/mapbox/mapping/wiki/Mapping%20with%20JOSM = Extended version of Introduction
- https://github.com/mapbox/mapping/wiki/JOSM%20shortcuts = https://josm.openstreetmap.de/wiki/Shortcuts no way you will can beat me in the speed of edits :P
- https://josm.openstreetmap.de/wiki/Help/Preferences/Advanced#Explanation = https://gist.github.com/planemad/517401649204c474c906 

I mean, it would be nice to describe JOSM in one place, not in every individual company: a correct, but incomplete guides - probably not what we want for our users/mappers. As far as I can see, It doesn't matter what is target audience: a Mapbox employee or a real mapper, one day they will need exhaustive info on some topic: [how to correct validation errors](https://josm.openstreetmap.de/wiki/Help/Preferences/Validator)

I haven't seen a single guide that explains status bar as well as is it should: https://josm.openstreetmap.de/wiki/Help/StatusBar or a search interface: https://josm.openstreetmap.de/wiki/Help/Action/Search or expert mode https://josm.openstreetmap.de/wiki/Help/ExpertMode

**Comment by planemad** [comment]
@d1g thanks for bringing this up. Lets be very clear that the intention of these mapping guides is not to replace the JOSM wiki which is the right source for the latest software documentation. 

These mapping guides are just a condensed version of all the existing guidelines and best practices for ease of access for our data team internally. 

All the material is cc-0, so please feel to reuse/backport any of the materials to update the JOSM/OSM wiki. Let us know how we can assist.

Closing for now.

**Comment by d1g** [comment]
@planemad, thanks! [My progress, may contain mistakes](https://gist.github.com/d1g/e6741f71f1b5b36bc7b8)

Plugins are not documented: simply install some plugin, hover mouse over button, then press F1

If there no help, then it means something should be written here (button in top right corner used to edit wiki page using browser).

If we were documenting tools this way, then we could simplify all instructions to: 1. here is first edit guide, 2. if you have questions about JOSM - press F1 over element 3. custom tasks are here ...

You could assist by documenting plugins you use in your workflows first (for example Mapillary plugin): [1](https://josm.openstreetmap.de/wiki/Dialog/MapillaryMain) [2](https://josm.openstreetmap.de/wiki/Help/Dialog/MapillaryHistory) [3](https://josm.openstreetmap.de/wiki/Help/Dialog/MapillaryFilter)

**Comment by seb-1204** [comment]
@planemad I thank you very  much for your effort on this, however I think you are avoiding @d1g concern with this. Yes you say this is your 'internal guide/best practice' but at the same time you have invested time and resources to summarise and condense the best practice in the osm world. I would think that the wiki would be the better place to reach more mappers and spread adoption and knowledge of these best practices.

**Comment by d1g** [comment]
@seb-1204, it's a more tricky question because (say, JOSM documentation) documents [all 400+ hotkeys](https://josm.openstreetmap.de/wiki/Shortcuts) or [all toggle dialogues](https://josm.openstreetmap.de/wiki/Help/ToggleDialogs), but not everyone needs everything.

Re-documenting (say, JOSM features) is wrong, but combining right subset of links to a complete JOSM documentation - is correct. Improving navigation within JOSM wiki - is also correct (consider using feature X when you are using B, D but A is not available).

When we talk about "best practice" (say, lanes), there a page about it at wiki: https://wiki.openstreetmap.org/wiki/Lanes.

Based on [edit history](https://wiki.openstreetmap.org/w/index.php?title=Lanes&action=history), I can say that it wasn't expanded as well as it should: [1](https://github.com/mapbox/mapping/wiki/Mapping-guide-for-turn-lanes-from-imagery) [2](https://github.com/mapbox/mapping/wiki/QA-for-turn-lane-data)

Some of information is US-only, but we can use region-specific paragraphs (similar to [this page](https://wiki.openstreetmap.org/wiki/Multilingual_names))

PS. I'm happy that we could simply reuse what Mapbox(ers) did for themselves without need to worry about license compliance and all that legal nonsense
