### ISSUE TITLE
Adding missing one-ways and missing roads using Improve-OSM

### ISSUE THREAD

**Issue by jinalfoflia** [mapbox/mapping#164]
**Objective:** Our goal is to use [ImproveOSM](http://improve-osm.org/#12.2111800,-36.2988300,4/layer=OSM/OPEN/true,1-0-0/true,1-0-0-0-0/true,1-0) to add missing one-ways and missing roads

**Team:** @pratikyadav @oini @maning @planemad @jinalfoflia

#### Task Workflow [Trial in progress]

- Use the web-interface of [Improve-OSM](http://improve-osm.org/#12.2111800,-36.2988300,4/layer=OSM/OPEN/true,1-0-0/true,1-0-0-0-0/true,1-0) to select a particular way
- Open the feature in JOSM 
- Verify with the imagery and look for cues for the existence of the road or for it to be a one way
- Do the necessary changes to the road and upload the changes

**Changeset Comment:** `Adding missing roads and one ways using ImproveOSM (https://github.com/mapbox/mapping/issues/164)`
**Imagery:** `Bing`

/cc @planemad @lxbarth @maning @mikelmaron

**Comment by mikelmaron** [comment]
@jinalfoflia cool. for a trial, how long will the team spend? what are will you focus on?

**Comment by planemad** [comment]
**Missing Roads**
Area: SF

Seeing many false positives at SFO Airport, marking them as invalid.
<img width="226" alt="screenshot 2016-03-23 15 35 26" src="https://cloud.githubusercontent.com/assets/126868/13983118/ccbfef42-f113-11e5-8a6f-1723c1855601.png">

**Comment by oini** [comment]
#### Observation

The data on ImproveOSM is not upto date. While adding oneways, I came across 4 instances where the roads were already marked as `oneways`. Below is a screenshot of an instance where the oneway tag was added as early as 2014.

![screen shot 2016-03-23 at 4 19 37 pm](https://cloud.githubusercontent.com/assets/1933377/13985076/6bd7a956-f120-11e5-9540-6b9fdab3589a.png)

Otherwise, I found it to be an extremely effective way to detect missing oneways.

**Comment by jinalfoflia** [comment]
We spent **2 hours** in mapping **San Francisco** and **LA** region. We used the web interface of ImproveOSM.

**Teams**

-- 

- **Missing one ways:** @oini @jinalfoflia

@oini worked in **SF** region.
![screen shot 2016-03-23 at 5 30 57 pm](https://cloud.githubusercontent.com/assets/4470913/13985595/b846b9b4-f123-11e5-89f3-39856aa22362.png)

@jinalfoflia worked in **LA** region.
![screen shot 2016-03-23 at 5 26 27 pm](https://cloud.githubusercontent.com/assets/4470913/13985603/c14e608e-f123-11e5-8404-a081bb360926.png)

--

- **Missing ways:** @planemad @maning 

@planemad worked in **SF** region.
![screen shot 2016-03-23 at 5 28 46 pm](https://cloud.githubusercontent.com/assets/4470913/13985596/bd295ad6-f123-11e5-8dd1-f8238459cde3.png)

@maning worked in **LA** region.
![screen shot 2016-03-23 at 6 12 27 pm](https://cloud.githubusercontent.com/assets/4470913/13985605/c53461c6-f123-11e5-8771-649bc75b236d.png)

--

### Observations

##### Missing one ways

- There were around 30% false-positives
- 10% we could not verify either through imagery or Mapillary
- We were not adding one ways to the service roads
- There were some issues that were already marked (`were fixed`)
- The data seems to be outdated, because we have noticed `fixed issues` as early as 2014
- It is effective in detecting missing one ways and the current work flow using the web version of ImproveOSM is efficient.

##### Missing ways

- Most of the roads detected were service roads
- Each of them were divided into multiple blocks, a long stretch would involve us marking each of these as `solved` individually.
- ImproveOSM has a very high rate of false-positives for missing ways.

/cc @mikelmaron @lxbarth

**Comment by jinalfoflia** [comment]
### Next Action[s]

- As per the trial run and analysis, the team will only work on adding the **missing one ways** using this tool.
- The team will jump into this task from the coming week **[4 - 8 April ]**

/cc @planemad @mikelmaron @lxbarth @maning @shvrm @oini @pratikyadav

**Comment by mikelmaron** [comment]
@jinalfoflia sounds good. how many cities do you expect to cover over the week?

**Comment by jinalfoflia** [comment]
> @jinalfoflia sounds good. how many cities do you expect to cover over the week?

@mikelmaron As per the time taken, one person can knock a city off within a day. We are looking forward to cover at-least 10 cities in the coming week. If the target is achieved faster then we'll scale up the number of cities.

### Next action[s]

- [ ] @oini and @jinalfoflia to make a list of top 10 cities that has many possible one-ways by Monday.

**Comment by talllguy** [comment]
@planemad I've done a lot of work around Baltimore with this tool and found that areas around airports and also next to major highways have a lot of false positives.

**Comment by jinalfoflia** [comment]
To begin with @oini and I have come up with the list of 13 cities based on the density of probable one-ways. The team shall start working on these cities from the coming week.

#### List of the cities

- New York city
- Washington DC
- Boston
- Phildelphia
- LA
- San Jose
- Chicago
- Denver
- San Deigo
- Houston
- Dallas
- Seattle
- SF

### Next Action[s]

- [ ] @oini and @jinalfoflia will update the work-flow for this task

/cc @planemad @mikelmaron @lxbarth

**Comment by lxbarth** [comment]
Very interesting for the numbers of updated one ways coming out of this. We should get an idea of % one ways missing in US. Can we limit ourselves to five cities to start with?

**Comment by talllguy** [comment]
[Mike](http://www.openstreetmap.org/user/mdroads) and I knocked out Baltimore. :100: 
![2016-04-05 12_20_01-improve osm](https://cloud.githubusercontent.com/assets/1827881/14289509/191f6c72-fb29-11e5-815d-e7b60daed220.png)

## Pro tips:

* Look at the direction that cars are facing in aerial imagery to validate one-way status (see fig. 1)
* In the US, look for [stop lines](http://mutcd.fhwa.dot.gov/htm/2009/part3/part3b.htm#section3B15) (a solid white strip of pavement marking) that go all the way across the road on one way streets. On two way streets, the stop line only goes to the centerline of the road. (see fig. 2)
* The tool was usually dead on accurate with these suggestions, except in the case of a missing turn restriction, which is also useful to look for when doing the one-way analysis.

![2016-04-05 12_28_26-openstreetmap](https://cloud.githubusercontent.com/assets/1827881/14289771/470343c4-fb2a-11e5-9597-f0c670fbf171.png)
Figure 1

![2016-04-05 12_37_26-openstreetmap](https://cloud.githubusercontent.com/assets/1827881/14290167/f8ed70c2-fb2b-11e5-9635-c7d51a386306.png)
Figure 2

**Comment by jinalfoflia** [comment]
> We should get an idea of % one ways missing in US. 

@lxbarth have sent a message to Martin in their slack channel to get this information.

> Can we limit ourselves to five cities to start with?

:+1:  @lxbarth

**Comment by jinalfoflia** [comment]
@talllguy this is amazing! :clap: 
Thank you for the pro-tips, will in-corporate them in the workflow to make the best out of it!

**Comment by jinalfoflia** [comment]
Here is the detailed workflow for this project - https://gist.github.com/jinalfoflia/f83b6c936e005d14de8d287c95ba0575
Let us know if there is any feedback and improvements related to this workflow.

We are wrapping up the trial run for this project. A new ticket will be opened when the entire team will jump in to work on mapping missing one-ways using ImproveOSM.

Would like to thank @talllguy and [Mike](http://www.openstreetmap.org/user/mdroads) for mapping Baltimore and for the pro-tips. 💥 

/cc @planemad @mikelmaron @maning
