### ISSUE TITLE
To-fix: Overlapping highways

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#167]
### Objective

Delete the overlapped street based on the number of attributes, the age of the street  and the experience of the mapper who traced it.
### Tasks

**The below tasks are updating everyday from Monday to Friday with the latest errors in OpenStreetMap**

To-Fix issues:
- Major: http://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways
- Minor: http://osmlab.github.io/to-fix/#/stats/overlappingminorhighways
#### Changeset comment

```
Deleting overlapped highways using #to-fix https://github.com/mapbox/mapping/issues/167
```
### Coverage

All countries in this list: https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt
### Tools  for edition
- If using iD editor, work with [To-Fix web](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)
- If using JOSM, work with [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin)
### Instructions
- Delete the road wih less attributes
- Change `highway=*` tag if it necessary
- If editing in a actively mapped area, add a note instead of making a fix
## Common issues

![image](https://cloud.githubusercontent.com/assets/10425629/14258245/31f48a88-fa67-11e5-8211-16718e5f495f.png)

![image](https://cloud.githubusercontent.com/assets/10425629/14258256/44269520-fa67-11e5-8046-f8f32adb370c.png)
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
## Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data

**Comment by samely** [comment]
Done!  :rocket: 
![image](https://cloud.githubusercontent.com/assets/10425629/14291175/e32ecd2a-fb27-11e5-8058-d0dc5327b3b0.png)

**Comment by calfarome** [comment]
##### [Overlapping major highways](http://osmlab.github.io/to-fix/#/task/overlappingmajorhighways) issues from 06/20/2016 - 06/24/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 22  | 0 |
Tuesday 21st, June  | 23 | 16 |
Wednesday 22nd, June | 0| 0 |
Thursday 23rd, June | 24| 16 |
Friday 24th, June | 29|  17|
**Total** | -- | **49** | 

##### [Overlapping minor highways](http://osmlab.github.io/to-fix/#/task/overlappingminorhighways) issues from 06/20/2016 - 06/24/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 11  | 0 |
Tuesday 21st, June  | 14 | 13 |
Wednesday 22nd, June | 0 | 0 |
Thursday 23rd, June | 7 | 7 |
Friday 24th, June | 51 | 50 |
**Total** | -- | **70** |

**Comment by RichRico** [comment]
##### [Overlapping major highways](http://osmlab.github.io/to-fix/#/task/overlappingmajorhighways) issues from 06/27/2016 - 07/01/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 15  | 14 |
Tuesday 21st, June  | 8 | 7 |
Wednesday 22nd, June | 10 | 9 |
Thursday 23rd, June | 10 | 0 |
Friday 24th, June | 20 |  15 |
**Total** | -- | **32** | 

##### [Overlapping minor highways](http://osmlab.github.io/to-fix/#/task/overlappingminorhighways) issues from 06/27/2016 - 07/01/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 9  | 8 |
Tuesday 21st, June  | 4 | 4 |
Wednesday 22nd, June | 6 | 6 |
Thursday 23rd, June | 6 | 0 |
Friday 24th, June | 15 | 14 |
**Total** | -- | **45** |

**Comment by karitotp** [comment]
##### [Overlapping major highways](http://osmlab.github.io/to-fix/#/task/overlappingmajorhighways) issues from 07/04/2016 - 07/08/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 04th, July | 44 |42 |
Tuesday 05th, July  | 4 | 4 |
Wednesday 06th, July | 9 | 7 |
Thursday 07th, July |12  |12  |
Friday 08th, July |16  |13  |
**Total** | -- | **78** | 

##### [Overlapping minor highways](http://osmlab.github.io/to-fix/#/task/overlappingminorhighways) issues from 07/04/2016 - 07/08/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 04th, July | 10 |9 |
Tuesday 05th, July  |4  |2  |
Wednesday 06th, July | 0 | 0 |
Thursday 07th, July |4  |4  |
Friday 08th, July | 3 |0  |
**Total** | -- | **15** |

**Comment by dannykath** [comment]
##### [Overlapping major highways](http://osmlab.github.io/to-fix/#/task/overlappingmajorhighways)  issues from 07/11/2016 - 07/14/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July | 13 |13 |
Tuesday 12th, July  | 7 | --  |
Wednesday 13th, July | 12 | 9 |
Thursday 14th, July | 7 | -- |
**Total** | -- | **22** | 

##### [Overlapping minor highways](http://osmlab.github.io/to-fix/#/task/overlappingminorhighways) issues from  07/11/2016 - 07/14/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July |7  |-- |
Tuesday 12th, July  | 7 |7  |
Wednesday 13th, July | 10 |4  |
Thursday 14th, July | 14 | -- |
**Total** | -- | **11** |

**Comment by luiswalter** [comment]
##### [Overlapping minor highways](http://osmlab.github.io/to-fix/#/task/overlappingminorhighways) issues from  07/11/2016 - 07/14/2016

Date | N° detected error | Total Fixed 
---|---|---
Thursday 21th, July | 6018 | 5125 |
**Total** | -- | **5125** |

**Comment by samely** [comment]
##### [Overlapping major highways](http://osmlab.github.io/to-fix/#/task/overlappingmajorhighways)  issues from 07/18/2016 - 07/22/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 25th, July | 13 | 0 |
Tuesday 26th, July | 17 | 17 |
Wednesday 27th, July | 20 | 20 |
**Total** | -- | **37** |

**Comment by ridixcr** [comment]
##### [Overlapping minor highways](https://osmlab.github.io/to-fix/#/stats/overlappingminorhighways) issues from 08/01/2016 - 08/05/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 25th, July | 328|0 |
Tuesday 26th, July  | 339 |0  |
Wednesday 27th, July | 2171 | 0  :point_left:  There was a [problem](http://forum.openstreetmap.org/viewtopic.php?id=55220)|
Thursday 28th, August | 354 | 0 |
Friday 29th, August | 345 | 307 |
**Total** | -- | **307** |

**Comment by ridixcr** [comment]
##### [Overlapping minor highways](https://osmlab.github.io/to-fix/#/stats/overlappingminorhighways) issues from 08/08/2016 - 08/12/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 8th, July | 52|0 |
Tuesday 9th, July  | 48|0  |
Wednesday 10th, July | 53 | 38 |
Thursday 11th, August | 49 | 0 |
Friday 12th, August | 36 | 33 |
**Total** | -- | **71** |

**Comment by samely** [comment]
##### [Overlapping minor highways](https://osmlab.github.io/to-fix/#/stats/overlappingminorhighways)  issues from 08/08/2016 - 08/12/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 8th, July | 24 | 18 |
Tuesday 9th, July  | 17| 0  |
Wednesday 10th, July | 30 |0 |
Thursday 11th, August | 32 | 28 |
Friday 12th, August | 10 | 9 |
**Total** | -- | **55** |

**Comment by samely** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways)  issues from 08/22/2016 - 08/26/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 22th, August | 18 | 18 |
Tuesday 23th, August  | 24| 23  |
Wednesday 24th, August | 7 | 6 |
Thursday 25th, August | 13 | 0 |
Friday 26th, August | 22 | 17 |
**Total** | -- | **64** |

**Comment by samely** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways)  issues from 08/29/2016 - 08/31/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 29th, August | 41 | 34 |
Tuesday 30th, August  | 18| 16 |
Wednesday 31th, August | 23 | 16 |
**Total** | -- | **66** |

**Comment by samely** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways)  issues from 09/05/2016 - 09/09/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 5th, August | 44 | 36 |
Tuesday 6th, August  | 19 | 16 |
Wednesday 7th, August | 18 | 0 |
Thursday 8th, August | 13 | 0 |
Friday 9th, August | 15| 14 |
**Total** | -- | **66** |

**Comment by samely** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways)  issues from 09/12/2016 - 09/16/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 12th, August | 41 |28 |
Tuesday 13th, August  | 19 | 13 |
Wednesday 14th, August | 34 | 0 |
Thursday 15th, August | 41 | 36 |
Friday 16th, August | 19| 15 |
**Total** | -- | **92** |

**Comment by ridixcr** [comment]
##### [Overlapping minor highways](https://osmlab.github.io/to-fix/#/stats/overlappingminorhighways)   issues from 09/19/2016 - 09/23/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 19th, September | 238 |0 |
Tuesday 20th, September  | 67 | 66 |
Wednesday 21th, September | 24 | 24 |
Thursday 22th, September | 37 | 37 |
Friday 23th, September | 2223| 107 |
**Total** | -- | **234** |

**Comment by ridixcr** [comment]
##### [Overlapping minor highways](https://osmlab.github.io/to-fix/#/stats/overlappingminorhighways)   issues from 10/24/2016 - 10/28/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 24th, October|2457|0|
Tuesday 25th, October| 2450|0|
Wednesday 26th, October| 270| 46|
Thursday 27th, October| 267 |0|
Friday 28th, October| 222| 105|
**Total** | -- | **151** |

**Comment by ridixcr** [comment]
##### [Overlapping minor highways](https://osmlab.github.io/to-fix/#/stats/overlappingminorhighways)   issues from issues from 10/31/2016 - 11/04/2016


Date | N° detected error | Total Fixed 
---|---|---
Monday 24th, October|171|133|
Tuesday 25th, October| 170|0|
Wednesday 26th, October| 106| |
Thursday 27th, October| 123 |71|
Friday 28th, October| 116| 0|
**Total** | -- | **204** |

**Comment by samely** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways)  issues from 09/01/2017 - 13/01/2017

| Date | Total Fixed |
| --- | --- | 
| Thursday 12th, August | 1  |
| Friday 13th, August | 69  |
| **Total** |  **70** |

**Comment by samely** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways)  issues from 16/01/2017 - 20/01/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 16th, January | 68| 47 |
| Tuesday 17th, January| 113 | 77 |
| Wednesday 18th, January| 30 | 2 |
| Thursday 19th, January| 41 | 35 |
| Friday 20th, January| 26 | 17 |
| **Total** | -- | **178** |

**Comment by calfarome** [comment]
##### [Overlapping minor highways](https://osmlab.github.io/to-fix/#/stats/overlappingminorhighways)   issues from issues from 23/01/2017 - 27/01/2017

Date | N° detected error | Total Fixed 
---|---|---
Monday 23th, January |42|13| 
Tuesday 24th,January |0|0|
Wednesday 25th , January |89|47
Thursday 26th, January |0|0
Friday 27th, January|163|77
**Total** | -- | **137** |

**Comment by dannykath** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) issues    from 01/30/2017 - 02/03/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 30h January|231|86
Tuesday 31th January|154|72
Wednesday 01st February|138|50
Thursday 02th February|109|50
--| **Total**|**258**

**Comment by dannykath** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) issues    from 02/06/2017 - 02/10/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 06th February|170|75
Thursday 10th February|135|50
--| **Total**|**125**

**Comment by dannykath** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) issues    from 02/13/2017 - 02/17/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 13th February|164|80
Tuesday 14th February|97|50
Thursday 16th February|13|13
Friday 17th February|73|32
--| **Total**|**175**

**Comment by dannykath** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) issues    from 02/20/2017 - 02/24/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 20th February|21|10
Tuesday 21th February|31|10
Wednesday 23th February|16|12
Friday 24th February|40|20
--| **Total**|**52**

**Comment by dannykath** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) issues    from 02/27/2017 - 03/03/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 27th February|58|30
Tuesday 28th February|50|13
Wednesday 01st February|19|13
Thursday 02nd February|37|29
Friday 03rd February|79|20
--| **Total**|105

**Comment by dannykath** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) issues    from 03/06/2017 - 03/10/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 06th March|101|54
Tuesday 07th March|21|13
Wednesday 08th March|31|20
Friday 10th march|56|30
--| **Total**|105

**Comment by dannykath** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) issues    from 03/13/2017 - 03/17/2017

Date| Detected Issues | Fixed Issues
---|----|---
Friday 17th March|179|104
--| **Total**|**104**

**Comment by dannykath** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) issues    from 03/27/2017 - 03/31/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 27th March|19|13
--| **Total**|**13**

**Comment by dannykath** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) issues    from 04/03/2017 - 04/07/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 03rd April|4|4
--| **Total**|**4**

**Comment by dannykath** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) issues    from 04/10/2017 - 04/14/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 10th April|108|102
--| **Total**|**102**

**Comment by dannykath** [comment]
##### [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) issues    from 04/17/2017 - 04/21/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 18th April|6|3
Monday 20th April|6|4
--| **Total**|**7**

**Comment by RichRico** [comment]
#####  [Overlapping minor highways](https://osmlab.github.io/to-fix/#/stats/overlappingminorhighways) issues    from 04/24/2017 - 04/28/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 24th April |4 |3 
Wednesday 26th April|95 |15 
Thursday 27th April |195 |40
--| **Total**|**58**

**Comment by dannykath** [comment]
#####  [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) issues    from 04/24/2017 - 04/28/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 24th April |5 |4 
Monday 25th April |31 |24 
--| **Total**|**28**

**Comment by calfarome** [comment]
#####   [Overlapping minor highways](https://osmlab.github.io/to-fix/#/stats/overlappingminorhighways) issues  05/02/2017 - 05/05/2017

Date| Detected Issues | Fixed Issues
---|----|---
Wednesday 03th May|56 |33
Friday 05th May|6 |6
--| **Total**|**39**

**Comment by dannykath** [comment]
###  [Overlapping major highways](https://osmlab.github.io/to-fix/#/stats/overlappingmajorhighways) 
### Issues    from 05/08/2017 - 05/12/2017

Date| Detected Issues | Fixed Issues
---|----|---
Tuesday 9th May |61 |40 
Wednesday 10th May |6 |4 
Thursday 11th May| 6|5 
Friday 12th May | 927|90
--| **Total**|**139**
