### ISSUE TITLE
'scripting josm' es roto en Mapeo con JOSM

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapping#173]
![image](https://cloud.githubusercontent.com/assets/1551510/14558858/8d873a1c-0322-11e6-94fd-febab8ee751c.png)

**Comment by Rub21** [comment]
I will check this!

**Comment by Rub21** [comment]
it works: https://gist.github.com/Rub21/cc055320c925c855926e
![image](https://user-images.githubusercontent.com/1152236/33621336-60b21926-d9b8-11e7-9eb0-78e2cd65a4dc.png)
