### ISSUE TITLE
HOT Mapping for Ecuador 7.8 EQ 2016

### ISSUE THREAD

**Issue by maning** [mapbox/mapping#175]
Ecuador was hit by a 7.8 magnitude earthquake last weekend (16 Apr 2016).  At least 272 people were killed and 2,527 people injured [wikipedia](https://en.wikipedia.org/wiki/2016_Ecuador_earthquake).  The national government of Ecuador has declared a national state of calamity. **HOT is supporting the local OSM community to map the heavily affected areas.**

**Current status**

* AWG has not yet declared a full activation, this effort is to support local OSM community in Ecuador.
* [3 TM projects](http://tasks.hotosm.org/?sort_by=priority&direction=asc&search=Earthquake+in+Ecuador) are ready for pre-disaster mapping.
* Imagery WG is coordinating access to imagery (from government portal and satellite providers).

**Next actions**

*  Team will focus on completing (done/validation) of [Padernales Canton](http://tasks.hotosm.org/project/1794), lets hit this today.
* @maning will coordinate with the HOT community for next actions as the activation progresses.
* @Rub21 @rodowi to help in the coordination especially for compiling news on what's happening on the ground (mostly in Spanish).

**Comment by maning** [comment]
Here's a list of orthophotos available in [Ecuador's Geoportal](http://www.geoportaligm.gob.ec/portal/index.php/catalogo-de-datos/), use this to supplement Bing and Mapbox imagery in the areas we are tracing: https://gist.github.com/maning/da747dd283909b66950503eae4532517

New TM projects will be based on these imagery and reported damages in the populated areas.

**Comment by mikelmaron** [comment]
Public statement on activation from HOT https://hotosm.org/updates/2016-04-18_latest_update_earthquakes_in_japan_and_ecuador

**Comment by Rub21** [comment]
#### Updates

We are creating new tasks for each [Canton](https://gist.github.com/Rub21/f48e8fd839d5bb28acdfa2991d861f64), according the orthophotos available [Ecuador's Geoportal](http://www.geoportaligm.gob.ec/portal/index.php/catalogo-de-datos/),  and highlighting [priority areas](https://gist.github.com/anonymous/0b4294dc2df1ae7fd1c0ad378b5485c5)

- http://tasks.hotosm.org/project/1805

**Comment by pratikyadav** [comment]
### Project update

@mapbox/team-data  added about 16,000 buildings and 450 streets in [Portoviejo HOT task.](http://tasks.hotosm.org/project/1796)

![2a324a90-12ab-11e6-83a7-8458ae4f9f7b](https://cloud.githubusercontent.com/assets/12744420/15072158/db6887f8-13ae-11e6-9c3c-64624ebe1ed0.png)

OSM diary-> https://www.openstreetmap.org/user/dannykath/diary/38561

Closing here.
