### ISSUE TITLE
Mapping turn restrictions using Mapillary in San Francisco

### ISSUE THREAD

**Issue by jinalfoflia** [mapbox/mapping#177]
Lets focus on improving OSM for routing in SF which has a very dense Mapillary coverage and detected turn restrictions.
- **Area** SF City, work down list of highest traffic roads with maximum probability of turn restrictions
- **Timeline** 5 days
- **Team** @oini @jinalfoflia @shvrm @planemad @ramyaragupathy @srividyacb 

**Objectives**
- Use [Mapillary vector tiles](http://mapbox.github.io/mapillary-experiments/traffic/#19.25/38.90266/-77.03673/-65.9) to add missing turn restrictions, access restrictions and speed limits on OSM
- Determine the acceptance criteria for complete mapping coverage for routing in an area using available data sources
- Estimate data gaps in Mapillary data to achieve acceptance criteria for complete routing coverage

**Features**
- [Turn Restrictions](http://wiki.openstreetmap.org/wiki/Relation:restriction) `type=restriction`+`restriction=*`: No U-turn, no left turn, no right turn

**[Project spreadsheet](https://docs.google.com/spreadsheets/d/1xNM6Ev7Rq4B-HiUwTDgLCgEdghzStpJumwgWCE7horo/edit?ts=572048c6#gid=0)**

**Workflow**
- Use the spreadsheet to to pick a street to review and track progress
- Use the [Mapillary vector tiles](http://mapbox.github.io/mapillary-experiments/traffic/#12.36/37.7433/-122.4159) to review each junction on the road 
- Analyze the Mapillary street view coverage of the junction, validate existing turn restrictions and add missing ones

**Caution** 🚨 
- Be careful with interpreting signage and don't blindly follow Mapillary. This is a sign for no free right that Mapillary interpreted as `no-right-turn`. This is NOT a turn restriction, always ask if in doubt. <br><img width="232" alt="screenshot 2016-04-26 21 39 06" src="https://cloud.githubusercontent.com/assets/126868/14825399/67567b40-0bf7-11e6-9b61-dc875160ccc1.png">
- The location and bearing of the Mapillary photo is not reliable and is prone to usual GPS errors. Cross check the photograph with the map to confirm you are looking at the intersection from the correct bearing. This photograph is facing the reverse of actual heading.<br> 
  <img width="835" alt="screenshot 2016-04-27 12 28 12" src="https://cloud.githubusercontent.com/assets/126868/14844241/91873ce8-0c73-11e6-9785-a591f8534f89.png">
- Mapillary will detect only one sign type per image. Lookout for multiple restrictions in the photograph<br>
  <img width="178" alt="screenshot 2016-04-27 17 49 34" src="https://cloud.githubusercontent.com/assets/126868/14851913/a6235e66-0ca0-11e6-8180-366006e7fc7b.png">

**Special cases**
- [Conditional restrictions](http://wiki.openstreetmap.org/wiki/Conditional_restrictions) during peak hours are common in SF. Tag them as `restriction:conditional=no_left_turn @ (Mo-Sa 07:00-09:00,16:00-18:00)`<br>![](https://cloud.githubusercontent.com/assets/4470913/14850426/9d4643f8-0c96-11e6-8c0c-dc94887e1613.png)
- Conditional restriction during baseball games. Ignore<br>
  <img width="205" alt="screenshot 2016-04-27 16 51 33" src="https://cloud.githubusercontent.com/assets/126868/14850687/6208c57a-0c98-11e6-8535-2d434b9bf8fe.png">

**Reference**
- OSM tags for routing http://wiki.openstreetmap.org/wiki/OSM_tags_for_routing
- Turn restrictions http://wiki.openstreetmap.org/wiki/Relation:restriction
- Access restrictions http://wiki.openstreetmap.org/wiki/Key:access
- Conditional restrictions http://wiki.openstreetmap.org/wiki/Conditional_restrictions

**Changeset**
- Comment `Updating missing turn restrictions in SF using Mapillary https://github.com/mapbox/mapping/issues/177`
- Source `Bing;Mapillary`

cc @mapbox/team-data

**Comment by ramyaragupathy** [comment]
Came across a different type of condition for a turn restriciton, other than the one mentioned in the ticket.
Marking this as `restriction:conditional`. 
![screenshot 2016-05-02 12 01 18](https://cloud.githubusercontent.com/assets/12103383/14948422/b9f1838a-105d-11e6-9604-2781de0d6d96.png)

cc @jinalfoflia @srividyacb @oini @planemad

**Comment by planemad** [comment]
@ramyaragupathy good example, i'm leaning towards adding this as a regular `restriction` since it applies for all regular personal vehicles.

Lets add a conditional restrictions when the restriction is conditionally applied to a private vehicles:
- On certain times of the day
- On a certain day of the year

**Comment by oini** [comment]
Querying Overpass in SF, we found that currently there are:

- [22](http://overpass-turbo.eu/s/g3j) relations with the `restriction=conditional` tag

![screen shot 2016-05-05 at 12 13 45 pm](https://cloud.githubusercontent.com/assets/1933377/15039619/13dc80dc-12cc-11e6-83e3-fd7654801e8a.png)

- [93](http://overpass-turbo.eu/s/g3k) relations with any of `hour_on=*` or `hour_off=*` tags. Of these:
  - [6](http://overpass-turbo.eu/s/g3m) relations have the `restriction:conditional=*` tag
  - [87](http://overpass-turbo.eu/s/g3o) relations have the `restriction=*` tag

In order to have a consistent tagging scheme, I'll be following the workflow mentioned below:

- As a first pass, I'll work on mass-editing the [87](http://overpass-turbo.eu/s/g3o) relations having the `restriction=*` tag to `restriction:conditional=*` tag
- Once done, we'll work on each of the relations with the `restriction:conditional=*` tag and add the timings for each from the Mapillary images or the already existing `hour_on=*`, `hour_off=*`, `day_on=*`, `day_off=*` tags following the [current format](http://wiki.openstreetmap.org/wiki/Key:access#Access_time_and_other_conditional_restrictions). For example,  `restriction:conditional=no_left_turn  @  (Mo-Sa 07:00-09:00,16:00-18:00)`.

cc @planemad @lxbarth @jinalfoflia @shvrm @maning @srividyacb

**Comment by oini** [comment]
The [86](http://overpass-turbo.eu/s/g3o) relations having the `restriction=*` tag have been updated with a new `restriction:conditional=*` tag in this changeset: http://www.openstreetmap.org/changeset/39119075

**Next Action:** Each of the [103](http://overpass-turbo.eu/s/g3A) restrictions with the `restriction:conditional=*` tag but lacking the timing information according to the new tagging scheme will be reviewed and the timing information will be updated in the following format: `restriction:conditional=no_left_turn @ (Mo-Sa 07:00-09:00,16:00-18:00)`

**Comment by oini** [comment]
I have manually inspected each of the [103](http://overpass-turbo.eu/s/g3A) restrictions with the `restriction:conditional=*` tag that lacked the timing information according to the new tagging scheme.

### Current State of Conditional Turn Restrictions on OSM

- Total number of Conditional Turn Restrictions (`restriction:conditional=*` tag) currently present in SF: **[106](http://overpass-turbo.eu/s/g4Z)**
Of these:
  - **[87](http://overpass-turbo.eu/s/g51)** have both the `restriction=*` and `restriction:conditional=*` tags 
  - **[19](http://overpass-turbo.eu/s/g52)** Conditional Turn Restrictions have only the `restriction:conditional=*` tag

### State of Conditional Turn Restrictions before the modifications

- Conditional turn restrictions already present on OSM: **88** Of which:
  - **5** already had the timing information added according to the new tagging scheme (`restriction:conditional=no_left_turn @ (Mo-Sa 07:00-09:00,16:00-18:00)`)

### Modifications made to the Conditional Turn Restrictions

- Conditional turn restrictions **added** by the team: **18**
- `restriction:conditional=*` tag was added to **[86](http://overpass-turbo.eu/s/g54)** restrictions as a part of the [first pass](https://github.com/mapbox/mapping/issues/177#issuecomment-217137718)
- timing information was added to **101** following the new tagging scheme (`restriction:conditional=no_left_turn @ (Mo-Sa 07:00-09:00,16:00-18:00)`)
 - Of the [103](http://overpass-turbo.eu/s/g3A) restrictions that were inspected, **2** were incorrectly tagged as `restriction:conditional=*`. For these two, I have removed the `restriction:conditional=*` tag

### Other Observations

I came across the below instance where the restriction is applicable only on `School Days`. Per discussion with @planemad I added the restriction for `Monday - Friday`

![screen shot 2016-05-06 at 2 57 43 pm](https://cloud.githubusercontent.com/assets/1933377/15074787/7c6594d4-13be-11e6-9c01-1d277070960e.png)

cc @shvrm @lxbarth @jinalfoflia @srividyacb @ramyaragupathy

**Comment by planemad** [comment]
@gyllen The Mapillary detected sign layer has been super useful in adding turn restrictions to OpenStreetMap. Is there any way that certain important signages can show up at a lower zoom level than z16? This will allow quickly eyeballing an entire city instead of zooming in.

![untitled3](https://cloud.githubusercontent.com/assets/126868/15467708/958cd304-20fd-11e6-9a3a-58aa601bb867.gif)
https://www.mapbox.com/bites/00249/#16.94/37.76504/-122.41987

**Comment by jinalfoflia** [comment]
Here is the [work-flow](https://gist.github.com/jinalfoflia/208fef0c779e6b2d5694c58b9dfca7d8) that we followed to add turn restrictions on OpenStreetMap using Mapillary.

/cc @planemad @shvrm @oini @lxbarth @srividyacb @ramyaragupathy

**Comment by gyllen** [comment]
@planemad Would up to 14 help?

**Comment by planemad** [comment]
@gyllen z14 would be a definite improvement 👍 Since we're using GL, svg icons would be most convenient. Was planning on assembling them with traffico, but this just ended up much quicker 😸

**Comment by oini** [comment]
@gyllen Just checked that the signs are now loading at z14.

![otleyroad](https://cloud.githubusercontent.com/assets/1933377/15493928/057a953c-21a5-11e6-9abe-f615e2de6e5e.gif)

This makes our search 👀  through the map much easier. Thanks a lot! 😺

**Comment by planemad** [comment]
@gyllen can you let us know if the mapillary-vector.mapillary.io supports https?

**Comment by gyllen** [comment]
@planemad You are using our test tiles now, we are rewriting our API so all spatial data will be served as vector tiles. This will for sure support `https`. Two questions

1. What tool are you using above?
2. Now is the time if you have any feedback of anything you miss in the tiles.

**Comment by oini** [comment]
> Now is the time if you have any feedback of anything you miss in the tiles.

@gyllen The traffic sign detection algorithm that you are using is commendable as even very tiny, badly angled or lit up signs have been identified. Although, while investigating the detected traffic signs in NYC, I came across a couple of instances where the image that was identified to contain a turn restriction, actually had none in it. For example:

![screen shot 2016-05-25 at 11 28 25 pm](https://cloud.githubusercontent.com/assets/1933377/15550787/b1edcfe2-22d0-11e6-950b-5a46b5b5f608.png)

Also, it would be great to have the Traffic Sign detection at z10/z12 and a way to identify if one image has more than one detected traffic sign.

cc @planemad

**Comment by gyllen** [comment]
@ybkuang Is this a well known problem in our detector?

@oini I can see what I can do with the some levels. I will make sure that all detected signs in one image is listed.

**Comment by gyllen** [comment]
@oini @planemad @maning Have you guys thought about integrating MapillaryJS to the planemad viewer -> https://github.com/mapillary/mapillary-js

If you do that you would be able to try to move closer to an object. Also be able to zoom and navigate panos. Here is an easy example of MapillaryJS integrated http://mapillary.github.io/mapillary-js-examples/highline/ we also have a tagging system going, http://blog.mapillary.com/update/2016/05/19/mapillary-js-tagging.html

Will be used for tagging feedback so we can train better.

**Comment by maning** [comment]
@kepta, this should interesting for you since [you've worked on a similar thing in iD](http://www.openstreetmap.org/user/kepta/diary/38730).

**Comment by kepta** [comment]
@maning which tool are we using here.

**Comment by maning** [comment]
Related to [false detection](https://github.com/mapbox/mapping/issues/177#issuecomment-221657908), today, I encountered a shop sign tha was detected as a turn restriction.  The 🎯 sign seems to be detected as a turn restriction.

See below:

![screen shot 2016-05-27 at 16 39 02](https://cloud.githubusercontent.com/assets/353700/15608823/e921fba4-2439-11e6-8cbc-6ee2bddff93b.png)

![screen shot 2016-05-27 at 16 38 54](https://cloud.githubusercontent.com/assets/353700/15608824/e9240796-2439-11e6-8ebe-53bab80056e7.png)

**Comment by ybkuang** [comment]
@oini The false blur is due to errors of the face/license plate detectors. We will work on improving that. Right now, you will have to request an un-blur and look at the photos again once un-blur is done. @gyllen , can we figure something easier UI wise?

@maning The `target` sign confuses the traffic sign detector. We are doing an iteration of US signs improvement. This should be fixed once the new version is out.

**Comment by jinalfoflia** [comment]
> The false blur is due to errors of the face/license plate detectors. We will work on improving that. Right now, you will have to request an un-blur and look at the photos again once un-blur is done.

Oh this is great @ybkuang! Is there a specific procedure to request for un-blur images?

/cc @planemad @gyllen

**Comment by AndrewSnow** [comment]
Realize this was a commercial MBox effort and most likely you have moved on, but wanted to let you know that after stumbling on to it and noting the intersections of interest where you had no data, I set out on my E-bike to fill in as many as I could.  Didn't note many new restrictions except the ones you would expect at intersections with one way streets.  

@ybkuang You may want to set a detection rule that triggers a review for speed limits above 70 in the US.  In the new data I uploaded, I saw at least two register as detecting an 85 mph limit on a city street.

**Comment by planemad** [comment]
@AndrewSnow thank you for the special effort ❤️

**Comment by jinalfoflia** [comment]
No next actions here, closing this.
