### ISSUE TITLE
Data team peer review 5/02-5/06

### ISSUE THREAD

**Issue by chtnha** [mapbox/mapping#182]
Last week peer-review ticket: #179.

#### Mapping projects to be reviewed
1. [Exit and Destination Mapping](https://github.com/mapbox/mapping/issues/169).
2. [Turn lanes mapping](https://github.com/mapbox/mapping/issues/180)
3. [To-fix: Unconnected minor highways](https://github.com/mapbox/mapping/issues/106)
4. [To-fix: Overlapping major highways](https://github.com/mapbox/mapping/issues/167)
5. [To-fix: Crossing major highways](https://github.com/mapbox/mapping/issues/104)
6. To-fix: Crossing minor highways
7. [To-fix: Kinks major highways](https://github.com/mapbox/mapping/issues/107)
8. [To-fix: Kinks minor highways](https://github.com/mapbox/mapping/issues/107)

#### Instructions
* Download `.osm` files for last week.
 - [2016-05-02](https://s3.amazonaws.com/mapbox/osm-history-processor/day/000/001/2016-05-02.tar.gz)
 - [2016-05-03](https://s3.amazonaws.com/mapbox/osm-history-processor/day/000/001/2016-05-03.tar.gz)
 - [2016-05-04](https://s3.amazonaws.com/mapbox/osm-history-processor/day/000/001/2016-05-04.tar.gz)
 - [2016-05-05](https://s3.amazonaws.com/mapbox/osm-history-processor/day/000/001/2016-05-05.tar.gz)
 - [2016-05-06](https://s3.amazonaws.com/mapbox/osm-history-processor/day/000/001/2016-05-06.tar.gz)

* Select any date and extract the files. 
* Each team member will have an osm file of edits during the respective date, for example: `2016-04-20-andygol.osm`. Select any `.osm` file and open the data in JOSM. 
* If no edits were done during that day, JOSM will notify that no data was exist, load another file.

![screen shot 2016-04-25 at 6 08 07 pm](https://cloud.githubusercontent.com/assets/6770741/14811835/c1b461dc-0bb7-11e6-921c-69a3352d9b69.png)

* Examine user edits in detail. In JOSM, select a random small area edited by the user and press `3` to zoom.
* Download the latest data in OSM as a new layer and add a filter `Cmd + F` to see only the user's edits, e.g. `user:andygol`.

![andyfilter3](https://cloud.githubusercontent.com/assets/6770741/14813545/cf7409d2-0bbf-11e6-9389-5b6132b7bb55.gif)

* Select a way/node and load the the history (`Ctrl + H`), the changeset comment will describe what specific project the user was working on.
* To get an OSM link to the object, click `Cmd + Shift + H`. 
* Note down any feedback for each user in this ticket or comment directly in the changeset. Use this format:

```
username
changeset link - issue to fix
```

* @karitotp or @chtnha will post the feedback in the ticket (Use Github handle because OSM name is different from Github name) and make necessary changes on the same day.
* Close the ticket once user's have fixed their edits.

For clarifications, discuss with the @mapbox/team-data in this ticket.

**Comment by chtnha** [comment]
@dannykath 

##### Delete extra node
* https://www.openstreetmap.org/node/4163739097/history

##### Delete duplicated highway and node 
* https://www.openstreetmap.org/changeset/39125406

##### Moved the traffic sign 13 meter away
* https://www.openstreetmap.org/node/2092124412/history

**Comment by chtnha** [comment]
@jothirnadh 

##### Added `destination` & `destination:ref` to a node
* https://www.openstreetmap.org/node/81616425/history
* https://www.openstreetmap.org/node/50586868/history

**Comment by chtnha** [comment]
@andygol 

#### `parking_aisle` is not necessary for the whole stretch of service road
* https://www.openstreetmap.org/way/92194410/history
* https://www.openstreetmap.org/way/99814866/history

**Comment by chtnha** [comment]
@ridixcr 

##### If this a tertiary link, then it needs to be connected to the main highway  
* https://www.openstreetmap.org/changeset/39125819

**Comment by chtnha** [comment]
@Rub21 

##### polygons of the `landuse=wood` needs to be closed
https://www.openstreetmap.org/changeset/39127425 
https://www.openstreetmap.org/changeset/39127783

**Comment by Andygol** [comment]
@chtnha thank you for review

> `parking_aisle` is not necessary for the whole stretch of service road

> https://www.openstreetmap.org/way/92194410/history
> https://www.openstreetmap.org/way/99814866/history

Here is really parking aisles in the Google campus ☝️ 
but I made minor fixes

https://www.openstreetmap.org/changeset/39242639

**Comment by ridixcr** [comment]
@chtnha  thank for the feedback

here is the fix 
https://www.openstreetmap.org/changeset/39268632

**Comment by dannykath** [comment]
@chtnha  thanks for your review
#### Delete extra node 
- https://www.openstreetmap.org/changeset/39268602

#### Delete highway and node 
 - https://www.openstreetmap.org/changeset/39268687

#### Moved the traffic sign 13 meter away
- https://www.openstreetmap.org/changeset/39268812

**Comment by Rub21** [comment]
> polygons of the landuse=wood needs to be closed

The errors was fixed!

**Comment by jothirnadh** [comment]
Thanks for the review @chtnha!

Fixed the issues:
https://www.openstreetmap.org/changeset/39344386#map=17/32.66032/-96.72701&layers=N
https://www.openstreetmap.org/changeset/39344441#map=18/38.81910/-76.91418&layers=N
