### ISSUE TITLE
HOT: Sri Lanka Floods (May 2016)

### ISSUE THREAD

**Issue by pratikyadav** [mapbox/mapping#184]
OSM-WIKI - http://wiki.openstreetmap.org/wiki/2016_Sri_Lanka_Floods
Slack Channel - hotslfloods.slack.com

> The Disaster Management Center of Sri Lanka has requested HOT's generating an estimate of the number of buildings affected by flooding in the Kelani River Basin. We'll map all the visible buildings and roads to make this possible.

![image](https://cloud.githubusercontent.com/assets/12744420/15418103/1529abcc-1e7a-11e6-9e50-103af1e62b72.png)
[Source- thepeninsulaqatar ](http://www.thepeninsulaqatar.com/news/asia/382238/sri-lanka-flood-toll-hits-11-thousands-more-homeless)

**Point of contact from Mapbox-** @geohacker @maning 

### Tasks
- Western Kelani River Basin http://tasks.hotosm.org/project/1913 

#### Next actions
- @mapbox/team-data will work on **mapping and validation** in [Western Kelani River Basin](http://tasks.hotosm.org/project/1913) task.
- @ramyaragupathy will work on Tamil translation.
- I will coordinate for imagery related issues

**Comment by Andygol** [comment]
@pratikyadav 
Could you add Russian and Ukrainian description to the task?

```
Russian

Центр ликвидации последствий стихийных бедствий Шри-Ланки обратился к HOT за
помощью в оценке количества домов, пострадавших в следствии наводнения в 
бассейне реки Келани. Для этого необходимо нанести на карту все дома, которые 
возможно различить на снимках, а также подъезды к ним.

Это задание покрывает западную часть басейна Келани.
```

```
Ukrainian

Центр ліквідації наслідків стихійних лих Шрі-Ланки звернувся до HOT за допомогою 
в оцінці кількості будинків постраждалих в наслідок повіні в басейні ріки 
Келані. Потрібно нанести на мапу всі будинки, які можливо винайти на знімках, а 
також дороги, що ведуть до них.

Це завдання покриває західну частину басейну Келані.
```

**Comment by ramyaragupathy** [comment]
Task instruction translation available here https://gist.github.com/karthikb351/62ba72dc37c62baa7bf59e8839081f62.  UI strings translation on transifex is complete. They can be accessed here https://www.transifex.com/hotosm/osm-tasking-manager2/ 
cc @pratikyadav @maning

**Comment by maning** [comment]
@ramyaragupathy Thanks! Merge [in progress](https://www.openstreetmap.org/changeset/39444705).

**Comment by ruthmaben** [comment]
We completed tracing 89% of the blocks and validated 50%.

![screenshot 2016-05-20 20 57 41](https://cloud.githubusercontent.com/assets/10308123/15432862/8fa4d234-1ecd-11e6-9d85-f01256e27b03.png)

**Comment by pratikyadav** [comment]
No further actions for now. Closing here.
