### ISSUE TITLE
Broken transit and turn restriction relations in Portland

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#185]
Investigating issue from https://github.com/mapbox/mapping/issues/180#issuecomment-220530881 by @dobratzp, three accidental changesets cased a major breakage in relations in Portland, USA. A large set of ways replaced existing members of multiple bus routes from Beaverton Transit Center and turn restriction relations.

Changesets responsible:
- https://www.openstreetmap.org/changeset/39375027
- https://www.openstreetmap.org/changeset/39375345
- https://www.openstreetmap.org/changeset/39375690

Relations affected:
- https://www.openstreetmap.org/relation/1654457
- https://www.openstreetmap.org/relation/166138
- https://www.openstreetmap.org/relation/1829927
- https://www.openstreetmap.org/relation/1830136
- https://www.openstreetmap.org/relation/2026211
- https://www.openstreetmap.org/relation/2903404
- https://www.openstreetmap.org/relation/2903405
- https://www.openstreetmap.org/relation/4033810
- https://www.openstreetmap.org/relation/4040351
- https://www.openstreetmap.org/relation/4071514
- https://www.openstreetmap.org/relation/4071570
- https://www.openstreetmap.org/relation/4100472
- https://www.openstreetmap.org/relation/4100473
- https://www.openstreetmap.org/relation/4132040
- https://www.openstreetmap.org/relation/4241959
- https://www.openstreetmap.org/relation/4241962
- https://www.openstreetmap.org/relation/4244274
- https://www.openstreetmap.org/relation/4250113
- https://www.openstreetmap.org/relation/5553728

**Additional information**
The changes happened in a 30 minute window on May 17 UTC1200-1230 during validation of the turn lanes task. JOSM reported no conflicts during these uploads.

All relations were modified twice by the same changeset 2 minutes apart:
<img width="1025" alt="screenshot 2016-05-20 14 48 58" src="https://cloud.githubusercontent.com/assets/126868/15423221/1e021caa-1e9a-11e6-88a9-c9ab54a3d08e.png">

![untitled3](https://cloud.githubusercontent.com/assets/126868/15424148/ab3d3704-1e9e-11e6-9624-e5febdcf4d16.gif)

Confirmed with @poornibadrinath that we close a changeset after every upload. It is a mystery how ^ happened:
<img width="523" alt="screenshot 2016-05-20 14 51 42" src="https://cloud.githubusercontent.com/assets/126868/15423304/82d59c92-1e9a-11e6-94c9-88711281de3e.png">

**Summary**
- It is unclear how these breakages happened or how to recreate such a scenario
- Attempting to revert the 3 changesets causes multiple conflicts. A clean revert is not possible.
- Next actions: Notify talk-us of the breakages for best strategy on restoring the data

cc @mapbox/team-data

**Comment by planemad** [comment]
@dobratzp can you please share how you detected all the broken relations? This would be very useful to add to our workflow.

**Comment by dobratzp** [comment]
I was doing some edits in Southeast Portland based on pictures that I took while out jogging.  As part of those edits, I was adding a bus stop to the bus route relations for bus route 4.  Then I got the "Route relation contains a gap" warning in JOSM.  Bus route relations frequently contain gaps after people have edited roads that make them up, so I started going through all of the bus routes in Portland looking for gaps.

Then I realized that one direction of bus route 52 was missing.  Luckily, I created [a wiki page describing the Portland area bus routes](http://wiki.openstreetmap.org/wiki/Portland,_Oregon/Transit_Route_Relations), so I was able to download [Bus 52: Beaverton Transit Center => Portland Community College Rock Creek](http://www.openstreetmap.org/relation/4132039) using its OSM ID.

Note: it's impossible to download a relation object during normal editing if there are no members.  The relation members are the things that have the lat/long.  If any changesets that you are making are resulting in Relation objects with zero members, then you are creating errors in OSM data.

As I started to recreate that leg of bus route 52, I noticed that some of the Ways were members of a number of different bus routes that didn't make sense.  These are bus routes that travel near my house and I know that they don't go to Portland Community College Rock Creek.  Then I looked closer at the relations affected by the same changeset and found a strange pattern of many of the relations becoming corrupted with exactly the same members.

As far as fixing bus routes, I usually download a small area of OSM data containing the route, then edit the route.  Inside the JOSM relation editor, there is a button to download the rest of the members of the relation.  Then you can right-click on the first Way and select "find next gap."

**Comment by rickmastfan67** [comment]
I have a theory here on how it might have happened.  Since these changes were done with JOSM, did you keep the same layer open and continue making changes for the next upload?  If you did, I would immediately stop doing that.  Close the layer and start completely fresh with a new layer of downloaded data from the area via the OSM api after every upload.

JOSM has this little quirky bug that I reported a long time ago that might have a hand in this, but not 100% sure it's the cause here.  https://josm.openstreetmap.de/ticket/6332

Either way, do what I suggested at the top, and I don't think this will happen again.

**Comment by dobratzp** [comment]
I've gone through and updated the turn restrictions.  I think there was a part of Beaverton Hillsdale Highway where a traffic island was recently added (not on the Bing images).  I'm guessing you guys deleted the dual-carriageway since you were working remotely with the latest imagery you have available.  I deleted the turn restriction for now since they don't make sense without the dual-carriageway, and I put an OSM note down so I remember to stop by there at some point.  Maybe I'll take the time to walk around and Mapillary everything.

I will update the transit route and road route relations later when I get a chance.  I think I'm fairly confident in my ability to load in prior versions of relations in JOSM.

**Comment by dobratzp** [comment]
I updated the rest of the route relations that had all of their members replaced.  I'll go through each bus route at some point and make sure they are connected.

**Comment by dobratzp** [comment]
I finished updating all of the regional bus routes so there are no gaps.

**Comment by abhisheksaikia** [comment]
@dobratzp Thank you for your help in cleaning up the broken transit and turn restrictions relations in Portland. I have reviewed the relations mentioned by @planemad [above](https://github.com/mapbox/mapping/issues/185#issue-155926092) and it seems that one of the relations: https://www.openstreetmap.org/relation/4132040 might have missed your review. Can you please take a look at it and see if it requires any corrections.

**Comment by abhisheksaikia** [comment]
@maning and @planemad have conducted a review of the possible reasons behind the mass broken transit relations in Portland. The results are still inclusive as to the exact reason what caused this mass breakage of relations.

#### Here are some of the most probable reasons for this error:

* [Working in the same layer after uploading the data](https://github.com/mapbox/mapping/issues/185#issuecomment-220713627): It is advisable to close a layer after an upload and work in a completely new layer of downloaded data from OSM.

* Working in multiple layers at the same time: Avoid working on multiple layers at the same time. Delete a layer if you are not working on it. This will avoid unnecessary complications and conflicts.

* Deleting dual carriageways: Dual carriageways must not be deleted specially when they are parts of relations. Deleting any dual carriageway will cause multiple relations to be broken.

#### Capturing the steps followed by the community in resolving the issue:

* @dobratzp Used this workflow in restoring the previous versions of the broken route relations:

1. Use the API to download the last good version of the route relation,
save as a .osm file.
2. Add action="modify" to the relation element in the OSM XML file
3. Load OSM XML file into JOSM
4. Download the relation by ID to get the latest version.
5. Handle conflicts by discarding the current relation and using the
version that I loaded from the file.
6. Use the JOSM relation editor to download the members
7. Use the JOSM relation editor to "find the next gap"
8. Download current OSM data for the area with the gap and add appropriate
members to the relation

#### Next actions:

* Continue monitoring relations during all validation work and develop a workflow to detect similar cases in the future- @planemad 
* @mapbox/team-data to be mindful of the potential reasons that might have caused this issue and avoid them during any future mapping.

#### Resources:

1. https://lists.openstreetmap.org/pipermail/talk-us/2016-May/016310.html
2. http://wiki.openstreetmap.org/wiki/Portland,_Oregon/Transit_Route_Relations
3. https://help.openstreetmap.org/questions/4019/how-do-i-restore-data-that-was-lost-during-editing

**Comment by dobratzp** [comment]
https://www.openstreetmap.org/relation/4132040 is correct.  This is the relation that for some reason had its members copied over the other relations.

**Comment by dobratzp** [comment]
There is one thing to add about opening the OSM XML file in JOSM for a prior version of a relation.  After you load the file, open the relation editor and download all of the members.  Then when you are resolving the conflict to restore the prior version, members that refer to OSM objects that have been delete will get automatically filtered out.

**Comment by planemad** [comment]
**Next actions**
- @planemad post on diary on the incident

**Comment by planemad** [comment]
Thank you dobratzp for resolving this. We have not seen a similar issue and this seems like it could have been a one off incident thats not reproducable. This is great documentation and we should revisit if this happens again.
