### ISSUE TITLE
To-fix: Invalid turn lanes

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#193]
### Objective

Verified that the number of `lanes` matches with the sum of `lanes:*`. And also check the order of `turn:lanes:*` values.
### Task

**The task below is updating everyday from Monday to Friday with the latest errors in OpenStreetMap**

To-Fix issue: http://osmlab.github.io/to-fix/#/task/invalidturnlanes
#### Changeset comment

```
Fixing incorrectly added turn-lanes using #to-fix https://github.com/mapbox/mapping/issues/193
```
### Coverage

All countries in this list: https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt
### Tools for edition
- If using iD editor, work with [To-Fix web](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)
- If using JOSM, work with [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin)
- Use the [turn lanes editor plugin](https://github.com/mapbox/turnlanes-tagging) to check the matching of lanes numbers and  sort the signs in the right position.

![](https://cloud.githubusercontent.com/assets/1152236/16128803/bc894456-33c7-11e6-9d8f-62e5a58b24ab.gif)
### Instructions
- Check if the number of `lanes` match with the sum of `lanes:backward`\+ `lanes:forward` + `lanes:both_ways`
- Check if the number of `lanes`, `lanes:backward`, `lanes:forward` and `lanes:both_ways` match with the lanes number of `turn:lanes:backward`, `turn:lanes:forward` and `turn:lanes:both_ways`
- Check the order of the `turn:lanes:*` which should be [`left-through-right`](http://wiki.openstreetmap.org/wiki/Key:turn#Turning_indications_per_lane)
- If a way has the `turn:lanes:*` tag and it's not clear in the satellite imagery,  just check the points above without deleting the `turn:lanes:*` tag.
- Check if the `turn:lanes:*` tag match with the signs in the street.
- If editing in an actively mapped area, add a note instead of making a fix.
## Common issues

![image](https://cloud.githubusercontent.com/assets/10425629/16020605/7e124150-3174-11e6-8719-ad5da4d1b8d5.png)
_Tag should be `turn:lanes=left|left;through`_

![image](https://cloud.githubusercontent.com/assets/10425629/16020738/f939a71a-3174-11e6-8013-d35dd26c0f37.png)
_Tag should be `lanes=5`_

![image](https://cloud.githubusercontent.com/assets/10425629/16020783/324d0b3c-3175-11e6-8db5-a1bc36ac05b2.png)
_Tag should be deleted since it's very clear this doesn't have any sign in the street and this is not  `oneway=yes`_

![image](https://cloud.githubusercontent.com/assets/10425629/16020912/b2bef5a0-3175-11e6-9315-d06887472f0c.png)
_Tag should be `turn:lanes=left||`_
# Tips
- `none` itself is valid value but **not** in conjunction with other  
  - ✅ `turn:lanes=none|right` is equal to `turn:lanes=|right` - we use `none` for "_better readability_"
  - 👎  `turn:lanes=left||none|merge_to_right` - this combination of values is valid but there is mixing `none` and `||` (empty) - this is not good choice.  
  - 👍  `turn:lanes=left|none|none|merge_to_right` or `turn:lanes=left|||merge_to_right`  
  - ❎ `turn:lanes=none|none|none` or `turn:lanes=||` - in this case `turn:lanes=*` tag is redundant, just specify `lanes=3` or real number of lanes  
  - ❎ `turn:lanes=none|none;slight_right` - isn't valid combination - "_there are no turn indications_"  on the rightmost lane. Instead, must be used :

```
lanes=2
turn:lanes=none|through;slight_right
transit:lanes=continue|new_on_right
```
- using `*right` | `*left` values  
  - ✅ `turn:lanes=left|none|none` or `turn:lanes=||right` or `turn:lanes=merge_to_right||` or `turn:lanes=left|left;through|none|slight_right|right|right`\- 👍  
  - ❎  `turn:lanes=|right|left|` or `turn:lanes=none|right|left|through` or `turn:lanes=none|left|none`\- 👎  lanes that go in one direction should not cross with each other
- using `reverse` value
  - `reverse` (u-turn) have to be in the leftmost lane for right-hand traffic or on the rightmost lane for right-hand
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
## Question

Tag @planemad  @jothirnadh @abhisheksaikia @samely or @rub21 for questions.

cc. @mapbox/team-data

**Comment by calfarome** [comment]
##### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 06/20/2016 - 06/24/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 0  | 0 |
Tuesday 21st, June  | 97 | 49 |
Wednesday 22nd, June | 0| 0 |
Thursday 23rd, June | 65| 20 |
Friday 24th, June | 278 |  0|
**Total** | -- | **69** |

**Comment by RichRico** [comment]
##### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 06/27/2016 - 07/01/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 279  | 0 |
Tuesday 21st, June  | 292 | 0 |
Wednesday 22nd, June | 65 | 0 |
Thursday 23rd, June | 65| 0 |
Friday 24th, June | 300 |  0|
**Total** | -- | **0** |

**Comment by dannykath** [comment]
##### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 07/11/2016 - 07/14/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July |157  |-- |
Tuesday 12th, July  | 153 | -- |
Wednesday 13th, July | 153 | 153 |
Thursday 14th, July | 17 | -- |
**Total** | -- | **153** |

**Comment by luiswalter** [comment]
##### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 07/18/2016 - 07/22/2016

Date | N° detected error | Total Fixed 
---|---|---
Tuesday 19th, July  | 6 | 6 |
Friday 22th, July | 3 | 2 |
**Total** | -- | **8** |

**Comment by calfarome** [comment]
##### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 07/25/2016 - 07/27/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 25th, July |7  |0 |
Tuesday 26th, July  | 14 | 12 |
Wednesday 27th, July | 8 | 8 |
**Total** | -- | **20** |

**Comment by calfarome** [comment]
##### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 08/01/2016 - 08/05/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 01th, August | 13 | 9 |
Tuesday 02th, August  | 0 | 0 |
Wednesday 03th, August |2  | 0 |
Thursday 04th, August | 4| 0 |
Friday 05th, August | 11 | 0 |
**Total** | -- | **9** |

**Comment by calfarome** [comment]
##### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 08/08/2016 - 08/12/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 08th, August | 19 | 0 |
Tuesday 09th, August  | 26 | 21 |
Wednesday 10th, August |7  | 5 |
Thursday 11th, August | 6| 6 |
Friday 12th, August | 0 | 0 |
**Total** | -- | **32** |

**Comment by calfarome** [comment]
##### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 08/15/2016 - 08/19/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 15th, August | 44 | 16 |
Tuesday 16th, August  | 16 | 5 |
Wednesday 17th, August |8  | 5 |
Thursday 18th, August | 8| 2 |
Friday 19th, August | 38 | 29 |
**Total** | -- | **57** |

**Comment by jfburke3** [comment]
Please STOP running this script.  You are breaking completely correct turn:lanes values.

**Comment by jfburke3** [comment]
I recently found this section of road https://www.openstreetmap.org/way/438028863/history which I had added turn:lanes to a week or so ago, had been (for lack of a better word) vandalized by that to-fix script.

The value for turn:lanes I had initially set, and which I have gone back and re-established, was "none|none|none|none|none;slight_right". The script changed that to "||||slight_right" which turns the far-right lane from a through-and-exit lane into an exit-only lane.

There are other turn:lanes I've recently created that were similarly broken by to-fix.  The script appears to simply remove every occurrence of "none" even though that is a perfectly valid value according to the turn:lane wiki page.

**Comment by samely** [comment]
@jfburke3 
Thanks for fixing and reporting our edits. We are looking into it and will get back to you soon with our finding.

**Comment by jfburke3** [comment]
Please hurry, because I now have 200 miles of Interstate that I'd been adding lane guidance at exits that I have to go back through and re-check.

**Comment by calfarome** [comment]
@jfburke3 
Thanks for commenting about our edits.  
The to-fix script is just for detecting invalid `turn:lanes` issues that don't match about `lanes:*` number and have a strange value combination. So editing is completely manual using the [turnlanes-tagging plugin](https://github.com/JOSM/turnlanes-tagging). 

We add the `turn:lanes` according to the [wiki](http://wiki.openstreetmap.org/wiki/Key:turn) and the community [discussion](https://github.com/mapbox/mapping/issues/180#issuecomment-225323025). And you are right, values such as none, trough, left, right, slight_right and so on are completely valid, but not all combination of them like `none;slight_right` which **isn't** valid and instead of that you can use `transit:lanes`. Also the `none` value is used only in these cases:
>- There are **no turn indications** on this lane.
>- Used especially for **better readability** in case of many lanes

Thanks  again for your feedback as this helps us to improve our workflow.

**Comment by jfburke3** [comment]
Hi @calfarome !

I use the `none` value precisely for the two reasons you listed.  And that you listed them confuses me about why y'all are removing "none" from the turn:lanes value.

As for `none;slight_right`, I don't see what's invalid about it.  In fact, it is even specifically mentioned in the discussion thread you linked to as an example of a valid combination.  Just because a particular combination isn't described on the wiki, doesn't mean it's not correct to use.

--jack

**Comment by jfburke3** [comment]
To expound on why I think `none;slight_right` is a valid combination:

In the example image included in the wiki, `through;slight_right` is explicitly given as a valid combination.  A value of `through` should only be used when there is an explicit marking (either via paint-on-pavement or an overhead sign) that the lane is a through lane.  Why would `none;slight_right` not also be valid in situations, such as the way I linked to earlier, where there is no such marking?

**Comment by calfarome** [comment]
> I use the `none` value precisely for the two reasons you listed.  And that you listed them confuses me about why y'all are removing "none" from the turn:lanes value.

They wasn't removed intentionally, we use turnlanes-tagging plugin and the this deletes the `none` value per default. We will take into account your comment and won't delete those `none` values, neither the strange combination; however, we suggest you can replace those strange values based on the wiki, or even propose new combinations and add them to the wiki page.

If we can help you to restore your previous work, please, let us know.
Thanks again for your feedback.

Best regards, Calfarome.

**Comment by jfburke3** [comment]
@calfarome Thank you.  I've brought the issue up on the tagging and talk-us mailing lists, because it's really a hole in the tagging scheme (which some of the discussion participants agree with, and others don't).  The problem has been brought up a few times before, but the discussions seemed to just die out without a resolution.  Right now, people _seem_ to be siding with `through;slight_right` for the right lanes at exits.  If I can get enough of a consensus, then I'll propose that to be added to the wiki.  I don't really care if it's that, or `none;slight_right` or something completely new.

On a related note, I wanted to make your team aware that there is a lot of road construction taking place along I 75 just north and south Atlanta area right now, so satellite imagery should not be trusted to be current with respect to those areas.

**Comment by calfarome** [comment]
##### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 08/22/2016 - 08/26/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 22th, August | 19 | 13 |
Tuesday 23th, August  | 12 | 9 |
Wednesday 24th, August |35  | 33 |
Thursday 25th, August | 15| 1 |
Friday 26th, August | 4 | 0 |
**Total** | -- | **56** | 

##### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 08/29/2016 - 08/31/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 29th, August | 24 | 20 |
Tuesday 30th, August  | 2 | 0 |
Wednesday 31th, August |2 | 0 |
**Total** | -- | **20** | 

##### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 09/05/2016 - 09/09/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 05th, September | 14 | 1 |
Tuesday 06th, September  | 1 | 0 |
Wednesday 07th, September |0  | 0 |
Thursday 08th, September | 0| 0 |
Friday 09th, September | 3 | 0 |
**Total** | -- | **1** |

**Comment by ediyes** [comment]
##### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 09/12/2016 - 09/16/2016

Date | N° detected error | Total Fixed 
---|---|---|
Monday 12th, September|3|0|
Tuesday 13th, September| 2 |1|
Thursday 15th, September| 1 | 1 |
Friday 16th, September| 1 | 0 |
**Total** | -- | **2** |

**Comment by calfarome** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 09/19/2016 - 09/23/2016

Date | N° detected error | Total Fixed 
---|---|---|
Monday 19th, September|7|0|
Tuesday 20th, September| 8 |5|
Wednesday 21th, August |6  | 5 |
Thursday 22th, September| 0 | 0 |
Friday 23th, September| 3 | 2 |
**Total** | -- | **12** |

**Comment by calfarome** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 10/31/2016 - 11/04/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 31th, October|81|8|
Wednesday 2nd, November| 61| 15 |
Thursday 3rd, November| 43 |13|
Friday 4th, November| 22| 3|
**Total** | -- | **39** |

**Comment by calfarome** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 11/07/2016 - 11/11/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 7th, November|10|0|
Tuesday 8th, November| 17|7|
Wednesday 9th, November| 12| 0 |
Thursday 10th, November| 8 |2|
Friday 11th, November| 2| 0|
**Total** | -- | **9** |

**Comment by calfarome** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 11/14/2016 - 11/18/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 7th, November|14|6|
**Total** | -- | **6** |

**Comment by calfarome** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 12/05/2016 - 12/09/2016

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
|
| Tuesday 6th, November | 271 | 8 |
| Wednesday 7th, November | 234 | 7|
| Thursday 8th, December | 214 | 4|
| **Total** | -- | **19** |

**Comment by calfarome** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) issues from 12/12/2016 - 12/16/2016

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 12th, December | 177 | 0 |
| Tuesday 13th, December | 179 | 38 |
| Wednesday 14th, December | 25 | 3 |
| Thursday 15th, December | 3 | 0 |
| Friday 16th, December | 6 | 1 |
| **Total** | -- | **42** |

**Comment by calfarome** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes)  issues from 09/01/2017 - 13/01/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 09th, January | 3| 0 |
| Tuesday 10th, January| 0 | 0|
| Wednesday 11th, January| 2 | 0 |
| Thursday 12th, January| 7 | 2 |
| Friday 13th, January| 3 | 3 |
| **Total** | **15** | **5** |

**Comment by calfarome** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes)  issues from 16/01/2017 - 20/01/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 16th, January | 2|0  |
| Tuesday 17th, January|21  | 17 |
| Wednesday 18th, January| 0 |0  |
| Thursday 19th, January| 18 | 7 |
| Friday 20th, January| 10 |7  |
| **Total** | -- | **31** |

**Comment by Yurasi** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes)  issues from 23/01/2017 - 26/01/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 23th, January | 19|12  |
| Tuesday 24th, January|--  | -- |
| Wednesday 25th, January| 07 |03  |
| Thursday 26th, January| 01 | 00 |
| **Total** | **27** | **15** |

**Comment by Yurasi** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) Progress  issues from 30/01/2017 - 02/02/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
| Monday 30th, January | 26|26 |
| Tuesday 31th, February| -- |--|
| Wednesday 01st, February| 07 |03|
| Thursday 02nd, February| 02 |01|
| **Total** | **35** | **30** |

**Comment by Yurasi** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) Progress  issues from 02/06/2017 - 02/07/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 6th February|05|03
Tuesday 7th February|07|05
Wednesday 8th February :point_left:(No detected)|0|0
Thursday 9th February :point_left:(No detected)|0|0
Friday 10th February :point_left:(No detected)|0|0
**Total** | **12** | **08** |

**Comment by Yurasi** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) Progress  issues from 13/02/2017 - 16/02/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 13th February|11|11
Tuesday 14th February|02|02
Wednesday 15th February :point_left:(No detected)|0|0
Thursday 16th February |14|09
Friday 17th February |11|11
**Total** | **38** | **33** |

**Comment by Yurasi** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) Progress  issues from 20/02/2017 - 24/02/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 20th February |05|04
Tuesday 21th February |18|17
Wednesday 22th February |01|01
Thursday 23th February :point_left:(No detected)|00|00
Friday 24th February |02|02
**Total** | **26** | **24** |

**Comment by Yurasi** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) Progress issues from 02/27/2017 - 03/03/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 27th February|11|05
Tuesday 28th February|06|06
Wednesday 1st March |02|02
Thursday 2nd March |02|02
Friday 3rd March |00|00
**Total** | **21** | **15** |

**Comment by Yurasi** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) Progress issues from 03/06/2017 - 03/10/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 06th March|10|10
Tuesday 07th March|01|01
Wednesday 08th March |06|06
Thursday 09th March |04|01
Friday 10th March |04|04
**Total** | **25** | **22** |

**Comment by Yurasi** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) Progress issues from 03/13/2017 and 03/17/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 13th March|18|18
Friday 17th March |02|02
**Total** | **20** | **20** |

**Comment by Yurasi** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) Progress issues on 03/20/2017 

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Tuesday 21th March |05|05
**Total** | **05** | **05** |

**Comment by Yurasi** [comment]
#### [Invalid turnlanes](http://osmlab.github.io/to-fix/#/task/invalidturnlanes) Progress issues from 03/29/2017 to 03/30/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Wednesday 29th March |00|00
Thursday 30th March |01|01
**Total** | **01** | **01** |
