### ISSUE TITLE
To-fix: Highway intersects water

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#195]
### Objective

Fix major and minor highways overlapping water features, by adding bridge, tunnel, layer or ford.
### Tasks

**The tasks below are updating everyday from Monday to Friday with the latest errors in OpenStreetMap**

To-Fix issue:
-  Major: http://osmlab.github.io/to-fix/#/task/highwayintersectswatermajor
-  Minor: http://osmlab.github.io/to-fix/#/task/highwayriverbank
#### Changeset comment

```
Fixing overlapping highway and water features, by adding bridge, tunnel, layer or ford using #to-fix https://github.com/mapbox/mapping/issues/195
```
### Tools for edition
- If using iD editor, work with [To-Fix web](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)
- If using JOSM, work with [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin)
- Use the [Knife-tool](https://github.com/mapbox/auto-tools) to split ways.
### Instructions
- Split the way at the starting and ending point of the tunnel or bridge.
- If bridge add `bridge=yes` and `layer=1` tags. Otherwise, `tunnel=culvert` and `layer=-1`
- If editing in an actively mapped area, add a note instead of making a fix.
- If satellite imagery isn't clear click on `not an error` of to-fix
## Common issues

![image](https://cloud.githubusercontent.com/assets/10425629/16160564/8dca2352-348e-11e6-8e63-81198d680083.png)
_Add `bridge=yes` and `layer=1` tags_

![image](https://cloud.githubusercontent.com/assets/10425629/16160787/8ac1c57e-348f-11e6-9909-ff2598af5516.png)
_Add `tunnel=culvert` and `layer=-1` tags_

![image](https://cloud.githubusercontent.com/assets/10425629/16160637/e75ffe5a-348e-11e6-9f1d-46b506b49ace.png)
_Move points so bridge cover completely the river_

![image](https://cloud.githubusercontent.com/assets/10425629/16160823/c9c22282-348f-11e6-8364-05082850bffa.png)
_Reshape the lake_
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
## Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data

**Comment by calfarome** [comment]
##### [Highway intersects water major](http://osmlab.github.io/to-fix/#/task/islandsmajorhighways) issues from 06/20/2016 - 06/24/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 20th, June | 105870  | 2129 |
Tuesday 21st, June  | 102579 | 0 |
Wednesday 22nd, June | 102579| 0 |
Thursday 23rd, June | 102293| 0 |
Friday 24th, June | 105714 |  0|
**Total** | -- | **2129** |

**Comment by ediyes** [comment]
##### [Highway intersects water major](http://osmlab.github.io/to-fix/#/task/highwayintersectswatermajor) issues from  09/12/2016 - 09/16/2016

Date | N° detected error | Total Fixed 
---|---|---|
Monday 12th, September|98793|48|
Tuesday 13th, September| 98,679 |50|
Thursday 15th, September| 98,582 | 44 |
Friday 16th, September| 98,482 | 52 |
**Total** | -- | **194** |
