### ISSUE TITLE
To-fix: Missing layer bridges

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#201]
### Objective

Add missing **layer tag** to bridges in major or minor highways.
### Tasks

**The below tasks are updating everyday from Monday to Friday with the latest errors in OpenStreetMap**

To-Fix issue:
-  Major: http://osmlab.github.io/to-fix/#/task/missinglayerbridgesmajor
-  Minor: http://osmlab.github.io/to-fix/#/task/missinglayerbridgesminor
#### Changeset comment

```
Adding missing layer tag to bridges using #to-fix  https://github.com/mapbox/mapping/issues/201
```
### Coverage

All countries in this list: https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt
## Tools for edition
- If using iD editor, work with [To-Fix web](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)
- If using JOSM, work with [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin)
## Instructions
- Check satellite imagery/Mapillary to make sure a bridge is visible:
  - If a bridge is visible add `layer=1` tag. For complex intersections add appropriate `layer=` value based on the overlap order
  - If bridge clearly does not exist and there is no crossing ways, remove the `bridge` tag
- If editing in an actively mapped area, add a note instead of making a fix.
- If satellite imagery isn't clear click on `not an error` of to-fix
## Common issues

![image](https://cloud.githubusercontent.com/assets/10425629/16427723/3bf762b6-3d34-11e6-90dc-9f64c7a551d9.png)

![image](https://cloud.githubusercontent.com/assets/10425629/16427764/78b34e2c-3d34-11e6-9ebd-0aa9d35ffc2c.png)

![image](https://cloud.githubusercontent.com/assets/10425629/16427843/ed02b1fa-3d34-11e6-9cff-4aa27e35683a.png)
_Add `layer=1` tag_
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
## Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data

**Comment by planemad** [comment]
@samely the way might also have an incorrect `bridge` tag. Please check updated instructions.

**Comment by dannykath** [comment]
##### [Missing layer bridges minor](http://osmlab.github.io/to-fix/#/task/missinglayerbridgesminor) issues from 07/11/2016 - 07/14/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July | 93026 |5220 |
Tuesday 12th, July  | 104140 | 5701 |
**Total** | -- | **10921** |

**Comment by dannykath** [comment]
#### This is the Andy's comment:
![advice](https://cloud.githubusercontent.com/assets/8483644/16918177/289fda72-4cca-11e6-80d0-2121b8960000.png)

@mapbox/team-data

**Comment by tankaru** [comment]
Hello Mapbox Data Team mappers,

Last week I had a discussion with one of your team members here.
https://www.openstreetmap.org/changeset/40603672

I want to ask you about your tagging standard.

When a waterway has "layer=-1" and a crossing bridge has no layer tag, do you add "layer=*" to the bridge? And what about its value?
I think "layer=*" is not required in this case, because the waterway already has layer tag. Even if "layer=*" is required, its value should be "layer=0".
(Note: "layer=-1" is valid and does not mean that object is underground. See http://wiki.openstreetmap.org/wiki/Key:layer)


And I have a favor to ask. If you don't have any rational basis, please do not modify existing tags.
I think existing tag has priority.

Thanks.

**Comment by bhousel** [comment]
Waterways do not need layer tags.  Bridges, tunnels, etc do not need layer tags except in cases where multiple bridges or multiple tunnels cross over one another.

I hope we are not adding unnecessary `layer` tags, because these tags do nothing other than suppress valid warnings and make it more difficult for downstream consumers to use OSM.

**Comment by bhousel** [comment]
Btw it is pretty clear from the Japan GSI ortho imagery layer that these features are indeed bridges and not culverts.  (A culvert is a pipe/tube that the water flows through).

<img width="561" alt="screenshot 2016-07-20 12 28 06" src="https://cloud.githubusercontent.com/assets/38784/16994474/7ed65770-4e75-11e6-9e42-9eca36cbae7d.png">

**Comment by Andygol** [comment]
Hey @tankaru 
there is quote from http://wiki.openstreetmap.org/wiki/Key:layer#Guidelines concerning waterways

>Rivers and streams should **not** be tagged with layer **-1** along long sections of their length, crossings should be tagged like other crossings with bridges, tunnels and layer. Waterways that are covered may be tagged with `covered=yes` and are generally rendered as if they flow underneath built features. Where a highway is at the same level as a waterway, you can add `ford=*`.

and http://wiki.openstreetmap.org/wiki/Key:layer#Things_to_avoid
>Rivers and streams should not be tagged with layer -1 along their entire length or long sections as it makes harder to detect missing bridges for roads passing over waterways.

@bhousel 
>Although some map rendering and quality assurance services assume that bridges and tunnels are at layers +1 and -1 respectively, it is better to **explicitly** state the layer for all bridges and tunnels.

**Comment by bhousel** [comment]
> @bhousel
> 
> Although some map rendering and quality assurance services assume that bridges and tunnels are at layers +1 and -1 respectively, it is better to explicitly state the layer for all bridges and tunnels.

We have never added explicit `layer` tags in iD.

**Comment by Andygol** [comment]
Validator in JOSM notify about intersection of features when anyone of them missed `layer=*` tag 

<img width="729" alt="java openstreetmap editor 2016-07-20 20-36-22" src="https://cloud.githubusercontent.com/assets/369696/16996473/176c3f7e-4eba-11e6-9be2-878e3c7c941e.png">

**Comment by bhousel** [comment]
> Validator in JOSM notify about intersection of features when anyone of them missed layer=* tag

That's so weird.. Neither Keepright nor Osmose complain as long as the bridge/tunnel tag is there.

**Comment by tankaru** [comment]
Thanks all for your comments.

>Rivers and streams should not be tagged with layer -1 along their entire length or long sections

Yes. In Japan many rivers are tagged with "layer=-1" to entire way, but it's not a good manner. Layer tag should be added to limited way. I think it's not invalid but it's not good way. This is another problem.

>it is pretty clear from the Japan GSI ortho imagery layer that these features are indeed bridges and not culverts

I agree. I just wanted to ask him/her why he/she tagged as culvert.

**Comment by piligab** [comment]
#### [Missing layer bridges minor](http://osmlab.github.io/to-fix/#/task/missinglayerbridgesminor) Progress issues from 08/29/2016 - 08/31/2016
Date | N° detected error | Total Fixed 
---|:---:|:---:
Tuesday 30th, August | 92443 |253 |
**Total** | -- | **253** |

**Comment by piligab** [comment]
#### [Missing layer bridges minor](http://osmlab.github.io/to-fix/#/task/missinglayerbridgesminor)  Progress  issues from 09/05/2016 - 09/09/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 05th, September | 92303  |231  |
Tuesday 06th, September |92078  |218  |
Thursday 08th, September| 90797|431 |
Friday 09th, September |90318 |44 |
**Total** | -- | **924** |

**Comment by piligab** [comment]
#### [Missing layer bridges minor](http://osmlab.github.io/to-fix/#/task/missinglayerbridgesminor) Progress  issues from 09/12/2016 - 09/16/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 12th, September | 90,407  | 246 |
Tuesday 13th, September | 90,204 | 335|
Wednesday 14th, September | 89,880 | 319 |
Thursday 15th, September| 89,589 |336 |
Friday 16th, September | 89,271 | 358 |
**Total** | -- | **1,594** |

**Comment by 1ec5** [comment]
The JOSM warning is quite a pedantic one. As https://github.com/mapbox/mapping/issues/201#issuecomment-234028419 points out, JOSM is the outlier here. Is there any evidence that data _consumers_ are encountering problems caused by ways such as [this bridge](http://www.openstreetmap.org/way/218701654) lacking `layer` tags, or is this just mapping for the validator? 😕

**Comment by piligab** [comment]
#### [Missing layer bridges minor](http://osmlab.github.io/to-fix/#/task/missinglayerbridgesminor) Progress  issues from 09/19/2016 - 09/23/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 12th, September | 88,996  | 346 |
Tuesday 13th, September | 88,665 | 351|
Wednesday 14th, September | 88,365 | 376 |
Thursday 15th, September| 87,952 |393 |
Friday 16th, September | 100,019 | 324 |
**Total** | -- | **1,790** |

**Comment by dannykath** [comment]
#### [Missing layer bridges major](http://osmlab.github.io/to-fix/#/task/missinglayerbridgesmajor) Progress  issues from 09/19/2016 - 09/23/2016

Date | N° detected error | Total Fixed 
---|---|---|
Tuesday 20th, September | 65,238 | 89 |
Wednesday 21th, September | 65,142 | 102  |
Thursday 22th, September | 65,062 | 124 |
Friday 23th, September  | 81,227 | 80  |
**Total** | -- | **395** |

**Comment by piligab** [comment]
#### [Missing layer bridges minor](http://osmlab.github.io/to-fix/#/task/missinglayerbridgesminor) Progress  issues from 10/24/2016 - 10/28/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Tuesday 25th, October| 98,774|331|
Wednesday 26th, October| 98,395| 342|
Thursday 27th, October| 98,395 |360|
Friday 28th, October| 97,704| 240|
**Total** | -- | **1,273** |

**Comment by dannykath** [comment]
#### [Missing layer bridges major](http://osmlab.github.io/to-fix/#/task/missinglayerbridgesmajor) Progress  issues from 10/31/2016 - 11/02/2016
Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 31th, October|80923	|103|
Wednesday 02nd, November|80853|133|
**Total** | -- | **236** |

**Comment by piligab** [comment]
#### [Missing layer bridges minor](http://osmlab.github.io/to-fix/#/task/missinglayerbridgesminor) Progress  issues from 10/31/2016 - 11/04/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 31th, October|--|251|
Wednesday 02nd, November|80,854|259|
Thursday 03rd, November|97,259|330|
Friday 04th, November|80,720|241|
**Total** | -- | **1,081** |

**Comment by piligab** [comment]
#### [Missing layer bridges minor](http://osmlab.github.io/to-fix/#/task/missinglayerbridgesminor) Progress  issues from 11/14/2016 - 11/18/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 14thth, November|96545|304|
Tuesday 15th, November|96320|318|
Friday 18th, November|96047	|285|
**Total** | -- | **907** |

**Comment by piligab** [comment]
#### [Missing layer bridges minor](http://osmlab.github.io/to-fix/#/task/missinglayerbridgesminor) Progress  issues from 11/14/2016 - 11/18/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 14thth, November|95861|359|
Tuesday 15th, November|95176|364|
**Total** | -- | **723** |
