### ISSUE TITLE
To-fix: Mixed layers highways

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#202]
### Objective

Remove incorrect `layer=*` tag from major or minor highways.
### Tasks

**The below tasks are updating everyday from Monday to Friday with the latest errors in OpenStreetMap**

To-Fix issue:
-  Major: http://osmlab.github.io/to-fix/#/task/mixedlayersmajorhighways
-  Minor: http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways
#### Changeset comment

```
Fixing invalid layer tag in intersected highways using #to-fix https://github.com/mapbox/mapping/issues/202
```
### Coverage

All countries in this list: https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt
### Tools
- If using iD editor, work with [To-Fix web](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)
- If using JOSM, work with [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin)
### Instructions
- If the highway has `layer=*` without `bridge` or `tunnel`, inspect imagery to make one of the following fix:
  - Remove `layer` if the road is on the ground surface without any crossing with any other way
  - Add missing `bridge=yes` or `tunnel=yes` if  visible on the imagery/Mapillary
- If editing in an actively mapped area, add a note instead of making a fix.
- If satellite imagery isn't clear click on `not an error` of to-fix
### Common issues

![image](https://cloud.githubusercontent.com/assets/10425629/16428186/5c9a2d58-3d36-11e6-8f41-ff818d49b09d.png)
_Delete `layer=-1`_

![image](https://cloud.githubusercontent.com/assets/10425629/16428220/86090d8a-3d36-11e6-9022-0f90312f2738.png)
_Delete `layer=1`_
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
### Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data

**Comment by planemad** [comment]
@samely The way might also be missing a `bridge` or `tunnel` tag, please check updated instructions.

**Comment by dannykath** [comment]
##### [Mixed layer minor highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 07/11/2016 - 07/14/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July | 456 |271 |
Tuesday 12th, July  | 82 |56  |
Wednesday 13th, July | 82 | 1 |
Thursday 14th, July | 28 | 5 |
**Total** | -- | **333** | 

##### [Mixed Layer major highways](http://osmlab.github.io/to-fix/#/task/mixedlayersmajorhighways) issues from 07/11/2016 - 07/14/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July | 1563 |773 |
Tuesday 12th, July  | 236 |  --|
Wednesday 13th, July | 236 | -- |
Thursday 14th, July | 102 |--  |
**Total** | -- | **773** |

**Comment by luiswalter** [comment]
##### [Mixed layer minor highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 07/18/2016 - 07/22/2016
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 19th, July  | 5 | 5  |
Thursday 21th, July | 3 | 3 |
**Total** | -- | **8** | 

##### [Mixed Layer major highways](http://osmlab.github.io/to-fix/#/task/mixedlayersmajorhighways) issues from 07/11/2016 - 07/14/2016
Date | N° detected error | Total Fixed 
---|---|---
Friday 22th, July | 42 | 27 |
**Total** | -- | **27** |

**Comment by karitotp** [comment]
##### [Mixed layer minor highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 07/25/2016 - 07/29/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 25th, July  | 2 | 2  |
Tuesday 26th, July | 4 | 2 |
**Total** | -- | **4** |

**Comment by karitotp** [comment]
##### [Mixed layer minor highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 08/01/2016 - 08/05/2016

Date | N° detected error | Total Fixed 
---|---|---
Thursday 04th, August | 1 | 1 |
**Total** | -- | **1** |

**Comment by karitotp** [comment]
##### [Mixed layer minor highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 08/15/2016 - 08/19/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 15th, August | 1 | 0 |
Tuesday 16th, August  | 1 | 1 |
Friday 19th, August | 1 | 1 |
**Total** | -- | **2** |

**Comment by karitotp** [comment]
##### [Mixed layer minor highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 08/22/2016 - 08/26/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 22nd, August | 2 | 2 |
Tuesday 23rd, August  | 1 | 1 |
Friday 26th, August | 3 | 2 |
**Total** | -- | **5** |

**Comment by karitotp** [comment]
##### [Mixed layer minor highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 08/29/2016 - 08/31/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 29th, August |2 | 1 |
Tuesday 30th, August  | 2 | 1 |
Wednesday 31th, August | 3 | 2 |
**Total** | -- | **4** |

**Comment by karitotp** [comment]
##### [Mixed layer minor highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 09/05/2016 - 09/09/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 05th, September |2 | 2 |
Friday 09th, September | 2 | 2 |
**Total** | -- | **4** |

**Comment by luiswalter** [comment]
##### [Mixed layer major highways](https://osmlab.github.io/to-fix/#/task/mixedlayersmajorhighways) issues from 09/05/2016 - 09/09/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 05th, September |14 | 6 |  
Wednesday 07th, September | 3 | 2 |
Friday 09th, September | 4 | 2 |			
**Total** | -- | **10** |

**Comment by karitotp** [comment]
##### [Mixed layer minor highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 09/12/2016 - 09/16/2016
Date | N° detected error | Total Fixed 
---|---|---
Wednesday 14th, September |1 | 1 |
**Total** | -- | **1** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 09/19/2016 - 09/23/2016
Date | N° detected error | Total Fixed 
---|---|---
Friday 23rd, September |153| 101| 					
**Total** | -- | **101** |

**Comment by karitotp** [comment]
##### [Kinks minor  highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 10/24/2016 - 10/28/2016
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 25th, October |157|57|
Thursday 27th, October| 88| 80|
Friday 28th, October |11| 9| 					
**Total** | -- | **146** |

**Comment by karitotp** [comment]
##### [Mixed layer minor  highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 10/31/2016 - 11/04/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 31st, October |4|3|
Wednesday 2nd, November|5|5|
Friday 4th, November |2|2| 					
**Total** | -- | **10** |

**Comment by karitotp** [comment]
##### [Mixed layer minor  highways](http://osmlab.github.io/to-fix/#/task/mixedlayersminorhighways) issues from 11/07/2016 - 11/11/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 07th, November |6|6|
Tuesday 08th, November|1|1|				
**Total** | -- | **7** |

**Comment by karitotp** [comment]
##### [Mixed layer minor  highways](https://osmlab.github.io/to-fix/#/task/mixedlayersminorhighwayswdtvm) issues from 11/21/2016 - 11/25/2016
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 22nd, November |48|31|				
**Total** | -- | **31** |

**Comment by karitotp** [comment]
##### [Mixed layer minor  highways](https://osmlab.github.io/to-fix/#/task/mixedlayersminorhighwayswdtvm) issues from 11/28/2016 - 12/02/2016
Date | N° detected error | Total Fixed 
---|---|---
Wednesday 30th, November |4|4|
Thursday 01st, December |2|2|		
**Total** | -- | **6** |

**Comment by karitotp** [comment]
##### [Mixed layer minor  highways](https://osmlab.github.io/to-fix/#/task/mixedlayersminorhighwayswdtvm) issues from 12/05/2016 - 12/09/2016
Date | N° detected error | Total Fixed 
---|---|---
Thursday 08th, December |4|4|
**Total** | -- | **4** |

**Comment by karitotp** [comment]
##### [Mixed layer minor  highways](https://osmlab.github.io/to-fix/#/task/mixedlayersminorhighwayswdtvm) issues from 01/02/2017 - 01/06/2017
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 03rd, January |10|5|
Thursday 05th, January |2|1|
**Total** | -- | **6** |

**Comment by karitotp** [comment]
##### [Mixed layer minor  highways](https://osmlab.github.io/to-fix/#/task/mixedlayersminorhighwayswdtvm) issues from 01/09/2017 - 01/13/2017
Date | N° detected error | Total Fixed 
---|---|---
Monday 09th, January |2|2 
Wednesday 11th , January |1|1 
**Total** | -- | **3** |

**Comment by dannykath** [comment]
##### [Mixed layer major  highways](https://osmlab.github.io/to-fix/#/task/mixedlayersmajorhighwaysqx) issues from 01/09/2017 - 01/13/2017
Date | N° detected error | Total Fixed 
---|---|---
Monday 09th, January |7|5 
Wednesday 11th , January |3|2
Friday 13th , January |16|11 
**Total** |  | **18** |

**Comment by dannykath** [comment]
##### [Mixed layer major  highways](https://osmlab.github.io/to-fix/#/task/mixedlayersmajorhighwaysqx) Progress  issues from 01/16/2017 - 01/20/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 16th January|6|4|
Tuesday 17th January|4|4|
Thursday 19th January|12|6|
Friday 20th January|8|6|
**Total** | -- | **20** |

**Comment by karitotp** [comment]
##### [Mixed layer major  highways](https://osmlab.github.io/to-fix/#/stats/mixedlayersmajorhighwaysqx) Progress  issues from 01/23/2017 - 01/27/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 23rd January|10|6|
Wednesday 25th January|5|4
Thursday 26th January|6|6|
Friday 27th January|7|6|
**Total** | -- | **22** |

**Comment by piligab** [comment]
##### [Mixed layer minor highways](https://osmlab.github.io/to-fix/#/task/mixedlayersminorhighwayswdtvm) Progress issues from 01/23/2017 - 01/27/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 23rd, January|1|0|
Wednesday 25th, January|2|0|
**Total** | -- | **0** |

**Comment by piligab** [comment]
##### [Mixed layer minor highways](https://osmlab.github.io/to-fix/#/task/mixedlayersminorhighwayswdtvm) Progress  issues from 30/01/2017 - 03/02/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
| Monday 30th, January | 4|2 |
| Tuesday 31th, February| 4 |1|
| Wednesday 01st, February| 1 |0|
| Thursday 02nd, February| 2 |1|
| Friday 03rd, February| 4 |3|
| **Total** | -- | **7** |

**Comment by piligab** [comment]
#### PROGRESS ISSUES FROM 02/06/2017 - 02/10/2017


#### - [Mixed layer minor highways](https://osmlab.github.io/to-fix/#/task/mixedlayersminorhighwayswdtvm) 

Date | N° detected error | Total Fixed 
---|:---:|:---:
| Tuesday 7th, February| 4 |4|
| **Total** | -- | **4** |

**Comment by karitotp** [comment]
#### PROGRESS ISSUES FROM 02/13/2017 - 02/17/2017

#### - [Mixed layer major highways](https://osmlab.github.io/to-fix/#/stats/mixedlayersmajorhighwaysqx) 

Date | N° detected error | Total Fixed 
---|:---:|:---:
|Monday 13th, February| 107|25|
| Thursday 16th, February| 5 |3|
Friday 17th, February|12|4
| **Total** | -- | **32** |

**Comment by karitotp** [comment]
#### PROGRESS ISSUES FROM 02/20/2017 - 02/24/2017

#### - [Mixed layer major highways](https://osmlab.github.io/to-fix/#/stats/mixedlayersmajorhighwaysqx) 

Date | N° detected error | Total Fixed 
---|:---:|:---:
|Monday 20th, February| 6|3|
|Tuesday 21st, February| 9|2|
|Wednesday 22nd, February|16|4|
|Friday 24th, February|10|5|
| **Total** | -- | **14** |

**Comment by piligab** [comment]
#### PROGRESS ISSUES FROM 02/27/2017 - 03/03/2017

#### - [Mixed layer minor highways](https://osmlab.github.io/to-fix/#/task/mixedlayersminorhighwayswdtvm) 
Date | N° detected error | Total Fixed 
---|:---:|:---:
|Monday 27th, February|3|3|
| **Total** | -- | **3** |

**Comment by karitotp** [comment]
#### PROGRESS ISSUES FROM 03/06/2017 - 03/10/2017

#### - [Mixed layer major highways](https://osmlab.github.io/to-fix/#/stats/mixedlayersmajorhighwaysqx) 

Date | N° detected error | Total Fixed 
---|:---:|:---:
|Monday 06th, March| 8|2|
|Tuesday 07th, March| 2|2|
|Thursday 09th, March|9|6|
|Friday 10th, March|6|2
| **Total** | -- | **12** |

**Comment by piligab** [comment]
#### PROGRESS ISSUES FROM 03/13/2017 - 03/17/2017

#### - [Mixed layer minor highways](https://osmlab.github.io/tofix/#/task/mixedlayersminorhighwayswdtvm) 

Date | N° detected error | Total Fixed 
---|:---:|:---:
|Wednesday 15th, March|2|2|
| **Total** | -- | **2** |

**Comment by karitotp** [comment]
#### PROGRESS ISSUES FROM 03/20/2017 - 03/24/2017

#### - [Mixed layer major highways](https://osmlab.github.io/to-fix/#/stats/mixedlayersmajorhighwaysqx) 

Date | N° detected error | Total Fixed 
---|:---:|:---:
|Monday 20th, March| 50|23|
|Wednesday 22nd, March| 3|3|
|Thursday 23rd, March|3|1|
| **Total** | -- | **27** |

**Comment by piligab** [comment]
#### PROGRESS ISSUES FROM 03/27/2017 - 03/31/2017

#### - [Mixed layer minor highways](https://osmlab.github.io/to-fix/#/task/mixedlayersminorhighwayswdtvm) 

Date | N° detected error | Total Fixed 
---|:---:|:---:
|Wednesday 29th, March| 14|8|
|Thursday 30th, March| 4|1|
| **Total** | -- | **9** |

**Comment by karitotp** [comment]
#### PROGRESS ISSUES FROM 05/08/2017 - 05/12/2017

#### - [Mixed layer major highways](https://osmlab.github.io/to-fix/#/stats/mixedlayersmajorhighwaysqx) 

Date | N° detected error | Total Fixed 
---|:---:|:---:
|Monday 08th, May| 266|124|
Tuesday 09th, May|9|8|
|Wednesday 10th, May| 1|1|
|Thursday 11th, May|831|192|
|Friday 12th, May||45
| **Total** | -- | **370** |
