### ISSUE TITLE
To-fix: Self intersecting highways

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#203]
### Objective

Split or disengage major o minor self-intersect way.
### Tasks

**The below tasks are updating everyday from Monday to Friday with the latest errors in OpenStreetMap**

To-Fix issue:
-  Major: http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways
-  Minor: http://osmlab.github.io/to-fix/#/task/selfintersectingminorhighways
#### Changeset comment

```
Splitting self-intersecting highways using #to-fix https://github.com/mapbox/mapping/issues/203
```
### Coverage

All countries in this list: https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt
### Tools
- If using iD editor, work with [To-Fix web](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)
- If using JOSM, work with [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin)
- Use the [Knife-tool](https://github.com/mapbox/auto-tools) to split ways.
- Use `unglue` tool (Shortcut: `G`)
### Instructions
- If intersecting with the starting or ending point, split the way  according to satellite imagery.
- If intersecting with by a middle node, disengage the last one and reshape the way.
- If editing in an actively mapped area, add a note instead of making a fix.
- If satellite imagery isn't clear click on `not an error` of to-fix
### Common issues

![image](https://cloud.githubusercontent.com/assets/10425629/16428868/818df402-3d39-11e6-988f-4571b0ed32ee.png)
_Split the way according to satellite imagery_

![image](https://cloud.githubusercontent.com/assets/10425629/16428895/a794f736-3d39-11e6-9924-c567915ebf9e.png)
_Disengage the intersecting node and reshape the way_
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
### Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data

**Comment by dannykath** [comment]
##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingminorhighways) issues from 07/11/2016 - 07/14/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July | 2076 |1868  |
**Total** | -- | **1868** |

**Comment by luiswalter** [comment]
##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingminorhighways) issues from 07/18/2016 - 07/22/2016

Date | N° detected error | Total Fixed 
---|---|---
Tuesday 19th, July | 65 | 45 |
Friday 22th, July | 6 | 4 |
**Total** | -- | **49** | 


##### [Self intersecting major highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 07/18/2016 - 07/22/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 18th, July |3  |3 |
Tuesday 19th, July | 3 | 3  |
Friday 22th, July | 1 | 0 |
**Total** | -- | **6** |

**Comment by calfarome** [comment]
##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 07/25/2016 - 07/27/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 25th, July |5  |0 |
Tuesday 26th, July | 8 | 3 |
Wednesday 27th, July | 10 |8  |
**Total** | -- | **22** |

**Comment by ediyes** [comment]
##### [Self intersecting mayor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 08/01/2016 - 08/05/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 1st, August |3  | 0 |
Tuesday 2nd, August | 4 | 2 |
Wednesday 3rd, August | 168 | 0  |
Thursday 4th, August | 1 | 1 |
Friday 5th, August | 3 | 2 |
**Total** | -- | **5** |

**Comment by ediyes** [comment]
##### [Self intersecting mayor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 08/01/2016 - 08/05/2016

Date | N° detected error | Total Fixed 
---|---|---|
Monday 1st, August |3  | 0 |
Tuesday 2nd, August | 4 | 2 |
Wednesday 3rd, August | 168 | 0  :point_left:  There was a [problem](http://forum.openstreetmap.org/viewtopic.php?id=55220)  |
Thursday 4th, August | 1 | 1 |
Friday 5th, August | 3 | 2 |
**Total** | -- | **5** |

**Comment by ediyes** [comment]
##### [Self intersecting mayor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 08/08/2016 - 08/12/2016

Date | N° detected error | Total Fixed 
---|---|---|
Monday 1st, August |3  | 0 |
Tuesday 2nd, August | 4 | 2 |
Wednesday 3rd, August | 168 | 0  :point_left:  There was a [problem](http://forum.openstreetmap.org/viewtopic.php?id=55220)  |
Thursday 4th, August | 1 | 1 |
Friday 5th, August | 3 | 2 |
**Total** | -- | **5** |

**Comment by ediyes** [comment]
##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 08/15/2016 - 08/19/2016

Date | N° detected error | Total Fixed 
---|---|---|
Monday 15th, August |4| 3|
Tuesday 16th, August | 1 | 0 |
Wednesday 17th, August | 1 | 1 |
Thursday 18th, August | 2 | 0 |
Friday 9th, August | 1 | 1 |
**Total** | -- | **15** |

**Comment by ediyes** [comment]
##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 08/22/2016 - 08/26/2016

Date | N° detected error | Total Fixed 
---|---|---|
Monday 22nd, August |0| 0|
Tuesday 23rd, August | 1 | 1 |
Wednesday 24th, August | 3 | 2 |
Thursday 25th, August | 1 | 1 |
Friday 26th, August | 0 | 0 |
**Total** | -- | **4** |

**Comment by ediyes** [comment]
##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 08/29/2016 - 08/31/2016

Date | N° detected error | Total Fixed 
---|---|---|
Monday 29th, August |1| 1|
Tuesday 30th, August | 1 | 1|
Wednesday 31th, August | 1 | 1 |
**Total** | -- | **3** |

**Comment by ediyes** [comment]
##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 09/05/2016 - 09/09/2016

Date | N° detected error | Total Fixed 
---|---|---|
Monday 5th, September |8|7|
Tuesday 6th, September | 1 |1|
Wednesday 7th, September | 1 | 1 |
Thursday 8th, September | 4 | 1 |
Friday 9th, September | - |- |
**Total** | -- | **10** |

**Comment by ediyes** [comment]
##### [Self intersecting major highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 09/12/2016 - 09/16/2016

Date | N° detected error | Total Fixed 
---|---|---|
Monday 12th, September|3|1|
Tuesday 13th, September| 1 |0|
Thursday 15th, September| 5 | 5 |
Friday 16th, September| 1 | 1 |
**Total** | -- | **7** | 

##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from  09/12/2016 - 09/16/2016
Date | N° detected error | Total Fixed 
---|---|---|
Monday 12th, September|16|14|
Tuesday 13th, September| 2 | 2|
Thursday 15th, September| 13 | 8 |
Friday 16th, September| 1 |0 |
**Total** | -- | **24** |

**Comment by ediyes** [comment]
##### [Self intersecting major highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 09/19/2016 - 09/23/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 19th, September|6|3|
Tuesday 20th, September| 0|0|
Wednesday 21st, September| 3| 3 |
Thursday 22nd, September| 1 |1|
Friday 23rd, September| 77| 64|
**Total** | -- | **71** |

**Comment by tomass** [comment]
Why the FIRST case in your "Common issues" chapter example is a problem? Because geometry is perfectly OK there. As far as I know all open routing algorithms deal with it without a problem because during routing graph creation they split all ways on intersections anyway.

**Comment by ediyes** [comment]
##### [Self intersecting major highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 10/24/2016 - 10/28/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 24th, October|37|12|
Tuesday 25th, October| 0|0|
Wednesday 26th, October| 3| 3 |
Thursday 27th, October| 2 |0|
Friday 28th, October| 11| 10|
**Total** | -- | **25** |

**Comment by ediyes** [comment]
##### [Self intersecting major highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 10/31/2016 - 11/04/2016

Date | N° detected error | Total Fixed 
---|---|---
Thursday 3rd, November| 4 |3|
Friday 4th, November| 2| 1|
**Total** | -- | **4** |

**Comment by ediyes** [comment]
##### [Self intersecting major highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 11/07/2016 - 11/11/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 7th, November|2|0|
Tuesday 8th, November| 2|1|
Wednesday 9th, November| 1| 0 |
Thursday 10th, November| 3 |0|
Friday 11th, November| 4| 1|
**Total** | -- | **2** |

**Comment by calfarome** [comment]
##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 11/14/2016 - 11/18/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 14th, November|13|2|
Tuesday 15th, November| 7|0|
**Total** | -- | **2** |

**Comment by calfarome** [comment]
##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 11/14/2016 - 11/18/2016

Date | N° detected error | Total Fixed 
---|---|---
Tuesday 22th, November|317|16|
Friday 25th, November| 317|53|
**Total** | -- | **69** |

**Comment by Hjart** [comment]
Apparently To-fix considers constructs like https://www.openstreetmap.org/way/115967195 "self-intersecting" and flags them as errors (I have noticed a bunch of you splitting a number of these in Denmark). I have been an extremely active JOSM user since 2009 and have run it's validator at least 15000 times in that timespan. I have also created hundreds of the mentioned constructs, so I would like to know which one of To-fix and JOSM's validator is wrong and whether I should stop creating these.

**Comment by samely** [comment]
Hi @Hjart :wave: ,

We detect these kinds of geometries because there are some of them as the example bellow that should be fixed by splitting them.

![image](https://cloud.githubusercontent.com/assets/10425629/16428868/818df402-3d39-11e6-988f-4571b0ed32ee.png)
*It's not possible that this way could have the same name*

However based on your [changeset comment](http://www.openstreetmap.org/changeset/44017219), this shouldn't be considered as an error, and I've already updated this ticket.

As an immediate action, we will stop splitting this kind of edits, and just mark them as `not an error`, but also we will  improve the osmlint validator for this task to avoid detecting them

Thank you for pointing this out since we can improve our tools and workflow, at the same time that we grow as a community

**Comment by calfarome** [comment]
##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 11/28/2016 - 12/02/2016

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 28th, November | 184 | 27 |
| Tuesday 29th, November | 138 | 3 |
| Wednesday 30th, November | 71 | 17|
| Thursday 1st, December | 16 | 0 |
| Friday 2nd, December | 10 | 3 |
| **Total** | -- | **50** |

**Comment by calfarome** [comment]
##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from 11/05/2016 - 12/09/2016

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
|
| Tuesday 6th, November | 14 | 1 |
| Wednesday 7th, November | 6 | 4|
| Thursday 8th, December | 2 | 1 |
| **Total** | -- | **6** |

**Comment by ediyes** [comment]
##### [Self intersecting major highways](https://osmlab.github.io/to-fix/#/stats/selfintersectingminorhighwaysjtma) issues from 12/12/2016 - 12/16/2016
| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 7th, December | 5 | 5 |
| Friday 11th, December | 4 | 4 |
| **Total** | -- | **9** |

**Comment by ediyes** [comment]
##### [Self intersecting major highways](https://osmlab.github.io/to-fix/#/stats/selfintersectingmajorhighwayseyy) issues from 01/09/2017 - 01/13/2017
Date | N° detected error | Total Fixed 
---|---|---
Monday 09th, January |3|3| 
Wednesday 11th , January |2|2 
Thursday 12th, January |3|2
**Total** | -- | **7** |

**Comment by calfarome** [comment]
##### [Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways) issues from issues from 16/01/2017 - 20/01/2017
| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 16th, January | 12|7  |
| Tuesday 17th, January|12  | 3 |
| Wednesday 18th, January| 0 |0  |
| Thursday 19th, January| 7| 5 |
| Friday 20th, January| 3 |0  |
| **Total** | -- | **15** |

**Comment by ridixcr** [comment]
##### [Self intersecting major highways](https://osmlab.github.io/to-fix/#/stats/selfintersectingmajorhighwayseyy) issues from issues from 23/01/2017 - 27/01/2017
| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 23th, January | 4|1  |
| Tuesday 24th, January|1  | 0 |
| Wednesday 25th, January| 7 |0  |
| Thursday 26th, January| 16| 9 |
| Friday 27th, January| 5 |3  |
| **Total** | -- | **13** |

**Comment by samely** [comment]
[Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways)  issues from issues from 01/30/2017 - 02/03/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 30th January|189|45|
Tuesday 31st January|138|99|
Wednesday 01st February|100|6
Thursday 2nd February|20|10
Friday 3nd February|20|5
**Total** | -- | **165** |

**Comment by samely** [comment]
[Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways)  issues from issues from 02/06/2017 - 02/07/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 30th January|75|66|
Tuesday 31st January|13|12|
**Total** | -- | **78** |

**Comment by ridixcr** [comment]
[Self intersecting major highways](https://osmlab.github.io/to-fix/#/stats/selfintersectingmajorhighwayseyy) issues from issues from 02/13/2017 - 02/17/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Wednesday 15th February :point_left:(No detected)|0|0
Thursday 16th February |4|4
Friday 17th February |1|0
**Total** | -- | **5** |

**Comment by samely** [comment]
[Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways)  issues from issues from 02/20/2017 - 02/24/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 20th February|11|9|
Tuesday 21st February|7|6|
Wednesday 22nd February|9|9
Friday 24th February|10|7
**Total** | -- | **31** |

**Comment by ridixcr** [comment]
[Self intersecting major highways](https://osmlab.github.io/to-fix/#/stats/selfintersectingmajorhighwayseyy) issues from issues from 02/27/2017 - 03/03/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 27th February|2|1
Tuesday 28th February|1|0
Wednesday 1st March |9|0
Thursday 2nd March |11|3
Friday 3rd March |4|0
**Total** | -- | **4** |

**Comment by ridixcr** [comment]
[Self intersecting major highways](https://osmlab.github.io/to-fix/#/stats/selfintersectingmajorhighwayseyy) issues from 03/06/2017 - 03/10/2017
:point_right:  *Full not an error* :point_down:

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 06th March|1|0
Tuesday 07th March|0|0
Wednesday 08th March |1|0
Thursday 09th March |3|0
Friday 10th March |2|0
**Total** | --| **0** |

**Comment by ridixcr** [comment]
[Self intersecting major highways](https://osmlab.github.io/to-fix/#/stats/selfintersectingmajorhighwayseyy) issues from 03/13/2017 - 03/17/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 13th March|14|12
Wednesday 15th March |11|0
Friday 17th March |10|4
**Total** | -- | **16** |

**Comment by RichRico** [comment]
[Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways)  issues from 05/01/2017 - 05/05/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Friday 5th May |71|58
**Total** | -- | **58** |

**Comment by samely** [comment]
[Self intersecting minor highways](http://osmlab.github.io/to-fix/#/task/selfintersectingmajorhighways)  issues from 05/06/2017 - 05/12/2017
:point_right:  *Full not an error* :point_down:

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 08th March|32|4
Tuesday 09th March|3|0
Wednesday 10th March |6|3
Thursday 11th March |3|0
**Total** | --| **7** |
