### ISSUE TITLE
To-fix: Missing oneway in motorway_link

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#204]
### Objective

Add missing `oneway=yes` tag to the `highway=motorway_link`.
### Tasks

**The task below is updating everyday from Monday to Friday with the latest errors in OpenStreetMap**
-  http://osmlab.github.io/to-fix/#/task/missingonewaysmotorwaylink
### Changeset comment

```
Adding missing oneway tag to motorway_links using #to-fix https://github.com/mapbox/mapping/issues/204
```
### Coverage

All countries in this list: https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt
### Tools
- Use the [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin) instead of ToFix directly
### Instructions
- Add `oneway=yes` to the `highway=motorway_link`
- If editing in an actively mapped area, add a note instead of making a fix.
- If satellite imagery isn't clear click on `not an error` of to-fix
### Common issues

![image](https://cloud.githubusercontent.com/assets/10425629/16496434/70403096-3eb7-11e6-988a-afa2a290c96a.png)

![image](https://cloud.githubusercontent.com/assets/10425629/16496452/8c173206-3eb7-11e6-9e46-b94138ba4f78.png)

_Add `oneway=yes`_ tag.
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
### Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data

**Comment by luiswalter** [comment]
#### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink) Progress  issues from 07/18/2016 - 07/22/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 18th, July |6 | 6 |
Tuesday 19th, July  | 6 | 0 |
**Total** | -- | **6** |

**Comment by Yurasi** [comment]
##### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/task/missingonewaysmotorwaylink) issues from 07/11/2016 - 07/14/2016
Date | N° detected error | Total Fixed 
---|---|---
Tuesday 12th, July  | 12 |11  |
Wednesday 13th, July | 2 |0  |
Thursday 14th, July | 0 | 0 |
**Total** | -- | **11** |

**Comment by Yurasi** [comment]
#### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink) Progress  issues from 08/01/2016 - 08/05/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 1st, August | 8 | 8 |
**Total** | -- | **8** |

**Comment by Yurasi** [comment]
#### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink) Progress issues from 08/08/2016 - 08/12/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 08th, August | 01 | 01 |
Tuesday 09th, August  | 01 | 01 |
Wednesday 10th, August | 0 | 0 |
Thursday 11th, August | 0 | 0 |
Friday 12th, August | 0 | 0 |
**Total** | **02** | **02** |

**Comment by Yurasi** [comment]
#### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink) Progress issues from 08/15/2016 - 08/19/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 15th, August | 2 | 2 |
Tuesday 16th, August  | 0 | 0 |
Wednesday 17th, August | 0 | 0 |
Thursday 18th, August | 0 | 0 |
Friday 19th, August | 1 | 1 |
**Total** | **3** | **3** |

**Comment by Yurasi** [comment]
#### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink) Progress issues from 08/22/2016 - 08/26/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 22nd, August | 1 | 1 |
Tuesday 23rd, August  | 10 |10 |
Wednesday 24th, August | 1 | 1 |
Thursday 25th, August | 0 | 0 |
Friday 26th, August | 0 | 0 |
**Total** | **12** | **12** |

**Comment by Yurasi** [comment]
#### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink) issues from 08/29/2016 - 08/31/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 29th, August | 0 | 0 |
Tuesday 30th, August  | 0 | 0 |
Wednesday 31st, August | 1 | 1 |
**Total** | **1** | **1** |

**Comment by Yurasi** [comment]
#### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink)  issues from 09/05/2016 - 09/09/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 05th, September | 02 | 02 |
**Total** | **02** | **02** |

**Comment by Yurasi** [comment]
#### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink)  issues from 09/12/2016 - 09/17/2016

Date | N° detected error | Total Fixed 
---|---|---
Tuesday 13th, August  | 2 | 2 |
Thursday 15th, August | 4 | 3 |
**Total** | **6** | **5** |

**Comment by Yurasi** [comment]
#### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink)  issues from 09/19/2016 - 09/23/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 19th, August | 01 | 01 |
Tuesday 20th, August  | 04 | 04 |
Wednesday 21st, August | 06 | 06 |
Thursday 22nd, August | 02 | 02 |
Friday 23rd, August | 140 | 138 |
**Total** | **153** | **151** |

**Comment by Yurasi** [comment]
#### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink)  issues from 10/24/2016 - 10/28/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 24th, October | 37 | 37 |
**Total** | **37** | **37** |

**Comment by Yurasi** [comment]
##### [Island minor highways](http://osmlab.github.io/to-fix/#/task/islandsminorhighways) issues 10/31/2016 

Date | N° detected error | Total Fixed 
---|---|---
Monday 31st, November | 01 | 01 |
**Total** | **01** | **01** |

**Comment by Yurasi** [comment]
#### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink)  issues from 11/10/2016 - 11/11/2016

Date | N° detected error | Total Fixed 
---|---|---
Thursday 10th, November | 1 | 1 |
Friday 11th, November | 5 | 4 |
**Total** | **6** | **5** |

**Comment by Yurasi** [comment]
#### [Missing oneway in motorway_link](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink) issues from 11/22/2016 - 11/25/2016

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Tuesday 22nd, November | 23 | 22 |
| Friday 25th, November | 2 | 1 |
| **Total** | **25** | **23** |

**Comment by Yurasi** [comment]
##### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylinkcvwp) issues of 12/13/2016

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Tuesday 13th, December | 06 | 06 |
| **Total** | **06** | **06** |

**Comment by Yurasi** [comment]
##### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylinkcvwp) issues from 01/09/2017 - 01/12/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 09th, January |02|02|
| Tuesday 10th, January| -- | -- |
| Wednesday 11th, January| 01 | 01 |
| Thursday 12th, January| 01 | 01 |
| **Total** | **04** | **04** |

**Comment by Yurasi** [comment]
##### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylinkcvwp) issues from 01/16/2017 - 01/20/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 16th, January |07|07|
| Tuesday 17th, January| 02 | 02 |
| Wednesday 18th, January| 02 | 00 |
| Thursday 19th, January| 00 | 00 |
| Friday 20th, January|02  | 01 |
| **Total** | **13** | **10** |

**Comment by dannykath** [comment]
##### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylinkcvwp) issues    from 01/30/2017 - 02/03/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 30h January|3|2
Tuesday 31th January|1|1
Wednesday 01st February|1|1
Thursday 02th February|3|3
--| **Total**|7

**Comment by dannykath** [comment]
##### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylinkcvwp) issues    from 02/06/2017 - 02/10/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 30h January|4|4
Thursday 02th February|7|7
--| **Total**|11

**Comment by dannykath** [comment]
##### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylink) issues    from 02/13/2017 - 02/117/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 13th February|12|11
Thursday 16th February|2|2
Friday 17th February|3|3
--| **Total**|16

**Comment by dannykath** [comment]
##### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylink) issues    from 02/20/2017 - 02/24/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 20th February|2|2
Tuesday 21th February|1|1
Friday 24th February|1|1
--| **Total**|4

**Comment by dannykath** [comment]
##### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylink) issues    from 02/27/2017 - 03/03/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 27th February|3|3
Tuesday 28th February|2|2
Thursday 02nd February|2|2
--| **Total**|7

**Comment by dannykath** [comment]
##### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylink) issues   from 03/06/2017 - 03/10/2017

Date| Detected Issues | Fixed Issues
---|----|---
Tuesday 07th March|1|1
--| **Total**|1

**Comment by dannykath** [comment]
##### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylink) issues   from 03/13/2017 - 03/17/2017

Date| Detected Issues | Fixed Issues
---|----|---
Tuesday 07th March|11|11
--| **Total**|11

**Comment by dannykath** [comment]
##### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylink)  issues   from 04/04/2017 - 04/07/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 03rd April|44|42
--| **Total**|**42**

**Comment by dannykath** [comment]
### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylink) 
### Issues   from 04/24/2017 - 04/28/2017

Date| Detected Issues | Fixed Issues
---|----|---
Tuesday 25th April|71|64
Thursday 27th April|19|11
--| **Total**|**75**

**Comment by dannykath** [comment]
### [Missing oneway in motorway_link](https://osmlab.github.io/to-fix/#/stats/missingonewaymotorwaylink) 
### Issues   from 05/08/2017 - 05/12/2017

Date| Detected Issues | Fixed Issues
---|----|---
Tuesday 09th May|4|4
Thursday 11th May|370|80
Friday 12th May|370|100
--| **Total**|**184**
