### ISSUE TITLE
To-fix: Impossible one-way highways

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#205]
### Objective

Ensure highways with `oneway=yes` are no blocked because of the direction of the roads connected to it.
### Tasks

**The below tasks are updating everyday from Monday to Friday with the latest errors in OpenStreetMap**
-  Major: http://osmlab.github.io/to-fix/#/task/impossibleonewaysmajorhighways
-  Minor: http://osmlab.github.io/to-fix/#/task/impossibleonewaysminorhighways
#### Changeset comment

```
Adding or deleting oneway=* tag to make the roads navigable using #to-fix https://github.com/mapbox/mapping/issues/205
```
### Coverage

All countries in this list: https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt
### Tools
- If using iD editor, work with [To-Fix web](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)
- If using JOSM, work with [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin)
- Use reverse tool (Shortcut: `R`)
### Instructions
- Reverse the highway pressing `R`
- Ensure the way has `oneway=yes` instead of `oneway=-1`
- If editing in an actively mapped area, add a note instead of making a fix.
- If satellite imagery isn't clear click on `not an error` of to-fix
### Common issues

![image](https://cloud.githubusercontent.com/assets/10425629/16501066/3612f4f6-3ecd-11e6-97aa-ee60a5153c85.png)
_Reverse the way and ensure it has `oneway=yes` instead of `oneway=-1` tag_

![image](https://cloud.githubusercontent.com/assets/10425629/16501774/b58e0c90-3ed0-11e6-9862-ffd712485ed0.png)
_Join all nodes_
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
### Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data

**Comment by luiswalter** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/missingonewaysmotorwaylink) Progress  issues from 07/18/2016 - 07/22/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 18th, July |6 | 5 |
Friday 22th, July  | 12 | 3 |
**Total** | -- | **9** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 07/25/2016 - 07/29/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 25th, July | 16|3 |
Tuesday 26th, July  | 4 |3  |
Wednesday 27th, July | 6 | 2 |
**Total** | -- | **8** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 08/01/2016 - 08/05/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 1st, August | 9 | 3 |
Tuesday 2nd, August | 5 | 4 |
Wednesday 3rd, August | 32 | 0   :point_left:  There was a [problem](http://forum.openstreetmap.org/viewtopic.php?id=55220)|
Thursday 4th, August | 9 | 4 |
Friday 5th, August | 11 | 5 |
**Total** | -- | **16** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 08/01/2016 - 08/05/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 08th, August | 12 | 0 |
Tuesday 09th, August | 18 | 11 |
Wednesday 10th, August | 6 | 4 |
Thursday 11th, August | 7 | 6 |
Friday 12th, August | 5 | 4 |
**Total** | -- | **25** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 08/15/2016 - 08/19/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 15th, August | 6 | 2 |
Tuesday 16th, August | 9 | 5 |
Wednesday 17th, August | 4 | 2 |
Thursday 18th, August | 1 | 1 |
Friday 19th, August | 5 | 3 |
**Total** | -- | **13** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 08/22/2016 - 08/26/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 22th, August | 8 | 3 |
Tuesday 23th, August | 5 | 2 |
Wednesday 24th, August | 7 | 4 |
Thursday 25th, August | 2 | 2 |
Friday 26th, August | 2 | 1 |
**Total** | -- | **12** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 08/29/2016 - 08/31/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 22th, August | 5 | 0 |
Tuesday 23th, August | 3 | 1 |
Wednesday 24th, August | 0 | 0 |
**Total** | -- | **1** |

**Comment by dannykath** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysminorhighways) Progress  issues from 09/05/2016 - 09/09/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 05th | 1261  |39  |
Tuesday 06th |1212  |105  |
Wednesday 07th | 1046 | 55 |
Thursday 08th| 938|65 |
Friday 09th |837 |10 |
**Total** | -- | **274** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 09/05/2016 - 09/09/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 05th | 11  |4  |
Tuesday 06th |3  |2  |
Wednesday 07th | 2 | 0 |
Thursday 08th| 3|1 |
Friday 09th |7 |5 |
**Total** | -- | **12** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 09/12/2016 - 09/16/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 12th, September | 8  |3  |
Tuesday 13th, September | 4 |2  |
Wednesday 14th, September | 3 | 0 |
Thursday 15th, September| 3|1 |
Friday 16th, September |5 |3 |
**Total** | -- | **9** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 09/19/2016 - 09/23/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 19th, September | 9  |7  |
Tuesday 20th, September | 8 |6  |
Wednesday 21th, September | 8 | 7 |
Thursday 22th, September| 2|2 |
Friday 23th, September |366 |32 |
**Total** | -- | **54** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 10/24/2016 - 10/28/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Tuesday 25th, October|91|15|
Wednesday 26th, October|62|21|
Thursday 27th, October|23|1|
Friday 28th, October|7|3|
**Total** | -- | **40** |

**Comment by dannykath** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysminorhighways) Progress  issues from 10/31/2016 - 11/03/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 31th, October|14|8|
Wednesday 02th, November|9|6|
Thursday 03th, November|9|3|
**Total** | -- | **17** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 10/31/2016 - 11/04/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 31th, October|--|2|
Wednesday 02nd, November|15|6|
Thursday 03rd, November|8|3|
Friday 04th, November|11|1|
**Total** | -- | **12** |

**Comment by calfarome** [comment]
Bear in mind the [issues comments](https://github.com/mapbox/data/issues/1931)   to solve some errors like this :  [Impossible oneways highways connected to buildings](https://github.com/mapbox/data/issues/1931).
cc. @mapbox/team-data

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 11/14/2016 - 11/18/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 14thth, November|12	|8|
Tuesday 15th, November|9|4|
Thursday 17th, November|5|2|
Friday 18th, November|4	|2|
**Total** | -- | **16** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 11/14/2016 - 11/18/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 14thth, November|12	|7|
Tuesday 15th, November|7|0|
**Total** | -- | **7** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 12/05/2016 - 12/09/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 05th, November|10|4|
Tuesday 06th, November|18|3|
**Total** | -- | **7** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 12/12/2016 - 12/16/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Tuesday 13th, November|21|13|
Friday 16th, November|12|4|
**Total** | -- | **17** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 12/19/2016 - 12/23/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Wednesday 21th, November|21|6|
Thursday 22th, November|5|2|
**Total** | -- | **8** |

**Comment by dannykath** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysminorhighways) Progress   from 11/24/2016 

Date | N° detected error | Total Fixed 
---|:---:|:---:
Wednesday 24th, November|622|34|
**Total** | -- | **34** | 

#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysminorhighways) Progress  issues from 12/05/2016 - 12/06/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 05th December|450|27|
Tuesday 06th December|397|26|
**Total** | -- | **53** | 


#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysminorhighways) Progress  issues from 12/14/2016 - 12/21/2016

Date | N° detected error | Total Fixed 
---|:---:|:---:
Wednesday 14th December|253|15|
Thursday 15th December|238|63|
Friday 16th December|179|35|
Wednesday 21st December|156|27|
**Total** | -- | **140** |

**Comment by dannykath** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysminorhighways) Progress  issues from 01/09/2017 - 01/13/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 09th January|16|8|
Wednesday 11th January|3|2|
Friday 13th January|16|11|
**Total** | -- | **21** |

**Comment by dannykath** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysminorhighways) Progress  issues from 01/16/2017 - 01/20/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 16th January|13|2|
Tuesday 17th January|6|4|
Thursday 19th January|13|7|
Friday 20th January|6|5|
**Total** | -- | **18** |

**Comment by piligab** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 16/01/2017 - 20/01/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
| Monday 16th, January | 31|9  |
| Tuesday 17th, January|2  | 1 |
| Wednesday 18th, January| 1 |0  |
| Thursday 19th, January| 8 | 2 |
| Friday 20th, January| 7 |2  |
| **Total** | -- | **14** |

**Comment by Yurasi** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress issues from 23/01/2017 - 26/01/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 23th, January | 10|04  |
| Tuesday 24th, January|--  | -- |
| Wednesday 25th, January| 12 |06  |
| Thursday 26th, January| 04 | 00 |
| **Total** | **26** | **10** |

**Comment by luiswalter** [comment]
#### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress issues from 23/01/2017 - 26/01/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Monday 23th, January | 16|2  |
| Tuesday 24th, January|--  | -- |
| Wednesday 25th, January| 15 |7  |
| Thursday 26th, January| 08 | 00 |
| **Total** | **** | **9** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways)  Progress  issues from 30/01/2017 - 02/02/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
| Monday 30th, January | 42|19 |
| Tuesday 31th, February| -- |--|
| Wednesday 01st, February| 00 |00|
| Thursday 02nd, February| 07 |04|
| **Total** | **49** | **23** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways)  Progress  issues from 02/06/2017 - 02/07/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 6th February|20|09
Tuesday 7th February|05|01
Wednesday 8th February :point_left:(No detected)|0|0
Thursday 9th February :point_left:(No detected)|0|0
Friday 10th February :point_left:(No detected)|0|0
**Total** | **--** | **10** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 16/02/2017 - 17/02/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Thursday 16th February |580|40
Friday 17th February |475|83
**Total** | **--** | **123** |

**Comment by luiswalter** [comment]
##### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from  13/02/2017 - 17/02/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 13th February|64|07
Tuesday 14th February|65|08
Thursday 16th February|143|48 
Friday 17th February|115|31 
**Total** | **--** | **94** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from 20/02/2017 - 24/02/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 20th February |441|83
Tuesday 21th February |94|36
Wednesday 22th February |06|01
Thursday 23th February :point_left:(No detected)|00|00
Friday 24th February |09|05
**Total** | **--** | **125** |

**Comment by luiswalter** [comment]
##### [Impossible one-way major highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress  issues from  20/02/2017 - 24/02/2017

Date | N° detected error | Total Fixed 
---|---|---
Monday 20th February|160|52|
Tuesday 21st February|10|9|
Thursday 23st February|11|4
**Total** | -- | **65** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress issues from 02/27/2017 - 03/03/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 27th February|13|09
Tuesday 28th February :point_left:(No detected)|00|00
Wednesday 1st March |10|07
Thursday 2nd March |04|01
Friday 3rd March |14|05
**Total** | **--** | **22** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress issues from 03/06/2017 - 03/10/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 06th March|13|10
Tuesday 07th March|04|02
Wednesday 08th March |01|01
Thursday 09th March |01|00
Friday 10th March |13|03
**Total** | **--** | **16** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress issues from 03/13/2017 and 03/17/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 13th March|8|8
Friday 17th March |15|6
**Total** | **--** | **14** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress issues on 03/21/2017 

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Tuesday 21th March |20|15
**Total** | **20** | **15** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress issues from 03/29/2017 to 03/30/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Wednesday 29th March |89|50
Thursday 30th March |03|01
**Total** | **--** | **51** |

**Comment by luiswalter** [comment]
#### [Impossible one-way minor highways](http://osmlab.github.io/to-fix/#/stats/impossibleonewaysmajorhighways) Progress issues from 04/03/2017 - 04/07/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Friday 07th April |106|37
**Total** | **--** | **37** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](https://osmlab.github.io/to-fix/#/stats/impossibleonewaysminorhighways)  Progress issues from 04/10/2017 - 04/13/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 19th March|496|63
Tuesday 11th March|420|93
Wednesday 12th March |303|66
Thursday 13th March |218|153
**Total** | **--** | **375** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](https://osmlab.github.io/to-fix/#/stats/impossibleonewaysminorhighways)  Progress issues from 04/17/2017 - 04/21/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 17th April|06|04
Tuesday 18th April|03|03
Wednesday 19th April |00|00
Thursday 20th April |03|03
Friday 21th April |01|00
**Total** | **13** | **10** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](https://osmlab.github.io/to-fix/#/stats/impossibleonewaysminorhighways)  Progress issues on Monday 04/24/2017 and Thursday  04/27/2017.

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 17th April|07|04
Thursday 20th April |323|37
**Total** | **--** | **41** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](https://osmlab.github.io/to-fix/#/stats/impossibleonewaysminorhighways)  Progress issues from 05/02/2017 - 05/03/2017.

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Tuesday 02nd |256|68
Wednesday 03rd |155|71
**Total** | **--** | **139** |

**Comment by Yurasi** [comment]
#### [Impossible one-way minor highways](https://osmlab.github.io/to-fix/#/stats/impossibleonewaysminorhighways)  Progress issues from 05/08/2017 - 05/12/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
Monday 08th May|08|05
Tuesday 09th May|05|01
Wednesday 10th May |06|05
Thursday 11th May |63|32
Friday 12th May|1804|44
**Total** | **--** | **87** |
