### ISSUE TITLE
To-fix: Broken polygons

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#206]
### Objective

Close polygons which are broken.
## Tasks

**The task below is updating everyday from Monday to Friday with the latest errors in OpenStreetMap**
-  http://osmlab.github.io/to-fix/#/task/nonclosedways
### Changeset comment

```
Fixing invalid multipolygon relation by closing unclosed rings and self intersecting areas using #to-fix https://github.com/mapbox/mapping/issues/206
```
### Coverage

All countries in this list: https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt
### Tools
- If using iD editor, work with [To-Fix web](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)
- If using JOSM, work with [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin)
- Use split way tool (Shortcut: `P`)
- Use unglue tool (Shortcut: `G`)
### Instructions
- If the highway has any tag for areas (i.e. `landuse` or `buildings`) delete this tag.
- If the area has a self-intersect node, disengage it and reshape the area.
- If editing in an actively mapped area, add a note instead of making a fix.
- If satellite imagery isn't clear click on `not an error` of to-fix
- Check in osm layer if the polygon dos not show. [example](https://cloud.githubusercontent.com/assets/1152236/18569401/f6e828aa-7b67-11e6-8536-f0c1ba8ddbfc.png)
### Common issues

![image](https://cloud.githubusercontent.com/assets/10425629/16502180/b50a18ac-3ed2-11e6-8314-1a8ff70574f0.png)
_Delete the `building=yes` tag_

![image](https://cloud.githubusercontent.com/assets/10425629/16502199/cc1efecc-3ed2-11e6-8204-c0fbff0a147a.png)
_Delete the irrelevant node_

![image](https://cloud.githubusercontent.com/assets/1152236/18569401/f6e828aa-7b67-11e6-8536-f0c1ba8ddbfc.png)
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
### Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data

**Comment by dannykath** [comment]
##### [Broken polygons](http://osmlab.github.io/to-fix/#/task/nonclosedways) issues from 07/11/2016 - 07/14/2016

Date | N° detected error | Total Fixed 
---|---|---
Wednesday 13th, July |65652  |1600  |
Thursday 14th, July | 49930 | 1526 |
**Total** | -- | **3126** |

**Comment by luiswalter** [comment]
##### [Broken polygons](http://osmlab.github.io/to-fix/#/task/nonclosedways) issues from 07/18/2016 - 07/22/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 18th, July | 44,430  |1,992  |
Wednesday 20th, July | 39,380 | 2,574  |
Thursday 21th, July | 38,709 | 671 |
**Total** | -- | **5,237** |

**Comment by calfarome** [comment]
##### [Broken polygons](http://osmlab.github.io/to-fix/#/task/nonclosedways) issues from 07/25/2016 - 07/27/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 25th, July | 18772   |189  |
Wednesday 26th, July | 17878 | 0  |
Thursday 27th, July | 17891 | 0 |
**Total** | -- | **189** |

**Comment by 1ec5** [comment]
[This changeset](http://www.openstreetmap.org/changeset/42212355) claims to be fixing a multipolygon, but it doesn’t look like the edited way was ever part of a multipolygon. Instead, it [removed](https://pewu.github.io/osm-history/#/way/250436749) `golf` and `water` tags added as part of iD’s [Lateral Water Hazard](https://github.com/openstreetmap/iD/blob/d130c517b0a98c470aef269176bda729532f8ff1/data/presets/presets/golf/lateral_water_hazard.json#L8) preset. Was this intentional, and if so, should iD’s preset be corrected?

**Comment by bhousel** [comment]
Thanks for catching this @1ec5.. Indeed iD was adding broken `natural=water` polygons via the water hazard presets.  Just fixed this! 🏌️  

re https://github.com/openstreetmap/iD/issues/3483

**Comment by rory** [comment]
Hi! I think there might be a bug with your workflow/scripts/detection/etc. In [changeset 44,381,869](https://www.openstreetmap.org/changeset/44381869) mapper [piligab](https://www.openstreetmap.org/user/piligab) broke a previously valid relation ([relation 4,590,559 - Ballybetagh](https://www.openstreetmap.org/relation/4590559)) with the changeset comment of "Fixing broken relation"

**Comment by bsrinivasa** [comment]
@rory Thank you for identifying this. This could have possibly happened due to flagging of the relation under `ring not closed` in To-Fix Task. Usually, in the cases similar to the above, the missing way segment is added into the relation but wherein in this [changeset 44,381,869](https://www.openstreetmap.org/changeset/44381869), the [way segment 326233195](http://www.openstreetmap.org/way/326233195) was deleted from the relation. @piligab It would be great if you can check the relation in To-Fix task and clarify why the member was removed from the relation.
cc: @geohacker @Rub21 @poornibadrinath

**Comment by piligab** [comment]
Hi @rory!
I'm not sure how this happened, maybe I could have confused any tags and deleted. I will be careful about my future editions. Thanks for your feedback. 

cc. @bsrinivasa, @poornibadrinath, @Rub21

**Comment by luiswalter** [comment]
##### [Broken polygons](http://osmlab.github.io/to-fix/#/task/nonclosedways) issues from 01/16/2017 - 01/20/2017

| Date | N° detected error | Total Fixed |
| --- | --- | --- |
| Tuesday 17th, January |121  |18  |
| Thursday 26th, January | 31| 1 |
| **Total** | -- | **19** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 01/23/2017 - 01/27/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 23rd January|58|24|
Wednesday 25th January|52|41
Thursday 26th January|13|7|
Friday 27th January|36|23|
**Total** | -- | **95** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 01/30/2017 - 02/03/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Tuesday 31st January|73|54
Thursday 02nd Febrary|51|39|
**Total** | -- | **93** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 02/13/2017 - 02/17/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Thursday 16th February|229|80
Friday 17th February|128|84
**Total** | -- | **164** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 02/20/2017 - 02/24/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 20th February| 53|17
Tuesday 21st February|25|7
Wednesday 22nd February|18|5
**Total** | -- | **29** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 02/27/2017 - 03/03/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Tuesday 28th February|131|49
Wednesday 01st March|74|20
Thursday 02nd March|87|38
**Total** | -- | **107** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 03/06/2017 - 03/10/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 06th March|84|42
Tuesday 07th March|24|12
Wednesday 08th March|12|2
Friday 10th March|69|43
**Total** | -- | **99** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 03/13/2017 - 03/17/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Wednesday 15th March|133|17
Friday 17th March|134|63
**Total** | -- | **80** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 03/20/2017 - 03/24/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 20th March|58|30
Wednesday 22nd March|22|7
Thursday 23rd March|48|3
**Total** | -- | **40** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 04/03/2017 - 04/07/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Wednesday 05th April|80|45
Thursday 06th April|7|5
**Total** | -- | **50** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 04/10/2017 - 04/14/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Monday 10th April|365|67
Tuesday 11th April|224|42
Wednesday 12th April|182|102
**Total** | -- | **211** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 04/17/2017 - 04/21/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Tuesday 18th April|21|14
Wednesday 19th April|3|1
**Total** | -- | **15** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 04/24/2017 - 04/28/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Thursday 27th April|247|43
**Total** | -- | **43** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 05/01/2017 - 05/05/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
Tuesday 02nd|247|35
Wednesday 03rd May|47|27
Thursday 04th May|30|9
Friday 05th May|3|2
**Total** | -- | **73** |

**Comment by karitotp** [comment]
##### [Broken polygons](https://osmlab.github.io/to-fix/#/stats/brokenpolygonsgkvy) Progress  issues from 05/08/2017 - 05/12/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
|Monday 08th, May| 26|7|
Tuesday 09th, May|4|4|
|Wednesday 10th, May| 3|1|
|Friday 12th, May||31
| **Total** | -- | **43** |
