### ISSUE TITLE
To-fix: Strange layer

### ISSUE THREAD

**Issue by samely** [mapbox/mapping#210]
### Objective

Correct the `layer=*` tag of bridges and tunnels.
### Tasks

**The tasks below are updating everyday from Monday to Friday with the latest errors in OpenStreetMap**

To-Fix issue:
- http://osmlab.github.io/to-fix/#/task/strangelayer
#### Changeset comment

```
Fixing incorrectly added layer tag to bridges and tunnels using #to-fix https://github.com/mapbox/mapping/issues/210
```
### Coverage

All countries in this list: https://s3.amazonaws.com/mapbox/to-fix/mbtiles.txt
### Tools
- If using iD editor, work with [To-Fix web](http://osmlab.github.io/to-fix/#/task/crossingmajorhighways)
- If using JOSM, work with [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin)
### Instructions
- If the bridge has `layer=-1`, change it by `layer=1`, inspect imagery to fix the level.
- If the tunnel has `layer=1`,  change it by `layer=-1`, inspect imagery to fix the level.
- If editing in an actively mapped area, add a note instead of making a fix.
- If satellite imagery isn't clear click on `not an error` button of to-fix
### Common issues

![image](https://cloud.githubusercontent.com/assets/10425629/16776384/c0019800-482a-11e6-9345-e39b87a78392.png)
_Correct `layer` tag of the tunnel as `layer=-1` instead of `layer=1`_

![image](https://cloud.githubusercontent.com/assets/10425629/16776486/281880fc-482b-11e6-9af4-bd632d739b20.png)
_Correct `layer` tag of the bridge as `layer=1` instead of `layer=-1`_
### How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [selfIntersectingHighways](https://github.com/osmlab/osmlint/tree/master/validators/selfIntersectingHighways)
### Who will work on these tasks?

Everybody is available to work on resolving these issues. However, @mapbox/data-team (Peru office) will work on everyday.
### Question

Tag @planemad or @rub21 for questions.

cc. @mapbox/team-data

**Comment by dannykath** [comment]
#### [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) Progress  issues from 07/11/2016 - 07/14/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 11th, July |1029  |-- |
Tuesday 12th, July  | 1028 | 744 |
Wednesday 13th, July | 762 | -- |
Thursday 14th, July | 40 | -- |
**Total** | -- | **744** |

**Comment by samely** [comment]
#### [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) Progress  issues from 07/11/2016 - 07/14/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 25th, July | 3 | 0 |
Tuesday 26th, July  | 4 | 4 |
Wednesday 27th, July | 4 | 4 |
**Total** | -- | **8** |

**Comment by samely** [comment]
[Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from 08/01/2016 - 08/05/2016
Date | N° detected error | Total Fixed 
---|---|---
Monday 1st, July | 3 | 3 |
Tuesday 2nd, July  | 4 | 4 |
Wednesday 3th, July | 4 | 0 [obs.](http://forum.openstreetmap.org/viewtopic.php?id=55220)|
Thursday 4th, August | 0 | 0 |
Friday 5th, August | 0| 0 |
**Total** | -- | **7** |

**Comment by samely** [comment]
#### [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from 08/08/2016 - 08/12/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 8th, August | 4 | 4 |
Tuesday 9th, August  | 0 | 0 |
Wednesday 10th, August | 0 | 0 |
Thursday 11th, August | 1 | 1 |
Friday 12th, August | 0| 0 |
**Total** | -- | **5** |

**Comment by samely** [comment]
#### [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from 08/15/2016 - 08/19/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 15th, August | 0 | 0 |
Tuesday 16th, August  | 1 | 1 |
Wednesday 17th, August | 0 | 0 |
Thursday 18th, August | 0 | 0 |
Friday 19th, August | 1| 1 |
**Total** | -- | **2** |

**Comment by samely** [comment]
#### [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from 08/22/2016 - 08/26/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 22th, August | 0 | 0 |
Tuesday 23th, August  | 2 | 1 |
Wednesday 24th, August | 0 | 0 |
Thursday 25th, August | 2 | 0 |
Friday 26th, August | 2| 2 |
**Total** | -- | **3** |

**Comment by samely** [comment]
#### [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from 08/29/2016 - 08/31/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 29th, August | 1 | 1 |
Tuesday 30th, August  | 0 | 0 |
Wednesday 31th, August | 0 | 0 |
**Total** | -- | **1** |

**Comment by samely** [comment]
#### [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from 09/05/2016 - 08/09/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 5th, August | 0 | 0 |
Tuesday 6th, August  | 0 | 0 |
Wednesday 7th, August | 3 | 2 |
Thursday 8th, August | 27 | 0 |
Friday 9th, August | 34| 32 |
**Total** | -- | **34** |

**Comment by samely** [comment]
#### [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from 09/12/2016 - 09/16/2016

Date | N° detected error | Total Fixed 
---|---|---
Monday 12th, August | 2 | 2 |
Tuesday 13th, August  | 0 | 0 |
Wednesday 14th, August | 0 | 0 |
Thursday 15th, August | 2 | 1 |
Friday 16th, August | 0| 0 |
**Total** | -- | **3** |

**Comment by piligab** [comment]
#### [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) Progress  issues from 16/01/2017 - 20/01/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
| Monday 16th, January | 54|16 |
| Tuesday 17th, January|17 | 1 |
| Wednesday 18th, January| 13 |0  |
| Thursday 19th, January| 13 | 0 |
| Friday 20th, January| 12 |0  |
| **Total** | -- | **14** |

**Comment by luiswalter** [comment]
#### [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) Progress  issues from 23/01/2017 - 27/01/2017

Date | N° detected error | Total Fixed 
---|:---:|:---:
| Monday 23th, January | 13|9 |
| Wednesday 25th, January| 11 |0  |
| Thursday 26th, January| 12 | 0 |
| **Total** | -- | **9** |

**Comment by calfarome** [comment]
#####  [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from    30/01/2017 - 03/02/2017

Date | N° detected error | Total Fixed 
---|---|---
Monday 30th January|31|4|
Tuesday 31st January|11|0|
Wednesday 01st February|1|1
Thursday 2nd February|0|0
Friday 3nd February|13|0
**Total** | -- | **5** |

**Comment by calfarome** [comment]
#####  [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from 06/02/2017 - 10/02/2017

Date| Detected Issues | Fixed Issues
---|----|---
Monday 06th February|24|2
--| **Total**|**2**

**Comment by luiswalter** [comment]
#####  [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from    13/02/2017 - 17/02/2017

Date | N° detected error | Total Fixed 
---|---|---
Monday 13th February|15|4|
Tuesday 14st February|02|0|
Thursday 16st February|11|4
Friday 17st February|2|2
**Total** | -- | **10** |

**Comment by luiswalter** [comment]
#####  [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from    20/02/2017 - 24/02/2017

Date | N° detected error | Total Fixed 
---|---|---
Monday 20th February|9|4|
Tuesday 21st February|03|0|
Thursday 23st February|0|0
**Total** | -- | **4** |

**Comment by luiswalter** [comment]
#####  [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from    27/02/2017 - 03/03/2017

Date | N° detected error | Total Fixed 
---|---|---
Monday 27th February|2|2|
Tuesday 28st February|12|4|
Wednesday 01th March|8|1|
Friday 03st March|9|6
**Total** | -- | **13** |

**Comment by luiswalter** [comment]
#####  [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from    06/03/2017 - 10/03/2017

Date | N° detected error | Total Fixed 
---|---|---
Monday 06th February|10|8|
Tuesday 07st February|02|1|
Friday 10st March|7|2
**Total** | -- | **11** |

**Comment by luiswalter** [comment]
#####  [Strange layer](http://osmlab.github.io/to-fix/#/task/strangelayer) issues from    03/04/2017 - 07/04/2017

Date | N° detected error | Total Fixed 
---|---|---
Friday 07st April|32|12
**Total** | -- | **12** |
