### ISSUE TITLE
Adding turn restrictions in Canada using Mapillary

### ISSUE THREAD

**Issue by poornibadrinath** [mapbox/mapping#213]
### Goal
- Mapping [turn-restrictions](http://wiki.openstreetmap.org/wiki/Relation:restriction) in top 5 Canadian cities using Mapillary as the source
- Cities: Ottawa, Toronto, Montréal, Vancouver, Calgary

### Task Workflow
1. [Using the OSM navigation map](http://mapbox.github.io/osm-navigation-map/#7.99/43.835/-79.557)
2. [Mapping turn restrictions from Mapillary](https://github.com/mapbox/mapping/wiki/Mapping-guide-for-adding-turn-restrictions-using-Mapillary)
3. [Progress spreadsheet](https://docs.google.com/a/mapbox.com/spreadsheets/d/1rytOtAMau3HVuiCHu61Nv-doug_hxl1-uGc4lkrTH2c/edit?usp=sharing)

------

![](https://swanboatsteve.files.wordpress.com/2009/12/img_0711c.jpg)

**Team** : @mapbox/team-data 

**Timeline** : 1 week (Estimate)

**Tagging guidelines** 
- [Absolute turn restrictions](http://wiki.openstreetmap.org/wiki/Relation:restriction) 
- [Conditional turn restrictions](http://wiki.openstreetmap.org/wiki/Conditional_restrictions)

**Data sources**
- Mapillary detected traffic signs via [OSM navigation map](http://mapbox.github.io/osm-navigation-map/) and JOSM plugin
- Bing/Mapbox satellite imagery for cross verification of photograph location/bearing and turn lane markings

## Process
- Two mappers can work on one city together and update the spreadsheet with their names, start and end time
- Divide the city into half based on a road/landmark and work at different parts of the city to avoid conflict
- The number of already mapped turn restrictions is given in the spreadsheet. Use the Overpass queries given in the [spreadsheet](https://docs.google.com/spreadsheets/d/1rytOtAMau3HVuiCHu61Nv-doug_hxl1-uGc4lkrTH2c/edit#gid=459496498) to get the edit count after a city is completed

### JOSM Setup

- **Plugins:**

 - [Mapillary plugin](http://blog.mapillary.com/update/2015/06/25/josm-mapillary.html)
 - [Turn-Restriction plugin](http://wiki.openstreetmap.org/wiki/JOSM/Plugins/Turnrestrictions)

- **Paint Styles**

 - [Traffic Signs](https://raw.githubusercontent.com/species/josm-preset-traffic_sign_direction/master/direction.mapcss) : JOSM Preferences -> Map Settings -> traffic signs

**Changeset Comment:** 
`Updating turn restrictions in CITYNAME using Mapillary imagery https://github.com/mapbox/mapping/issues/213`

**Source:**  `Bing/Mapillary`

-----

## Daily Stats:

|     Date     |  City  | Reviewed | Before  | After | Added Turn Restrictions* |
|:------------:|:------:|:--------:|:-------:|:-----:|:-----:|
| 21 July 2016 | Ottawa |    111   |   450   |  476  |   26  |
| 25 July 2016 | Ottawa |    229   |   476   |  489  |   13  |
|  | Toronto |       |   1129   |  1140  |   11  |
|  | Vancouver |       |   441   |  471  |   30  |
|  | Montreal |       |   372   |  385  |   13  |
|  | Calgary |       |   64   |  73  |   9  |
| 26 July 2016 | Ottawa |    138   |   489   |  503  |   14  |
|  | Toronto |       |   1140   |  1148  |   8  |
|  | Vancouver |       |   471   |  477  |   6  |
|  | Montreal |       |   385   |  409  |   24  |
| 27 July 2016 | Ottawa |    118   |   503   |  521  |   18  |
|  | Toronto |       |   1148   |  1160  |   12  |
|  | Vancouver |       |   477   |  488  |   11  |
|  | Montreal |       |   409   |  424  |   15  |
| 28 July 2016 | Ottawa |    166   |   521   |  548  |   17  |
|  | Toronto |       |   1160   |  1166  |   6  |
|  | Vancouver |       |   488   |  488  |   0  |
|  | Montreal |       |   424   |  428  |   4  |
| 01 August 2016 | Ottawa |    230   |   548   |  571  |   23  |
|  | Toronto |       |   1166   |  1206  |   40  |
|  | Vancouver |       |   488   |  510  |   22  |
|  | Montreal |       |   428   |  430  |   2  |
| 02 August 2016 | Ottawa |    348   |   571   |  616  |   45  |
|  | Toronto |       |   1206   |  1222  |   16  |
|  | Vancouver |       |   510   |  557  |   47  |
| 03 August 2016 | Ottawa |    262   |   616   |  642 |   26  |
|  | Toronto |       |   1222   |  1247  |   25  |
|  | Vancouver |       |   557   |  561  |   4  |
| 04 August 2016 | Toronto |    393   |   1247   |  1293  |   46  |
| 05 August 2016 | **Toronto** |    393   |   1293   |  **1332**  |   **49**  |
|  |  |       |      |  **Total**  |   **582** *  |
* Note: The number of added turn turn restrictions includes modified(all versions) turn restrictions as well along with the newly mapped.

**Comment by geohacker** [comment]
🚗 🍁

**Comment by krishnanammala** [comment]
I came across this [issue](https://www.openstreetmap.org/edit?editor=id#map=19/45.34817/-75.80335) where the mapillary signage showing `no_u_turn` and it should be added via way instead of node. For this cases we should work in JOSM to add this kind of restrictions. It would be nice to have this feature in `iD` as well.

![screen shot 2016-07-21 at 3 18 44 pm](https://cloud.githubusercontent.com/assets/17470597/17020314/7de9f878-4f5e-11e6-9af9-bd9eb21edf05.png)

cc @planemad @bhousel

**Comment by planemad** [comment]
Came across this sign which I interpreted as no left turn on red or no free left. This is not a turn restriction.

<img width="148" alt="screenshot 2016-07-20 17 37 58" src="https://cloud.githubusercontent.com/assets/126868/17020948/2541dc14-4f62-11e6-98c1-789a7593c906.png">

**Comment by manoharuss** [comment]
The road signage detected in the Mapillary images are represented in [Navigation map](http://mapbox.github.io/osm-navigation-map/#18.66/45.36880/-75.70067/-12.3) using small green colour circles/dots. These are only visible beyond zoom level 14.

The green circular dots are too small and the colour is not easily distinguishable against Mapillary path background to spot easily when mapping to review. This is [captured here](https://github.com/mapbox/osm-navigation-map/issues/33) in the [OSM Navigation map repository.](https://github.com/mapbox/osm-navigation-map)

cc @poornibadrinath @planemad

**Comment by poornibadrinath** [comment]
Mapillary has an efficient tool in iD that displays the restriction detected. 
![image](https://cloud.githubusercontent.com/assets/17887418/17021728/6b9fde9a-4f67-11e6-9f69-084d54624ccd.png) 
It will help in filtering out the mapillary image with the restriction in iD editor and also know which restriction has been detected. 

Here's how activate the tool: 
![traffic overlay mapillary](https://cloud.githubusercontent.com/assets/17887418/17021782/d2e6af34-4f67-11e6-848f-9609fa008612.gif)

**Comment by bhousel** [comment]
> For this cases we should work in JOSM to add this kind of restrictions. It would be nice to have this feature in iD as well.

Yes, having turn restrictions via way in iD would be really useful..  We have an issue for it:
https://github.com/openstreetmap/iD/issues/2346

**Comment by manoharuss** [comment]
### Trial run for Ottawa using iD
**Summary**
- Reviewers: 4 (@poornibadrinath @maanyaumashaanker @krishnanammala @manoharuss)
- Mapillary restrictions reviewed: 111
- Missing turn restrictions added: **26**
- Time: 3 hours

**What worked well**
- Good Mapillary coverage for Ottawa. Most detected restrictions were already on OSM.
- [Mapillary data layer in iD](https://github.com/mapbox/mapping/issues/213#issuecomment-234232373) is very helpful to identify restrictions detected in specific mapillary images.

**Pain points**
- iD editor does not support adding no_u_turn restriction via way instead of node. Need to use JOSM for this.
- Adding conditional restrictions in iD requires editing the tags manually, just like JOSM.
- It is not possible to see the capture date of the mapillary image in both the Navigation map and iD editor in cases when more than one mapillary path exist on the road. JOSM conquers here.
- Mapping in iD editor along with the Navigation map requires switching between 3 tabs to map, 2 tabs to see the full image to orient to the location, where as with JOSM it is all baked in when opened from the Navigation map.

**Other observations**
- Sudden increase in detected restrictions in the evening corresponding with new Mapillary website launch.

cc @planemad @maning

**Comment by ramyaragupathy** [comment]
Since mapillary turn restrictions layer is not loading/taking a long time to load in my browser, I'm sticking to iD editor to find out mapillary turn restrictions. Also while doing this, I'm using the [gpx](http://www.aarondennis.org/geojson-to-gpx/) of the [boundary file](https://github.com/mapbox/mapping/tree/master/worldcities) so that I don't get lost outside the city boundary.
![image](https://cloud.githubusercontent.com/assets/12103383/17098857/3d8f040e-5282-11e6-849a-238e018a0920.png)

**Comment by srividyacb** [comment]
**Conditional turn-restriction written in French:** 
These board means `Monday-Friday`. [Source for translation](https://en.wikipedia.org/wiki/Names_of_the_days_of_the_week) in case anyone sees any other days of the week written in French.

![image](https://cloud.githubusercontent.com/assets/3423533/17099837/80c9cb04-5288-11e6-89e5-39ee02aedbd7.png)

**Comment by srividyacb** [comment]
**Instructions in french below the turn-restriction sign:** 💭 


![image](https://cloud.githubusercontent.com/assets/3423533/17100653/7af28680-528d-11e6-8cf7-68b4b363d8c6.png)

**Comment by srividyacb** [comment]
What are the usual instructions below turn-restrictions like these? The maximum words we can predict on the board is `Except Vehicles ?` 

![image](https://cloud.githubusercontent.com/assets/3423533/17101573/035ec718-5293-11e6-9557-b45e4487d04f.png)

**Comment by Peuc** [comment]
"Attendre la flèche pour virer à gauche" is not a turn restriction. It warns drivers who turn left to wait for their light with an arrow to appear green
The "Excepté véhicules autorisés" sign means the u-turn restriction doesn't apply to explicitely authorized vehicules.

**Comment by scruss** [comment]
You've got that Quebec is all *no right turn on red*, yes?

**Comment by Peuc** [comment]
Québec is NOT all *no right turn on red*. Only Montréal island is.

**Comment by srividyacb** [comment]
Is this turn-lanes or turn-restriction with condition for weekdays? ([Link to full size image](https://www.mapillary.com/app/?focus=photo&pKey=cMB64kF7LK0Hjg2Kz90YuQ))

![image](https://cloud.githubusercontent.com/assets/3423533/17128104/2ad9e1ac-5328-11e6-9582-4088775b0bda.png)
(*This is the best image of this sign board*)

**Comment by bsrinivasa** [comment]
Encountered this case while mapping turn-restrictions at Vancouver. There are a set of detected images of a junction from Mapillary which have been geo located at regular intervals (spacing) for a longer span and has no effect on the image frame with respect to distance. All images represent the same junction at various time intervals. Here are few screenshots to depict the above case.

  
![screen shot 2016-07-25 at 4 53 50 pm copy](https://cloud.githubusercontent.com/assets/17143802/17129380/5be19486-5330-11e6-893e-3a86342b9b1d.png)

![screen shot 2016-07-25 at 4 54 06 pm](https://cloud.githubusercontent.com/assets/17143802/17129396/8148b416-5330-11e6-8912-b0ff95f535c1.png)  

![screen shot 2016-07-25 at 4 54 28 pm](https://cloud.githubusercontent.com/assets/17143802/17129454/d88d3440-5330-11e6-833a-6990010d2787.png)

**Comment by maanyaumashaanker** [comment]
![screen shot 2016-07-26 at 1 12 25 pm](https://cloud.githubusercontent.com/assets/19161907/17129801/bdd462de-5332-11e6-80ae-e3c25ba02c84.png)

there seems to be an offset in the mapillary restriction as represented in the above image. The point in blue actually corresponds to the TR before it(the green one). This offset could lead to adding wrong turn restrictions. (In this case a no right turn from Sheppard Avenue to Grand Marshall drive but on inspecting the mapillary image closely that is not the case). It would be great if it could be fixed.

**Comment by oini** [comment]
While adding turn restrictions in Ottawa came across the following issues where I'd appreciate some feedback as to what would be the ideal way to address them.

- **Unnecessarily complicated tracing of roads and junctions**

![image](https://cloud.githubusercontent.com/assets/1933377/17132562/f3be8c46-533f-11e6-9ee3-12e8bcd64866.png)

The [secondary link](http://www.openstreetmap.org/way/219032015) here is unnecessary as there is no physical divider between the secondary road and the link. This looks like a normal oneway secondary road with 4 lanes and the junction could be just one small bi-directional link. Is it okay to clear such areas up and re-trace the roads?

- **Logically Invalid Turn Restrictions**

![image](https://cloud.githubusercontent.com/assets/1933377/17132633/3aa1f63e-5340-11e6-9d64-be11cbc87638.png)

The [no-straight-on turn restriction](http://www.openstreetmap.org/relation/3809341) added here seems logically inaccurate as this is resulting in OSRM to compute the below route. Note that this route is in fact inaccurate since there is a 'no-left-turn' restriction from south-bound Woodroffe Avenue to the service road.

![image](https://cloud.githubusercontent.com/assets/1933377/17132823/0f45cbae-5341-11e6-89d6-46d68a4f1271.png)

Also, none of the Mapillary images in that junction account for this turn restriction. I have left a [changeset comment requesting confirmation](https://www.openstreetmap.org/changeset/22841381).

**Comment by Peuc** [comment]
@srividyacb : Arrow with green circle means all drivers (no matter the line they are on) must follow this/these direction(s) at the intersection. The text at the bottom gives the application time frame.

The first sign says all drivers coming from "54ème Rue" must turn right on "Boulevard Pie IX" from monday to friday (readable) in the given (unreadable) time frames.

The second sign means all drivers from "51ème Rue" must turn right on "Boulevard Pie IX" from monday to friday (readable) in the given (unreadable) time frames.

By the way, it seems there is a rather important offset in the geolocation of the Mapillary images.

**Comment by srividyacb** [comment]
Thank you @Peuc for confirmation. 😄 

So turns like this with green circle means only-direction-turns (`only-right-turn`/`only-left-turn`) 👍. We are updating things like this in our [wiki](https://github.com/mapbox/mapping/wiki/Mapping-guide-for-adding-turn-restrictions-using-Mapillary) for future reference. 

cc @jinalfoflia @planemad @mapbox/india-office

**Comment by poornibadrinath** [comment]
Out of the five cities we targeted, we have completed Calgary and the other four cities are work in progress. Daily stats are being updated in the [main comment](https://github.com/mapbox/mapping/issues/213#issue-166595667).

/cc: @mapbox/team-data

**Comment by james2432** [comment]
@oini Seems someone that is inexperienced edited the Carling/Woodruff intersection. That part of town has a lot of invalid things like that and need to be corrected

**Comment by oini** [comment]
Any idea what this turn restriction implies?

![image](https://cloud.githubusercontent.com/assets/1933377/17214266/b4afd372-54f5-11e6-8e72-ef69b9f917d3.png)

**Comment by james2432** [comment]
@oini No left turns at baseline road (I imagine its the next intersection)

**Comment by oini** [comment]
Oh, right! Thank you so much @Bootprint1 and @james2432

**Comment by poornibadrinath** [comment]
Task update: Calgary and Montreal are completed 🎉  💥 . Targeting to finish Toronto, Vancouver and Ottawa in the coming week.

**Comment by srividyacb** [comment]
Is this turn-restriction saying `no-right-turn On Red` ? [Full size image](https://d1cuyjsrcm0gby.cloudfront.net/drPaP4xBPkac2Sdsz9RjFg/thumb-2048.jpg)

![image](https://cloud.githubusercontent.com/assets/3423533/17319622/7855c264-58ac-11e6-9cae-5f046944a4b8.png)

**Comment by andrewpmk** [comment]
This is "No Right Turn at Camosun" (I presume that Camosun is the name of a road).

**Comment by srividyacb** [comment]
@andrewpmk Yeah right. Seeing [Camosun Street](https://www.openstreetmap.org/way/159736216/history#map=19/49.23515/-123.19668) joining the main highway. Adding turn-restriction to it. Thank you very much.

**Comment by poornibadrinath** [comment]
![image](https://cloud.githubusercontent.com/assets/17887418/17329099/abc89cb6-58de-11e6-8d6b-13e085583d6e.png)
So this no left restriction board is placed on Dundas Street. 

![screenshot 2016-08-02 18 36 52](https://cloud.githubusercontent.com/assets/17887418/17329528/a4034074-58e0-11e6-936c-244ab81d38e2.png)

Just wanted to confirm whether this restriction is for no left from Dundas Street to Beamish street (because Beamish Street is on the right side) or is it for Beamish Street to Dundas Street, or for Bloor to Beamish street since all three are different streets. 

This is the [restriction point](http://mapbox.github.io/osm-navigation-map/#19.01/43.64115/-79.53568) that is detected.

**Comment by james2432** [comment]
I think they are warning ppl they cant cut through beamish if they want to turn left on bloor street, because you cant turn left on beamish and bloor, you can only turn right

**Comment by krishnanammala** [comment]
Any Idea on what this Turn Restriction implies?

![screen shot 2016-08-02 at 6 48 13 pm](https://cloud.githubusercontent.com/assets/17470597/17329782/bbfb2470-58e1-11e6-866f-e2d4e9717be0.png)

**Comment by poornibadrinath** [comment]
@james2432, so this restriction is for Bloor Street from Beamish Street?

**Comment by james2432** [comment]
Would seem so I interpret it as people often try taking beamish street to turn left on bloor, but can't and get pissed off. This sign seems to be a warning that there are only right turns at beamish and bloor. So if people want to do so continue on dundas for a street that will allow it

**Comment by poornibadrinath** [comment]
@james2432 Thank you so much for the help! Will add the restriction.

**Comment by poornibadrinath** [comment]
Turn restriction task update: Out of the five cities, we have only Toronto left to finish adding turn restrictions. The other four cities: Montreal, Vancouver, Calgary and Ottawa are completed 🎉  The stats are being updated in the [OP](https://github.com/mapbox/mapping/issues/213#issue-166595667)

**Comment by CloCkWeRX** [comment]
One plugin for JOSM that may help highlight areas of interest is the improve-osm tools. Combined with mapillary photos, it would likely call out areas where road signs may not have been detected, but traffic patterns suggest there is a restriction.

See http://www.openstreetmap.org/user/mvexel/diary/37571 for a bit more detail.

**Comment by poornibadrinath** [comment]
Turn restriction task update: Adding turn restrictions in five priority cities of Canada (Toronto, Ottawa, Montreal, Vancouver, Calgary) is now complete! 🎉  We are now validating the turn restrictions we added during the sprint. Stats are updated in the [OP](https://github.com/mapbox/mapping/issues/213#issue-166595667)

**Comment by shvrm** [comment]
@gundersen - We added a total of 379 turn restrictions, and modified/improved 29 turn-restrictions as a team. Between the community and us, we contributed a total of 423 turn restrictions in five cities in Canada. 

Here is a detailed breakdown.

Table 1: Breakdown of turn restrictions between Mapbox and Community


|    City   | Turn restrictions Version 1(Newly added) | Modified/improved (Version 2) |
|:---------:|:----------------------------------------:|:-----------------------------------------------:|
|  Toronto  |        Mapbox : 90 ; Community : 18        |            Mapbox : 5 ; Community : 12           |
|   Ottawa  |         Mapbox : 94 ; Community : 3        |            Mapbox : 6 ; Community : 1           |
|  Montreal |        Mapbox : 95 ; Community : 38        |           Mapbox : 9 ; Community : 7           |
| Vancouver |         Mapbox : 83 ; Community : 0        |            Mapbox : 8 ; Community : 1            |
|  Calgary  |         Mapbox : 2 ; Community : 0         |             Mapbox : 1 ; Community : 2            |
|   **Total**   |        Mapbox : 364 ; Community : 59       |            Mapbox : 29 ; Community : 21          |

**Note:** Version 2 is when we modify/improve already existing mapped turn restrictions.

Table 2: Total brand new turn restrictions created during the project (No version 2)

|    City   | Total adding during this project both by community and Mapbox |
|:---------:|:-------------------------------------------------------------:|
|  Toronto  |                              108                              |
|   Ottawa  |                               97                              |
|  Montreal |                              133                              |
| Vancouver |                               83                              |
|  Calgary  |                               2                               |
|   Total   |                              423                              |


cc: @manoharuss

**Comment by poornibadrinath** [comment]
Adding turn restrictions in Canada is completed in all priority cities. The team and community together have added **423** turn restrictions. :clap: :tada: The stats for individual cities are:

|    City   | Total adding during this project both by community and Mapbox |
|:---------:|:-------------------------------------------------------------:|
|  Toronto  |                              108                              |
|   Ottawa  |                               97                              |
|  Montreal |                              133                              |
| Vancouver |                               83                              |
|  Calgary  |                               2                               |
|   Total   |                              423                              |

Detailed stats for all the turn restrictions we added can be found [here](https://github.com/mapbox/mapping/issues/213#issuecomment-238587320)

Also, we have completed validating all the turn restrictions added in five cities. It would be helpful to have the community look into our edits and let us know if there are any errors that we could rectify. There is a neat tool, [restriction validator](http://restrictions.morbz.de/), which shows all the restrictions added, highlighting which ones are incorrect/correct. 

It was great to have the community working alongside us in adding turn restrictions, clearing doubts, improving our workflow and suggesting better ways to add restrictions in Canada. We hope the support would continue in our next task of adding [exits and destinations](https://github.com/mapbox/mapping/issues/220) for all the major highways in the five priority cities of Canada.

/cc: @mapbox/team-data

**Comment by poornibadrinath** [comment]
Closing #213 🚀
