### ISSUE TITLE
Workflow is confusing, and requires multiple website edits

### ISSUE THREAD

**Issue by scruss** [mapbox/mapping#215]
Please provide these errors as proper [Notes](https://wiki.openstreetmap.org/wiki/Notes "Notes") on the OSM map itself so **all** editors can see them. Also, having your error nodes/ways as a WMS or an iD layer or whatever will work on the OSM website for everyone would be ideal.

As it stands, leaving comments on github needs a github account, so the way it's set up now, it kinda feels like we're doing Mapbox's work for you.

**Comment by maning** [comment]
@scruss, thank you for your feedback.  We do have a couple of ongoing projects, can you specify which one you find confusing?  We will review the workflow/tools if necessary.

**Comment by scruss** [comment]
This one: [Adding turn restrictions in Canada using Mapillary · Issue #213 · mapbox/mapping](https://github.com/mapbox/mapping/issues/213 "Adding turn restrictions in Canada using Mapillary · Issue #213 · mapbox/mapping")

With Mapbox's process, you have to:

1. Find the restriction on mapbox's site;
2. Make the edit on OSM;
3. Mark the change as done on mapbox's site;
4. Discuss any changes on github, which requires a github account
   and takes OSM change discussion away from OSM servers onto 
   a third party.

OSM already has the tools to handle this:

1. Drop Map Notes at the contested turn restrictions;
2. Provide a WMS or other iD/josm compatible imagery layer if need be.

**Comment by jinalfoflia** [comment]
@scruss thank you for the suggestions. 

> Drop Map Notes at the contested turn restrictions;

- We make sure that we add notes and [comment on the changesets](https://www.openstreetmap.org/changeset/22841381) when we have doubts regarding a turn restriction or a feature. 
- The reason for not using notes for identifying turn restrictions is that the [images are not supported ](https://github.com/openstreetmap/openstreetmap-website/issues/1257) in notes, and it becomes difficult for anyone in the community to search for particular restriction that we have questions for.

> Provide a WMS or other iD/josm compatible imagery layer if need be.

We are currently integrating various external layers into the map and it's not possible to create a single layer in JOSM. For more details please have a look at [this.](https://github.com/mapbox/osm-navigation-map/issues/36)

/cc @planemad @maning
