### ISSUE TITLE
Mapping project for consideration: investigate DeepOSM potential errors

### ISSUE THREAD

**Issue by CloCkWeRX** [mapbox/mapping#217]
http://www.deeposm.org/ is an effort by @andrewljohnson and co to identify potential mapping errors.
It seems to pick up quite a few possible problems, given the lower quality tiger data in some areas.

A concerted effort from skilled mappers would likely provide very good feedback to the model for certain areas in the US.
Those error in turn could then be regularly fed into http://osmlab.github.io/to-fix/ or similar as well, probably without too much effort.

Given mapbox has facilitated access to the imagery this model was trained on, the possibility of scaling it to other similar areas is there for the longer term without too many barriers.

**Comment by maning** [comment]
@CloCkWeRX thanks for this info.  We will discuss with team.  Closing for now.
