### ISSUE TITLE
Mapping project for consideration: investigate ImproveOSM.org missing road errors in the US

### ISSUE THREAD

**Issue by CloCkWeRX** [mapbox/mapping#218]
http://improve-osm.org/ is an effort by Telenav to detect potentially missing roads from GPS data (as well as turn restrictions or one way travel).

I've spent the last few months slowly working through the US, Ireland, Spain, & France - it regularly and accurately detects a range of issues like:
 * New residential property developments that have been completed (US, in particular Florida)
 * New industrial property developments (wind farms galore!)
 * Minor/unclassified roads
 * Industrial roads (quarries, service roads around warehouses, etc)
 * Misaligned road data, such as TIGER

In particular, because these areas are detected by GPS trace density; the errors detected often indicate a well used road over less important, infrequently travelled errors.

While my efforts have been fairly solid over the last period; this is well suited for a larger team based approach with an interest in larger US cities, as some of your other work has been focused on.

**Comment by planemad** [comment]
Thats a great suggestion @CloCkWeRX! We'll add it to our queue of upcoming projects.

cc @Rub21 @mikelmaron
