### ISSUE TITLE
Mapping exit numbers and destinations in Canada

### ISSUE THREAD

**Issue by manoharuss** [mapbox/mapping#220]
In an effort to make OpenStreetMap more navigable and accurate in guidance, we have previously worked on [adding turn restrictions in Canada.](https://github.com/mapbox/mapping/issues/213) We are now focussing on adding missing exit numbers and destinations in these 5 Cities of Canada:

1. Ottawa
2. Toronto
3. Vancouver
4. Montreal
5. Calgary

![file-page1 2](https://cloud.githubusercontent.com/assets/8921295/17512901/b0b6c19e-5e47-11e6-9551-ae9e3fbc750a.jpg)

**Features to map:** Highway Exit Numbers and Destinations

**Estimated features to map:** To be calculated

**Estimated time to map:** To be calculated

**Sources:** We are only using [Mapillary](https://www.mapillary.com/) as the source to refer exit numbers and destinations.

### Mapping Workflow

**Tasking Manager**: **[Task Link](http://cfn-tasking-manager-staging-vpc-387856624.us-east-1.elb.amazonaws.com/project/20)**

In tandem with tasking manager, we are using [k1wiosm's](https://github.com/k1wiosm) [Checkautopista2 tool](http://k1wiosm.github.io/checkautopista2/?lat=52.4962&lon=-88.7256&z=5) to map on each highway in the cities mentioned above. To understand how to use Checkautopista2 tool to map exit numbers and destinations, please refer to the [detailed workflow guide here](https://gist.github.com/manoharuss/3a1b4f640aaf2c052365fcb1ddb09beb). 

* Mark the highway as  **DONE** if it has been completely mapped and if the resources to map the highway are not sufficient, comment on the task stating the reason: **No resources/ No Mapillary coverage.** 

  
**JOSM Filters:**
 These below filters can be used to ease work in JOSM editor.

* Filter out non road features with `boundary: | leisure: | landuse: | waterway: | amenity: | natural: | building:`

* Add inverse filter: `highway=motorway | motorway_link | trunk| trunk_link | primary | secondary | tertiary`

**Changeset comment and source:**
 * **Comment** ---> ` Adding missing exit and destination tags in CITYNAME #https://github.com/mapbox/mapping/issues/220`
 * **Source**  ---> `Bing; Mapillary`

cc @mapbox/team-data

**Comment by andrewpmk** [comment]
You may want to use OpenStreetView (http://openstreetview.com/) as well.

**Comment by manoharuss** [comment]
We have finished mapping exit numbers and destinations in all the priority cities. The stats for individual cities are:


|    City   | ref tags to the junction nodes |  destinations to the ways | destination:streets to ways | destination:refs to ways |
|:---------:|:------------------------------:|:-------------------------:|:---------------------------:|:------------------------:|
|  Toronto  |     Mapbox: 71 Community: 2    |  Mapbox: 21 Community: 6  |   Mapbox 206 Community: 0   |  Mapbox: 49 Community: 1 |
| Vancouver |     Mapbox 2 Community: 48     |  Mapbox: 19 Community: 9  |    Mapbox: 6 Community: 6   |  Mapbox: 5 Community: 96 |
|   Ottawa  |     Mapbox: 0 Community: 3     |   Mapbox: 5 Community: 0  |    Mapbox: 4 Community: 0   |  Mapbox: 3 Community: 0  |
|  Montreal |     Mapbox: 61 Community: 5    |  Mapbox: 37 Community: 1  |   Mapbox: 26 Community: 0   |  Mapbox: 24 Community: 0 |
|  Calgary  |     Mapbox: 5 Community: 0     |  Mapbox: 18 Community: 0  |   Mapbox: 29 Community: 0   |  Mapbox: 3 Community: 0  |
|   Total   |    Mapbox: 139 Community: 58   | Mapbox: 100 Community: 16 |   Mapbox: 271 Community: 6  | Mapbox: 84 Community: 97 |
|  Together |               197              |            116            |             277             |            181           |



**Summary:**

- We were able to map extensively in Toronto as it had very good Mapillary coverage. 

- Community participated and mapped more than us in Vancouver. :rocket: 

- Ottawa was very well mapped before we jumped in, thereby allowing us to validate these exit numbers on Mapillary more than mapping. :sparkles: 

- Montreal and Calgary were mapped lesser due to lack of Mapillary coverage.

The community was very responsive and supportive through the talk-ca mailing list and diary post in clearing our doubts and working alongside us during this mapping sprint. We thank the community for working together and hope that the support continues as we continue Navigational mapping in Canada as Mapillary or OpenStreetView coverage increases as we move forward. :tada: 

/cc: @mapbox/team-data

**Comment by poornibadrinath** [comment]
No next actions here. Closing 🚀
