### ISSUE TITLE
Fixing broken multipolygons

### ISSUE THREAD

**Issue by Andygol** [mapbox/mapping#222]
OSM data consists of objects of different types. One of these types are multipolygons. (See more details http://wiki.openstreetmap.org/wiki/Relation:multipolygon)

Sometimes the data contains errors. It may be improperly placed tags and sometimes errors in the topology of the objects. They all lead to incorrect representation of features details for the data consumer or to a lack of objects on the map.

![̛](https://cloud.githubusercontent.com/assets/126868/15822611/6ca5eec2-2c14-11e6-8894-ff3913dca4ae.png)

Objects formed using Multipolygons can be easily damaged by users during editing. As a result of the Data Team research a large number of such objects was found. See [link](https://gist.github.com/e2fdb6d35b156ba2af29f53f585d8288)

To help debug broken multipolygons, we have a map tool that can be used to check if its one of the bad ones and the location of the issues: http://osmlab.github.io/fixing-polygons-in-osm/map/

**Goal**: to fix corrupted multipolygons

**Estimated features to fix**: 2917

**Estimated time to fix**: To be calculated

**Sources**: [Spreadsheet](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1986415453), Bing, experiences, local knowledge, http://osmlab.github.io/fixing-polygons-in-osm/map/

To work with Multipolygons best to use [JOSM](https://josm.openstreetmap.de/) with plugins:
- [Relation Toolbox](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/Relation_Toolbox) - help to work with multipolygons
- [UtilsPlugin2](https://josm.openstreetmap.de/wiki/Help/Plugin/UtilsPlugin2) (see [wiki ](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/utilsplugin2) osm) - provide a lot of useful tools.
-  [DownloadAlong](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/DownloadAlong) - Downloads data and raw GPS data along one or more ways
- [GeoChat](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/GeoChat) - live chat for coordination with other mappers
#### Setup
- Add Layers in JOSM:
  - **OSMInspector Areas WMS** (_Enter URL > GET Layers > Select Geofabrik Tools > Image format: png_) - `http://tools.geofabrik.de/osmi/view/areas/wxs?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities`
  - **mapbox-streets** - `tms[99]:https://api.mapbox.com/v4/mapbox.streets/{zoom}/{x}/{y}.png?access_token=pk.eyJ1IjoicHJhdGlreWFkYXYiLCJhIjoiMTA2YWUxNjRkNmFmZGQ4YzAxZWFiNDk0NDM1YjE1YjAifQ.4P6N5dNmA_WQXd3BsJvu5w`
  
  ![](https://cloud.githubusercontent.com/assets/369696/17661881/86e6aea4-62ea-11e6-924e-26162cc7cc20.png)
  _\* Adding WMS Layer_
- Install plugins
#### Instruction
1. Choose broken multipolygon from the [spreadsheet](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1986415453)
2. Download it into JOSM. For manual downloading use menu `File`->`Download Object…` <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>O</kbd> (<kbd>⌘</kbd>+<kbd>⇧</kbd>+<kbd>O</kbd>)

![](https://cloud.githubusercontent.com/assets/369696/17587292/028c83f8-5fd0-11e6-8e14-882f1d28edb6.png)
1. Find a place with a problem
   ![ring not closed](https://cloud.githubusercontent.com/assets/369696/17661060/84d82214-62e5-11e6-8a3f-5dc9772398fa.png)
2. Download the data around it to avoid possible damage of data during the repair process <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>↓</kbd> (<kbd>⌘</kbd>+<kbd>⇧</kbd>+<kbd>↓</kbd>)
3. Open relation in the Relation editor. Find the gaps and missing roles
   ![](https://cloud.githubusercontent.com/assets/369696/17662470/57324052-62ee-11e6-86f1-d87164b547bd.png)
4. Fix the multipolygon, adding the missing segments or removing unnecessary ones
5. As a result, you'll have closed inner and outer loops of the multipolygon
   ![](https://cloud.githubusercontent.com/assets/369696/17662651/b577e21a-62ef-11e6-8e5f-563664ef7a36.png)
6. Run Validation to check your edits <kbd>Shift</kbd>+<kbd>V</kbd> (<kbd>⇧</kbd>+<kbd>V</kbd>)
7. If needed repeat steps 5 - 8
#### What to fix
- touching rings
- selfintersections
- unclosed ways

In case of old style tagging - put tags on the multipolygon instead it members

**Changeset comment and source:**
- **Comment** ---> `Fixed broken multipolygon #https://github.com/mapbox/mapping/issues/222`
- **Source**  ---> `Bing; OSMInspector`

@mapbox/team-data

**Comment by chtnha** [comment]
Today (08/23) the @mapbox/team-data has fixed  **180**  invalid relations. Most of the relations in the [spreadsheet](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1986415453) are actually fixable. The overview of the stats are here. 
				
| Fixed issues | No error  | rendering  | won't fix | Grand total |
| ------------- |:----------:| -----:|:------|------:|
| 125    |4| 17 |34|180|

**Comment by bsrinivasa** [comment]
On 24th and 26th of August, @mapbox/team-data has fixed 176 broken relations. Relations with tags `water`, `waterway` and `wetland` have been completely fixed along with relations containing more than 200 members with various tags. 

| Fixed issues | No error  | rendering  | won't fix | Grand total |
| -------------:|----------:| -----:|------:|------:|
| 156    |0| 10 |11|176|

#### Next actions
 Few of the members from the team will continue to fix the remaining invalid relations from the [spreadsheet](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1986415453) on Monday(29th August).

**Comment by bsrinivasa** [comment]
The team has fixed 116 and has reviewd 147  broken relations for the day. Most of the relations with more than 100 members have been fixed so far. The statistics for the day is as tabulated below.

| Fixed issues | No error  | rendering  | Won't fix | Grand total |
|:-------------:|:----------:|:-----:|:------:|:------:|
| 116    |0| 3 |26|147|

#### Next actions
 @batpad will be generating a new list of broken relations. Few of the members from the team will continue to fix the remaining invalid relations tomorrow from the [spreadsheet](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1986415453) using the same workflow.

**Comment by bsrinivasa** [comment]
Today, @mapbox/team-data has reviewed 65 invalid relations out of which 49 of them have been fixed. All relations consisting of more than 100 members have been fixed as of today. The statistics for the day has been tabulated below.

| Fixed issues | No error  | rendering  | Won't fix | Grand total |
|:-------------:|:----------:|:-----:|:------:|:------:|
| 49    |0| 1 |15|65|

#### Next actions
The significant relations which were broken/invalid which includes `water`, `waterway`, `wetland`, `wood` and huge `boundaries` have been fixed. 
@batpad will be generating a new list of broken relations and the priorities will be based on the newly generated list.

**Comment by gundersen** [comment]
Great framing on this progress @bsrinivasa, it's really helpful to see the context in addition to the table break down of numbers.

**Comment by bsrinivasa** [comment]
Today, few from @mapbox/team-data has reviewed 71 invalid relations out of which 61 of them have been fixed. @batpad has generated an updated`GeoJSON` which contains numerous invalid/broken relations that failed to render in Mapbox Streets layer. A list of these has been generated and has been classified in the [spreadsheet](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1440256161). The statistics on the daily progress of reviewing these has been tabulated below.

| Fixed issues | No error  | rendering  | Won't fix | Grand total |
|:-------------:|:----------:|:-----:|:------:|:------:|
| 60   |0| 2|9|71|

#### Next actions
Few members of the team will focus fixing relations from the freshly prepared list in the spreadsheet prioritising the features including water (tag: `natural=water`) tomorrow. 

Here is the [spreadsheet](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1440256161) that has the lists of invalid / broken relations and the detailed statistics

**Comment by oini** [comment]
[Relation 362725](http://www.openstreetmap.org/relation/362725) is broken due to being unclosed. There were earlier attempts made by our team to fix this as can been seen in the earlier spreadsheet as well as the history of the relation and various of it's components, especially the point where the ring is unclosed.

![image](https://cloud.githubusercontent.com/assets/1933377/18340924/3abeb0f6-75c5-11e6-9a66-6bc230bb7208.png)

Unsure why/how this is happening. It would be great to get some clarity on how we can make sure that our fixes actually work and does not cause any further breakage. 

cc @maning @bsrinivasa

**Comment by bsrinivasa** [comment]
### Today's highlights: 
* The team has reviewed 68 relations and fixed 55 out of them
* All 66 invalid/broken relations with tag `natural=water` has been reviewed and most of them are fixed

| Fixed issues | No error  | rendering  | Won't fix | Grand total |
|:-------------:|:----------:|:-----:|:------:|:------:|
| 55  |0| 7|6|68|

### Next actions:
Members with more than 100 members and version numbers greater than 20 have been filtered and 92 relations have been shortlisted. The @mapbox/team-data will be focusing on reviewing these tomorrow.


Here is the updated [spreadsheet](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1440256161) that has the lists of invalid / broken relations and the detailed statistics.

**Comment by bsrinivasa** [comment]
## Today's progress:
* The team has fixed 18 relations out of 30 being reviewed.
* The list was categorised based on relations with more than 100 members and version number higher than 20
* There are 91 invalid/broken relation with above filter out of which 30 has been reviewed for the day
* Per voice with @Andygol, he will be helping out in fixing few of these in the coming week.

 | Fixed issues | Validated| Rendering  | Won't fix | Grand total |
|:-------------:|:----------:|:-----:|:------:|:------:|
| 15 |3| 3|9|30|

## Next actions
The @mapbox/team-data will continue to fix these relations on Monday with the current prioritised list.


Here is the updated [spreadsheet](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1440256161) that has the lists of invalid / broken relations and the detailed statistics.

**Comment by bsrinivasa** [comment]
## Highlights for the day
* Reviewing and fixing broken multi-polygons is now a part of [daily product QA](https://github.com/mapbox/data/issues/2147#issue-176307071) and is addressed by the assigned team for 1 hour every day.
* Today 8 relations have been reviewed out of which 2 have been fixed.

 | Fixed issues | Validated| Rendering  | Won't fix | Grand total |
|:-------------:|:----------:|:-----:|:------:|:------:|
| 2 |0| 2|4|8|


### Next actions
* @Andygol and 4 members from Peru team will be joining the product QA along with 4 members from Bengaluru data team. 
* The @mapbox/team-data will continue to fix these relations with the current prioritised list.

Here is the updated [spreadsheet](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1440256161) that has the lists of invalid / broken relations as well the detailed statistics.

**Comment by bsrinivasa** [comment]
## Progress update

* In the past 2 days, 20 relations have been reviewed out of which 11 have been fixed.

 | Fixed issues | No error| Rendering  | Won't fix | Grand total |
|:-------------:|:----------:|:-----:|:------:|:------:|
| 11  |0| 1 | 8 | 20 |


### Next actions
* Few members from Peru team will start working on fixing from today
* The @mapbox/team-data will continue to fix these relations with the current prioritised list.


Here is the updated [spreadsheet](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1440256161) that has the lists of invalid / broken relations as well the detailed statistics.

**Comment by bsrinivasa** [comment]
## Progress update

- Today @mapbox/team-data has reviewed 146 broken multi-polygons of which 78 have been fixed.
- @mapbox/peru-office has started fixing these broken/invalid relations from today.
- The spreadsheet has been re-filtered for the relations with `members` greater than 25 and `version` higher than 5.
 
 | Fixed issues | No error | Validated  | Won't fix | Grand total |
|:-------------:|:----------:|:-----:|:------:|:------:|
|78 |45| 0|20|143|


### Next actions
- [x] A [new `GeoJSON`](https://gist.github.com/geohacker/6e8b1726cc5579023e6ae7c2a88217c1) of these broken multi-polygons has been generated by @batpad.
- [ ] A new prioritised list of these relations would be prepared by Monday and few members from @mapbox/team-data will spend an hour as part of product QA and continue to fix these relations.

Here is the current [spreadsheet] (https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1440256161) that has the lists of invalid / broken relations as well the detailed statistics.

**Comment by bsrinivasa** [comment]
## Progress update

- The statistic and progress on fixing the broken multi-polygons will be updated weekly.
- A new spreadsheet has been generated which has the prioritised list of broken polygons that needs to fixed.
- The list has been filtered out for all the previously reviewed relation ids, `type=boundary`, relations with `members > 25` and `version number > 25`
 
The total number of broken/invalid relations that has been reviewed in the past week (19th and 23rd September 2016) are as tabulated.
 

| Fixed  | No errors | Won't fix | Grand total |
|:------:|:---------:|:---------:|:-----------:|
|   21   |     12    |     7     |      40     |


### Next actions
- [ ] @batpad to continuously monitor the OSM for broken multi-polygon and facilitate @mapbox/team-data with a better workflow based on classification of errors responsible for these broken multipolygons
- [ ] @bsrinivasa to keep track of the list and update the stats on progress next week


Here is the [spreadsheet] (https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1583883299) that has the prioritised list of invalid / broken relations as well the detailed statistics of each list.

**Comment by bsrinivasa** [comment]
## Progress update

During the past week @mapbox/team-data worked on fixing the broken multi-polygons from the spreadsheet for 2 days as part of product QA.
 
The total number of broken/invalid relations that has been reviewed in the past week (19th and 23rd September 2016) are as tabulated.
 

| Fixed  | No errors |Grand total |
|:------:|:---------:|:-----------:|
|   12   |     6   |     18     |


### Next actions
- [ ] Fixing these broken multipolygons is halted until @mapbox/team-data completes the data priority - [Mapping and Aligning road network in Taiwan](https://github.com/mapbox/mapping/issues/233)
- [ ] @batpad to continuously monitor the OSM for broken multi-polygon and facilitate @mapbox/team-data with a better workflow based on classification of errors responsible for these broken multi-polygons



Here is the [spreadsheet] (https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1583883299) that has the prioritised list of invalid / broken relations as well the detailed statistics of each list.

cc: @maning

**Comment by bsrinivasa** [comment]
All the prioritised multipolygons from the [spreadsheet](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1583883299) have been reviewed and a total of 47 relations were fixed out 91 being reviewed by @mapbox/team-data 

The stats for the previous week's progress (Starting 24th October to 3rd November) are as follows,

| Fixed issues | No error | Validated | Won't fix | Grand total |
| :----------: | :------: | :-------: | :-------: | :---------: |
|      21      |    11    |    10     |    11     |     53      |

The prioritised invalid relations from 3 lists generated have been reviewed, breakdown below:

|                  Lists                   | Reviewed |  Fixed  | Validated | Won't fix | No errors |
| :--------------------------------------: | :------: | :-----: | :-------: | :-------: | :-------: |
| [List 1](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1986415453) |   637    |   498   |    34     |    103    |     2     |
| [List 2](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1440256161) |   296    |   173   |    16     |    54     |    53     |
| [List 3](https://docs.google.com/spreadsheets/d/1wBlckEfTSq4gjQjzMQ5JKMJrP8PjH6ZIaAVwt9pVVms/edit#gid=1583883299) |    91    |   47    |    12     |    11     |    21     |
|                **Total**                 | **1024** | **718** |  **62**   |  **168**  |  **76**   |


![screen shot 2016-11-07 at 9 38 00 am](https://cloud.githubusercontent.com/assets/17143802/20046272/f2106aba-a4cd-11e6-8c2c-cee75535fb48.png)



| Status    | Description                              |
| --------- | ---------------------------------------- |
| Fixed     | Error resolved |
| Validated | Minor errors but doesn't break other data and has no issues with map rendering |
| Won't fix | Possibly administrative boundaries of `type=boundary` and disputed borders which were not reviewed. |
| No errors | No errors exist during the review|


### Common errors we fixed
- Self intersecting rings
- Ring not closed
- Duplicate segments or duplicate nodes
- Issues with sorting and direction of various members involved in the multi polygon relations
- Issues with assigning roles for members
- Improper tagging of the relation which causes issues with rendering on the map

### Few errors being ignored which did not break the relation nor caused issues for map rendering
- Touching rings
- Area tag assigned for inner role

#### Next actions:
 Invalid relations are now flagged in [OSMCHA](https://osmcha.mapbox.com/) tool. These will be filtered out and the priority ones will be fixed.



cc: @planemad @maning @batpad

**Comment by bsrinivasa** [comment]
A list of broken relations for the past 45 days have been prepared in this **[spreadsheet](https://docs.google.com/spreadsheets/d/1mhXhbdUd3QSWYXpEQcPl5KqyALT0weQ2DKaUFsbuYGk/edit#gid=0)**. 

It has been categorised into four categories based on the following tags,
![image](https://cloud.githubusercontent.com/assets/17143802/22871821/9f84c16a-f1da-11e6-9e7c-23ce111bde4a.png)

The list of invalid relations could be prioritised based on the area of the feature and the category it belongs to. 

cc; @mapbox/team-data

**Comment by bsrinivasa** [comment]
The broken multipolygons have been moved to ToFix as tasks under each category. These broken relations would be fixed in ToFix rather than using the above spreadsheet. 

Here are the list of tasks in ToFix.

|              High priority               |               Low priority               |
| :--------------------------------------: | :--------------------------------------: |
| [Waterway broken relations](https://osmlab.github.io/to-fix/#/task/waterwaybrokenrelations) | [Waterway broken relations - low priority](https://osmlab.github.io/to-fix/#/task/waterwaybrokenrelationslowpriority) |
| [Conservation broken relations](https://osmlab.github.io/to-fix/#/task/conservationbrokenrelations) | [Conservation broken relations - low priority](https://osmlab.github.io/to-fix/#/task/conservationbrokenrelationslowpriority) |
| [Vegetation broken relations](https://osmlab.github.io/to-fix/#/task/vegetationbrokenrelations) | [Vegetation broken relations  low priority](https://osmlab.github.io/to-fix/#/task/vegetationbrokenrelationslowpriority) |
| [Miscellaneous broken relations](https://osmlab.github.io/to-fix/#/task/miscellaneousbrokenrelations) | [Miscellaneous broken relations - low priority](https://osmlab.github.io/to-fix/#/task/miscellaneousbrokenrelationslowpriority) |


No next actions here. Closing this.
