### ISSUE TITLE
Your process is broken and needs to be fixed.

### ISSUE THREAD

**Issue by drkludge** [mapbox/mapping#223]
[I submitted an issue against auto-tools/knife.](https://github.com/mapbox/auto-tools/issues/11)  I don't see how you all can move on to another city when there are known issues with your process.  If the problem is not with auto-tools/knife, then when you cut up a way to add lane counts, etc. you will have to add a manual process to carry the relations to the new ways.  Please see the comments on [the Phoenix lane count/turn information](https://github.com/mapbox/mapping/issues/180#issuecomment-240295557).

**Comment by planemad** [comment]
Tracking in #224
