### ISSUE TITLE
Incorrect guidance in wiki: semicolons instead of underscores

### ISSUE THREAD

**Issue by goldfndr** [mapbox/mapping#229]
At [the github wiki's guidance](https://github.com/mapbox/mapping/wiki/Mapping-guide-for-turn-lanes-from-imagery), the four recommendations after "left;right" are "slight;left", "slight;right", "merge;to;left", "merge;to;right". This contrasts with [the OSM wiki](http://wiki.openstreetmap.org/wiki/Key:turn#Values), which has underscores instead of semicolons for these four recommendations.

I think the github wiki's guidance is incorrect and should be changed to use the OSM wiki's values. Furthermore, a check should be performed to see if the incorrect guidance was followed and thus should be corrected.

**Comment by planemad** [comment]
@goldfndr thank you for reporting the typo, have updated the wiki. Checked OSM via overpass, and do not see any occurrences of the incorrect tag http://overpass-turbo.eu/s/ia8 . Everything clean!
