### ISSUE TITLE
Data Team peer review 09/07 - 09/13

### ISSUE THREAD

**Issue by dannykath** [mapbox/mapping#231]
Last peer review ticket: https://github.com/mapbox/mapping/issues/230

#### Mapping projects to be reviewed:

- [To-Fix - Kink major highway](http://osmlab.github.io/to-fix/#/stats/impossibleangle)
- [To-Fix - Kink minor highway](http://osmlab.github.io/to-fix/#/stats/kinksminorhighways)
- [Map all turn restrictions in SF](https://github.com/mapbox/data/issues/2090#issuecomment-241258511)
- Turn Restriction and Exit-Destination Mapping in Frankfurt and Munich 
- [Fixing broken multipolygons](https://github.com/mapbox/mapping/issues/222)

#### Instructions
* Download `.osm` files for last week.
 - [2016/09/07 - 2016/09/13](https://s3.amazonaws.com/mapbox/osm-history-processor/day/latest.osm.tar.gz)

* Extract the tar file and select any OSM file of the team member.
* Each team member will have an .osm file of edits for the last seven days. For example: `latest-andygol.osm`. Select any `.osm` file and open the data in JOSM. 
* If you don't find any osm file of a particular team member, then it means that user has not edited during the week.
* Examine user edits in detail. In JOSM, select a random small area edited by the user and press `3` to zoom.
* Download the latest data in OSM as a new layer and add a filter `Cmd + F` to see only the user's edits, e.g. `user:andygol`.

![andyfilter3](https://cloud.githubusercontent.com/assets/6770741/14813545/cf7409d2-0bbf-11e6-9389-5b6132b7bb55.gif)

* Select a way/node and load the the history (`Ctrl + H`), the changeset comment will describe what specific project the user was working on.
* To get an OSM link to the object, click `Cmd + Shift + H`. 
* Note down any feedback for each user in this ticket or comment directly in the changeset. Use this format:

```
username
changeset link - issue to fix
```

* @krishnanammala @chtnha or @dannykath will post the feedback in the ticket (Use Github handle because OSM name is different from Github name) and make necessary changes on the same day.
* Close the ticket once user's have fixed their edits.

For clarifications, discuss with the @mapbox/team-data in this ticket.

**Comment by dannykath** [comment]
@luiswalter 

#### Crossing ways
https://www.openstreetmap.org/way/62045154

#### Untagged ways
https://www.openstreetmap.org/way/440980107

**Comment by dannykath** [comment]
@yurasi
#### Overlapping highways
https://www.openstreetmap.org/way/442139793

#### Crossing building
https://www.openstreetmap.org/way/442210394

**Comment by dannykath** [comment]
@abhisheksaikia 
#### Add layer 1
https://www.openstreetmap.org/way/240272680

**Comment by dannykath** [comment]
@bsrinivasa 

#### Add layer 1

https://www.openstreetmap.org/way/104698377
https://www.openstreetmap.org/way/104698399
https://www.openstreetmap.org/way/104698362

**Comment by dannykath** [comment]
@samely
#### split way 
https://www.openstreetmap.org/way/56029839
https://www.openstreetmap.org/way/139230458

#### align way 
https://www.openstreetmap.org/way/184127169

**Comment by dannykath** [comment]
@karitotp
#### Split way
https://www.openstreetmap.org/way/207200585

**Comment by dannykath** [comment]
@calfarome
#### align highway
https://www.openstreetmap.org/way/12588005/history

**Comment by dannykath** [comment]
@srividyacb 

#### Unnamed highways 
https://www.openstreetmap.org/way/442003795 - Check around and add the names acording Tiger layer
#### Overlapping ways
https://www.openstreetmap.org/way/442002807

**Comment by dannykath** [comment]
@ridixcr 
#### Overlapping ways
https://www.openstreetmap.org/way/441647652

In this case don't split the way, you should align it
https://www.openstreetmap.org/way/441626509
![split](https://cloud.githubusercontent.com/assets/11504548/18518982/c4b32c64-7a67-11e6-85e0-890a86cab295.png)

In this case you should add `highway:turning_circle`
https://www.openstreetmap.org/way/441670749

**Comment by dannykath** [comment]
@planemad
#### Overlapping ways
https://www.openstreetmap.org/way/441671086 - Check around, some ways also overlap

**Comment by dannykath** [comment]
@maning 
#### Crossing ways 
https://www.openstreetmap.org/node/4398567380/history
https://www.openstreetmap.org/way/260232950/history
https://www.openstreetmap.org/way/373404711/history
https://www.openstreetmap.org/way/223981401/history

#### Add layer=1
https://www.openstreetmap.org/way/442050853/history
https://www.openstreetmap.org/way/442050854

**Comment by dannykath** [comment]
@RichRico 
#### Crossing ways 
https://www.openstreetmap.org/way/440087366/history
https://www.openstreetmap.org/node/4393803419/history
https://www.openstreetmap.org/way/440145161

**Comment by dannykath** [comment]
@jothirnadh 
Overlapping highways
https://www.openstreetmap.org/way/135247069/history

**Comment by samely** [comment]
Thanks for reviewing team! 

**Split way**
- https://www.openstreetmap.org/changeset/42160326
- It's the same way, I don't need to split

*Align way*
- There's an offset in the whole area, I don't consider correct to align it.

**Comment by dannykath** [comment]
@dannykath

#### Overlapping

https://www.openstreetmap.org/way/386628165

#### Add tag highway

https://www.openstreetmap.org/way/361064853

**Comment by dannykath** [comment]
Thanks for the review team! 
####  Overlapping highways
https://www.openstreetmap.org/changeset/42043389
#### Add tag highway
https://www.openstreetmap.org/changeset/42160456

**Comment by Yurasi** [comment]
Thanks for the review team
#### Overlapping highways
https://www.openstreetmap.org/changeset/42160702

#### Crossing building
https://www.openstreetmap.org/changeset/42160722

**Comment by karitotp** [comment]
Thanks for the review team!

> #### Split way

https://www.openstreetmap.org/changeset/42160792

**Comment by bsrinivasa** [comment]
Thank you for reviewing the edits. Here are the corrected change-sets.

#### Adding layer 1

https://www.openstreetmap.org/changeset/42206020

https://www.openstreetmap.org/changeset/42205943

https://www.openstreetmap.org/changeset/42206078

**Comment by luiswalter** [comment]
thanks team!

#### Crossing ways
https://www.openstreetmap.org/way/442139793#map=18/35.03805/136.62860

#### Untagged ways
https://www.openstreetmap.org/way/440980107#map=19/45.53639/9.18124

**Comment by ridixcr** [comment]
### thanks team!

#### Overlapping ways
https://www.openstreetmap.org/changeset/42207397

In this case don't split the way, you should align it
https://www.openstreetmap.org/changeset/42207451

In this case you should add `highway:turning_circle`
https://www.openstreetmap.org/changeset/42207521

**Comment by abhisheksaikia** [comment]
Thank you team for the review:
http://www.openstreetmap.org/way/240272680
layer=-1 already tagged to the waterway.

**Comment by RichRico** [comment]
##### Thanks for the feedback

#### Corssing Ways
https://www.openstreetmap.org/changeset/42215407
https://www.openstreetmap.org/changeset/42215428
https://www.openstreetmap.org/changeset/41978845

**Comment by calfarome** [comment]
Thank you team for the review:
#### align highway
https://www.openstreetmap.org/way/12588005/history aligned

**Comment by planemad** [comment]
Well spotted!

Fixed overlapping way https://www.openstreetmap.org/changeset/42265069

**Comment by jothirnadh** [comment]
Thank you team for the review. 

https://www.openstreetmap.org/way/135247069/history
This is a polygon, not a highway. No need to fix this.

**Comment by srividyacb** [comment]
Thank you for the feedback 🙏 
Fixed them : https://www.openstreetmap.org/changeset/42314187

**Comment by maning** [comment]
Thanks! My fixes below:

> https://www.openstreetmap.org/way/260232950/

https://www.openstreetmap.org/changeset/42314223
https://www.openstreetmap.org/changeset/42314256


> https://www.openstreetmap.org/way/223981401

https://www.openstreetmap.org/changeset/42314288

> https://www.openstreetmap.org/way/442050853
> https://www.openstreetmap.org/way/442050854

https://www.openstreetmap.org/changeset/42314330

**Comment by krishnanammala** [comment]
Everyone fixed the issues. Closing it 😄
