### ISSUE TITLE
Data Team peer review 09/21 - 09/27

### ISSUE THREAD

**Issue by dannykath** [mapbox/mapping#235]
Last peer review ticket: https://github.com/mapbox/mapping/issues/232

#### Mapping projects to be reviewed:

-  [To-Fix](http://osmlab.github.io/to-fix/#/stats/missinglayerbridgesminor)
- [Mapping and Aligning road network in Taiwan](https://github.com/mapbox/mapping/issues/233)

#### Instructions
* Download `.osm` files for last week.
 - [2016/09/21 - 2016/09/27](https://s3.amazonaws.com/mapbox/osm-history-processor/day/latest.osm.tar.gz)

* Extract the tar file and select any OSM file of the team member.
* Each team member will have an .osm file of edits for the last seven days. For example: `latest-andygol.osm`. Select any `.osm` file and open the data in JOSM. 
* If you don't find any osm file of a particular team member, then it means that user has not edited during the week.
* Examine user edits in detail. In JOSM, select a random small area edited by the user and press `3` to zoom.
* Download the latest data in OSM as a new layer and add a filter `Cmd + F` to see only the user's edits, e.g. `user:andygol`.

![andyfilter3](https://cloud.githubusercontent.com/assets/6770741/14813545/cf7409d2-0bbf-11e6-9389-5b6132b7bb55.gif)

* Select a way/node and load the the history (`Ctrl + H`), the changeset comment will describe what specific project the user was working on.
* To get an OSM link to the object, click `Cmd + Shift + H`. 
* Note down any feedback for each user in this ticket or comment directly in the changeset. Use this format:

```
username
changeset link - issue to fix
```

* @krishnanammala @chtnha or @dannykath will post the feedback in the ticket (Use Github handle because OSM name is different from Github name) and make necessary changes on the same day.
* Close the ticket once user's have fixed their edits.

For clarifications, discuss with the @mapbox/team-data in this ticket.

**Comment by Rub21** [comment]
@dannykath  can we postpone this for the next week? I think we have other priority for this week. https://github.com/mapbox/mapping/issues/233

cc. @lxbarth

**Comment by dannykath** [comment]
ok @Rub21  for now,  I will close the ticket
