### ISSUE TITLE
Complex Intersection QA Sought

### ISSUE THREAD

**Issue by talllguy** [mapbox/mapping#236]
Mapbox mapping team: Since you all have a lot of experience with turn lanes and intersection mapping, I am wondering if one of you could review this intersection at the end of an expressway that I recently mapped. I attempted to follow the mapbox guide on the subject, and want some feedback.

[Use the 2013/14 Maryland imagery](https://wiki.openstreetmap.org/wiki/Maryland#JOSM_Instructions).

![image](https://cloud.githubusercontent.com/assets/1827881/19487662/b88dacc2-9531-11e6-9f98-04a492ff3425.png)

[Here it is on the map](http://osm.org/go/ZZdGgdtAx--?m=).

Please let me know if I need to improve my methodology.

**Comment by planemad** [comment]
😍 @talllguy , paging our street modelling expert @Andygol

**Comment by Andygol** [comment]
@talllguy 
All of your edits looks good 👍 

But I decide to make some little improvement and adjustments. I don't upload my changes to the OSM server. You are able to review all of them in the file - [Maryland-talllguy.osm.zip](https://github.com/mapbox/mapping/files/542089/Maryland-talllguy.osm.zip)

Here 👇  gif that shows what was before my edits and after. 
![maryland-talllguy_1](https://cloud.githubusercontent.com/assets/369696/19566412/c575d13a-9707-11e6-8259-389a4b41930f.gif)

before | after
---|--- 
![java openstreetmap editor 2016-10-20 20-01-25](https://cloud.githubusercontent.com/assets/369696/19566923/a58c096e-9709-11e6-9f41-fac0439a1ebe.png) | ![java openstreetmap editor 2016-10-20 20-45-45](https://cloud.githubusercontent.com/assets/369696/19566924/a58c10e4-9709-11e6-9eb0-94a82e52708f.png)


Please pay attention how I changed  `tertiary_link` on **Fields Road**

This is step by step demonstration of all my changes
![maryland-talllguy_](https://cloud.githubusercontent.com/assets/369696/19566426/d5329b6c-9707-11e6-8046-9162b13d122e.gif)

You may refer to https://www.mapbox.com/mapping/mapping-to-improve-navigation/modeling-roads-for-navigation/ and especially  👇 
![](https://cloud.githubusercontent.com/assets/369696/13231932/5b417e00-d9b5-11e5-854e-dbed2d209d7c.png)

**Comment by Andygol** [comment]
@talllguy 
If you wish I'll upload my changes to OSM.

**Comment by talllguy** [comment]
@Andygol this is awesome, thank you! Yes, go ahead and make the changes. I reviewed the GIFs and tabled screenshots (markdown tables, l337), and will take some more time to review later.

However, to prevent any conflicts, I'd go ahead and upload the data. I can also compare on the live map.

Thanks! 🚀

**Comment by Andygol** [comment]
@tallguy 

changes is on the air 📡 
Fill free to review, if you have any questions ping me

**Comment by maning** [comment]
Great work @Andygol @talllguy! Closing.
