### ISSUE TITLE
Inconsistent mapping observed from OSM user: Lafeer

### ISSUE THREAD

**Issue by manoharuss** [mapbox/mapping#241]
Opened this ticket to track progress on this issue.

**OSM user:** [Lafeer](http://www.openstreetmap.org/user/Lafeer)

**Background for context:** During our validation work  2 months ago, I came across this Maps.Me user who added a lot(233) of `amenity=atm` and `amenity=post_office` POIs with numbers in the `name=*` tag. These POIs were spread across northern and middle part of across Sri Lanka.

I commented [on one of his changesets](http://www.openstreetmap.org/changeset/41880150#map=10/8.4438/80.5064) and the user has not replied. After reviewing his changesets, I have put together a report to escalate this over to DWG to request a block and revert of his edits.

Case report: [Gist](https://gist.github.com/manoharuss/ec2be65f00b6751a99f9861f6e336fe9)

cc @planemad @maning @chtnha @krishnanammala @mikelmaron

**Comment by manoharuss** [comment]
Update from OSM Changeset discussion:



![screenshot 2016-10-27 11 14 51](https://cloud.githubusercontent.com/assets/8921295/19755928/cf1bbfea-9c36-11e6-9c64-d906ea15e564.png)

**Comment by manoharuss** [comment]
Update from changeset discussion:

SomeoneElse from the DWG left a comment on another changeset of the same user. Link to the changeset: https://www.openstreetmap.org/changeset/43025905.

Further actions detailed in continued discussion on the changeset I commented on:

![screenshot 2016-10-28 10 19 01](https://cloud.githubusercontent.com/assets/8921295/19795293/fd13798a-9cf7-11e6-9dd4-e68b72af92f8.png)

**Comment by manoharuss** [comment]
Update: Sent a mail to talk-lk@openstreetmap.org which is a Sri Lankan mailing list.

![screenshot 2016-11-14 16 30 10](https://cloud.githubusercontent.com/assets/8921295/20262306/ae86c996-aa87-11e6-8a40-3091990d2b85.png)

**Comment by manoharuss** [comment]
Left a quick post on OpenStreetMap Sri Lanka Facebook group as I have not received any reply for the talk-lk email.

![screenshot 2016-11-24 16 38 03](https://cloud.githubusercontent.com/assets/8921295/20596550/1020175e-b265-11e6-947e-8c742feaa7b1.png)

**Comment by srimalsl** [comment]
Dear Manohar - It seems this guy is intentionally collecting the PoIs on ATM and Postoffices. As you said those are no mapper well and most are on the road. I think he has intesion to do map those PoI but the problem is he may lack of knoledge how to do it properly.  I am thinking toget his contacts and talk to him.  We have to collectively decide whether we fix these location or remove repmanently. Lets try first.

Srimal

**Comment by manoharuss** [comment]
@srimalsl Thanks for the reply. It would be great if you can keep us posted here on the ticket or on the [changeset discussion](http://www.openstreetmap.org/changeset/41880150#map=10/8.4438/80.5064).
