### ISSUE TITLE
Adding missing buildings and roads in Singapore

### ISSUE THREAD

**Issue by abhisheksaikia** [mapbox/mapping#244]
![image](https://cloud.githubusercontent.com/assets/13744156/20056361/c5e232be-a50b-11e6-83ff-799940713127.png)

**Objective**: In a bid to improve OpenStreetMap base data, @mapbox/team-data will be adding missing streets and buildings in Singapore. 

**Tasks**: 
* [Missing streets in Singapore](http://tasks.mapbox.com/project/74)
* [Missing buildings in Singapore](http://tasks.mapbox.com/project/75)

### Workflow:

**Mapping missing roads**

- Pick a task from the [Tasking Manager](http://tasks.mapbox.com/project/74)
- Load the Mapbox imagery to JOSM.
- Load Strava Cycling and Running heatmap traces and use it as an additional reference for alignment and satellite imagery offsets
- Inspect the imagery to find the missing roads
- Add only missing streets with appropriate tag
- Ignore areas with cloud cover/ look at Bing for those areas

* Changeset comment: `Tracing missing roads in Singapore #https://github.com/mapbox/mapping/issues/244`
* Source: `Mapbox/Bing`

**Mapping missing buildings**
- Pick a task from the [Tasking Manager](http://tasks.mapbox.com/project/75).
- Load the Mapbox imagery to JOSM. 
- Install JOSM Buildings Plugin for easy tracing.
- Inspect the imagery to find the missing buildings.
- Add only missing buildings.
- Ignore areas with cloud cover/ look at Bing for those areas.

* Changeset comment: `Tracing missing buildings in Singapore #https://github.com/mapbox/mapping/issues/244`
* Source: `Mapbox/Bing`

**Resources**:
* [Mapping common features using JOSM](https://www.mapbox.com/mapping/mapping-common-features/)

**Comment by maning** [comment]
![screen shot 2016-11-07 at 18 02 10](https://cloud.githubusercontent.com/assets/353700/20057957/62993b9a-a514-11e6-8d68-44a1056e0dc7.png)

Found this section that has a missing road from imagery, I'm assuming the imagery is outdated because of the highway=proposed tag.

Need local mappers to confirm.

OSM location: http://osmlab.github.io/to-fix/#/task/crossinghighwaysandbuildings
TM block: http://tasks.mapbox.com/project/74#task/332

**Comment by abhisheksaikia** [comment]
Similar to @maning's comment above: 
![screen shot 2016-11-07 at 6 26 41 pm](https://cloud.githubusercontent.com/assets/13744156/20058607/d3dd978a-a517-11e6-8e99-cc6be703f3fe.png)

OSM location:https://www.openstreetmap.org/history#map=17/1.37264/103.74986
TM block: http://tasks.mapbox.com/project/74#task/169

Need confirmation from the local community

**Comment by abhisheksaikia** [comment]
There are many high-rise buildings in Singapore. This means that the building footprint should be traced for the base of the building and not the rooftop. Also previously traced buildings with the base should not be realigned to the roof footprint.

Example:

* Correct:

![screen shot 2016-11-07 at 8 49 01 pm](https://cloud.githubusercontent.com/assets/13744156/20062992/ab03b592-a52b-11e6-97d2-083dcfbc17f2.png)

* Incorrect
![screen shot 2016-11-07 at 8 50 18 pm](https://cloud.githubusercontent.com/assets/13744156/20063045/d2e10f7e-a52b-11e6-809f-c071bcf65686.png)

cc @calfarome @samely

**Comment by ridixcr** [comment]
### Help me please :pray:
![seleccion_078](https://cloud.githubusercontent.com/assets/1646072/20064260/1ab9c696-a4d8-11e6-9929-0c9f4bc2ca4d.png)


how to proceed with the buildings without clear boundaries

is correct?
![seleccion_079](https://cloud.githubusercontent.com/assets/1646072/20064430/b9408d90-a4d8-11e6-9e3c-011dae87aff4.png)


cc. @mapbox/team-data

**Comment by Andygol** [comment]
@ridixcr 

I think so. In this case it is possible to trace terraced building in such way

**Comment by maning** [comment]
![screen shot 2016-11-08 at 16 02 38](https://cloud.githubusercontent.com/assets/353700/20095762/d8985778-a5cc-11e6-840c-c51aa87bc62f.png)

Potentially old imagery, need local to verify.

OSM location: https://www.openstreetmap.org/#map=17/1.4043429177133648/103.88379172609326
TM block: http://tasks.mapbox.com/project/74#task/393

**Comment by maanyaumashaanker** [comment]
**Status update:**

Approximately **308 Kms** and **645Kms** of roads where **added** and **modified** respectively, thus in total we have **improved** close to **953Kms** of road network data on OSM for Singapore, in a span of 3 days 🎉 . This is just amazing

Great work everyone! Thank you 👏  👏 

@mapbox/team-data

**Comment by abhisheksaikia** [comment]
The local OSM community and @mapbox/team-data had completed mapping and validating the road network in Singapore. Here's the current status of the road network in Singapore.

At present, **we have 82% road network coverage in Singapore on OpenStreetMap** after **~1,213 km** of roads were refreshed over the last two weeks. 

### Summary of Road Network in Singapore

* OSM coverage: 7,600 km of road
* Paved roads in Singapore ([per Govt. of Singapore in 2015](http://www.tablebuilder.singstat.gov.sg/publicfacing/createDataTable.action?refId=5248)): 9,200 km
* The local community and @mapbox/team-data  improved at total of **~1,213 km** of roads

Additionally, we are also adding and improving building footprints in Singapore and wrapping up validation of the [building tracing task](http://tasks.mapbox.com/project/75).

**Next actions**:
* [ ] @jothirnadh to update this ticket with the status of building data in Singapore and observations during validation

**Comment by abhisheksaikia** [comment]
The @mapbox/team-data along with the community wrapped up mapping and validation of missing building footprints in Singapore. 🎉 🚀 

During the course of last two weeks, a total of **40,280** buildings were added to OSM in Singapore. This translates to a lift of **42%** in missing building data during the last two weeks.

### Some observations from mapping and validation of roads and buildings in Singapore:

* The main issue that the team encountered was the lack of good quality satellite imagery for both Bing and Mapbox. While Bing had better quality than Mapbox, it was not recent and had huge patches of cloud cover. So secondary sources like Strava were used for verification of major roads during adding missing roads.
* Also due to the presence of a huge number of high-rise buildings, there often was distortion and the building footprint had to be very carefully aligned around the base and not the rooftop.


**A diary post on Singapore base map improvements along with a great visualization of the changes made to the map during the last two weeks have been posted by @poornibadrinath : https://www.openstreetmap.org/user/poornibadrinath/diary/39951**. Do check it out.

Also, thanks to the community for participating in the mapping tasks along with the Mapbox data team. It would be immensely helpful to have their eyes on our edits and point out any errors/feedback in this ticket.
