### ISSUE TITLE
project manager creds @ tasks.mapbox.com

### ISSUE THREAD

**Issue by govvin** [mapbox/mapping#248]
Is the Task Manager instance of Mapbox available for hosting non-emergency, community mapping tasks?

If so, and if it's allowed, I'd like to apply for project manager credentials so we can use it to host local project tasks.

**Comment by planemad** [comment]
@govvin the primary use of the http://tasks.mapbox.com is for projects by the Mapbox data team that may need special features not available in the other existing tasking managers. We're completely open to hosting community projects, but would ideally limit to include only those that are managed by an active community member and has a good reason to not use any of the existing tasking managers.

You can share the following and we can hook you up:
- Why you feel the existing TMs are not appropriate for your project
- Your OSM username

**Comment by govvin** [comment]
@planemad thanks for the quick turnaround.

I'm [GOwin](http://hdyc.neis-one.org/?GOwin) on OpenStreetMap.

At present, I can (and do) create tasks on the TM instance managed by HOT. I feel, though, that projects there should be reserved for critical and urgent tasks, to highlight their importance for emergencies and crises. 

I also like the fact that your instance is branded as "**OSM** Tasking Manager". I believe all contributions done under OpenStreetMap are essentially _humanitarian_ , because of the Free and Open philosophy that fuels the project, which gives everyone equal access and rights to the same data.

The HOT TM, of course, is very generous, and doesn't actually make any distinction between projects, and would be very happy to host almost any mapping task.

**Comment by planemad** [comment]
@govvin done! You have an amazing contribution history, and we look forward to your projects 💥 

Will just add some conditions that we will assume you agree to by using this TM:
- The Mapbox team maintains full admin rights over TM and may make undiscussed modifications to the software or projects to improve the overall experience of mappers using the TM
- We make no guarantee for eternal support to keep this instance running

cc @maning @batpad  @geohacker

**Comment by govvin** [comment]
Thank you for your kind words, @planemad . 

I agree with the conditions you've specified.  My only request is to be notified if there are expected outages or down times. :smile_cat:
