### ISSUE TITLE
Adding height to City of San Francisco buildings

### ISSUE THREAD

**Issue by chtnha** [mapbox/mapping#249]
![1200px-sanfrancisco_from_twinpeaks_dusk_mc](https://cloud.githubusercontent.com/assets/6770741/20626226/52c0ed5c-b33e-11e6-9218-80fc8060c952.jpg)
*Image from Wikipedia*

#### Objective
Adding height to the existing building footprints for the entire San Francisco city. 

#### Background
Back in 2014, @mapbox/team-data added buildings to the entire SF city on OpenStreetMap. In 2016, SF local government released [CC0-licensed](http://cadmapper-support.s3.amazonaws.com/sf_building_height_import/SF_BldgFoot_2016-10_description.pdf) building dataset derived from LIDAR that lacks discrete footprints, but includes accurate height information. There are **143953** buildings without a height tag. Adding height tag to the existing building footprints will improve OSM, especially when used with popular renderers like [OSM Buildings](http://osmbuildings.org/?lat=40.70881&lon=-74.00946&zoom=15.8&rotation=0&tilt=30) and [Mapbox GL JS](https://www.mapbox.com/blog/3d-features-in-mapbox-gl-js/).

* **Task** http://tasks.openstreetmap.us/project/71 

* **Total duration to complete the project**: Two weeks including validation.

#### Source
* Bing Satellite Imagery
* SF Local Government dataset
* LIDAR imagery
* Mapillary (for reference) 

#### Workflow

* Create an import specific account on [openstreetmap.org](http://www.openstreetmap.org/#map=10/40.7228/-73.9668) E.g. `bdon_sfimport` and [post the user names here](https://github.com/osmlab/sf_building_height_import/issues/23).
* Go to `My settings` and choose JOSM as your `Preferred Editor` and Save Changes. 
* Enable `Remote Control` in JOSM.
* Add this Map Paint Style to JOSM: [buildingheights.css](https://raw.githubusercontent.com/osmlab/sf_building_height_import/master/buildingheights.css). Make sure it is activated in the Map Paint Styles.
* Add the raw LIDAR imagery in JOSM : Menu > Imagery Prefrences > Add TMS  `tms:https://s3-us-west-2.amazonaws.com/openmassing/sf_lidar/{z}/{x}/{y}.png`

* **Changeset comment:** `San Francisco Building Height Import #sfbuildingheights https://wiki.openstreetmap.org/wiki/San_Francisco_Building_Height_Import`
* **Source:** `San Francisco Enterprise Geographic Information Systems Program (SFGIS) Building Footprints, 2016. https://sfgis-svc.sfgov.org/sfgis/San_Francisco_Bldg_withZ_20161028.zip`

**Comment by maning** [comment]
![screen shot 2016-11-28 at 12 49 55](https://cloud.githubusercontent.com/assets/353700/20659376/3e12b430-b569-11e6-94d1-30da98b70562.png)

The 2 selected buildings were tagged as `building=abandoned` the Lidar layer doesn't show this anymore although still visible in Bing. Possibly demolished but need confirmation on the ground.

http://tasks.openstreetmap.us/project/71#task/428

**Comment by chtnha** [comment]
The import trying to add `height=0.50` for this building. But in reality the building doesn't exists in LIDAR layer or Mapbox imagery. Bing is old here (2013).  In this case, please DELETE height tag and upload the data. 

![incorrect_height](https://cloud.githubusercontent.com/assets/6770741/20666174/f790e016-b588-11e6-8528-7d633e6822a4.gif)

**Comment by ramyaragupathy** [comment]
There were cases where the height has been set to zero/one. Removing them before importing
![image](https://cloud.githubusercontent.com/assets/12103383/24691059/e8342e00-19ee-11e7-9c28-25248fb2571d.png)

_http://tasks.openstreetmap.us/project/71#task/300_

**Comment by chtnha** [comment]
Finally San Francisco City buildings height has been successfully completed.  Imported **140484** 💥  building heights with the help from community members. Big thanks to @bdon for leading the project. I will be posting a OSM diary post on completion of the project soon.

![sf_illustration](https://cloud.githubusercontent.com/assets/6770741/24750231/be28c882-1ae3-11e7-8423-e82604aa9b36.gif)

The next action would be to validate the buildings height through street level imageries. Both [Mapillary](https://www.mapillary.com/app/?focus=map&pKey=133QnlZotVVA5lMmVa4IfQ&lat=37.749555444601185&lng=-122.43693827143241&z=11.171984569941344) and [OpenStreetCam](https://www.openstreetcam.org/map/) have a very good coverage in San Francisco City. Right now we have OpenStreetMap and Mapillary comparison tool to validate these buildings height. 

#### Link to OSM/Mapillary comparison tool:
http://openmassing.org/validator/?import_url=http://tiles.openmassing.org/api/sfbuildingheight_16_10473_25336.osm#15/37.7512/-122.4673/0/43

Also, follow [Gitter](https://gitter.im/osmlab/sf_building_height_import) channel for next updates and to participate in validation. 

@mapbox/team-data

**Comment by royandrewng** [comment]
Amazing and beautiful work @mapbox/team-data.  Congratulations @chtnha @bdon and everyone on the open data import and bringing this all into OpenStreetMap!! 🎉 🎉 - 3D data like this will help city planners and make 😎 video games in Unity, and we can now power all these apps!  🥇

**Comment by jothirnadh** [comment]
@chtnha are we good to close this ticket?

**Comment by chtnha** [comment]
Closing here for now. Will open it, if we need to rethink of adding more details to buildings.
