### ISSUE TITLE
Localizing names of popular tourist POIs for select world cities

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#252]
Reference: [China tops the world in outbound tourism](http://www.ecns.cn/cns-wire/2016/01-29/197628.shtml)

**Objective** Add localized labels for popular POIs for Chinese in top tourist destinations

**Workflow**
- [x] Shortlist a list of 100 popular POIs each listed in Chinese travel websites for 20 cities
- [x] Verify translated labels with native Chinese speakers
- [x] Match the POI with the corresponding OSM feature using [quick-geocode](https://github.com/batpad/quick-geocode) and manual search
- [x] Match each OSM feature with a corresponding Wikidata feature using matching workflow https://github.com/mapbox/mapping/issues/242
- [x] Check if target translation exists on Wikidata for the OSM feature using [osm-wikidata scripts](https://github.com/amishas157/osm-wikidata) 
- [ ] Add missing localized POI labels to the corresponding Wikidata or OSM feature
- [ ] Final validation and feedback

**Worksheet** https://docs.google.com/spreadsheets/d/1LNbZkPnDmygRXlIL_oa5HZ-iM_yHUdmXZi5ar-o5JYU/edit?usp=sharing

**Mappers** 
- @abhisheksaikia 
- @samely 
- @dannykath 
- @ramyaragupathy 
-  @planemad
- @bsrinivasa 
- @kupendrayadav 
- @piligab 
- @RichRico 
- @karitotp 
- @jothirnadh

**Comment by assanges** [comment]
[Suggestion]
Daiso prefer to use 「日本大创百货(zh-hans)／日本大創百貨(zh-hant)」 as brand name in Chinese, 
and use 「公司 (Company)」 to describe the legal entity at most circumstance, 
as the subsidiary in Taiwan「台灣大創百貨股份有限公司 (Taiwan Daiso Co., Ltd.)」, 
of which「股份有限公司」 stands for Company Limited .

![image](https://cloud.githubusercontent.com/assets/4113063/20936814/0672114e-bc1f-11e6-81ab-09765793c69a.png)

**Comment by bsrinivasa** [comment]
####  Update

The list containing popular POIs around selected World cities and the corresponding revised Chinese translations has been updated in this [spreadsheet](https://docs.google.com/spreadsheets/d/1dPxBmtPplqaNerERNb4uOvOHrDsBrh_0r0r4bdOez0E/edit#gid=0)

#### Workflow for updating Wikidata and OpenStreetMap with Chinese translations. 
- The validated list is checked for existing Wikidata ids in OpenStreetMap
- Reviewed Chinese labels are uploaded to Wikidata using the[ Wikidata label upload](https://github.com/amishas157/wikidataLabelUpload) tool for those features which has a Wikidata item tagged in OpenStreetMap
- Reviewed Chinese labels are uploaded to OpenStreetMap in a batch for each city using [OSM Name translation](https://github.com/srividyacb/osm-name-translation) tool for those which do not have a Wikidata tag in OpenStreetMap 


#### Validations steps 

The current list of POIs have undergone the followings validation processes. 

✅  Visual check for the offsets in the OSM coordinates for the corresponding cities from the list
✅  Check for duplicates of OSM ids and Wikidata ids and matched names from both OSM and Wikidata platforms
✅  Compared distance between OSM and Wikidata coordinates for those features which had Wikidata id tagged in OpenStreetMap using [Wikidata-OSM Validator](https://github.com/amishas157/Wikidata-OSM-Validator) tool


cc: @maning @planemad

**Comment by bsrinivasa** [comment]
The translations for the list of POIs was posted in talk-cn and were reviewed by Chinese community. We are grateful to the Chinese community for their splendid job in reviewing these translations. 🎉 

Find the reviewed translations in the [spreadsheet](https://docs.google.com/spreadsheets/d/1dPxBmtPplqaNerERNb4uOvOHrDsBrh_0r0r4bdOez0E/edit#gid=0).

#### Next actions
- The reviewed translations are to be uploaded to OSM manually using the JOSM url in the spreadsheet which opens up the feature and add `name:zh` tag automatically.

**Comment by bsrinivasa** [comment]
#### Progress update

OpenStreetMap was updated with **142 Chinese translations** in an effort of facilitating a localised map. 
Here is the [**spreadsheet**](https://docs.google.com/spreadsheets/d/1dPxBmtPplqaNerERNb4uOvOHrDsBrh_0r0r4bdOez0E/edit#gid=0) which was used to upload translations to OSM which has the reviewed Chinese translations by Chinese community. 

**Changeset comment**: _"Adding localised name https://github.com/mapbox/mapping/issues/252"_

**OpenStreetMap accounts involved:**
- [BharataHS](https://www.openstreetmap.org/user/BharataHS)
- [PlaneMad](https://www.openstreetmap.org/user/PlaneMad)

**Comment by bsrinivasa** [comment]
The team updated OpenStreetMap with Chinese translations for a total of 796 POIs in top 20 global cities.  This was the **[spreadsheet](https://docs.google.com/spreadsheets/d/1dPxBmtPplqaNerERNb4uOvOHrDsBrh_0r0r4bdOez0E/edit#gid=0)**  used for uploading translations which were reviewed Chinese translations by Chinese community.

We are grateful to Chinese community for joining us in the effort of localising names of Point of Interests.

cc: @maning @planemad @kupendrayadav @chtnha

**Comment by bsrinivasa** [comment]
No next actions here! Closing this ticket. :tada:
