### ISSUE TITLE
Mapping traffic signals in San Francisco City area

### ISSUE THREAD

**Issue by krishnanammala** [mapbox/mapping#255]
### Aim 

To review and add all the traffic signals at junctions(intersection of major highways and minor-major ways) in SF city area.

### Proposed workflow

<img width="1279" alt="af1be85a-c157-11e6-854a-0a240acceb62" src="https://cloud.githubusercontent.com/assets/17143802/21174981/213ba052-c206-11e6-9b95-6d29700cbb99.png">

_Snapshot of the traffic signals map window_

##### Map Legend

| Highlighted Colors          | Description                              |
| ---------------------------- | ---------------------------------------- |
| Yellow nodes                 | Junctions to be reviewed                 |
| Blue buffer with yellow node | Traffic signal already present in OSM but needs review |
| Cyan                         | Reviewed as `Added`                      |
| Dark Grey                    | Reviewed as `No Signal`                  |
| Light Grey                   | Reviewed - (usually when when traffic signal is already present) |
| Grayish white lines          | Highlights the highways with intersection of major ways and major with minor ways which have been prioritized for the current mapping task |

1. Assign a block from the map in the [spreadsheet](https://docs.google.com/spreadsheets/d/1Ay8JOn9T408LDMhYO4fe17SxBuzkrg3TD1gOLN-uuGg/edit#gid=0).

2. Manually review the junctions by checking around the Mapillary images from the trails around the junction.

3. Skip the junctions which already has a mapped traffic signal in OSM by marking as `Reviewed` if highlight is `yellow node with blue buffer`.

4. Check the Mapillary traces and associated photos for missing traffic signal at the highlighted junctions (yellow nodes). 

5. If visible in Mapillary photo, Use `Open in JOSM` option to open the bounding box in JOSM and add the tag `highway=traffic_signals` on the node. {Note: Use [](https://localhost:8112/version) if `Open in JOSM` doesn't work initially}

   **Note**: Refer to [OSM Wiki](http://wiki.openstreetmap.org/wiki/Tag:highway=traffic%20signals?uselang=en-US) on for a complete guide on adding and various cases we might come across during the review.

6. If traffic signal is not visible in the Mapillary photos,  review the junction as `No Signal`.

7. There are few `Traffic Signal Ahead` signage detections from Mapillary which might be used as an additional reference during the review.

   **Important Note:** Traffic signals (traffic lights) at intersections are not detected in Mapillary and hence all junctions are being reviewed manually by peeking into the photos from Mapillary trails. 

### Elements to ignore from the map during this project

1. The Round buffer - Indicating already mapped `Stop` sign in OSM
2. The Mapillary `STOP` detections (Red Hexagon with STOP written on it)
3. `Stop sign ahead`  Mapillary detections 

**Changeset Comment** : ` Added/Reviewed Traffic signals in SF`
**Source** : `Bing/Mapillary`

Use this ticket to capture various cases that are encountered during the process of reviewing or adding. 

Drop in tickets if you face any issues related to traffic signals map tool at [mapbox/traffic-signals](https://github.com/mapbox/traffic-signals/issues). 

cc: @mapbox/team-data  @poornibadrinath @bsrinivasa  @ajithranka  @rasagy @maning @planemad

**Comment by maning** [comment]
![screen shot 2016-12-15 at 16 31 17](https://cloud.githubusercontent.com/assets/353700/21221595/fd414e0c-c2e3-11e6-9a59-849e19c628c3.png)
[This intersection](https://mapbox.github.io/traffic-signals/#17.48/37.79345/-122.41866) has traffic_signal (mapillary and OSM data), but I can't review because it doesn't have the yellow dot.

**Comment by rasagy** [comment]
@maning That’s probably because it doesn’t come on a priority junction:
> The white roads highlight the highways with intersection of `major ways` and `major with minor ways` which have been prioritized for the current mapping task.

**Comment by poornibadrinath** [comment]
## Progress of Mapping Traffic Signals in SF: 

A team of **9** people worked on adding traffic signals in SF over two days. A total of **941** junctions were reviewed. Out of which: 

Already present on OSM | No signal | Added by the team
--- | --- | ---
265 | 549 | 127

#### Here's the detailed breakdown of the stats for two days: 

* 14 Dec 2016: 
    Number of team members: 7 
    Area: SF Bay 

* 15 Dec 2016: 
   Number of team members: 5
   Area: SF city core

Date reviewed | Already Present on OSM | No signal  | Added by the team
--- | --- | --- | ---
14 Dec 2016 | 41 | 81 | 11
15 Dec 2016 | 224 | 468 | 116

_Initially the focus was on complete Bay Area of San Francisco. But as of today, we have prioritised San Francisco city._

**Comment by poornibadrinath** [comment]
### Progress update: 

**16-dec-2016**:

A team of 11 mappers (3 BLR & 8 AYP) worked on reviewing **164** blocks out of which: 

Already present on OSM | No signal | Added by the team
--- | --- | ---
289 | 1016 | 190

Total number of blocks reviewed so far, in the course of three days: **528**
Blocks left to cover: **611** 
% of completion: **47%**

**Comment by poornibadrinath** [comment]
### Progress update: 

**19 Dec 2016**:

**Area**: **SF city**

A team of **14** mappers (6 BLR & 8 AYP) worked on reviewing **317** blocks out of which: 

Total number of junctions reviewed: **2875**

Already present on OSM | No signal | Added by the team
--- | --- | ---
524 | 2111 | 240

Total number of blocks reviewed so far, in the course of five days: **845**
Blocks left to cover: **291** 
% of completion: **73%**

**Comment by maning** [comment]
![screen shot 2016-12-20 at 11 52 42](https://cloud.githubusercontent.com/assets/353700/21340962/d4e50fc8-c6af-11e6-8218-aeaabb4326c7.png)

per @bsrinivasa 

> This is a Traffic signal and the sign board is present to indicate that only one light you 
> see in the photo is a traffic signal and not a warning _Amber_ light which blinks throughout the day

location: https://mapbox.github.io/traffic-signals/#18.63/37.65193/-122.47144

**Comment by poornibadrinath** [comment]
### Next actions: 

Since **SF city** is near completion, moving onto **adding traffic signals** in **SF bay area**.

The spreadsheet created for the SF Bay area can be found [here](https://docs.google.com/spreadsheets/d/1Ay8JOn9T408LDMhYO4fe17SxBuzkrg3TD1gOLN-uuGg/edit#gid=1408171523)

**Comment by krishnanammala** [comment]
We wrapped up reviewing and adding traffic signals in the SF city. We moved onto adding traffic signals for the rest of SF bay area which has dense Mapillary coverage. [Spreadsheet](https://docs.google.com/spreadsheets/d/1Ay8JOn9T408LDMhYO4fe17SxBuzkrg3TD1gOLN-uuGg/edit#gid=1408171523).

[Traffic signal Map](https://mapbox.github.io/traffic-signals/#9.16/37.4787/-122.1482).

### Progress update: 

**20 Dec 2016**:

**Area**: **SF city and rest of SF bay area**

A team of **13** mappers (8 BLR & 5 AYP) worked on reviewing **361** blocks out of which: 

Total number of junctions reviewed: **2332**

Already present on OSM | No signal | Added by the team
--- | --- | ---
198 | 1877 | 257

Total number of blocks in the rest of SF bay area which has dense Mapillary coverage: **3870**
Number of blocks completed: **70**
Blocks left to cover: **3800**.

**Comment by krishnanammala** [comment]
### Progress update of SF city:

Total number of blocks: **1136**
Time taken to complete: **5** days (14th Dec - 20th Dec)
Number of mappers: **12** on average including BLR + AYP
Number of hours: **30** hours 
Number of traffic signals added by team on OSM: **749**

![screen shot 2016-12-21 at 6 12 45 pm](https://cloud.githubusercontent.com/assets/17470597/21390042/c0d9ead4-c7aa-11e6-83e4-baef950c3cfa.png)
overpass link: http://overpass-turbo.eu/s/kNb

cc @mapbox/team-data

**Comment by poornibadrinath** [comment]
### Progress update: 

**21 Dec 2016**:

**Area**: **SF bay area**

A team of **3** mappers worked on reviewing **73** blocks out of which: 

Total number of junctions reviewed: **585**

Already present on OSM | No signal | Added by the team
--- | --- | ---
35 | 586 | 73

Total number of blocks reviewed so far: **153**
Blocks left to cover: **3719** 
% of completion: **4%**

**Comment by maning** [comment]
![screen shot 2016-12-22 at 12 32 44](https://cloud.githubusercontent.com/assets/353700/21417774/db18a906-c842-11e6-8a42-c7ab0e7decf1.png)
![screen shot 2016-12-22 at 12 32 25](https://cloud.githubusercontent.com/assets/353700/21417775/db20a02a-c842-11e6-982e-0d04d996a73c.png)

Not sure if this is common, but I found traffic signal from a motorway_link before it merged to the motorway with a sign board "Stop when on red".
Location: https://mapbox.github.io/traffic-signals/#17.15/37.42445/-121.92310

**Comment by krishnanammala** [comment]
### Progress update: 

**22 Dec 2016**:

**Area**: **SF bay area**

A team of **5** mappers worked on reviewing **298** blocks out of which: 

Total number of junctions reviewed: **1796**

Already present on OSM | No signal | Added by the team
--- | --- | ---
195 | 1426 | 175

Total number of blocks reviewed so far: **441**
Blocks left to cover: **3429** 
% of completion: **11%**

**Comment by krishnanammala** [comment]
### Progress update: 

**23 Dec 2016**:

**Area**: **SF bay area**

A team of **3** mappers worked on reviewing **68** blocks out of which: 

Total number of junctions reviewed: **155**

Already present on OSM | No signal | Added by the team
--- | --- | ---
62 | 61 | 32

Total number of blocks reviewed so far: **509**
Blocks left to cover: **3361** 
% of completion: **13%**

**Comment by krishnanammala** [comment]
Today i.e., 27-12-2016 , we kept on hold on this task. Will resume tomorrow working on this.

**Comment by krishnanammala** [comment]
### Progress update: 

**29 Dec 2016**:

**Area**: **SF bay area**

A team of **3** mappers worked on reviewing **182** blocks out of which: 

Total number of junctions reviewed: **1034**

Already present on OSM | No signal | Added by the team
--- | --- | ---
109 | 887 | 38

Total number of blocks reviewed so far: **691**
Blocks left to cover: **3179** 
% of completion: **18%**

**Comment by krishnanammala** [comment]
### Progress update: 

**2 Jan 2017**:

**Area**: **SF bay area**

A team of **6** mappers worked on reviewing **186** blocks out of which: 

Total number of junctions reviewed: **925**

Already present on OSM | No signal | Added by the team
--- | --- | ---
279 | 588 | 58

Total number of blocks reviewed so far: **879**
Blocks left to cover: **2991** 
% of completion: **23%**

**Comment by krishnanammala** [comment]
### Progress update: 

**3 Jan 2017**:

**Area**: **SF bay area**

A team of **6** mappers worked on reviewing **345** blocks out of which: 

Total number of junctions reviewed: **1305**

Already present on OSM | No signal | Added by the team
--- | --- | ---
237 | 1011 | 57

Total number of blocks reviewed so far: **1479**
Blocks left to cover: **2391** 
% of completion: **38%**

**Comment by krishnanammala** [comment]
### Progress update: 

**4 Jan 2017**:

**Area**: **SF bay area**

A team of **7** mappers worked on reviewing **651** blocks out of which: 

Total number of junctions reviewed: **1461**

Already present on OSM | No signal | Added by the team
--- | --- | ---
293 | 1012 | 156

Total number of blocks reviewed so far: **2345**
Blocks left to cover: **1525** 
% of completion: **60%**

**Comment by RichRico** [comment]
Hi @krishnanammala 

The application has an option which is marked with a red circle in the pic, this makes a 3D view effect, I do not know if this is a very necessary option and I think that maybe the application consumes a lot of system resources because of this option. The laptops overheat and get slow. How feasible would it be to remove that option to see if this improves the application? maybe for the following tasks.

![screenshot from 2017-01-04 11-27-23](https://cloud.githubusercontent.com/assets/8484029/21651276/01692a8a-d276-11e6-9139-3f8f51147154.png)

**Comment by ajithranka** [comment]
Hi @RichRico! That's the drag-to-rotate interaction that comes by default with Mapbox GL JS. If you press the Control key and drag the map, the bearing (rotation) and pitch (tilt) changes. The navigation control (highlighted in red in your screenshot) resets the bearing to zero.

The intended interaction would look like this:

![drag-to-rotate](https://cloud.githubusercontent.com/assets/11095038/21670012/c2076458-d336-11e6-95b6-de93d4be012d.gif)

However, I can see who this can be confusing. Since we don't need to adjust rotations most of the time, is it ok to remove it from the map?

Regarding the performance: drag-to-rotate is a standard default in GL maps. The performance issue is unlikely to be related to this.

**Comment by ajithranka** [comment]
@RichRico This should be fixed now. Rotation is disabled.

**Comment by krishnanammala** [comment]
### Progress update: 

**5 Jan 2017**:

**Area**: **SF bay area**

A team of **5** mappers worked on reviewing **732** blocks out of which: 

Total number of junctions reviewed: **1223**

Already present on OSM | No signal | Added by the team
--- | --- | ---
237 | 836 | 150

Total number of blocks reviewed so far: **3357**
Blocks left to cover: **513** 
% of completion: **87%**

**Comment by poornibadrinath** [comment]
### Progress update:
We have wrapped up adding traffic signals in entire SF bay area. 👇  you can find the breakdown of stats for this task: 

Total number of blocks: **3870**
Time taken to complete: **9** working days (21st Dec 2016 - 06th Jan 2017)
Number of mappers: **12** on average including BLR + AYP
Number of hours: **54** hours 
Number of traffic signals added by team on OSM: **926**

**Comment by poornibadrinath** [comment]
### Traffic Signal Mapping: 
 
  Traffic signal mapping in SF city and the SF bay area has been completed. The task was started on 14 of December and concluded on 6 of January, with the number of working days of 14. A team of 12 mappers contributed to adding traffic signals. 

👇  is the full breakdown of how the task went:

- Total number of blocks worked on: **5006** (1136: SF city; 3870: Bay area excluding city) 
- Total number of junctions reviewed: **~16000** (Total number in SF city and Bay area included) 
- Total number of traffic signals added: **1675** (749: SF city; 926: Bay area) 

Out of **1696** traffic signals added during this period, **1675** were added through this task. 

It was great to have the community members keeping an eye on the edits and letting us know if there were any traffic signals added wrongly.

No further actions required. Closing this ticket 🚀
