### ISSUE TITLE
Using google imagery for tracing in Taiwan

### ISSUE THREAD

**Issue by chtnha** [mapbox/mapping#256]
Documenting this for future reference. During our validation work, we came across an OSM user: [TaiwanMap](https://www.openstreetmap.org/user/TaiwanMap) using custom google imagery to add highway details to OpenStreetMap. 

#### More details on the user
* Edits count: 1206
* Mapping since: March 8th 2016

![google_imagery](https://cloud.githubusercontent.com/assets/6770741/21342084/01327d80-c6b6-11e6-997d-0566134162ea.png)

#### Actions

* @Supaplextw reverted few changesets. On top of his reverts, SomeoneElse from DWG has reverted large changesets. 
   - http://www.openstreetmap.org/changeset/44496385
   - http://www.openstreetmap.org/changeset/44497876

* Large changesets were also reverted in China too.   http://www.openstreetmap.org/changeset/44396421

**Comment by assanges** [comment]
YES! YES! ｷﾀｷﾀｷﾀｷﾀ━━━(ﾟ∀ﾟ≡(ﾟ∀ﾟ≡ﾟ∀ﾟ)≡ﾟ∀ﾟ)━━━━!!
The community in Taiwan has aware of this series of edits, 
and the Google imagery issue has been reported.
Thanks again for the validation work! Cheers mate! (´▽`ʃ♡ƪ)"

However edits by user 愛台玩 still haunted the map... (・∀・`)
Erm... dog's breakfast...

See https://github.com/openstreetmap/iD/issues/3623

Changesets reverted by @Supaplextw:
44074680 44074661 44074493 44074456 44074239

44074120 44073929 44073798 44073673 44073627 
44073491 44073061 44072809 44072594 44072483 
44072404 44072125 44071744 44071688 44056824

44056743 44056644 44056401 44056170 44056120 
44055213 44055155 44054808 44054669 44054556
44054447 44054140 44053737 44053644 44053439 
44053284 44053119 44052962 44052835 44052700

44052459 44052296 44052228 44052141 44052050 
44051990 44051828 44051619 44050996 44050966 
44050762

**Comment by SomeoneElseOSM** [comment]
@assanges If the Taiwan community (or anyone else) is aware of google.cn imagery use by anyone else please do let the DWG know (email to data@osmfoundation.org is best) so that we can revert and redact as appropriate.  Also thanks to the Taiwan community for spotting the issue in the first place around 1st December.
Best Regards,
Andy (OSM Data Working Group, not Mapbox)

**Comment by maning** [comment]
TW community is aware (they are awesome). 
Any next actions should be reported to DWG by the TW community. Closing
