### ISSUE TITLE
Fixing major highways which is crossing with buildings

### ISSUE THREAD

**Issue by osMatt** [mapbox/mapping#258]
Hi, I have some remarks to changesets with the comment "Fixing major highways which is crossing with buildings". I didn't see any To-Fix task for this, so I opened this issue.

Earlier today, I noticed [this changeset](http://overpass-api.de/achavi/?changeset=44598853). I am not sure what the exact purpose was to re-align the road as it was not overlapping any building (it was overlapping with this [`amenity=school` way](https://www.openstreetmap.org/way/259490349), which is tagged with `building=no` so maybe your algorithm detected this as a problem).

To better understand what you are trying to fix, I looked at a handful of edits that were made right before or after this changeset with the same changeset comment and noticed some potential issues:

- [This changeset](http://overpass-api.de/achavi/?changeset=44600501) moves the road, but completely misses the initial problem what triggered the road/building overlap: [this way](https://www.openstreetmap.org/way/192917397) should have been tagged as `landuse=residential` instead of `building=yes`.

- [This changeset](http://overpass-api.de/achavi/?changeset=44600306) tags the road as `tunnel=building_passage`. However, the road is never in a tunnel, instead the "building" is an underground object (cf. `layer=-1`, should probably also tagged as `location=underground` or so).

- In [this changeset](http://overpass-api.de/achavi/?changeset=44600830) the building is tagged as building=roof. The [wiki](http://wiki.openstreetmap.org/wiki/Key:covered) says that in this case the road should be tagged with `covered=yes` rather than `tunnel=building_passage`. This might be also the case for other toll booths crossing roads.

I understand that especially the last point is not always easy to determine remotely, but I would expect that as professional mappers you would check what kind of tagging triggered the error in the first place. Naturally, this is probably difficult if the edits are made at a rate of >=1 per minute. However, I looked at about 7 or 8 changsets, so finding 3-4 problematic ones seems quite a lot to me.

**Comment by maning** [comment]
@osMatt Thanks for this report, could it be that `building=no` tag should be removed? There are ~12k `building=no` tags in OSM, but the consensus seems to be that this is [not an appropriate tag](https://help.openstreetmap.org/questions/53555/clarifying-buildingno)?

Btw, for issues related to to-fix validators, we track them in the [OSMLint repo](https://github.com/osmlab/osmlint/issues).

**Comment by maning** [comment]
Tracking here: https://github.com/osmlab/osmlint/issues/191

**Comment by samely** [comment]
@osMatt thank you for such an explicit feedback as you help us to improvement this validator.

- You are right about features tagged as `building=no`, these were removed from detection.
- About retagging features as `landuse=residential` instead of `building=yes`, it probably will be another validator, thanks for pointing this out. 
- [This edit](https://osmcha.mapbox.com/44600306/) has been fixed in this [changeset](https://www.openstreetmap.org/changeset/45277283)
- For now, we will remove the detections of `building=roof` for being locally tagged.
- Finally, we will a master ticket for this task adding some tips to fix those issues.

Regards!
