### ISSUE TITLE
Fantasy Pokemon mapper vandalism

### ISSUE THREAD

**Issue by krishnanammala** [mapbox/mapping#259]
We came across a [user](https://www.openstreetmap.org/user/firepanda11) who is adding random `footways` all over the park.

He was a new mapper joined recently in 25th December 2016 having **73** changesets using iD editor. [Here](https://www.openstreetmap.org/user/firepanda11/history#map=13/49.8570/-97.0230) are the list of his changesets.

![screen shot 2017-01-03 at 9 39 30 am](https://cloud.githubusercontent.com/assets/17470597/21599955/ff117a34-d19a-11e6-85cc-b562f4368f87.png)

Changeset: https://www.openstreetmap.org/changeset/44695341

**Next Actions**

- [ ] All of these changesets needs to be reverted using reverting scripts.

cc @geohacker @batpad @manoharuss @chtnha @planemad @maning

**Comment by pnorman** [comment]
The next action should be contacting a user via a changeset discussion explaining what they're doing is wrong. If the user's changes don't include deletes, it's probably easier to delete the data than revert it.

**Comment by geohacker** [comment]
@krishnanammala @pnorman - this looks like from the recent Pokemon movement. I think this is easier to delete than revert.

**Comment by krishnanammala** [comment]
I went ahead and deleted the data. 
Changeset: http://www.openstreetmap.org/changeset/44862436

Also, commented on the changeset of the user
https://www.openstreetmap.org/changeset/44719485#map=19/49.84424/-96.96264

cc @geohacker @pnorman

**Comment by krishnanammala** [comment]
Will keep an eye on this user if he again starts editing. Closing the ticket for now.
