### ISSUE TITLE
Adding building footprints in Oakland

### ISSUE THREAD

**Issue by bsrinivasa** [mapbox/mapping#261]
**Objective**: In an effort to improve base data in OpenStreetMap, [@mapbox/team-data](https://github.com/orgs/mapbox/teams/team-data) will be adding missing buildings footprints in Oakland.

![image](https://cloud.githubusercontent.com/assets/17143802/21796978/566edc44-d732-11e6-85c8-dddcffd72751.png)
_Image Source: Wikipedia_

Project in tasking manager: [project#80](http://tasks.mapbox.com/project/80)

**Workflow for mapping building footprints**

- Pick a task from the [Tasking Manager](http://tasks.mapbox.com/project/80).
- Load the Bing imagery to JOSM.
- Install JOSM Buildings Plugin for easy tracing.
- Inspect the imagery to find the missing buildings.
- Trace all the missing buildings in OpenStreetMap.

**Resources**:

- [Mapping common features using JOSM](https://www.mapbox.com/mapping/mapping-common-features/)
- [Fast building tracing with JOSM](https://www.mapbox.com/blog/fast-building-tracing/)
- [Becoming a power mapper](https://www.mapbox.com/mapping/becoming-a-power-mapper/)
- [Guide for JOSM shortcuts](https://www.mapbox.com/mapping/becoming-a-power-mapper/josm-shortcuts/)
- [Check your OpenStreetMap edits with the JOSM Validator](https://www.mapbox.com/blog/josm-validation/)

**Comment by luiswalter** [comment]
@bsrinivasa Improving the map is one of our priorities, you have a statistic of how many buildings are missing?

**Comment by Andygol** [comment]
Adding building footprints in Oakland project was finished.

Thanks everyone who took part in that. More than 150'000 buildings were added on the map. 🏘  🎉
 
![](https://cloud.githubusercontent.com/assets/369696/23373274/e9169670-fd27-11e6-89e3-0eb5e60bf537.png)
