### ISSUE TITLE
Mapping turn-restriction in world 50 cities

### ISSUE THREAD

**Issue by srividyacb** [mapbox/mapping#262]
### Aim:

To map turn-restriction in priority world cities using Mapillary

**Workflow**

- **Tool** :  [osm-navigation-map](http://mapbox.github.io/osm-navigation-map/?days=150#20/37.33746/-122.03540) 
- [Instructions to use map](https://github.com/mapbox/osm-navigation-map/blob/gh-pages/README.md)
- **Features to map** : `turn-restriction`

![screenshot 2017-01-10 16 25 38](https://cloud.githubusercontent.com/assets/3423533/21803859/10e5e580-d752-11e6-9c1b-43d10bdd06e4.png)

**Plugins:**
- [Mapillary plugin](http://blog.mapillary.com/update/2015/06/25/josm-mapillary.html)
- [Turn-Restriction plugin](http://wiki.openstreetmap.org/wiki/JOSM/Plugins/Turnrestrictions)

**Paint Styles**
- [Traffic Signs](https://raw.githubusercontent.com/species/josm-preset-traffic_sign_direction/master/direction.mapcss) : JOSM Preferences -> Map Settings -> traffic signs

**Changeset Comment:** `Updating turn restrictions in CITYNAME using Mapillary imagery https://github.com/mapbox/mapping/issues/262`
**Source:** Bing/Mapbox, Mapillary

cc @mapbox/team-data

**Comment by maning** [comment]
I'm seeing a lot of **no straight through** detection which was falsely detected from **no entry signs**.  

@srividyacb **Can we relay this issue to mapillary so they can improve their algo?**

See screenshots and nav-map link below:
http://mapbox.github.io/osm-navigation-map/?days=150#17.4/37.36929/-121.91580

![screen shot 2017-01-10 at 16 18 50](https://cloud.githubusercontent.com/assets/353700/21803551/8d178e58-d750-11e6-9a24-6f5431199471.png)
![screen shot 2017-01-10 at 16 15 04](https://cloud.githubusercontent.com/assets/353700/21803548/8b85cf96-d750-11e6-972f-2ca445dac1d1.png)
![screen shot 2017-01-10 at 16 14 26](https://cloud.githubusercontent.com/assets/353700/21803553/8ee9c8f4-d750-11e6-8bda-81d907f84b11.png)
![screen shot 2017-01-10 at 16 10 20](https://cloud.githubusercontent.com/assets/353700/21803549/8b8c5cb2-d750-11e6-884d-546f36cf9860.png)

**Comment by srividyacb** [comment]
@gyllen Can you please look at the above ^^ issue?

**Comment by ybkuang** [comment]
@maning thanks for the feedback (I am the one work with traffic signs at Mapillary most often ;) ) `No straight through` sign look very similar to the false positives you showed above. To improve this, it will super helpful to get your feedback data to our system (which is currently not possible). cc @gyllen

**Comment by Yurasi** [comment]
@maning, a new case of `no straight through` is this type of image:
![image 2](https://user-images.githubusercontent.com/12261974/27112988-beaee170-507f-11e7-8429-f1cb51c117b7.png)

There are a lot of `no_u_turn` detection which was falsely detected. I realized that this restriction is confused with `No Parking Sign`.
See screenshots and [nav-map link](https://mapbox.github.io/osm-navigation-map/?days=150#14.64/40.6230/-73.9727) below:
![image](https://user-images.githubusercontent.com/12261974/27108571-a29912f6-5063-11e7-8f49-b817fd28a419.png)
![seleccion_033](https://user-images.githubusercontent.com/12261974/27112770-b0d7f51a-507e-11e7-9e26-d593a2c76ce7.png)

The Mapillary photos on OPENSTREETMAP NAVIGATION DATA MAP it shows `No Parking` signal, being those correct. But those photos on JOSM are visualised how restriction `no_u_turn` that appear drawed.  I think that not is sure work only with plugin Mapillary on JOSM. We should verify the correct photos.
![image 1](https://user-images.githubusercontent.com/12261974/27112799-df0a98a2-507e-11e7-9f6e-7730c2daae87.png)

There aren't Mapillary photos around of the possible TR detected.
![image 3](https://user-images.githubusercontent.com/12261974/27113124-b1eab404-5080-11e7-8530-4a5d8a1ad4c2.png)

cc. @srividyacb @gyllen @ybkuang

**Comment by ybkuang** [comment]
@Yurasi Thanks for the feedback again. We are now in the process of implementing our feedback system on detected objects. Once that is done, you will be able to teach the machine detection to improve. 

> The Mapillary photos on OPENSTREETMAP NAVIGATION DATA MAP it shows No Parking signal, being those correct. But those photos on JOSM are visualised how restriction no_u_turn that appear drawed. I think that not is sure work only with plugin Mapillary on JOSM. We should verify the correct photos.

It could be that OSM Navigation Data Map is using a different API than JOSM. @gyllen? Can you share the location where you observe this abnormality @Yurasi. Thanks

**Comment by Yurasi** [comment]
Hi @ybkuang :wave: 
There are a lot de cases in this box: [4825,6164](https://mapbox.github.io/osm-navigation-map/?days=150#14.64/40.6230/-73.9727). A particular case is in this [link](https://mapbox.github.io/osm-navigation-map/?days=150#19.18/40.62358/-73.97293).

**Comment by gyllen** [comment]
@peterneubauer Could this be that their Mapillary JOSM plugin is outdated?

**Comment by batpad** [comment]
Seems like we are using 1.6 on osm-navigation-map: https://github.com/mapbox/osm-navigation-map/blob/f0971223a556aaee11b03b12d0b19b2107367098/index.html#L21 :-(

Does this sound like the problem we're seeing here @gyllen ? We can work on trying to update our version - although from looking at [this](https://github.com/mapillary/mapillary-js/blob/master/MIGRATING.md), the work maybe slightly involved. Will update here once I can figure out a rough timeline for us doing this.

**Comment by gyllen** [comment]
@batpad Aha yes I see. We are just about to release `2.6` of `MJS`, it will be coming up somewhere around next week. Its going to include better support for tagging and include examples. If I were you I would wait with any updated until this release.
