### ISSUE TITLE
Update building mapping guide for touching buildings

### ISSUE THREAD

**Issue by planemad** [mapbox/mapping#264]
@Rub21 how did you trace buildings touching each other like this: 

<img width="228" alt="screenshot 2017-01-11 16 33 34" src="https://cloud.githubusercontent.com/assets/126868/21846145/b570afa8-d81b-11e6-8a51-1bba0b7c3610.png"><br>
https://www.openstreetmap.org/#map=19/37.75372/-122.41574

Can you make a short gif showing the operation and add it to our [guide](https://www.mapbox.com/mapping/mapping-common-features/#buildings). We have a community request for this.

cc @Andygol @chtnha @bsrinivasa

**Comment by Andygol** [comment]
@planemad @Rub21 
may be it looks like this - https://www.youtube.com/watch?v=7GQtNnjIO0Q

**Comment by Andygol** [comment]
There is need to have `buildings_tools` and `utilsplugin2` installed in JOSM

**Comment by Andygol** [comment]
There is need to install `buildings_tools` plugin for easing building tracing (Shortcut - <kbd>B</kbd>); `utilsplugin2` for getting some extra tools <kbd>Alt</kbd>+<kbd>X</kbd> for `Split Object`; and use Extrusion Mode <kbd>X</kbd> (<kbd>Shift</kbd>+<kbd>X</kbd>). Then clip nodes to the ways - <kbd>N</kbd>

**Comment by planemad** [comment]
This is so amazing @Andygol ❤️ This is a super tutorial to trace such a building formation in detail! There are a few parts like trying to [get extrude to work](https://youtu.be/7GQtNnjIO0Q?t=2m57s) 🐭 👈 and [this mystery operation](https://youtu.be/7GQtNnjIO0Q?t=4m56s) which might be puzzling for someone new.

I'm seeing the following fundamental concepts:
- Draw a rectangular **b**uilding ([Video](https://youtu.be/7GQtNnjIO0Q?t=4s))
- Create points to e**x**trude on the building wall ([Video](https://youtu.be/7GQtNnjIO0Q?t=11s))
- E**x**trude the building wall to extend to the next building ([Video](https://youtu.be/7GQtNnjIO0Q?t=11s))
- Correct the building profile by e**x**truding any extensions ([Video](https://youtu.be/7GQtNnjIO0Q?t=30s))
-  **s**elect the shared nodes between two buildings and split using `option+x` ([Video](https://youtu.be/7GQtNnjIO0Q?t=3m57s))

**Comment by Andygol** [comment]
@RichRico could you please share a link on your video tutorial here?

**Comment by RichRico** [comment]
This is the link of the video 
https://www.youtube.com/watch?v=VNPfKh_ZI58&t=1s

**Comment by Rub21** [comment]
There are not more actions here!!!
