### ISSUE TITLE
Inconsistent mapping observed from OSM user: pedroyoshio22

### ISSUE THREAD

**Issue by manoharuss** [mapbox/mapping#265]
OSM user: [pedroyoshio22](http://www.openstreetmap.org/user/pedroyoshio22)
OSMCha: [Link](http://osmcha.mapbox.com/?usernames=pedroyoshio22&is_suspect=False&is_whitelisted=True&harmful=False&checked=All)
Hdyc: [Profile](http://hdyc.neis-one.org/?pedroyoshio22)
Overpass: http://overpass-turbo.eu/s/lqF

#### Context

 During validation, I have come across a OSM user who was mapping for Pokemons. More context [on mapping for Pokemons here](https://www.reddit.com/r/TheSilphRoad/comments/5jfnrm/how_to_find_the_new_rural_spawn_points/).

#### Observations

![image](https://cloud.githubusercontent.com/assets/8921295/22193211/c9e66552-e15f-11e6-8042-3b1d826c418d.png)

_changeset: [45376358](http://osmcha.mapbox.com/45376358/) added zig-zag footways and modified previously mapped footway around the park by an experienced user_

![image](https://cloud.githubusercontent.com/assets/8921295/22193277/386e0b42-e160-11e6-9be9-a19fdf21a682.png)

_In the same changeset he added footways over buildings_

![image](https://cloud.githubusercontent.com/assets/8921295/22193301/62ad6916-e160-11e6-9262-d59497fb617b.png)

_Changeset: [44883117](http://osmcha.mapbox.com/44883117/) changed road classification of a teritiary road to a footway_

#### Unresponsive to changeset comment

OSM user [user_5359](http://www.openstreetmap.org/changeset/44882618#map=18/30.16949/-95.46944) commented on the flagged user's changeset 19 days ago and have not received any reply.

All of the changesets by the user are related to mapping footways either through adding or through modification of existing ways. 

Next Actions:

- [ ] Revert all the changesets(18) done by the user on OSM

**Comment by manoharuss** [comment]
cc @planemad @maning @geohacker @batpad @chtnha @krishnanammala

**Comment by manoharuss** [comment]
Text file containing all changeset iD's done by the user is here: https://www.dropbox.com/s/lr8x7xfpwmgh4xl/revert.txt?dl=0

It sorted from top to bottom in the order of latest to oldest changesets on OSM.

**Comment by geohacker** [comment]
I'm starting to revert one by one using https://github.com/woodpeck/osm-revert-scripts

* [ ] 45376358
* [ ] 45376018
* [ ] 45375642
* [ ] 45375623
* [ ] 44929925 
* [ ] 44929866 
* [ ] 44883117 
* [ ] 44882792 
* [ ] 44882770 
* [ ] 44882704 
* [ ] 44882618 
* [ ] 44882541 
* [ ] 44882430 
* [ ] 44882308 
* [ ] 44882236 
* [ ] 44882168 
* [ ] 44882020 
* [ ] 44881854

**Comment by geohacker** [comment]
Just finished reverting all the above changesets: http://www.openstreetmap.org/user/geohacker/history#map=2/29.8/4.0

@manoharuss can you check if all is well? Thank you.

**Comment by manoharuss** [comment]
@geohacker Thank you for reverting these. There were few ways that were not reverted due to community edit over the flagged user edits. I fixed these in this changeset: http://www.openstreetmap.org/changeset/45462549

All good here.
