### ISSUE TITLE
Mapping Points of Interest in San Francisco City

### ISSUE THREAD

**Issue by poornibadrinath** [mapbox/mapping#266]
## Aim: 
  To map points of interest in SF city
  
[Tasking manager](http://tasks.mapbox.com/project/81) 

### Outlined workflow:

- Start with priority areas. Our priority areas cover the important junctions of major streets of SF city. Select and load a block from tasking manager and open in JOSM editor. 
- Select all highways using `highway -type:node` filter and add it to the to-do list.
- Start reviewing the mapillary traces along the list of highways from to-do list.
- Apply the filter `highway|amenity|shop|tourism|historic|(railway & name)|(public_transport & name)|leisure|natural|"addr:housename"|aeroway|power|(building & name)` to show only important features. 
- Manually review the Mapillary traces for the points of interests present/missing from OSM. Filter out traces that is less than an year old. 
- If a POI is already present on OSM, ignore. 
- If seen on the imagery but not mapped, map that particular POI. 
- When relatively finished with adding POIs in a particular block, mark it as done and move onto the next block. 

### Few cases:
- If any indication of a POI present cannot be confirmed using Mapillary, do not map. 
- If there is any POI seen in the imagery but there is no indication of what category it belongs to, do not map. 
- [Muni metro station signage](https://en.wikipedia.org/wiki/Muni_Metro)

![image](https://cloud.githubusercontent.com/assets/12103383/21879917/ded10180-d8c1-11e6-9e07-cc512dc7ef68.png)

**Comment by maning** [comment]
Closing for now, re-open if we have bandwidth to do this.
