### ISSUE TITLE
Check Mapillary or Date of Source Imagery prior to editing?

### ISSUE THREAD

**Issue by talllguy** [mapbox/mapping#271]
Today I [observed an instance](http://www.openstreetmap.org/changeset/45299644#map=18/39.24620/-76.85186) where a Mapbox data team editor modified a newly surveyed road using outdated source data.

**To prevent this from happening again, I suggest that the Date Team compare the imagery / TIGER data dates with the OSM last edit date**. Mapillary data would have also illustrated the inaccuracy in this case, but not in all cases.

For this particular problem, I suggest rolling back [changeset 45299644](http://www.openstreetmap.org/changeset/45299644) by @Yurasi to [changeset 36232893](http://www.openstreetmap.org/changeset/36232893) by @roadgeek. 

Also, for any tasks that target Maryland, I suggest using the Maryland imagery layers found in JOSM or iD. Howard County imagery is now updated to 2016, which would have shown the error above:

![image](https://cloud.githubusercontent.com/assets/1827881/22715048/37891628-ed5d-11e6-8943-cb951276d9dc.png)

**Comment by roadgeek** [comment]
Elliott,

Nice catch.  Removing a road with “Source=GPS” and a good changeset comment is rather annoying!  Darn paid mappers.  ;-)

But what’s up with the new imagery?  It looks like a blend from before and after those houses were built.  Notice the below image has a shadow on the north side of the house shows sidewalk, but the sunny side of the house is dirt in the below image.  https://www.openstreetmap.org/node/37143560/history#map=19/39.24502/-76.85208 <https://www.openstreetmap.org/node/37143560/history#map=19/39.24502/-76.85208>

Robert

**Comment by talllguy** [comment]
@roadgeek I noticed that as well. The issue is that the 2016 orthophotos have been overlaid on the 2013 regular imagery. I think that the two will match once the rest of the western shore counties are updated with the 2016 data.

**Comment by talllguy** [comment]
Update: The changeset was rolled back, thanks! Now, if someone can figure out a way to determine how up-to-date the TIGER data really is, that'd be a useful tool!

Also, when using Bing as a source, consider the [handy Bing Image Analyzer tool](https://github.com/mvexel/bingimageanalyzer) by @mvexel.

**Comment by Yurasi** [comment]
Hi @talllguy. I've already fixed my edit. Thanks for contributing to the workflow while adding/updating ways, as you said there many roads that need to be improved and but also few ones like this case are not errors. Fortunately, we have guys like you who contribute actively to OSM. We definitely will consider your suggest when working on this task. 
Thanks again.
