### ISSUE TITLE
Mapping toll-booths in US

### ISSUE THREAD

**Issue by srividyacb** [mapbox/mapping#272]
A **tolled road** or a **toll-booth** is added to either on a public or a private highway where toll or fee is collected while passing through.

### Aim

**Step 1** : Check for `barrier=toll_booth` mapped as polygon and add all the `barrier=toll_booth` as a node on highway

Physical Toll booths | Transponder toll booths
------ | ------
![image](https://cloud.githubusercontent.com/assets/3423533/22694302/a78eddae-ed6c-11e6-9ebd-9b3568fdbde5.png) | ![screenshot 2017-01-31 15 50 49](https://cloud.githubusercontent.com/assets/3423533/22461167/2c2abc94-e7ce-11e6-9997-3eaa6d98a4df.png)

### Workflow

- Open a way, where a closed polygon is mapped as `barrier=toll_booth`.
- Download extra highway data around the toll-booth.
- Add a node on all the lanes/highways which are entering or exiting the toll-booth with `barrier=toll_booth`. (*Make sure all the lanes have toll-booth tag*)
- Upload the data to OpenStreetMap.
    - Changeset Comment : `Added toll-booth on highways https://github.com/mapbox/mapping/issues/272`
    - Source : `Bing/Mapbox`

**Comment by maning** [comment]
Will revisit later.
