### ISSUE TITLE
Localising names of neighbourhoods for world cities 

### ISSUE THREAD

**Issue by bsrinivasa** [mapbox/mapping#273]
Reference: [China tops the world in outbound tourism](http://www.ecns.cn/cns-wire/2016/01-29/197628.shtml)

#### Objective 

Add localised labels in Chinese for neighbourhoods and suburbs of popular world cities.

### Workflow

- [x] Generate a list of neighbourhoods and suburbs in OpenStreetMap for 20 cites.

- [x] Link Wikidata entities for  corresponding OSM neighbourhood using [Wikimama tool](https://github.com/mapbox/wikimama). Refer the [Diary post](https://www.openstreetmap.org/user/BharataHS/diary/40357)

- [x] Check if target translation exists on Wikidata for the OSM feature using [lookup-osm-wikidata tool](https://github.com/amishas157/lookup-osm-wikidata)

- [x] Translate the labels of these features in Chinese from native Chinese speakers

- [ ] Review and verification of these translations from Chinese community

- [ ] Update Wikidata and OpenStreetMap with community verified translations using [Wikidata-label-upload](https://github.com/amishas157/wikidataLabelUpload) and [osm-name-translation](https://github.com/srividyacb/osm-name-translation) scripts respectively.

**Spreadsheet**: [**Link**](https://1drv.ms/x/s!AtvwHIklPp7QgQwTHUv9WZdBFjEO)

**Comment by jothirnadh** [comment]
@bsrinivasa what is the status of this task?

**Comment by bsrinivasa** [comment]
> Review and verification of these translations from Chinese community

The list of Chinese translations have been updated in [wikidata: project chat](https://www.wikidata.org/wiki/User:Planemad_mapbox/World_places_translation_project#Community_reviewers) seeking Wikidata community review on translations. Waiting for a 👍  before that could be updated in Wikidata and OSM respectively. 

cc: @jothirnadh
