### ISSUE TITLE
Edit war in South Korea

### ISSUE THREAD

**Issue by Andygol** [mapbox/mapping#276]
![image](https://cloud.githubusercontent.com/assets/369696/23065450/566dde98-f51e-11e6-91ac-6a5c9a3c1f0b.png)

Today I found this place in South Korea ☝️ that looks like edit war. I was using **Potlatch 1** to view deleted features.
https://www.openstreetmap.org/edit?editor=potlatch#map=16/37.4661/127.0759
Building complex and features around were deleted and restored several times.

Current state is **deleted**. 

@mapbox/team-data  what we have to do here?

PS Read https://potlatchosm.wordpress.com/2009/04/26/potlatch-011/ about adding custom imagery in Potlatch 1

![image](https://cloud.githubusercontent.com/assets/369696/23065659/4e90cab8-f51f-11e6-8d09-af596ad56e35.png)

**Comment by woodpeck** [comment]
https://www.openstreetmap.org/changeset/46159124
