### ISSUE TITLE
Inconsistent mapping observed from OSM user: ninjaslayer461

### ISSUE THREAD

**Issue by krishnanammala** [mapbox/mapping#277]
I came across one [user](https://www.openstreetmap.org/user/ninjaslayer461) today who seems to be a addicted Pokemon Mapper and doing some fantasy mapping on the Map which strange changeset comments.
![screen shot 2017-02-20 at 9 52 36 am](https://cloud.githubusercontent.com/assets/17470597/23114130/2d631f3a-f763-11e6-9b19-a66bbbaadc32.png)

He is new to OSM and created his account on 19th February and has [**12** changesets](https://www.openstreetmap.org/user/ninjaslayer461/history#map=16/41.9563/-71.2338) all of them having with strange changeset comments.

Link to [Overpass query](http://overpass-turbo.eu/s/mQQ), [OSMCha link](https://osmcha.mapbox.com/?usernames=ninjaslayer461&is_suspect=False&is_whitelisted=True&harmful=False&checked=All).

* Out of **12** changesets, **10** of them are suspicious with strange changeset comments on them
* **6** changesets were already deleted and commented by the community.
* I commented on one of the [changeset](https://www.openstreetmap.org/changeset/46208780) asking for reason behind deleting some buildings.
* There was no reply from the user regarding the changeset comments.

Link to [HDYC user profile](http://hdyc.neis-one.org/?Jigair37)

#### Mapped objects:

* Fake buildings, golf_courts, beach and some fantasy pokemon edits.

#### Some examples with screenshots:

* Fake `natural=wood`
![screen shot 2017-02-20 at 12 13 09 pm](https://cloud.githubusercontent.com/assets/17470597/23114618/254f6e7c-f766-11e6-933d-e768c5f5898b.png)

* Fantasy mapping.
![screen shot 2017-02-20 at 12 13 47 pm](https://cloud.githubusercontent.com/assets/17470597/23114630/3490395c-f766-11e6-8037-1f16884783b1.png)

#### Next actions:

* A 0hr block to let the user know of observed inconsistent mapping and to temporarily stop the user from mapping further until message is read.
* There were some changesets to be cleaned up and preserve mapped objects.

cc @geohacker @maning @planemad @batpad @manoharuss @chtnha

**Comment by krishnanammala** [comment]
The User has been a 0hr block from the DWG.
![screen shot 2017-02-21 at 9 21 37 am](https://cloud.githubusercontent.com/assets/17470597/23150252/344677ba-f818-11e6-9458-9f63e757add9.png)

http://www.openstreetmap.org/user_blocks/1214

cc @maning @planemad @geohacker @manoharuss @chtnha

**Comment by geohacker** [comment]
Awesome. Can we close here?

**Comment by krishnanammala** [comment]
@geohacker We will keep an eye on this user to track whether he again started mapping or not. Closing here
