### ISSUE TITLE
Data team peer review 02/15/2017 - 02/21/2017

### ISSUE THREAD

**Issue by kupendrayadav** [mapbox/mapping#279]
Last peer review ticket: #275   

#### Mapping projects to be reviewed:

-  [To-Fix](https://github.com/mapbox/data/issues/2357)
- [Turn lanes in LA](http://tasks.openstreetmap.us/project/81)
- Missing streets.

#### Instructions

* Download `.osm` files for last week.
 - [2017/02/15- 2017/02/21](https://s3.amazonaws.com/mapbox/osm-history-processor/day/latest.osm.tar.gz)

* Extract the tar file and select any OSM file of the team member.
* Each team member will have an .osm file of edits for the last seven days. For example: `latest-andygol.osm`. Select any `.osm` file and open the data in JOSM. 
* If you don't find any osm file of a particular team member, then it means that user has not edited during the week.
* Examine user edits in detail. In JOSM, select a random small area edited by the user and press `3` to zoom.
* Download the latest data in OSM as a new layer and add a filter `Cmd + F` to see only the user's edits, e.g. `user:andygol`.

![andyfilter3](https://cloud.githubusercontent.com/assets/6770741/14813545/cf7409d2-0bbf-11e6-9389-5b6132b7bb55.gif)

* Select a way/node and load the the history (`Ctrl + H`), the changeset comment will describe what specific project the user was working on.
* To get an OSM link to the object, click `Cmd + Shift + H`. 
* Note down any feedback for each user in this ticket or comment directly in the changeset. Use this format:

```
username
changeset link - issue to fix
```

* @krishnanammala @chtnha @kupendrayadav or @dannykath will post the feedback in the ticket (Use Github handle because OSM name is different from Github name) and make necessary changes on the same day.
* Close the ticket once user's have fixed their edits.

For clarifications, discuss with the @mapbox/team-data in this ticket.

**Comment by kupendrayadav** [comment]
@calfarome

### Trace the highway links matching exactly to the imagery 

- https://www.openstreetmap.org/way/475111427/history
- https://www.openstreetmap.org/way/475111430/history
- https://www.openstreetmap.org/way/475111437/history

**Comment by kupendrayadav** [comment]
@jothirnadh

#### `building=yes` for leisure=park

- https://www.openstreetmap.org/way/475421301/history

**Comment by kupendrayadav** [comment]
@Andygol

### Duplicated building
- https://www.openstreetmap.org/way/475143261/history

**Comment by kupendrayadav** [comment]
@bsrinivasa 

### Split dual carraigways
- https://www.openstreetmap.org/way/7349339/history

### Connect to the other dual-carraigeway, if there is a turnlane, it should connect to another road
- https://www.openstreetmap.org/way/474601629/history

**Comment by kupendrayadav** [comment]
@kupendrayadav

### Straighten roads along intersections
- https://www.openstreetmap.org/way/474793441/history 
- https://www.openstreetmap.org/way/240056662/history

**Comment by kupendrayadav** [comment]
@luiswalter 
### Align the joinings of the roads very well
- https://www.openstreetmap.org/way/80314177/history
- https://www.openstreetmap.org/way/239504792/history
### Please fix the Traffic signals
- https://www.openstreetmap.org/node/4687241577/history
- https://www.openstreetmap.org/node/4687241578/history

**Comment by kupendrayadav** [comment]
Thanks for the review. My changes 👇 

- https://www.openstreetmap.org/way/474793441/history

**Comment by jothirnadh** [comment]
Thanks for the review. My changes:

https://www.openstreetmap.org/way/475421301/history

**Comment by bsrinivasa** [comment]
Thanks for the review. Here are the fixes.
- https://www.openstreetmap.org/changeset/46307355
- https://www.openstreetmap.org/changeset/46307420

**Comment by luiswalter** [comment]
Thanks for the review
### Align the joinings of the roads very well
- https://www.openstreetmap.org/way/239504792/history#map=19/33.94619/-117.40059
- https://www.openstreetmap.org/way/80314177/history#map=19/33.94619/-117.40060
### Please fix the Traffic signals
- https://www.openstreetmap.org/node/4687241578/history#map=19/33.94521/-117.45286
- https://www.openstreetmap.org/node/4687241577/history#map=19/33.94558/-117.45343

**Comment by calfarome** [comment]
Thanks for the review team: Here are the fixes.

- https://www.openstreetmap.org/way/475111427/history fixed
- https://www.openstreetmap.org/way/475111430/history fixed
- https://www.openstreetmap.org/way/475111437/history fixed
- https://www.openstreetmap.org/node/54653910/history fixed
- https://www.openstreetmap.org/node/54559021/history fixed

**Comment by Andygol** [comment]
>Duplicated building

>https://www.openstreetmap.org/way/475143261/history

fixed
https://www.openstreetmap.org/changeset/46311661

**Comment by krishnanammala** [comment]
Everyone fixed the issues. Closing
