### ISSUE TITLE
Inconsistent mapping by OSM user

### ISSUE THREAD

**Issue by osMatt** [mapbox/mapping#281]
Hi, I just came across the edits by https://www.openstreetmap.org/user/aNut and https://www.openstreetmap.org/user/Nuting%20Like%20a%20good%20Nut. Some of them seem "real" (but would need some fixing, e.g. adding houses, but with bad names such as `name=XYZ's house`), others seem more like vandalism (e.g. re-naming streets into bogus names). Unfortunately, I don't have time to check (and fix or revert) all the edits by these users now, so it would be appreciated if you could take a look at these! Thanks a lot!

**Comment by krishnanammala** [comment]
Hi @osMatt ! Thanks for opening the ticket and letting us know about the inconsistent mapping happening by the 2 users.

I have gone through the edits of both the users and observed that Most of the data are real expect the tagging , naming the roads, buildings, invalid areas and nodes seems inappropriate. So, I went ahead and made corrections for all the changesets of the users , keeping the good data edits and deleting the bad edits. 

Also commented on the changesets, to let the user know about OpenStreetMap and the quality of data to be added.
1. https://www.openstreetmap.org/user/aNut/history#map=2/42.1/5.3
2. https://www.openstreetmap.org/user/Nuting%20Like%20a%20good%20Nut/history#map=3/28.84/-0.09

Will keep an eye on the users for the next actions. If they continue to do so, will file a report to the DWG.

Once again thanks for the ticket 🙇 . Let us maintain the quality of data in OSM and make OpenStreetMap the best.

**Comment by osMatt** [comment]
Thanks a lot for the swift response!

**Comment by krishnanammala** [comment]
Fixed the issues. No next actions. Closing
