### ISSUE TITLE
Moving multipolygon tags from outer way to the relation of water bodies

### ISSUE THREAD

**Issue by jothirnadh** [mapbox/mapping#282]
### Objective:
To move all the tags of a multi-polygon from outer way to the relation of water bodies
### To-fix Task: 
[Moving multipolygon tags from outer way to the relation of water bodies ](https://osmlab.github.io/to-fix/#/task/overlappingwaterbodies)

### Why we need to fix this?
For adding a [multipolygon](https://wiki.openstreetmap.org/wiki/Relation:multipolygon) it is necessary to define both the boundaries of the outer ring and the inner ring along with the tags assigned to the relation (multipolygon). But as per older convention, there are cases where the tags are assigned to the way of the outer ring and the assigned relation is just tagged with a `type:multipolygon`.

**Example:**

![screen shot 2017-03-03 at 3 32 34 pm](https://cloud.githubusercontent.com/assets/8401827/23546703/cd19e1e6-0026-11e7-96a0-852e879ee5ab.png)

*Multipolygon in OSM without any tags*

![screen shot 2017-03-03 at 3 32 44 pm](https://cloud.githubusercontent.com/assets/8401827/23546704/cd1c6c22-0026-11e7-92a6-696e4344a2ac.png)

*Tags assigned to the outer way*

![screen shot 2017-03-03 at 3 33 21 pm](https://cloud.githubusercontent.com/assets/8401827/23546705/cd1cb84e-0026-11e7-89d7-e72c2c4b8d52.png)

*Tags assigned to inner way*

### Workflow:
* Open the to-fix interface and go to the [Overlapping water bodies](https://osmlab.github.io/to-fix/#/task/overlappingwaterbodies) task.

![screen shot 2017-03-06 at 3 41 53 pm](https://cloud.githubusercontent.com/assets/8401827/23605632/7baf2fd2-0283-11e7-9ff0-d1f8585a82a0.png)

* Load the feature into [JOSM](https://wiki.openstreetmap.org/wiki/JOSM)
* Move the tags assigned to the outer way ring to the relation.
* Run the validator and check if there are any broken relation issues; if so fix them and upload it to OpenStreetMap

**Note:** If the to-fix task doesn't remotely connect with JOSM do the following:
* Go to `https://localhost:8112/version` and accept the browser security exception (Advanced -> Proceed anyway)

**Changeset comment:** `Moving multi-polygon tags from outer way to relation using to-fix #https://github.com/mapbox/mapping/issues/282`

**Source:** Bing/ To-Fix/ JOSM-validator

@mapbox/team-data @ajithranka @ajashton

**Comment by Andygol** [comment]
There is possible to create script for [`Scripting` ](https://gubaer.github.io/josm-scripting-plugin/)plugin to make moving tags from `outer` way to the relation in one click.  🔧 👨 💭

**Comment by jothirnadh** [comment]
Great work guys 🚀 ! We fixed 330/500 water body multi-polygons today 💥 . Let's continue this mapping quest tomorrow as well and target to hit it out completely. Here is the breakdown of our mapping effort for today: 

![screen shot 2017-03-07 at 6 34 30 pm](https://cloud.githubusercontent.com/assets/8401827/23657698/60eaf2fc-0365-11e7-8093-f050ac5c6c9f.png)

**Comment by maning** [comment]
I found this way that is part of two relations.  One is outer and the other as inner.

The imagery from Bing and Mapbox shows its underwater.  Since we don't have other means to verify in this exist, skipping for now.

![flooded_water](https://cloud.githubusercontent.com/assets/353700/23696900/a887d160-040b-11e7-8911-6568c42589c1.gif)

WayID: https://www.openstreetmap.org/way/43444319/

**Comment by jothirnadh** [comment]
Great work everyone 👏 ! We moved **500** water body multi-polygon tags from an outer way to the relation. Out of these 500, we came across **7** issues which are already fixed by community members. As mentioned in the [above comment](https://github.com/mapbox/mapping/issues/282#issuecomment-284717263) we also fixed some wrongly tagged islet's and also added new islets. 

### What we learned from this task:
- To-Fix plugin integration for all To-Fix tasks
- Missing cut feature in JOSM. We have options to copy and paste tags, but we cannot cut tags or features. This feature can be of great help for this kind of cases.
- Considering area covered as one parameter as we came across many small water bodies while fixing

### Next actions:
- [ ] @ajashton to post the new set of multi-polygons that can be fixed

Join in if you are interested in mapping or let us know how we can improve the workflow at any time 🙏
