### ISSUE TITLE
Validate Tanzania mapping to eradicate FGM

### ISSUE THREAD

**Issue by kupendrayadav** [mapbox/mapping#283]
### Hot activation to eradicate FGM

Geographic information around remote parts of Africa are often unavailable for women. Information about amenities, facilities and places to seek are often undocumented. This is even more relevant with regards to Female Genital Mutilation. Rescue NGO organizations lack the geographic information to reach out to women in need.

There is a Humanitarian OSM activation addressing this problem with an objective to map buildings, roads as seen through Bing and Satellite imagery. This has been initiated with a HOT mapping task focused on Serengeti district, Tanzania.

Let's validate the mapping project and provide feedback to mappers

- [ ] http://tasks.hotosm.org/project/2261 (validation)
- [x] http://tasks.hotosm.org/project/2501 (mapping)

Read through the instructions of each task. If there are a few mistakes, fix them. If most of the features (i.e. buildings) have a lot of errors, invalidate and give advice to the respective contributor on how to improve the quality of mapping.

**See also**

* [Online mapping tool gives FGM runaways a path to help](https://www.theguardian.com/society/2017/feb/06/online-mapping-tool-gives-fgm-runaways-a-path-to-help)

cc @mikelmaron @maning

**Comment by AdamLombard** [comment]
Really glad this is your next HOT focus! 
Taking tomorrow off to contribute as much as I can. :)
