### ISSUE TITLE
Older mapbox imagery added over the Bucharest city

### ISSUE THREAD

**Issue by razor74** [mapbox/mapping#284]
Hello, 
Can someone help me with this problem? I have a problem regarding mapbox imagery in Romania over the Bucharest city. Recently someone ( probably)take out new imagery from 2015 and put older imagery - i think 2012-2013. Alot of new info which could collect from that imagery ( 2015) dissapeared. And now we cannot collect anything new about new road infrastructure which is now almost finished or is currently in development in Bucharest city... In past year , only me i drawed towsands of new buildings from that set of imagery, and now i cannot refer to imagery from which i drawed. 
The previous set of imagery must be added again over the Bucharest City if it possible. 

Thanks,

Razvan

**Comment by pratikyadav** [comment]
Hey @razor74,
We regularly improve our imagery all over the world. This recent change was targeted to improve imagery aesthetic not only in the city of Bucharest but a large area of ~50k sq km around it. This is not our last update here and we will keep improving our imagery coverage.

Thanks.

**Comment by razor74** [comment]
In this case , here is more important to have much recent imagery. Not aestetic. We cannot collect any new data from this aestetic set of imagery. Is for no use now... Here are more changes continuously in road infrastructure, and marginal cvartals are extended even now. Alot of new buildings, streets and parkings apears in that imagery and now gone. Mappers from here now cannot draw new buildings from these cvartals .We need that set of imagery in place of aestetic one but older and with no use.

**Comment by strainu** [comment]
@pratikyadav , just like @razor74, I am a bit puzzled by your explanation, and I would like to understand a bit better your reasoning if possible. Is there another usecase for Mapbox's imagery that would make it preferable to prioritize aesthetics vs recency? Bucharest and the area around it is already well-mapped, so having old, but clear images does not bring much value to mapping compared to recent imagery that shows new developments.

**Comment by razor74** [comment]
Here http://www.openstreetmap.org/#map=15/44.4502/25.9929  and here http://www.openstreetmap.org/#map=16/44.4587/26.2204 and here for example we still have to collect alot of new buildings and possibly some new streets.  Here for example is a big infrastructure changes in process. A big new passage is almost finished. We collect by gpx track the changes, but some of them are already visible on the mapbox recent imagery and only for comparation well be fine to be there. And here at Margina http://www.openstreetmap.org/#map=15/45.8599/22.2503 a new motorway link was opened to traffic and will be fine is some much more actual imagery will be available at least only in this area...
Best regards,
Razvan
