### ISSUE TITLE
Ayuda Humanitaria Hot en Peru

### ISSUE THREAD

**Issue by luiswalter** [mapbox/mapping#285]
(in English below)

Ahora en Peru, se esta registrando un fenomeno natural llamado "El Niño" el cual provoca grandes lluvias en la sierra peruana aumentado el cause de los rios y estos provacan grandes desbordamientos en la zona de la costa peruana llamados "Huaicos". 
Este fenomeno natural hasta el momento esta provocando destrucciones en en las ciudades de Norte de Peru y otras ciudades de la costa como Lima, Ica y Arequipa.
Como parte de la comunidad de OSM, ofrecemos nuestra ayuda para colaborar en el mapeo de estas ciudades  y perturando Tareas en Hot.

#### Estrategia:

Esta oportunidad nos permitira incorporarnos aun mas con la comunidad. desarrollando lazos mas fuertes con ellos.

Revisare de cerca como trabajan y como se comunican dentro de su organizacion

Buscare encontrar personas dispuestas a colaborar mas intesamente con nuestro evento LAtam 2017.

Aqui seguire informando sore lo que sucede, estare todo el fin de semana ayudando y trabajando directamente con ellos.

#### Pasos a seguir:

Buscamos los puntos donde se registran mayor destruccion y  tomarlos como prioridad en las tareas Hot

Encontrar puntos de ayuda y acopio para poder ser mapeados

buscamos acercarnos al [Instituto Nacional de Defensa Civil](http://www.indeci.gob.pe/contactos.php) para poder trabajar con ellos.

#### preguntas

Necesito saber como aperturar estas tareas, No puedo realizarlo.

@mapbox/team-data 

Cc. @michaelsteffen @ediyes @piligab @Rub21 

--------
Right now in Peru is a natural phenomenon called "El Niño" is causing huge amounts of rain in the Peruvian sierra, causing rivers to overflow, especially in an area near ​​the Peruvian coast called "Huaicos".
The greatest destruction is taking place in the cities of Northern Peru and other coastal cities like Lima, Ica and Arequipa.
As part of the OSM community, we are offering our help to collaborate in the mapping of these cities and disturbing Tasks in Hot.

#### Strategy:

This opportunity will allow us to become even more involved with the community, while developing stronger bonds.

We will be able to see up-close how they work and how they communicate within the organization.

Though this I hope to connect with people willing to collaborate more intensely with us in SOTM LatAM 2017.

I will be in Lima all weekend working directly with them on this effort, continuing to learn about the processes. 

#### Mapping Steps:

We look for the points where the greatest destruction is recorded and mark them as a priority in the HOT tasks.

Find helpul points and organize them to be mapped

We seek to approach the [Instituto Nacional de Defensa Civil](http://www.indeci.gob.pe/contactos.php) to work with them.

#### Questions

I need to learn how to open these tasks - not sure how it works at the moment.

**Comment by luiswalter** [comment]
El dia de ayer fui a la oficinas de INDECI, converse con el Asesor de la Alta Dirección Oficina Central en Lima, el señor Oscar Coello Salaverry. Explique el trabajo que deseamos realizar juntos con ellos. estan muy interesados.

Me solicitaron enviar un correo explicando el trabajo de HOT en casos de Desastres Naturales y el organizara una reunion con los gerentes generales del [CEPIG](http://www.indeci.gob.pe/contenido.php?item=MjI2)

Esto sera para la segunda semana de Abril, ya que ahora tienen a todo su equipo completo que estan trabajando en zonas de emergencia y no tienen tiempo para tener una reunion.

Basicamente esta reunion sera para intercambiar experiencias de como trabajan ellos en casos de emergencia y como nosotros apoyamos desde HOT en estos proyectos.

**Comment by luiswalter** [comment]
Tasks were enabled in HOT, as a way to improve the base map in the areas affected by the Huaicos. The main priority tasks are these http://tasks.hotosm.org/project/2679#task/59 and http://tasks.hotosm.org/project/2679#task/59

Cc. @mapbox/team-data

**Comment by luiswalter** [comment]
@maning We need to enable a task in the city of Trujillo, is this possible?

**Comment by luiswalter** [comment]
Yesterday and today we continued working with the OSM Peru Community, recognizing that agencies can intervene to help improve the base maps of the emergency zones, it is certainly a very productive work, very few people know OSM and now they want to work with US.

As Cesar Urrutia of the company SpaceData, He is interested in exchanging work experiences to be able to work together, His experience with Drones could help us in these types of jobs.

On Monday 20, we will have a meeting with members of the Community of OSM (Jhonatan and Alfonso) and Cesar.

I want to stay a few extra days to be able to get more involved in the community. I know we have a very tight schedule this week, but I want to do this work that will help the team in the organization of the event LATAM 2017

@Rub21  @ediyes

**Comment by luiswalter** [comment]
### Summary of Meetings
#### CONIDA
- I can not display images in a time not less than 21 days and the quality of the images depend a lot on the weather
- They seek that the delivery of images is legal, they have to send the documents asking for such images to CONIDA (a lot of bureaucracy)
- They want to have a much deeper meeting for the month of April with the Director General (José Pasapera)

#### OSM Community Peru
- Image processing Drones to JOSM
- Workshop at the University San Marcos on cartography in JOSM - Supporting in HOT Tasks
- [ANPE] (http://www.anpeperu.org/) - Cartography Workshop
- [Human Rights Coordinator] (http://derechoshumanos.pe/coordinadora-nacional-de-derechos-humanos/) Marina Navarro, requests the OSM data to be used as reference in disaster areas.
- Valerya Clavijo (Geographical Engineering) and Eduardo Andamayo (Geographical Engineer) joined our group.

@maning

**Comment by maning** [comment]
@luiswalter Great updates!  Next actions for us are:

- Validate TM tasks after the San Marcos and ANPE mapping workshop.
- Get clarity with the team doing drone imagery on how we can access imagery to prepare TMS that mappers can use in JOSM/iD.

**Comment by luiswalter** [comment]
@maning  Here the first images taken by Drones, used in Punta Hermosa http://tasks.hotosm.org/project/2701#task/123 They used this [picture](http://tiles.openaerialmap.org/58d25f5216e0d9001037459e/0/cea617ee-27c6-418d-b883-a3cfa0dd4277/preview#16/-12.2974/-76.7690)

**Comment by Rub21** [comment]
Per conversation on today scrum, we will involved for one hour in Mapping some hot projects. 

@luiswalter  podrias ver donde podemos trabajar por almenso una hora, que lugar vez que seria necesario.

**Comment by luiswalter** [comment]
@Rub21 - Pienso que esta tarea es la mejor para hacer validacion hoy en la tarde o mañana en la mañana. Ahora mismo la comunidad esta mapeando la zona de emergencia. Es la primera vez que trabajamos con Imagenes de Drones. y las imagenes son muy buenas.

I think this task is the best to do validation today in the afternoon or tomorrow in the morning. Right now the community is mapping the emergency zone. This is the first time we have worked with Drones Pictures. And the images are very good.

**Comment by luiswalter** [comment]
@maning @Rub21  Up to now 6 tasks have been created in different parts of Lima. There is still a need to create tasks for the Northern Zone of Peru. We do not have picture coverage of Drones for this project. We are in coordination with Spacedat, so that you can help us with this project.

http://tasks.hotosm.org/?sort_by=priority&direction=asc&search=peru
![hot](https://cloud.githubusercontent.com/assets/17984615/24362566/ce3117d4-12d2-11e7-900d-b58bd385d301.png)

**Comment by luiswalter** [comment]
The community is working closely with Blake Girardot, they are translating OSM videos guides from Youtube. For all new users in Latin America

![video](https://cloud.githubusercontent.com/assets/17984615/24363101/5fbd6652-12d4-11e7-9d4a-2b962ebd454f.png)

**Comment by luiswalter** [comment]
Ayer tuve una conversacion con Cesar Urrutia Gerente de la  Empresa Spacedat, me informo que ahora estan dispuestos a viajar a Piura, la zona mas golpeada por los huaicos en Peru.

Tuvo una conversacion con la Marina de Guerra del Peru y el Ministerio de Educacion para que viajen el dia Lunes 3 de abril por 2 o 3 dias a la zona de emergencia, realizar vuelos y registrar todo.

Necesitan ayuda ya que su equipo de trabajo no conocen Piura y solicito que si tenemos algun contacto dentro de la comunidad para realizar este trabajo.

@Rub21 @samely Tenemos algun contacto de la Comunidad en Piura.

**Comment by luiswalter** [comment]
Now I am a manager of HOT Tasks, thanks to Blake Girardot, I will be in charge of opening tasks related to the Huaicos in Peru, this will give me greater reach within the community of OSM Peru.

Right now the team Spacedat travel to the city of Piura to take photographs of that city, thanks to the Peruvian Government this trip is achieved, they will stay 4 days to do this work.

OpenStreetMap shows up on environmental issues like now. The government now knows OSM and seeks within its maps to find solutions to their problems of territorial organization in cases of emergencies.

------

Ahora soy administrador de Tareas HOT, gracias a Blake Girardot, me encargare de aperturar tareas relacionados con los Huaicos en Peru, esto me dara mayor alcanze dentro de la comunidad de OSM Peru.

Ahora mismo viajan el equipo Spacedat a la ciudad de Piura para hacer tomas fotograficas de esa ciudad, gracias al Gobierno Peruano se logra este viaje, se quedaran 4 dias para realizar este trabajo.

OpenStreetMap se muestra en problemas ambientales como ahora. El Gobierno conoce ahora OSM y busca dentro de sus mapas encontrar soluciones a sus problemas de organizacion territorial en casos de emergencias.

**Comment by luiswalter** [comment]
Today a new task is opened in HOT for the city of Catacaos, where drones images are used to make the layout.
Here is the homework

The Spacedat team is still working in the department of Piura, using Drones to take more photos of other cities.

We are debating how to help in HOT, if creating new tasks with Bing images with the help of the Mapbox Satelite team or support directly by drawing in the enabled tasks.

------

El dia de hoy se aperturo una nueva tarea en HOT para la ciudad de Catacaos, donde se usan imagenes drones para realizar el trazado.
Aqui la tarea

El equipo de Spacedat aun siguen trabajando en el departamento de Piura, usando Drones para realizar mas fotografias de otras ciudades.

Estamos debatiendo como ayudar en HOT, si creando nuevas tareas con imagenes Bing con ayuda del equipo de Satelite de Mapbox o apoyar directamente trazando en las tareas habilitadas.

@Rub21 @Juliannebg

**Comment by piligab** [comment]
According this [Luis's comment](https://github.com/mapbox/mapping/issues/285#issuecomment-287633771) we validated at 100%

![image](https://user-images.githubusercontent.com/19536044/33209896-021ec556-d0e6-11e7-97cf-932e14f93f6f.png)

**Comment by luiswalter** [comment]
Thanks for validating the tasks.
no more actions
