### ISSUE TITLE
Possible spam deletion of a boundary relation in Canada

### ISSUE THREAD

**Issue by SrihariThalla** [mapbox/mapping#286]
Changeset - https://www.openstreetmap.org/changeset/47087434

Relation history - https://osmlab.github.io/osm-deep-history/#/relation/1954127

User - https://www.openstreetmap.org/user/outdoorcoversca2/

Thanks!

**Comment by Andygol** [comment]
@SrihariThalla thank you for you collaboration 👍 

This was a spam deletion which I reverted. See https://openstreetmap.org/browse/changeset/47120538
