### ISSUE TITLE
Validator role in OpenStreetMap tasking manager 

### ISSUE THREAD

**Issue by kupendrayadav** [mapbox/mapping#289]
The Tasking Manager  is going to have a role for "validator" which will be a global list of folks who are considered to be qualified to validate projects.

### How this works:

- Project managers who are creating projects in OpenStreetMap tasking manager will have an option to select the validators to validate their projects.
- The project manager who does not select this option means everyone can validate their project just like now.

## The list of folks from BLR team who are good and active at validating the projects:

- [x] @abhisheksaikia  
- [x] @chtnha 
- [x] @krishnanammala 
- [x] @jothirnadh 
- [x] @bsrinivasa 
- [x] @poornibadrinath  
- [x] @nikhilprabhakar 
- [x] @srividyacb 
- [x] @planemad 
- [x] @maning 
- [x] @manoharuss 
- [x] @kupendrayadav 

cc @mikelmaron @maning @planemad

**Comment by mikelmaron** [comment]
Thanks @kupendrayadav. Note this will only add a flag in your HOT Tasking Manager profile that you are a `validator`, which will give another level of access. There will be no obligation to validate.

@kupendrayadav I'm happy for you to go ahead with this list, and anyone else who is interested. Could you update the [spreadsheet](https://docs.google.com/spreadsheets/d/18YmffxfkKCmtPBunKZnIxRgbmk9NdT0eHR0NMHeKhxY/edit#gid=264139089)?

**Comment by kupendrayadav** [comment]
@mikelmaron Updated the spreadsheet with `x` mark beside the name of our folks.

**Comment by mikelmaron** [comment]
thanks @kupendrayadav
