### ISSUE TITLE
To-fix: Double places

### ISSUE THREAD

**Issue by Yurasi** [mapbox/mapping#290]
Currently, there are many duplicated places in OpenStreetMap,which is not really good, and generates confusion some cases which we found are::point_down: 

- **Case 1:** Two points with the same tags `name:*` and `place:*`

![screenshot from 2017-04-28 11-18-49](https://cloud.githubusercontent.com/assets/1152236/25537626/de16c8a6-2c04-11e7-84c3-6c0a37254b5a.png)
[Node 1](https://www.openstreetmap.org/node/3009740294/history),[Node 2](https://www.openstreetmap.org/node/3009740295/history
)
- **Case 2:** A point and a polygon,  with the same tags `name:*` and `place:*`

![screenshot from 2017-04-28 11-12-14](https://cloud.githubusercontent.com/assets/1152236/25537628/e01ba43c-2c04-11e7-8b34-6676e9ee5158.png)
[Node](https://www.openstreetmap.org/node/360002227/history), [Way](https://www.openstreetmap.org/way/45781048/history).

# Objective

Cleaning up doubled places in OpenstreetMap.

# Tasks

We have a to-fix task, that  contains the doubled places issues

https://osmlab.github.io/to-fix/#/stats/doubleplaces

### Changeset comment

```
Fix double places:* and with the same name
```

### Tools
- If using iD editor, work with [To-Fix web](https://osmlab.github.io/to-fix/#/stats/doubleplaces).
- If using JOSM, work with [Josm-tofix-plugin](https://github.com/osmlab/josm-tofix-plugin).
- Use Replace Geometry (Shortcut: `E`).
- Add inverse filter: place.

<GIF del plugin>

# Instructions to fix

- When two place nodes exist, combine the tags into one, and set the place in the center of these nodes.
- When a landuse and a place node exist, combine the tags into one, replace geometry.
- When a boundary and a place node exist, create a relation `type=boundary` where the polygon will be the `outer` role and the node place will be the `admin_centre` or `label` role.
- When a landuse, boundary and node exist, combine the tags from landuse to boundary, except `landuse tag`, after delete the landuse. Check or add the place node into relation with `admin_centre` or `label` role.

> - `admin_centre` - The node that is considered to be the administrative centre (usually the node tagged with place=city/town/village)
> - `label` - The node that is considered to be a hamlet, village or neighbourhood.

**More info:** 
- http://wiki.openstreetmap.org/wiki/Relation:boundary
- http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative
- http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#admin_level
- http://wiki.openstreetmap.org/wiki/Key:place
- http://wiki.openstreetmap.org/wiki/Talk:Relation:boundary
- https://wiki.openstreetmap.org/wiki/Relation:boundary#Relation_members

### Case 1:
![point](https://cloud.githubusercontent.com/assets/12261974/25584984/fed3d27c-2e5d-11e7-9d74-fe49c0fc56e6.gif)
_Select the two place points at the same time, after press the `E` key (Replace Geometry)._

### Case 2:
![replace](https://cloud.githubusercontent.com/assets/12261974/26115554/ea8a9804-3a25-11e7-9cd9-94e81a91acf8.gif)
_Select the place point and the landuse at the same time, after press the `E` key (Replace Geometry)._
 
### Case 3
![boundary](https://cloud.githubusercontent.com/assets/12261974/26115207/ef61ddac-3a24-11e7-8a82-6e4c0ab10c5c.gif)
_Select the boundary and node at the same time, then add these in a relation of `type=boundary`. Also add the place node into the relation with the rol `admin_centre`._

### Case 4
![boundary_landuse](https://cloud.githubusercontent.com/assets/12261974/26123049/3c15ccc0-3a3f-11e7-81bf-b78da21a6693.gif)
_Select the landuse and copy the tags that lack into the boundary, after delete that landuse. Add the place node into the relation with the rol `admin_centre`._

# How are we doing the error detection?

We are using [osm-qa-tiles](https://osmlab.github.io/osm-qa-tiles/) and osmlint [doublePlaces](https://github.com/osmlab/osmlint/tree/master/validators/doublePlaces) to get a geojson file of these issues and then we uploaded into [to-fix](https://osmlab.github.io/to-fix/#/stats/doubleplaces).

# Who will work on these tasks?

Anybody on the community who is interesting on cleaning up these issues.

### Question

Any questions, please drop a comment to discuss it.

cc. @mapbox/team-data

**Comment by piligab** [comment]
In this case, How does it solve?
There are 2 points and a landuse with the same name  **San Francisco Del Monte Subdivision**
https://www.openstreetmap.org/way/153303599
![case](https://cloud.githubusercontent.com/assets/19536044/25725170/7b8313d6-30e4-11e7-945d-ed29eb567c5d.png)

In OpenStreetMap, It shows like this https://www.openstreetmap.org/#map=19/14.43091/121.01238
![case2](https://cloud.githubusercontent.com/assets/19536044/25725169/7b7f566a-30e4-11e7-8f9e-d79be35e16f4.png)

cc. @Yurasi

**Comment by Rub21** [comment]
:hand:   @ian29 @ajashton @ingalls , could you help us on this issue  https://github.com/mapbox/mapping/issues/290#issuecomment-299311120?

**Comment by Andygol** [comment]
1. Due to the fact that node (https://www.openstreetmap.org/node/3929066188) is inside of the "Veraville Homes 1" (https://www.openstreetmap.org/relation/3291321) I I would delete this node.
1.  The node https://www.openstreetmap.org/node/255059566 is good to merge with https://www.openstreetmap.org/relation/3291321 as they are the same.
1. The node https://www.openstreetmap.org/node/255064224 is good to merge with https://www.openstreetmap.org/way/153303599 as they are the same too

cc @Yurasi @piligab

**Comment by Yurasi** [comment]
![case_pili](https://cloud.githubusercontent.com/assets/12261974/26114665/810f2748-3a23-11e7-9431-de7185c080e1.gif)
This is the solution recommend by @Andygol. Thanks :)  
cc. @Andygol @Rub21 @piligab.
