### ISSUE TITLE
Turn lanes, revisited

### ISSUE THREAD

**Issue by mvexel** [mapbox/mapping#294]
Hey team, sorry to hijack this repo but I know you guys are interested in this topic too. I was struggling with how to correctly and completely map a complex intersection, taking into account **both** lane geometry / marking and lane connectivity. I posted a mapping challenge [on my diary](https://www.openstreetmap.org/user/mvexel/diary/41156) to see how others would do this. I'm curious to hear your opinions!

**Comment by planemad** [comment]
Pinging our tagging expert @Andygol
