### ISSUE TITLE
To-fix for overlapping and crossing buildings in Zimbabwe

### ISSUE THREAD

**Issue by kupendrayadav** [mapbox/mapping#295]
As part of Malaria elimination campaign under Clinton Health Access Initiative, a lot of community members and new mappers are contributing towards mapping buildings in the Zimbabwe from past few months. We gave our total support through validating tasks in Zambia and mapping in Zimbabwe. You can go through [#274](https://github.com/mapbox/mapping/issues/274) for detailed context

Due to sharing same task boundaries and few newbie errors, we observed a **10,034** overlapping and crossing building issues in Zimbabwe. We created a  [To-fix](https://osmlab.github.io/to-fix/#/task/crossingbuildinginzimbabwe) task for the overlapping and crossing buildings in Zimbabwe. 

### Points to remember:

![hot gif](https://cloud.githubusercontent.com/assets/20293098/25708354/e206e384-3103-11e7-83d2-264333872137.gif)

- Whenever you find duplicate buildings mapped, better to keep building mapped according to Digital globe imagery as it is the latest and updated imagery.
- It’s also fine to keep buildings which are in Bing imagery, even though they are not in DG imagery.

     It would be great If we complete this project before deadline i.e June 3rd week. @kupendrayadav and @luiswalter coordinate with their respective teams and will post the progress of the project daily.

**To-fix link**: https://osmlab.github.io/to-fix/#/task/crossingbuildinginzimbabwe

**Digital globe Imagery**: `tms:https://api.mapbox.com/v4/digitalglobe.2lnp1jee/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZGlnaXRhbGdsb2JlIiwiYSI6ImNpd3A2OTAwODAwNGUyenFuNTkyZjRkeWsifQ.Y44JcpYP9gXsZD3p5KBZbA`

cc @mikelmaron @maning @Rub21 @luiswalter

**Comment by mikelmaron** [comment]
@kupendrayadav TY. @luiswalter @Rub21 let's keep track of daily progress by both teams on this ticket

@kupendrayadav -- is the Bing imagery more recent than DG? that's what I gather from your bullets above

**Comment by kupendrayadav** [comment]
@mikelmaron No, DigitalGlobe is latest and updated imagery than Bing. I will update the point now.

**Comment by luiswalter** [comment]
@kupendrayadav - The task can be advanced much faster if we solve the errors together and not only in the only error that the tofix shows.

![zimbabwe1](https://cloud.githubusercontent.com/assets/17984615/26115818/bd06488c-3a26-11e7-99ff-b4d97751583a.png)

#### For this it is necessary to use the JOSM validator to locate errors faster.

![errores2](https://cloud.githubusercontent.com/assets/17984615/26115803/b597b7a2-3a26-11e7-8c69-88d98912e49f.png)

**Comment by luiswalter** [comment]
After performing the work of yesterday validating all the errors that indicated the validator of JOSM in every detection of tofix, we verified that we solve an approximate of 2000 errors in this task. @kupendrayadav @mikelmaron 
#### Before
![screenshot from 2017-05-16 12-09-49](https://cloud.githubusercontent.com/assets/17984615/26123053/3eca978e-3a3f-11e7-96b9-2c49d27f2e79.png)
#### After
![selection_006](https://cloud.githubusercontent.com/assets/17984615/26123334/243c0654-3a40-11e7-8425-5681c27ac5c5.png)

**Comment by kupendrayadav** [comment]
Great Work @piligab @luiswalter 👏  Yesterday two people in Bangalore worked on the to-fix task for one hour. We reviewed nearly 180 issues in the task. I had chat with @Rub21 on stats page as it is not reflecting my progress. It will be fixed soon.

### Questions:

![hot](https://cloud.githubusercontent.com/assets/20293098/26186355/c3f8d89c-3bae-11e7-9f25-361b315c6ea8.gif)

- We observed people mapping buildings using both imageries and buildings are overlapping each other. In this case which building should be deleted?

![hotter](https://cloud.githubusercontent.com/assets/20293098/26186471/a3dfc5ce-3baf-11e7-8e72-16a14b84c9a3.gif)

-  Even though DG imagery is good to map, they mapped buildings according to Bing which is not aligning to the DG imagery. Can we consider, if people map according to Bing? It would be great if we have one standard imagery to follow.

![hottest](https://cloud.githubusercontent.com/assets/20293098/26186626/6aecda1c-3bb0-11e7-8c4f-b1d3a8ace14f.gif)

- We noticed some buildings which are present in Bing, but not in DG. As DG is latest and updated, Does that mean those buildings are demolished? Should we delete them or not?


![hot 1](https://cloud.githubusercontent.com/assets/20293098/26186812/04a71734-3bb2-11e7-9147-3b1758bb8335.gif)

![hot 2](https://cloud.githubusercontent.com/assets/20293098/26186846/3feddf3a-3bb2-11e7-993f-ba819bf4715e.gif)

- Here are some examples where people mapping buildings using both imageries.


@mikelmaron @maning @luiswalter

**Comment by russdeffner** [comment]
Bing should be used for alignment when GPS is not available.  In most cases DG is newer, so if building are showing in Bing but not DG then they probably are gone, I usually inspect the trees and roads for which imagery is newer; if it's not obvious that Bing is newer, assume DG is.

**Comment by luiswalter** [comment]
- The buildings on top of each other, will always exist in HOT tasks. In the validation work we take into account the best edited building and that it is calibrated with the DG image.


- Consider removing buildings that are drawn with Bing and not with DG, I do not know, the work we are doing is more validation in building crossings, that is why in ayacucho we do not erase buildings (only if necessary). I think @mikelmaron would answer this question better.

@kupendrayadav

**Comment by mikelmaron** [comment]
> the work we are doing is more validation in building crossings, that is why in ayacucho we do not erase buildings

agree @luiswalter that the focus is on building crossings. however, if you noticed in passing an obvious building removal issues -- why not go ahead and remove?

**Comment by luiswalter** [comment]
@mikelmaron  Of course, yes, they can be eliminated under some characteristics like:

- buildings that do not make sense and are on other buildings.
- Buildings that are a replica of another.
- Buildings that have no relationship with the DG or Bing Imagen

**Comment by kupendrayadav** [comment]
> buildings that do not make sense and are on other buildings.
Buildings that are a replica of another.
Buildings that have no relationship with the DG or Bing Imagen 

@luiswalter Sounds good. We can definitely delete the buildings with ^^ characteristics. We can consider DG as newer and Follow DG as standard imagery. 

cc @mikelmaron @maning

**Comment by luiswalter** [comment]
## HOT-Malaria validation workflow 

#### - Objective:
  - Correct overlap errors and building crossings
#### - Tasks
  - The tasks below update every day from Monday to Friday with the latest errors in OpenStreetMap
#### - To-Fix issues:
  https://osmlab.github.io/to-fix/#/task/crossingbuildinginzimbabwe
#### - Changeset comment
    ``` Fixing the overlapping and crossing buildings in Zimbabwe, HOT task (https://osmlab.github.io/to-fix/#/task/crossingbuildinginzimbabwe)```                                                    
#### - Coverage
  - Zimbabwe
#### - Tools
  - If using iD editor, work with To-Fix web
  - If using JOSM, work with Josm-tofix-plugin
#### - Instructions
  - in each To-fix download you might find more than one error. you should try to resolve every error in the download so you don’t have to return to the same place.
  - The preferred download should be ~ .20 

![screenshot from 2017-05-22 16-53-47](https://cloud.githubusercontent.com/assets/17984615/26498058/4e69408a-41f3-11e7-831e-d83cb2d17ed1.png)

  - Use the validator to locate all possible errors in each To-Fix download.
![b597b7a2-3a26-11e7-8c69-88d98912e49f](https://cloud.githubusercontent.com/assets/17984615/26498083/65ee1cd0-41f3-11e7-8883-b1d1a3d28e53.png)

  - Guide the DG Image to eliminate or align the buildings.
  
  - Digital globe Imagery: `tms:https://api.mapbox.com/v4/digitalglobe.2lnp1jee/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZGlnaXRhbGdsb2JlIiwiYSI6ImNpd3A2OTAwODAwNGUyenFuNTkyZjRkeWsifQ.Y44JcpYP9gXsZD3p5KBZbA`
  
  - They should take into account these observations for the elimination of buildings:
    - Buildings that do not make sense and are on top of other buildings.
    - Buildings that are a replica of another.
    - Buildings that have no relationship with the DG or Bing image
![zimbabwe1](https://cloud.githubusercontent.com/assets/17984615/26498146/9f1fb6ee-41f3-11e7-8ecb-433d96ccc1d9.png)

  - Two members from Peru will work one hour per day to advance the work.

|User| Date|
|:----:|:----:|
|RichRico|29/05 - 02/06| 
|dannykath| 29/05 - 02/06 | 
|karitotp| 05/06 - 09/06   |   
|yurasi|  05/06 - 09/06  |    
|ridixcr| 12/06 - 16/06 |    
|calfarome|12/06 - 16/06|
|Luis36995|19/06 - 23/06|
|Piligab|19/06 - 23/06|


  - A daily progress report will be made, with a weekly report for Monday's Scrum.
  - The work will be registered in the to-fix tasks spreadsheet
  - You must run osmlint daily before starting work -> [the steps to follow for detections](https://paper.dropbox.com/doc/Detecting-overlap-buildings-in-Zimbabwe-L72iPbbF3kBRSrJZ7FlVm)

**Comment by dannykath** [comment]
### Progress Week 05/29/ - 06/02

|  User | Fixed | Not an error |
|  ------ | ------ | ------ |
|  dannykath | 152 | 116 |
|  RichRico | 386 | 298 |
|  Total | 538 | 414 |

Issues solved: 538
Taken time per member: 04:00:00 Hours

@Rub21  @maning

**Comment by Yurasi** [comment]
This week @karitotp  and I only worked Monday, because the file mbtiles for Zimbabwe isn't updating. I've reported this issue to @geohacker.
cc. @kupendrayadav @Rub21.

**Comment by luiswalter** [comment]
### Progress Week 06/12 - 06/16

|  User | Fixed | Not an error |
|  ------ | ------ | ------ |
| calfarome  | 1030 | 395 |
|  ridixcr | 820 | 56 |
|  Total | 1850 | 451 |

**Issues solved: 1850**
**Taken time per member: 4:30:00 Hours**

@mikelmaron  @Rub21  @kupendrayadav

**Comment by luiswalter** [comment]
This week we will not work on the validation of Zimbabwe, due to the launch of Gasper. We focus on Mapbox Street validations @Rub21 @mikelmaron @kupendrayadav

**Comment by luiswalter** [comment]
I will write a OSM diary, the subject will be the validation in Zimbabwe and I will publish it on July 5

@lukasmartinelli  wanted to use his tool to show the progress of the buildings in Zimbawe is this possible? Or is private for the exclusive use of Mapbox.

**Comment by mikelmaron** [comment]
@luiswalter that animation is public and updated frequently by @kupendrayadav https://www.mapbox.com/malaria-mapping/#5.04/-19.330/24.313

**Comment by kupendrayadav** [comment]
Yayy!! **1926** Issues completed by @mapbox/map-squad 👏 👏  They worked for 6hrs and made this progress. Amazing work guys.

![screen shot 2017-07-04 at 6 29 18 pm](https://user-images.githubusercontent.com/20293098/27831087-bfb52f26-60e6-11e7-9a35-a24ce6e12e5c.png)

**Comment by kupendrayadav** [comment]
![screen shot 2017-07-05 at 6 19 09 pm](https://user-images.githubusercontent.com/20293098/27865027-8a0927ce-61ae-11e7-8d00-f2014b7ce012.png)

Updated the task with new geojson today. We got 3k+ issues which were done by @mapbox/map-squad in 4hrs. Great progress guys. Keep going. 

@luiswalter @mikelmaron @maning

**Comment by luiswalter** [comment]
@kupendrayadav  @mapbox/map-squad thanks for helping in this task,  what are the following actions here? I have some questions.

- Going to we continue with the validation work in other countries?
- Until when will we continue with this validations? (The campaign ran until August 31.)

@mikelmaron

**Comment by kupendrayadav** [comment]
@luiswalter @mikelmaron As per chat with @maning I'm creating a to-fix task for crossing buildings in Zambia. The geojson is not returning any errors to work in Zimbabwe. We knocked off all crossing and overlapping building errors in Zimbabwe. Next actions will be in #311
