### ISSUE TITLE
Mapping guide intro has a 💔

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapping#296]
If you click the ℹ️ at the top of the main page, some introductory text slides down. The heading is supposed to say Mapbox ❤️ OpenStreetMap, but the heart is broken because the font we’re using doesn’t include that glyph:

![💔](https://cloud.githubusercontent.com/assets/1231218/26170658/0a7c27aa-3af7-11e7-8e10-c6d4adaae61b.png)

/cc @mayagao @davidtheclark

**Comment by jinalfoflia** [comment]
@1ec5 this is solved, all thanks to @katydecorah 🙇  (ref: https://github.com/mapbox/mapping/pull/302)

![image](https://user-images.githubusercontent.com/4470913/27178572-61039894-51e8-11e7-8cb8-e364debd1aed.png)
