### ISSUE TITLE
Adding missing buildings in Jacksonville

### ISSUE THREAD

**Issue by abhisheksaikia** [mapbox/mapping#300]
![jxfl2011n](https://cloud.githubusercontent.com/assets/13744156/26579763/d1857c88-4552-11e7-9b14-8855b38e785f.png)

*Source: Wikipedia; https://en.wikipedia.org/wiki/Jacksonville,_Florida#/media/File:JXFL2011N.png BY CC BY-SA 3.0*

**Objective**: Improve OpenStreetMap basemap data by tracing buildings in Jacksonville

**Estimated number of missing buildings**: ~50K buildings in downtown area

**Estimate numbers of days**: Complete downtown mapping in 14 days.

**Tasks**:

- [Missing buildings in Jacksonville](http://tasks.openstreetmap.us/project/96)

### Workflow

- Pick a task from the [Tasking Manager](http://tasks.openstreetmap.us/project/96).
- Load the Bing imagery to JOSM.
- Install [JOSM Buildings Plugin](https://www.mapbox.com/mapping/mapping-common-features/#buildings) for easy tracing.
- Inspect the imagery to find the missing buildings.
- Add only missing buildings.
- Ignore areas with cloud cover/ look at different imagery for those areas.
- Changeset comment: `Tracing missing buildings in Jacksonville #https://github.com/mapbox/mapping/issues/300`
- Source: `Bing`

**Resources**:

- [Mapping common features using JOSM](https://www.mapbox.com/mapping/mapping-common-features/)

cc: @mapbox/map-squad

**Comment by bhavana-naga** [comment]
I noticed a few roads that don't align with imagery.  See for example [West 3rd Street] (https://www.openstreetmap.org/way/10876273#map=18/30.34023/-81.66533).  These seems to be unreviewed TIGER import.  I'm fixing them within my block.
![pasted image at 2017_06_01 11_08 am](https://cloud.githubusercontent.com/assets/17854310/26666835/bb6b6c32-46bf-11e7-9f77-6d9b36f9cb5b.png)
![pasted image at 2017_06_01 11_42 am](https://cloud.githubusercontent.com/assets/17854310/26666852/d3090caa-46bf-11e7-86df-dffaf5bfa27b.png)

**Comment by maning** [comment]
Thanks for the comment @bhavana-naga, yes let's fix the road as we add buildings.
@abhisheksaikia @ramyaragupathy can we review how much of Jacksonville has un-reviewed TIGER data to estimate how much fixing we need to do here.

**Comment by abhisheksaikia** [comment]
Nice catch @bhavana-naga. Ran an overpass query for `tiger:reviewed=no` in the form of csv and even for a small bounding box (covering only downtown Jacksonville), returned close to ~5k roads which are unreviewed with version=1. 

Maybe we can create a to-fix task to clean up unreviewed tiger imports. 

The query: http://overpass-turbo.eu/s/prC

cc @maning @jothirnadh @Rub21

**Comment by maning** [comment]
I posted a message to the US mailing on the TIGER issue. 
![screen shot 2017-06-02 at 20 42 43](https://cloud.githubusercontent.com/assets/353700/26732127/1ecd9358-47d4-11e7-97b4-4a282e6a46da.png)

Waiting for the reply over the weekend if there are existing fixing effort we can support.

**Comment by muzirian** [comment]
Found this http://www.fdot.gov/geospatial/aerialmain.shtm
Have to confirm if we can use these sources
@maning

**Comment by abhisheksaikia** [comment]
Did some analysis of Bing vs FDOT aerial imagery. 

**Recency**:
Bing is 2014 and FDOT is 2017. But no significant changes in downtown Jacksonville visible in terms of buildings.

**QA**:
* In terms of building tracing, both Bing and FDOT good enough to trace
* Canopy cover: FDOT provides better quality when it comes to canopy covered areas.

But, considering the effort it will take right now + we are not losing any significant information when it comes to using Bing, let us continue using Bing for now.


![bing vs fdot11](https://cloud.githubusercontent.com/assets/13744156/26782447/4904dc1e-4a11-11e7-8fc8-3859a8e4e2aa.gif)
*FDOT vs Bing in canopy covered areas*

@maning @muzirian Thanks for the heads up 👍 

cc @pratikyadav so that the satellite team has this in 💭  whenever they get back to aerial imagery renders.

**Comment by abhisheksaikia** [comment]
No hold for now., reopen when we do building mapping again
