### ISSUE TITLE
Sentence for License compatibility at "sources" article

### ISSUE THREAD

**Issue by nyampire** [mapbox/mapping#303]
Hello team.
I found following sentence at ["source" text](https://github.com/mapbox/mapping/blob/mb-pages/sources/_posts/0000-01-01-sources.md).

> Permissively licensed datasets such as Wikidata - a permissive license would be CC0 or any terms of use that would pass the open definition and do not require share-alike.

AFAIK, compatibility between ODbL and other licenses is not automatically certificated even if the licenses are listed in (or matches with) Open Definition.
The most clearest issues are article about [CC BY4.0](https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/) and Taiwan OpenData Licence (discussed at [this thread](https://lists.openstreetmap.org/pipermail/legal-talk/2017-May/008607.html))

I propose to modify to suggest consulting Community (especially legal-talk ML or local community) before use the dataset.

P.S. [CC0 is OK to use](https://wiki.openstreetmap.org/wiki/Import/ODbL_Compatibility).

**Comment by planemad** [comment]
> pass the open definition and do not require share-alike

If these two conditions are met, it would be ok right?

**Comment by nyampire** [comment]
No.
Even [CC-BY is not compatible with ODbL](https://blog.openstreetmap.org/2017/03/17/use-of-cc-by-data/). Please see [waiver form](https://drive.google.com/file/d/0B3PN5zfbzThqeTdWR1l3SzJVcTg/view) for details.

So, I propose following lines. (grammar/expression correction is welcomed!)

> pass the [ODbL compatibility](https://wiki.openstreetmap.org/wiki/Import/ODbL_Compatibility). If your license is not listed on the wiki, please contact to local community or [OSM legal-talk Mailing List](https://lists.openstreetmap.org/listinfo/legal-talk).
