### ISSUE TITLE
Exit sign guide has incorrect tagging suggestions

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapping#308]
The “[Adding exit and destination tags](https://www.mapbox.com/mapping/mapping-for-navigation/adding-exit-and-destination-signs/#what-are-destination-tags)” and “[Road features](https://www.mapbox.com/mapping/mapping-for-navigation/road-features-mapping-guide/#1-exit--destination-signs)” guides incorrectly suggests that the following scenario:

![](https://cloud.githubusercontent.com/assets/17887418/15180428/2f96a4c4-179f-11e6-88ee-4b4e8857c441.jpg)

calls for the following tags on the `motorway_link` way:

```
destination=Spokane
destination:ref=I 90 East
destination:street=Dearborn Street;James Street;Madison Street
```

This is incorrect for two reasons, which are detailed below.

## `destination:street`

In the U.S., `destination:street` should only be used in a few states – Florida, Kentucky, Maryland, maybe a couple more – and it should only be used when a street name is displayed in small text next to a route shield, sort of like an image caption. For example, Kyles Lane is this exit’s `destination:street` because it’s less important than Fort Wright and Park Hills:

[<img src="https://user-images.githubusercontent.com/1231218/27760314-3646465c-5df9-11e7-8e05-7802fbc004bc.png" width="344" alt="kyles">](https://www.mapillary.com/map/im/WnqBrmNNaJrQ2AB9bzi47w)

whereas this exit has no `destination:street`; instead, it has a `destination` of `Woodward Avenue;Main Street;Detroit Zoo`, matching the sign’s layout:

[![woodward](https://user-images.githubusercontent.com/1231218/27760326-9eb62888-5df9-11e7-8f13-3e8ecd216956.jpg)](https://www.mapillary.com/map/im/0XK3B9LgsYjJ4EiETQS5ug)

It’s important that mappers understand this distinction, because routers [such as OSRM](https://github.com/Project-OSRM/osrm-backend/blob/fd57c5b48bd289ecf15ffa7ea703f0461536f784/profiles/lib/destination.lua#L25) ~~and [Valhalla](https://github.com/valhalla/valhalla/blob/3ba53c8ba3f6539bd5e58ba522b3b59393b0d46b/src/odin/narrativebuilder.cc#L670-L679)~~ use the following logic to decide what to call the exit:

* If there is a `ref`, use `ref`
* Otherwise, if there is a `destination`, use `destination`
* Otherwise, if there is a `destination:street`, use `destination:street`

With the tagging suggested in the guides, however, the most important name (Woodward Avenue) would be omitted in favor of the least important name (Detroit Zoo).

## Split exit

Going back to the example in the guides, the sign’s left and right columns describe two distinct exits, connected by a [collector-distributor road](https://en.wikipedia.org/wiki/Local-express_lanes#Example_of_cloverleaf_interchanges). That is, what begins as a single exit quickly branches into two subexits:

<img width="840" alt="iD" src="https://user-images.githubusercontent.com/1231218/27760241-724e6ed8-5df7-11e7-974d-6b96aa70360f.png">

The left lane goes to Dearboard, James, and Madison streets, while the right lane goes to I-90 eastbound towards Spokane:

[![dearborn](https://user-images.githubusercontent.com/1231218/27760257-ebb073fc-5df7-11e7-9516-40ffd833bbc3.jpg)](https://www.mapillary.com/map/im/lwQKQFVAf5SLiPFStjzL4A)

As it happens, [the `motorway_link` way](http://www.openstreetmap.org/way/431431064) before the split is correctly tagged:

```
destination=Dearborn Street;James Street;Madison Street;Spokane
destination:lanes=Dearborn Street;James Street;Madison Street|Spokane
destination:ref=I 90 East
destination:ref:lanes=|I 90 East
destination:symbol=hospital
lanes=2
```

Note the `destination:lanes` and `destination:ref:lanes` tags.

## Next steps

The guides should choose a better example to illustrate the basic concept. Please consult the [OpenStreetMap Wiki article on highway exit tagging](https://wiki.openstreetmap.org/wiki/Exit_Info) for more nuanced examples.

Also, it would be great if the team could review any exits affected by mapping projects relying on these guides, to ensure that `destination` and `destination:street` are being used correctly.

/cc @srividyacb @abhisheksaikia @planemad @danpat @daniel-j-h

**Comment by jothirnadh** [comment]
The new guide is updated and live in our [mapping guide](https://www.mapbox.com/mapping/mapping-for-navigation/adding-exit-and-destination-signs/). No next actions here.
