### ISSUE TITLE
tigerdeltas status question

### ISSUE THREAD

**Issue by harry-wood** [mapbox/mapping#309]
I was doing some updates to the list of "TIGER Fixup" tools on the osm wiki. There's a few which have gone offline for various reasons, and that seems to include a link we had to _"To Fix 'tigerdeltas'"_. There _was_ something here: http://osmlab.github.io/to-fix/#/task/tigerdelta 

See [my wiki edit](https://wiki.openstreetmap.org/w/index.php?title=TIGER_fixup&type=revision&diff=1487069&oldid=1486705). 

Did _all_ the detectable TIGER issues get fixed?

**Comment by Rub21** [comment]
hey @harry-wood ,  to detect the missing roads in OSM which exist in Tiger we are using osmlint , https://github.com/osmlab/osmlint/tree/master/validators/tigerDelta, and also we are using the tiger 2016. I saw in your description you are saying tiger2014 :point_down: 

> The [[To-fix]] tool has a [http://osmlab.github.io/to-fix/#/task/tigerdelta 'tigerdelta' task queue] which looks at comparison issues with the [[TIGER 2014]] dataset.  The [[Mapbox]] team has been using this to fix some errors, see https://github.com/mapbox/mapping/issues/100. But there are still millions more.


> Did all the detectable TIGER issues get fixed?

We did not finish yet, there is still a lot of issues. https://osmlab.github.io/to-fix/#/task/tigerdelta,, we are trying to clean up first in the main US cities.  :wink:
