### ISSUE TITLE
Duplicate segments of highways - SEO Spam revert

### ISSUE THREAD

**Issue by krishnanammala** [mapbox/mapping#310]
### Context 

While fixing the connectivity issues using [to-fix](https://osmlab.github.io/to-fix/#/), we came across errors in United States (US) where we noticed a lot of duplicate segments of major highways. 

**Example**

Way: https://www.openstreetmap.org/way/144422919/ 
[woodpeck_repair](https://www.openstreetmap.org/user/woodpeck_repair) changeset: https://osmcha.mapbox.com/changesets/50068382/

As the revert changeset undoes edits that were done years ago, geometry of these old ways have come back in the revert changeset causing duplicate ways and overlapping errors with recently made edits.

![SEO](https://user-images.githubusercontent.com/17470597/27953523-c323c484-6329-11e7-9891-770d4fd1f183.gif)
_gif showing the versions of both ways_

The revert changeset has 96 ways spanning across the map. All of these 96 ways may cause duplicate ways.

#### Next actions:

- [x] @maning to inform about the issue of SEO revert in the talk-us mailing list
- [ ] Let us not touch these ways that might complicate cleanup

cc @planemad @michaelsteffen @Rub21 @Andygol

**Comment by maning** [comment]
@krishnanammala https://lists.openstreetmap.org/pipermail/talk-us/2017-July/017509.html

**Comment by krishnanammala** [comment]
Today I have gone through the [SEO revert spam](https://www.openstreetmap.org/changeset/50068382) changeset and reviewed **91** ways in the changeset and fixed **25** issues with duplicates ways .

Interestingly, All of the ways are major highways i.e., tertiary and above and mostly with the route relations. I have fixed all the duplicates highways in the changeset.

cc @maning @planemad @michaelsteffen @Rub21

**Comment by maning** [comment]
Thanks @krishnanammala.  For recording purposes [here are the changesets.](https://osmcha.mapbox.com/filters?filters=%7B%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3Anull%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22Repair%20duplicated%20roads%20due%20to%20changeset%2050068382%20%22%2C%22value%22%3A%22Repair%20duplicated%20roads%20due%20to%20changeset%2050068382%20%22%7D%5D%7D)
