### ISSUE TITLE
To-fix task for overlapping and crossing buildings in Zambia

### ISSUE THREAD

**Issue by kupendrayadav** [mapbox/mapping#311]
Great work from @mapbox/team-data  @mapbox/map-squad 👏  👏 . We fixed all overlapping and crossing buildings errors in Zimbabwe #295. We are now going to continue to contribute our efforts to HOT malaria elimination through working on fixing overlapping and crossing buildings errors in Zambia. 

We observed 2809 issues to fix as per updated geojson in Zambia. These are errors are due to same task boundaries and newbie errors. Let's fix these errors and complete the task as soon as possible.

To-fix task link: https://osmlab.github.io/to-fix/#/stats/crossingbuildingsinzambia

Digital Globe Imagery: `tms:https://api.mapbox.com/v4/digitalglobe.2lnp1jee/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZGlnaXRhbGdsb2JlIiwiYSI6ImNpd3A2OTAwODAwNGUyenFuNTkyZjRkeWsifQ.Y44JcpYP9gXsZD3p5KBZbA`

 @luiswalter @maning @mikelmaron

**Comment by kupendrayadav** [comment]
There's a problem with to-fix. Even though we are loading valid geojson into to-fix, They are not showing up any tasks in it. Pinged @Rub21 on this. Will start working on this when it's get fixed.

@luiswalter @maning @mikelmaron

**Comment by Rub21** [comment]
@kupendrayadav @luiswalter @mikelmaron @maning  sorry for the delay,  to-fix was fixed https://osmlab.github.io/to-fix/#/task/crossingbuildingsinzambia,  feel free to hit me up if you have other issues.  with to-fix.

**Comment by kupendrayadav** [comment]
Thank you @Rub21
