### ISSUE TITLE
Data team peer review 07/05/2017 - 07/12/2017 

### ISSUE THREAD

**Issue by kupendrayadav** [mapbox/mapping#312]
Last peer review ticket: #279   

#### Mapping projects to be reviewed:

-  [To-Fix](https://github.com/mapbox/mapping/issues/295)

#### Instructions

* Download `.osm` files for last week.
 - [2017/07/05- 2017/07/12](https://s3.amazonaws.com/mapbox/osm-history-processor/day/latest.osm.tar.gz)

* Extract the tar file and select any OSM file of the team member.
* Each team member will have a .osm file of edits for the last seven days. For example: `latest-andygol.osm`. Select any `.osm` file and open the data in JOSM. 
* If you don't find any osm file of a particular team member, then it means that user has not edited during the week.
* Examine user edits in detail. In JOSM, select a random small area edited by the user and press `3` to zoom.
* Download the latest data in OSM as a new layer and add a filter `Cmd + F` to see only the user's edits, e.g. `user:andygol`.

![andyfilter3](https://cloud.githubusercontent.com/assets/6770741/14813545/cf7409d2-0bbf-11e6-9389-5b6132b7bb55.gif)

* Select a way/node and load the history (`Ctrl + H`), the changeset comment will describe what specific project the user was working on.
* To get an OSM link to the object, click `Cmd + Shift + H`. 
* Note down any feedback for each user in this ticket or comment directly in the changeset. Use this format:

```
username
changeset link - issue to fix
```

* @krishnanammala @chtnha @kupendrayadav or @dannykath will post the feedback in the ticket (Use Github handle because OSM name is different from Github name) and make necessary changes on the same day.
* Close the ticket once users have fixed their edits.

For clarifications, discuss with the @mapbox/team-data in this ticket.

**Comment by kupendrayadav** [comment]
@ashleyannmathew :

Connect the ways at intersections:

- https://www.openstreetmap.org/way/506360865/history 
- https://www.openstreetmap.org/way/506360863/history
- https://www.openstreetmap.org/way/506360864/history
- https://www.openstreetmap.org/way/506360870/history
- https://www.openstreetmap.org/way/506360861/history
- https://www.openstreetmap.org/way/506360859/history
- https://www.openstreetmap.org/way/506360867/history
- https://www.openstreetmap.org/way/506360871/history
- https://www.openstreetmap.org/way/377078259/history
- https://www.openstreetmap.org/way/505471308/history
- https://www.openstreetmap.org/way/128922474/history

**Comment by kupendrayadav** [comment]
@bhojaraj  :
 
  Split into dual carriage way:
  

- https://www.openstreetmap.org/way/11131915/history 
- https://www.openstreetmap.org/way/444684455/history

Connect highway at intersections: 

- https://www.openstreetmap.org/way/443701607/history
- https://www.openstreetmap.org/way/226313001/history

Alignment according to imagery:

- https://www.openstreetmap.org/way/255807862/history
- https://www.openstreetmap.org/way/320966293/history#map=19/35.57923/45.45533

**Comment by kupendrayadav** [comment]
@bhavana-naga 
Connect highway intersection
https://www.openstreetmap.org/way/505475359/history
https://www.openstreetmap.org/way/197875326/history
https://www.openstreetmap.org/way/481633468/history


Fix overlapping ways

https://www.openstreetmap.org/way/456292460/history
https://www.openstreetmap.org/way/456292460/history
https://www.openstreetmap.org/way/481633481/history
https://www.openstreetmap.org/way/33284909/history
https://www.openstreetmap.org/way/15117600/history

Delete way or add tag for untagged ways
https://www.openstreetmap.org/way/505745272/history
https://www.openstreetmap.org/way/456292458/history
https://www.openstreetmap.org/way/456292460/history

Split ways
https://www.openstreetmap.org/way/487019780/history
https://www.openstreetmap.org/way/83864642/history


Remove duplicated roads
https://www.openstreetmap.org/way/481633468/history

**Comment by kupendrayadav** [comment]
@Marthaleena 

Connect highway to intersection
https://www.openstreetmap.org/way/503017312/history
https://www.openstreetmap.org/way/503017318/history
https://www.openstreetmap.org/way/498690294/history
https://www.openstreetmap.org/way/9000721/history
https://www.openstreetmap.org/way/493149179/history
https://www.openstreetmap.org/way/147150387/history
https://www.openstreetmap.org/way/9984111/history
https://www.openstreetmap.org/way/147150410/history

Add tags to untagged ways
https://www.openstreetmap.org/way/33624497/history
https://www.openstreetmap.org/way/505481790/history

**Comment by kupendrayadav** [comment]
@muzirian 
Fix overlapping highways:

https://www.openstreetmap.org/way/506413927/history

Delete duplicated highways:

https://www.openstreetmap.org/way/376571529/history
https://www.openstreetmap.org/way/485959889/history

**Comment by muzirian** [comment]
Both issues fixed 
https://www.openstreetmap.org/way/506413927/history

https://www.openstreetmap.org/way/376571529/history

**Comment by bhojaraj** [comment]
Thanks for review.
Here are my fixes,
https://www.openstreetmap.org/way/443701607/history
https://www.openstreetmap.org/way/226313001/history
https://www.openstreetmap.org/way/255807862/history
https://www.openstreetmap.org/history#map=18/35.57898/45.45491
https://www.openstreetmap.org/way/11131915/history

**Comment by bhavana-naga** [comment]
Thanks for the review. 
Here are my fixes,
https://www.openstreetmap.org/history#map=19/31.58484/44.65446
https://www.openstreetmap.org/way/506950480/history#map=18/28.15270/-82.74167
https://www.openstreetmap.org/way/456292458/history
https://www.openstreetmap.org/way/197875326/history

**Comment by Marthaleena** [comment]
Thanks for the review
Done with the fixes
https://www.openstreetmap.org/way/503017312/history
https://www.openstreetmap.org/way/503017318/history
https://www.openstreetmap.org/way/498690294/history https://www.openstreetmap.org/way/493149179/history https://www.openstreetmap.org/way/9000721/history

**Comment by jothirnadh** [comment]
Great work team 👏 , no next actions here. Closing it
