### ISSUE TITLE
Mapping Exit numbers and Destinations in DC

### ISSUE THREAD

**Issue by jothirnadh** [mapbox/mapping#317]
**Objective:** Mapping/reviewing all exit numbers and destinations in DC

**Mapping Team:** @mapbox/map-squad 

**Task:** http://tasks.mapbox.com/project/116

**Plugins required:**
* Todo list
* Mapillary
* OpenStreetCam

### Workflow:
[Reference guide for mapping Exit numbers and Destinations in US](https://www.mapbox.com/mapping/mapping-for-navigation/adding-exit-and-destination-signs/)
* Load the block from [tasking manager](http://tasks.mapbox.com/project/116) into JOSM
* Activate Selection and Todo list in JOSM (`Windows > Selection & Todo list`)
* In selection window search for `motorway_link` and add it to Todo list
![selection](https://user-images.githubusercontent.com/8401827/28781963-6e9c0594-7629-11e7-90b7-de5707910183.gif)
* Identify the first segment of exit motorway_link (off-ramps) in the Todo list and add applicable tags as per existing signs on Mapillary/OpenStreetCam images
  * `destination=*`
  * `destination:ref=*`
  * `destination:ref:to=*`
  * `destination:lanes=*`
  * `destination:ref:lanes=*`
  * `destination:ref:to:lanes=*`
<img width="561" alt="screen shot 2017-07-31 at 8 12 50 pm" src="https://user-images.githubusercontent.com/8401827/28783046-ae979f98-762c-11e7-8eba-f3b30fae5f0e.png">

*exit way (off-ramp)*
* To the junction node where the exit way is started, add the applicable tags as per existing signs on Mapillary/OpenStreetCam images
  * `highway=motorway_junction`
  * `ref=*`
  * `noref=*`
  * `ref:left=*`
  * `ref:right=*`
* Identify the first segment of entrance ways (on-ramps) to motorways in the Todo list and add applicable tags as per existing signs on Mapillary/OpenStreetCam images
  * `destination=*`
  * `destination:ref=*`
<img width="415" alt="screen shot 2017-07-31 at 8 14 13 pm" src="https://user-images.githubusercontent.com/8401827/28783112-e0c55d70-762c-11e7-9309-2cf08bc71dbf.png">

*entrance way (on-ramp)*
*Note:* In the case of missing Mapillary/OpenStreetCam imagery for entrance ways, copy the `ref` number of the motorway it is joining to and add it as `destination:ref` to the entrance way.
* Addition of destination tags to the middle motorway segments is not necessary, so click on `Mark` to skip them.
* Upload the data into OpenStreetMap once gone through the queue in Todo list

### Things to note:
* Check the [reference mapping guide](https://www.mapbox.com/mapping/mapping-for-navigation/adding-exit-and-destination-signs/) for edge cases
* Do check for Cardinal directions of the roads from street level images. If cardinal directions are missing from sign boards get the cardinal direction from the route relation of the adjacent motorway which it is going to join ahead.
* The following highway shields exist in DC

|S.No|  **Highway shield preview** | **Tag** |
|---|  ------ | ------ |
1.|  <img width="100" alt="screen shot 2017-07-31 at 1 02 40 pm" src="https://user-images.githubusercontent.com/8401827/28767338-ec06714c-75f0-11e7-90f2-0a23a58e836e.png"> | <ul>`destination:ref=DC 295`</ul> `DC 296` is the only existing DC route |
2.|<img width="100" alt="screen shot 2017-07-31 at 1 00 55 pm" src="https://user-images.githubusercontent.com/8401827/28767398-2a55d6d6-75f1-11e7-8962-03494a0aa295.png">| <ul>`destination:ref=VA 5`</ul> `VA`represents Virginia state route |
3.|<img width="100" alt="screen shot 2017-07-31 at 1 09 57 pm" src="https://user-images.githubusercontent.com/8401827/28767514-a26bf402-75f1-11e7-9815-1c14b771cdcd.png">|<ul>`destination:ref=SR 613`</ul> `SR` represents State Route|
4.|<img width="100" alt="screen shot 2017-07-31 at 1 12 31 pm" src="https://user-images.githubusercontent.com/8401827/28767596-efc14d06-75f1-11e7-9b25-1cd470922f3d.png">|<ul>`destination:ref=US 58`</ul> `US` represents US state route|
5.|<img width="100" alt="screen shot 2017-07-31 at 1 15 42 pm" src="https://user-images.githubusercontent.com/8401827/28767717-64c3ea50-75f2-11e7-9140-38bf78c77d76.png">|<ul>`destination:ref= US 4`</ul> This is historic shield which is no longer in use. If you still find it, just add it as US state route|
6.|<img width="100" alt="screen shot 2017-07-31 at 1 17 04 pm" src="https://user-images.githubusercontent.com/8401827/28767768-99063cd2-75f2-11e7-8806-48d9f9283cd2.png">|<ul>`destination:ref=I 80`</ul> `I` represents Interstate routes|
7.|<img width="100" alt="screen shot 2017-08-02 at 4 12 16 pm" src="https://user-images.githubusercontent.com/8401827/28870307-66b467b6-779d-11e7-8ff9-d94cb3e6a0f0.png">|<ul>`destination:ref=MD`</ul> `MD` represents Maryland state route|

**Changeset Comment:** `Mapping missing Exit numbers and Destination signs in  DC #https://github.com/mapbox/mapping/issues/317`
**Source:** Mapillary, OpenStreetCam, Bing, Mapbox
**Filter:** `highway=motorway|motorway_link`

cc:// @michaelsteffen @maning @srividyacb @abhisheksaikia @planemad @Rub21

**Comment by muzirian** [comment]
![image](https://user-images.githubusercontent.com/14972525/28809346-8cb69b62-76a0-11e7-9e4b-f32cc6ad5f4c.png)
As this is state highway for Iowa shouldnt this be IA 613 ?

**Comment by jothirnadh** [comment]
As DC city boundary is located in between Virginia and Maryland the highway shields are changing from area to area. Thanks to @1ec5 for clarifying this. Here are some of the cases which we need to keep track of:

![pasted image at 2017_08_03 03_20 pm](https://user-images.githubusercontent.com/8401827/28963455-c63c0a24-7926-11e7-849b-d3dbc5fa17a4.png)

These tags are applicable in above case:
* `destination:street=George Washington Memorial Parkway South`
* `destination=Reagan National Airport; Boundary Channel Drive`
* `destination:lanes=Reagan National Airport| Boundary Channel Drive`

![](https://wiki.openstreetmap.org/w/images/9/97/I-695_ol_exit_007b_01.jpg)

These tags are applicable above cases:
* `destination:ref=MD 295 North`
* `destination=Baltimore-Washington Parkway; Baltimore`

Tags for the exit in 3/4th mile will be:

* `destination:street=Camp Meade Road`
* `destination=Linthicum`
* `destination:street=Md 170`

cc:// @mapbox/map-squad

**Comment by 1ec5** [comment]
Depending on the exact boundaries of this task, there may occasionally be some variants of the above shields, for example:

<img src="https://upload.wikimedia.org/wikipedia/commons/9/91/MD_Route_3_Business.svg" width="48"> `MD 3 Business`

**Comment by Yurasi** [comment]
![seleccion_039](https://user-images.githubusercontent.com/12261974/28985912-625f9030-792a-11e7-86d0-3e9410d400ee.png)
In this case the exit sign "I 495 South" should be considerate in the destination:ref tag?
`destination:ref = VA 267 West;I 495 South` Is it correct?
cc. @1ec5

**Comment by luiswalter** [comment]
#### I have a question: What to do when a Primary path has ref = #? We can add this to the via Motorway as destination: ref = #?
https://www.openstreetmap.org/way/6105617/history#map=19/38.99439/-76.87971

![screenshot from 2017-08-04 15-38-25](https://user-images.githubusercontent.com/17984615/28986229-a9d0fe3a-792b-11e7-9aef-70a026fa4c96.png)

![screenshot from 2017-08-04 15-38-06](https://user-images.githubusercontent.com/17984615/28986270-d4f27c38-792b-11e7-9bf6-e6d1c0bf3c3d.png)
@jothirnadh @srividyacb @abhisheksaikia

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapping/issues/317#issuecomment-320347300: no, the little I-495 sign says where you'd end up if you stay in the center lanes and don't take the left or right exit. It is possible to tag the main motorway with a destination tag, but it isn't necessary and OSRM will ignore the tag.

**Comment by 1ec5** [comment]
https://github.com/mapbox/mapping/issues/317#issuecomment-320349797: what do the signs look like at the beginning of the ramp, at the fork in the road? Based on the sign on the right side of [this image](http://www.mapillary.com/map/im/xXK3QfTWfiZBowZghldfPg/photo), it should be `destination=NASA Goddard` `destination:ref:to=MD 193 East`. (The other ramp to the left would be tagged `destination:street=Baltimore-Washington Parkway` `destination=Baltimore`.)

**Comment by jothirnadh** [comment]
Great work everyone 👏! We completed the task in 6 working days with a team of 5 working on daily basis and ended up adding **1322** new exit and destination features to OpenStreetMap. Here is the breakdown of features that we added during the mapping sprint:

|  **Feature** | **count** |
|  ------ | ------ |
|  destination | 455 |
|  destination:ref | 609 |
|  destination:street | 55 |
|  destination:lanes | 3 |
|  destination:ref:lanes | 3 |
|  destination:ref:to |  0 |
|  ref | 24 |
|  ref:left | 12 |
|  ref:right | 12 |
|  motorway:junction | 149 |
|  **Total** | **1322** |

### Next actions:
- [ ] Complete validation of the task and document common errors for further learnings
- [ ] Start working on [Exit and destination mapping in LA](https://github.com/mapbox/mapping/issues/323)

**Comment by Rub21** [comment]
Steping back to this comment https://github.com/mapbox/mapping/issues/317#issuecomment-320349797, 
We found some `motorway_link` which are entrances to  `primary` or `trunk` roads, those roads have the tag `ref:*`  e.g: `ref=CA 234`, Do we need to add  `destination:ref`  in the motorway_link if we don't find a mapillary imagen?  Only according the `ref` tag in the exit roads.

**Comment by michaelsteffen** [comment]
@Rub21 Can you just capture these locations in a spreadsheet or paper doc for now? Eventually we should be able to do the sort of inferential tagging you are talking about on an automated basis, so let's only tag explicitly for now where we have sign imagery.

**Comment by jothirnadh** [comment]
Great work everyone 👏 . No next action here.
