### ISSUE TITLE
Detroit Metro data improvement request

### ISSUE THREAD

**Issue by nickballen** [mapbox/mapping#321]
I understand Mapbox has recently opened a sales division in Detroit, and I wondered if your data team would have an interest in some fundamental improvements to the Detroit metro region. The metro is a hotbed of automotive testing, and I suspect having address and building data would be of high value to possible Mapbox clients using GPS systems. There is a lot of high-quality public-domain data available for the region, but little of it has been imported into OSM. For example, streets are fragmented, there are no address data, and only high-density areas have user-contributed building data. 

I'm a frequent OSM user but don't have the JOSM or validation skills to do bulk imports. But I have consolidated a lot of this information and wanted to provide it to you:

1. Building footprints/outlines (2m records)
Data source: [SEMCOG Open Data Portal](http://maps-semcog.opendata.arcgis.com/datasets?t=land) ([data visualization](http://maps.semcog.org/BuildingFootprints/))
Coverage area: City of Detroit, Wayne County, Washtenaw County, Livingston County, Macomb County
Summary: OSM only has user-contributed data for major commercial areas. This is a comprehensive database of buildings. Building features were extracted from 2015 aerial imagery by the Southeast Michigan Council of Governments. All buildings were assigned an address, NAICS use type, stories, and a LiDAR-based height ([see documentation](http://maps.semcog.org/BuildingFootprints/BuildingsDocumentation071916.pdf)). The only use restriction is that they need to be attributed to SEMCOG, and I can reach out to their staff if licensing is an issue.

Like the [NYC import](http://wiki.openstreetmap.org/wiki/Import/Catalogue/NYC_Buildings_Addresses) that Mapbox did in 2014, this would import both building footprints and address data

2. Roads and additional address data
Data source: [Michigan Department of Transportation](http://gis-michigan.opendata.arcgis.com/datasets/5fddb53b929b4b729b8d4282b4d23ade_20)
Coverage area: All areas of Michigan
Summary: OSM data appears to be based on U.S. national TIGER data, with significant user contributions. Unfortunately, these data lack address ranges and lines are highly fragmented. The dataset above includes to-from address ranges and other features to validate current data

3. Ward and neighborhood boundaries
Data source: [City of Detroit Open Data Portal](https://data.detroitmi.gov/Government/Detroit-Neighborhoods/5mn6-ihjv) 
Coverage area: City of Detroit
Summary: In OSM, the metro region has no data for [U.S. administrative boundaries](https://wiki.openstreetmap.org/wiki/WikiProject_United_States/Boundaries#Municipal_subdivisions) beyond TIGER municipal boundaries (OSM admin level 8). In Detroit, level 9 would be the [seven council districts](https://data.detroitmi.gov/Government/City-Council-Districts/4vse-9zps), and level 10 would be [neighborhoods](https://data.detroitmi.gov/Government/Detroit-Neighborhoods/5mn6-ihjv). I am not aware of other metro jurisdictions that have published this data. 

4. Land cover/Land use data
SEMCOG has created a [public respository of data](http://semcog.org/Land-Use) for the five-county area, current as of 2008.

**Comment by maning** [comment]
Thank you for this info @nickballen our team will look into this.

cc @jothirnadh @karitotp @chtnha

**Comment by jmcbroom** [comment]
Telenav is doing quite a bit of work around the roads:

https://github.com/TelenavMapping/mapping-projects/issues

**Comment by jmcbroom** [comment]
https://www.mapillary.com/app/?lat=42.375850266794885&lng=-83.15715197597068&z=15.74931841526201&pKey=sPYoqzTY2dwhcC2bn40RKQ
