### ISSUE TITLE
Mapping Exit numbers and Destinations in LA

### ISSUE THREAD

**Issue by jothirnadh** [mapbox/mapping#323]
**Objective:** Mapping/reviewing all exit numbers and destinations in LA

**Mapping Team:** @mapbox/map-squad 

**Task:** http://tasks.mapbox.com/project/117

**Plugins required:**
* Todo list
* Mapillary
* OpenStreetCam

### Workflow:
[Reference guide for mapping Exit numbers and Destinations in US](https://www.mapbox.com/mapping/mapping-for-navigation/adding-exit-and-destination-signs/)
* Load the block from [tasking manager](http://tasks.mapbox.com/project/116) into JOSM
* Activate Selection and Todo list in JOSM (`Windows > Selection & Todo list`)
* In selection window search for `motorway_link` and add it to Todo list
![selection](https://user-images.githubusercontent.com/8401827/28781963-6e9c0594-7629-11e7-90b7-de5707910183.gif)
* Identify the first segment of exit motorway_link (off-ramps) in the Todo list and add applicable tags as per existing signs on Mapillary/OpenStreetCam images
  * `destination=*`
  * `destination:ref=*`
  * `destination:ref:to=*`
  * `destination:lanes=*`
  * `destination:ref:lanes=*`
  * `destination:ref:to:lanes=*`
  * `junction:ref=*`

<img width="561" alt="screen shot 2017-07-31 at 8 12 50 pm" src="https://user-images.githubusercontent.com/8401827/28783046-ae979f98-762c-11e7-8eba-f3b30fae5f0e.png">

*exit way (off-ramp)*
* To the junction node where the exit way is started, add the applicable tags as per existing signs on Mapillary/OpenStreetCam images
  * `highway=motorway_junction`
  * `ref=*`
  * `noref=*`
  * `ref:left=*`
  * `ref:right=*`
* Identify the first segment of entrance ways (on-ramps) to motorways in the Todo list and add applicable tags as per existing signs on Mapillary/OpenStreetCam images
  * `destination=*`
  * `destination:ref=*`
<img width="415" alt="screen shot 2017-07-31 at 8 14 13 pm" src="https://user-images.githubusercontent.com/8401827/28783112-e0c55d70-762c-11e7-9309-2cf08bc71dbf.png">

*entrance way (on-ramp)*
*Note:* In the case of missing Mapillary/OpenStreetCam imagery for entrance ways, copy the `ref` number of the motorway it is joining to and add it as `destination:ref` to the entrance way.
* Addition of destination tags to the middle motorway segments is not necessary, so click on `Mark` to skip them.
* Upload the data into OpenStreetMap once gone through the queue in Todo list

### Things to note:
* Check the [reference mapping guide](https://www.mapbox.com/mapping/mapping-for-navigation/adding-exit-and-destination-signs/) for edge cases
* Do check for Cardinal directions of the roads from street level images. If cardinal directions are missing from sign boards get the cardinal direction from the route relation of the adjacent motorway which it is going to join ahead.
* The following highway shields exist in LA

|S.No|  **Highway shield preview** | **Tag** |
|---|  ------ | ------ |
1.|  <img width="100" alt="screen shot 2017-08-02 at 3 48 38 pm" src="https://user-images.githubusercontent.com/8401827/28869369-1c40b930-779a-11e7-9b16-010a00805ce6.png"> | <ul>`destination:ref=CA 1`</ul> `CA` represents California state route|
2.| <img width="100" alt="screen shot 2017-08-02 at 3 50 23 pm" src="https://user-images.githubusercontent.com/8401827/28869435-53a7e1d2-779a-11e7-86fd-134b43cdc9cd.png"> | <ul>`destination:ref=US 101`</ul> `US` represents US state route|
3.|<img width="100" alt="screen shot 2017-08-02 at 4 08 32 pm" src="https://user-images.githubusercontent.com/8401827/28870166-e52a2640-779c-11e7-8dc7-6d4447e97f84.png">| <ul>`destination:ref=I 5`</ul>|

**Changeset Comment:** `Mapping missing Exit numbers and Destination signs in  LA #https://github.com/mapbox/mapping/issues/323`
**Source:** Mapillary, OpenStreetCam, Bing, Mapbox
**Filter:** `highway=motorway|motorway_link`

cc:// @michaelsteffen @maning @srividyacb @abhisheksaikia @planemad @Rub21

**Comment by jothirnadh** [comment]
Great work everyone 👏! We completed the task in 6 working days with a team of 5 working on daily basis and ended up adding **1322** new exit and destination features to OpenStreetMap. Here is the breakdown of features that we added during the mapping sprint:

|  **Feature** | **count** |
|  ------ | ------ |
|  destination | 455 |
|  destination:ref | 609 |
|  destination:street | 55 |
|  destination:lanes | 3 |
|  destination:ref:lanes | 3 |
|  destination:ref:to |  0 |
|  ref | 24 |
|  ref:left | 12 |
|  ref:right | 12 |
|  motorway:junction | 149 |
|  **Total** | **1322** |

### Next actions:
- [ ] Complete validation of the task and document common errors for further learnings
- [ ] Start working on [Exit and destination mapping in LA](https://github.com/mapbox/mapping/issues/323)

**Comment by jothirnadh** [comment]
@mapbox/map-squad when ever you come across `ref:left` and `ref:right`at the junctions, add `junction:ref` tag to the connecting motorway_link with ref value as the key to the tag. Make sure the direction of the motorway_link is referring to the direction of the way on the sign board.

**Comment by ashleyannmathew** [comment]
![image](https://user-images.githubusercontent.com/28762545/29769597-be499242-8c08-11e7-845f-fabc5f5ebe0d.png) 
https://www.openstreetmap.org/node/1716422011/history
Coming across many issues with wrong "highway=motorway_junction" tagged as in the above example.
cc: @mapbox/map-squad

**Comment by jothirnadh** [comment]
@mapbox/map-squad this is clearly a wrong way to tag a junction. Please go ahead and delete the tags associated with that junctions if you come across any.

**Comment by jothirnadh** [comment]
@mapbox/map-squad is coming across a lot of missing motorways which are recently constructed in LA.
<img width="860" alt="screen shot 2017-08-31 at 12 22 25 pm" src="https://user-images.githubusercontent.com/8401827/29910340-304f1a5c-8e47-11e7-840d-eb87e5fcdc45.png">
Bing imagery : [Link](https://www.openstreetmap.org/way/32213386/history#map=17/33.90208/-118.06120) (Issue is fixed at the moment)

Bing, Mapbox, and even DG imagery are older than 2014 and these highways seem to be constructed after 2015. Esri world imagery is more recent than another imagery provider in this case. Right now the team is fixing the issues when ever they come across any, but it would be great if we can run a separate mapping project on this considering these missing highways are `motorway's`. 

cc:// @srividyacb @maning @michaelsteffen @planemad

**Comment by abhisheksaikia** [comment]
Great work @mapbox/map-squad on adding exit and destinations in LA 💥 👏 . A total of **6448** exit and destinations were added during two weeks. Here is a breakdown of the numbers added:

Feature  | Count
--- | ---
destination | 3002
destination:ref | 2808
destination:street | 4
destination:lanes | 107
destination:ref:lanes | 101
destination:ref:to | 18
ref | 67
ref:left | 10
ref:right | 10
motorway:junction | 321
**Total** | 6448
