### ISSUE TITLE
Mapping missing Turn lanes in SF City

### ISSUE THREAD

**Issue by jothirnadh** [mapbox/mapping#324]
**Objective:** Map missing [turn lanes](http://wiki.openstreetmap.org/wiki/Key:turn:lanes) from secondary and up in SF City

![turnlanes](https://cloud.githubusercontent.com/assets/8401827/15009897/ca49c6c0-1206-11e6-99ad-a458e6d7539c.jpeg)

**Team:** @mapbox/team-data

**Features to map**: Turn lanes (on motorway, trunk, primary, secondary and tertiary) from satellite imagery

**Tasks:** http://tasks.mapbox.com/project/118

#### Setup
- Activate the following in from JOSM preferences > Map Settings
  - **Map Paint Styles**: Lanes and road attributes
  - **Tagging Presets**: lane attributes
- Add inverse filter: `highway=motorway|trunk|primary|tertiary|secondary|*link|motorway_link or untagged`
- Read http://wiki.openstreetmap.org/wiki/Key:turn:lanes
- Read https://www.mapbox.com/mapping/mapping-for-navigation/adding-turn-lanes/
- Install the 🔪  tool in JOSM to easily split the roads: https://wiki.openstreetmap.org/wiki/JOSM/Plugins/Knife-tool

#### Mapping
- Check the roads for turn lanes at exits and entry points
  ![](https://cloud.githubusercontent.com/assets/126868/11710074/b58b52e4-9f42-11e5-971a-000a699a0b6d.png)
- Split the road into segments based on the total number of lanes for the segment
- For each road segment tag the turn lanes based on the road markings in the direction of the way. Eg. `turn:lanes=left|through|right`. See [OSM turn:lanes](http://wiki.openstreetmap.org/wiki/Key:turn:lanes)
- For bi-directional segments, use `turn:lanes:backward=` and `turn:lanes:forward=` to specify turn lanes in each direction.
- Verify correct tagging using the `Lane attributes` style
  ![](https://cloud.githubusercontent.com/assets/126868/11713668/d3f6d498-9f5a-11e5-91ea-5d9ab5714b39.png)
#### Issues to keep in mind:
- For QA and edge cases in turn lanes mapping and how to handle them (parking lanes, splitting roads for start and end of turn lanes, handling of dual carriageways, etc) look into the [QA for turn lane data](https://www.mapbox.com/mapping/mapping-for-navigation/adding-turn-lanes/#qa-for-turn-lanes-mapping) document.

**Changeset Comment**: `Add missing turn lanes from satellite imagery in SF https://github.com/mapbox/mapping/issues/324`

**Source**: `Bing`

**Turn lane mapping tickets**: #144, #153 , #180 

cc:// @michaelsteffen @maning @planemad @Rub21

**Comment by manoharuss** [comment]
Found this case where I was not able to verify.

![image](https://user-images.githubusercontent.com/8921295/29069755-ddc6e516-7c59-11e7-9488-b7f25a072b65.png)

The selected way from the image was tagged as `oneway=yes` since 2013 and was not changed since. The the lane markings as seen on bing imagery seem to suggest that the way is bi-directional. I could not verify it through other satellite imagery(old or worse), Mapillary(older than 1year).

@michaelsteffen I have seen that you added a [no_u_turn](https://www.openstreetmap.org/relation/7446017) here 3 days ago. If you are familiar with this road, could you confirm if this is bi-directional as the lane markings suggest or a oneway?

**Comment by jothirnadh** [comment]
Great Work everyone. It took 2 days for a team of 8 members to complete mapping/validating turn lanes in SF city. Overall we added/modified nearly **~500** turn lanes in SF city. Here is the breakdown of features that we added/modified during the mapping sprint:

|  **Features** | **Count** |
|  ------ | ------ |
|  turn:lanes | 354 |
|  turn:lanes:forward | 91 |
|  turn:lanes:backward | 70 |
|  lanes | 876 |
|  lanes:forward | 204 |
|  lanes:backward | 204 |
|  **Total** | **1799** |

### Next actions:
- [ ] Considering the huge lift lets continue to verify the turn lane data quality in rest of SF Bay as well
cc:// @michaelsteffen @dannykath @maning @planemad

**Comment by jothirnadh** [comment]
Turn lane mapping task for SF Bay is live : http://tasks.mapbox.com/project/119 
![bitmoji](https://render.bitstrips.com/v2/cpanel/10219618-274204037_3-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by ashleyannmathew** [comment]
![image](https://user-images.githubusercontent.com/28762545/29409615-b4a36b42-836a-11e7-920d-9131b8d72bf6.png)
Finding a lot of the slip roads tagged as service roads. I am correcting the same as when I come across. 
https://www.openstreetmap.org/way/492012664/history

**Comment by jothirnadh** [comment]
No next actions here
