### ISSUE TITLE
Indonesia country relation was stripped of all data

### ISSUE THREAD

**Issue by SrihariThalla** [mapbox/mapping#332]
Hi!

A contributor has [mistakenly] removed all data for the country relation of Indonesia.

Changeset: https://www.openstreetmap.org/changeset/52025337
Relation: https://www.openstreetmap.org/relation/304751
OSMCha: https://osmcha.mapbox.com/changesets/52025337
Deep History: https://osmlab.github.io/osm-deep-history/#/relation/304751

Please do a revert.

Thanks!

**Comment by manoharuss** [comment]
Hi @SrihariThalla. Thanks for bringing this to our attention. I have reverted the changeset partially for the relations that had translation and tag deletions in changeset - https://www.openstreetmap.org/changeset/52234826.

Thank you again. Closing this ticket.
