### ISSUE TITLE
[Mapping Guide] CoreHumanistSans font doesn't support Cyrillic 

### ISSUE THREAD

**Issue by Andygol** [mapbox/mapping#336]
For example - https://www.mapbox.com/mapping/getting-started/ in English and in Ukrainian (Cyrillic). A font that substitutes CoreHumanistSans have some issues with displaying markdown tagging in right way. For example, problem with **\*\*bold\*\*** tagging in Ukrainian.

![](https://user-images.githubusercontent.com/369696/31402314-42ca37e8-ae13-11e7-8712-4c66c5052b88.png)

PS. The list of supported languages https://www.fontsquirrel.com/fonts/corehumanistsans
>Languages: Afrikaans, Albanian, Alsatian, Aragonese, Arapaho, Aromanian, Arrernte, Asturian, Aymara, Basque, Belarusian (Lacinka), Bislama, Bosnian, Breton, Catalan, Cebuano, Chamorro, Cheyenne, Chichewa (Nyanja), Cimbrian, Corsican, Croatian, Czech, Danish, Dutch, English, Estonian, Faroese, Fijian, Finnish, French, French Creole (Saint Lucia), Frisian, Friulian, Galician, Genoese, German, Gilbertese (Kiribati), Greenlandic, Haitian Creole, Hiligaynon, Hmong, Hopi, Hungarian, Ibanag, Icelandic, Iloko (Ilokano), Indonesian, Interglossa (Glosa), Interlingua, Irish (Gaelic), Istro-Romanian, Italian, Jèrriais, Kashubian, Kurdish (Kurmanji), Ladin, Lithuanian, Lojban, Lombard, Low Saxon, Luxembourgian, Malagasy, Malay (Latinized), Maltese, Manx, Mohawk, Norfolk/Pitcairnese, Northern Sotho (Pedi), Norwegian, Occitan, Oromo, Pangasinan, Papiamento, Piedmontese, Polish, Portuguese, Potawatomi, Rhaeto-Romance, Romansh (Rumantsch), Rotokas, Sami (Lule), Samoan, Sardinian (Sardu), Scots (Gaelic), Seychellois Creole (Seselwa), Shona, Sicilian, Slovak, Slovenian (Slovene), Somali, Southern Ndebele, Southern Sotho (Sesotho), Spanish, Swahili, Swati/Swazi, Swedish, Tagalog (Filipino/Pilipino), Tetum (Tetun), Tok Pisin, Tswana, Turkmen, Turkmen (Latinized), Uyghur (Latinized), Veps, Volapük, Votic (Latinized), Walloon, Warlpiri, Welsh, Xhosa, Yapese, Zulu

/cc @katydecorah @jinalfoflia

**Comment by katydecorah** [comment]
Thanks for bringing this up @Andygol. I think we should remove CoreHumanistSans and use a version of Open Sans that supports Cyrillic. I can work on this.

**Comment by katydecorah** [comment]
@Andygol does this font and formatting look correct in the picture below?

![image](https://user-images.githubusercontent.com/2180540/31404962-8a994caa-adcb-11e7-8f87-a6fe3b6c7b21.png)

**Comment by Andygol** [comment]
@katydecorah Yes, it looks as expected 👍
![mapping 2017-10-11 13-20-06](https://user-images.githubusercontent.com/369696/31428035-078fe62c-ae87-11e7-9430-faf37b0169c1.png)
