### ISSUE TITLE
Duplicated roads and turn restrictions in South Florida

### ISSUE THREAD

**Issue by artischocke** [mapbox/mapping#344]
Hi,
While reviewing data quality in South Florida with OSMI, it seems that a large number of changesets from Mapbox mappers introduce duplicated roads (i.e. overlapping ways) and duplicated turn restrictions. I've left a number of [changeset comments](http://resultmaps.neis-one.org/osm-discussion-comments?uid=2533093&commented), with some getting a response while a number of them still remain open.

In addition to getting the issues fixed, the intent of my comments was to find out what data quality checks are in use by the team? It seems that the errors have been there at least since October 23-24, which would lead one to believe that there are currently no data checks being carried out for work completed. If this is the case, I'm sure you share the view that having quality data is more important than having tons of useless data, so I'd encourage the review of existing quality tools to check for issues as part of the normal post-editing workflow.

As I said in my comments, contributions are appreciated but unfortunately the community in some places is not large enough to take care of the burden to fix issues from a big mapping team such as yours, and in any case we would expect individual mappers to fix issues they've created, and the same should apply to everyone.

Thanks in advance for getting the errors fixed and finding ways in which we can help prevent this from happening in future, both by identifying how so many changesets from different mappers introduced duplicated ways (editor? editing technique? lack of proper task/workarea partitioning among teammebers) and by identifying data quality checks following edits.

Cheers :slightly_smiling_face: 

PS: I arrived here based on the information on [your page at the OSM Wiki](https://wiki.openstreetmap.org/wiki/Mapbox). If this is not the right place for this type of feedback, kindly either forward internally or let me know what is the appropriate channel.

**Comment by maning** [comment]
@artischocke Thank you for this report, our team is looking on the issue.  We have fixed all errors already  

We do run validation/QA after every task, I'll get back to you as we identify the problem.

**Comment by artischocke** [comment]
@maning I never did hear back from you. This is still open, for example https://www.openstreetmap.org/changeset/53171753

Not sure how to best handle these sort of issues, but something feels off about having to fix errors from paid mappers and having to chase and follow-up to get them resolved
