### ISSUE TITLE
Japanese navigation mapping guides are outdated

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapping#359]
The Japanese translation of the navigation mapping guides (added in #298) is out of date. For example, @tordans [pointed out](https://twitter.com/tordans/status/1026347037854507013) that [this turn restriction guide](https://www.mapbox.com/mapping/jp/mapping-for-navigation/adding-turn-restrictions/) says you have to use JOSM instead of iD to add `via` ways to turn restrictions. Since this guide isn’t actually translated into Japanese, perhaps it should redirect to the original English version, which was rewritten in #356.

https://github.com/mapbox/mapping/blob/6e39803f7fd9c76b9b5d3593e2106b64995358d9/jp/mapping-for-navigation/_posts/0000-01-04-adding-turn-restrictions.md#L57

/cc @bhousel @ghoshkaj @srividyacb

**Comment by 1ec5** [comment]
The Spanish translation (which is actually translated) also lists a lack of via way support as [a pain point in iD](https://github.com/mapbox/mapping/wiki/Guía-de-mapeo-para-añadir-restricciones-de-giro-utilizando-mapillary#puntos-de-dolor-en-la-adición-de-restricciones-de-giro-en-el-editor-id).

**Comment by nyampire** [comment]
@1ec5 Thank you for feedback. I'm a translator of Japanese article.
I'll renew it in next week. Is it OK for you?

**Comment by nyampire** [comment]
Also, if it is appropriate, I can add or replace the image of turn-restriction sign for Japanese ones.
I prefer to add (not replace) JP ones beside of US ones. Do you have any thought on this?

**Comment by 1ec5** [comment]
That’s a good question. I don’t have an opinion, as long as the JP guides are consistent. Perhaps @srividyacb @maning have a preference?

**Comment by maning** [comment]
> I can add or replace the image of turn-restriction sign for Japanese ones.

This is fine by me as long as we have consistency.
