### ISSUE TITLE
Map issue in Jiangsu, China

### ISSUE THREAD

**Issue by antifa-ev** [mapbox/mapping#361]
Dear Mapbox, 

may you please check your quality control or just map the missing feature from scratch?

[Here](https://api.mapbox.com/styles/v1/mapbox/streets-v9.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#12.73/32.20727/119.58963) an island inside the Yangtze river is totally broken in Mapbox. [At OpenStreetMap](https://www.openstreetmap.org/way/621512032) more parts of it exists, but still far from enough.

![Screenshot](https://user-images.githubusercontent.com/41199978/49407263-38631380-f758-11e8-9424-1b46ba1ecea7.png)

**Comment by LaoshuBaby** [comment]
![图片](https://user-images.githubusercontent.com/42690037/152341816-9a2c9c78-84f5-4488-8663-138b58444292.png)

Maybe this issue can be closed because this multipolygon had been fixed, more than 10 versions was made after 2018.12.04

**Comment by Andygol** [comment]
The issue was fixed. 
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/369696/152342859-c0ac5127-c82c-4dca-8177-1b10e5b91494.png">
