### ISSUE TITLE
Move to labs.mapbox.com

### ISSUE THREAD

**Issue by kepta** [mapbox/mapping#362]
As discussed in https://github.com/mapbox/frontend-platform-team/issues/44, we are planning to move this repository the `labs` subdomain.
 
I have deployed this website at https://labs.tilestream.net/mapping/ .@mikelmaron   can you please help me verify if the website looks good?

Next actions:
- [x] Launch the website at https://labs.mapbox.com/mapping/ .
- [x] Create a 301 redirect from the old URL to the new.
- [x] Search for and update references to the www URL.
- [x] Delete the www site version(s) and their corresponding branches.

cc @mapbox/frontend-platform

**Comment by jinalfoflia** [comment]
>I have deployed this website at https://labs.tilestream.net/mapping/ .@mikelmaron can you please help me verify if the website looks good?

@kepta the website at https://labs.tilestream.net/mapping/ looks fine. 

cc: @mikelmaron

**Comment by kepta** [comment]
This is live  https://labs.mapbox.com/mapping/ 🎆 !
