### ISSUE TITLE
[France] Reviewing osmlint-osmium and osmlint data issues

### ISSUE THREAD

**Issue by vladaboitsik** [mapbox/mapping#365]
### Background

As part of on-going work to improve the quality of OpenStreetMap data, we recently used [osmlint-osmium](https://github.com/osmlab/osmlint-osmium) and [osmlint](https://github.com/osmlab/osmlint) for detecting issues related to road network data in France. In total, there were 45808 issues detected across 11 types of linters.
Our plan is to review detected issues in Paris and areas in Northern France, and fix any valid issues in OpenStreetMap. [Link](https://wiki.openstreetmap.org/wiki/Organised_Editing/Activities/resolve_linting_issues_in_France) to the OSM Wiki page.

### Timeframe

We plan to start reviewing detected issues by the end of next week, and editing OpenStreetMap data to fix valid issues.

### Tools

We will use existing OpenStreetMap editing tools, and using the #hashtag mbx_france_roads

**Editor**: iD or JOSM
**Satellite Imagery**: Bing, Maxar, Esri
**Street Level Imagery**: Mapillary, Other open sources if available

### Contact Person

We welcome feedback, suggestions, and insights from local mappers. If you have questions about this work, or a specific edit by our team, please reach out to Vlada at vlada.boitsik@mapbox.com or post a comment in a changeset. 

### Linter Output

Issue | France Total | Data
--- | --- | ---
Cross Highways | 7,506 | [crossinghighways.zip](https://github.com/mapbox/mapping/files/5339491/crossinghighways.zip)
Crossing Highway Bridges | 29 | [crossinghighwaysbridges.zip](https://github.com/mapbox/mapping/files/5339500/crossinghighwaysbridges.zip)
Missing Role | 2,306 | [tr-missingroletr.zip](https://github.com/mapbox/mapping/files/5339533/tr-missingroletr.zip)
Impossible Angle | 594 | [impossibleangle.zip](https://github.com/mapbox/mapping/files/5339505/impossibleangle.zip)
Impossible Oneways | 1932 | [impossibleoneways.zip](https://github.com/mapbox/mapping/files/5339510/impossibleoneways.zip) 
Island Highways | 1226 | [islandshighways.zip](https://github.com/mapbox/mapping/files/5339520/islandshighways.zip)
Mixed Layer | 65 | [mixedlayer.zip](https://github.com/mapbox/mapping/files/5339524/mixedlayer.zip)
Missing Type Restriction | 1,532 | [tr-missingtyperestrictiontr.zip](https://github.com/mapbox/mapping/files/5339537/tr-missingtyperestrictiontr.zip)
Excessive Roles | 256 | [tr-excessiverolestr.zip](https://github.com/mapbox/mapping/files/5339527/tr-excessiverolestr.zip)
Invalid Roles | 101 | [tr-invalidroletr.zip](https://github.com/mapbox/mapping/files/5339529/tr-invalidroletr.zip) 
Crossing Highways Buildings | 30,262 | 

### Examples

Impossible angle or what we usually call “dragged node”. Link to example you can find [here](https://www.openstreetmap.org/edit#map=20/46.25641/-0.54262)

![изображение](https://user-images.githubusercontent.com/60132467/95456557-2ff14a80-0978-11eb-81bb-3fb7fb655acb.png)

There are problems with the connection of roads near polygons, especially parking lots. Parking lots in France are often mapped by polygons without lines (roads) inside the polygon and since there are no lines inside the polygon, routing will not work. Such example you can find [here](https://www.openstreetmap.org/edit#map=20/48.21981/-1.70019)

![изображение](https://user-images.githubusercontent.com/60132467/95456629-4b5c5580-0978-11eb-80f3-b8a4ae1d3dfa.png)

Also found unconnected roads. To be routable, they should be connected into the road network. You can find example [here](https://www.openstreetmap.org/edit#map=20/48.05248/-1.39666)

![изображение](https://user-images.githubusercontent.com/60132467/95456709-66c76080-0978-11eb-9f8d-08de95e489d7.png)

One more example where road is connected to gate not to the road [here](https://www.openstreetmap.org/edit#map=20/47.49060/-0.55362)

![изображение](https://user-images.githubusercontent.com/60132467/95456950-cc1b5180-0978-11eb-834a-b071be9fd7bd.png)

@legain  @Andygol @abrohood @shvrm

**Comment by Cyrille37** [comment]
Hello. That's a great news, thanks !
how can we recognize your contributions? By osm user or changeset tag?
Thanks again, and cheers.

**Comment by vladaboitsik** [comment]
Hi, @Cyrille37 ! We will use #mbx_france_roads. Thanks for your support!

**Comment by sonyahilchik** [comment]
As part of ongoing work to improve the quality of OpenStreetMap data, we are planning to do one more iteration for detecting issues related to road network data in France. In total, there were 3645 issues detected.
Our plan is to review detected issues in France, and fix any valid issues in OpenStreetMap.
Issue | France Total | Data
--- | --- | ---
Crossing Highways | 1021 | [crossinghighways.zip](https://github.com/mapbox/mapping/files/6631375/crossinghighways.zip)
Impossible Angle | 85 | [impossibleangle.zip](https://github.com/mapbox/mapping/files/6631388/impossibleangle.zip)
Impossible Oneways | 486 | [impossibleoneways.zip](https://github.com/mapbox/mapping/files/6631389/impossibleoneways.zip)
Island Highways | 1235 | [islandhighways.zip](https://github.com/mapbox/mapping/files/6631390/islandhighways.zip)
Mixed Layer | 43 | [mixedlayer.zip](https://github.com/mapbox/mapping/files/6631394/mixedlayer.zip)
Missing Role | 630 | [tr-missingroletr.zip](https://github.com/mapbox/mapping/files/6631395/tr-missingroletr.zip)
Missing Type Restriction | 48 | [tr-missingtyperestrictiontr.zip](https://github.com/mapbox/mapping/files/6631398/tr-missingtyperestrictiontr.zip)
Excessive Roles | 59 | [tr-excessiverolestr.zip](https://github.com/mapbox/mapping/files/6631400/tr-excessiverolestr.zip)
Invalid Roles | 38 | [tr-invalidroletr.zip](https://github.com/mapbox/mapping/files/6631401/tr-invalidroletr.zip)

**Comment by Bibi56** [comment]
Hi @vladaboitsik thanks for having sent the information on [OSM-talk-fr], normally the missing roads in France are known from Bano (comparing French land registry Cadastre to OSM data: https://bano.openstreetmap.fr/fantoir/index.html#insee=<ref:INSEE>&tab=0 indicates the missing highways with numbered houses and https://bano.openstreetmap.fr/fantoir/index.html#insee=<ref:INSEE>&tab=0 - `Libellé BAN` is the probable correct spelling of the street. `ref:INSEE` is the French ID of the commune. 
https://bano.openstreetmap.fr/fantoir/index.html#insee=<ref:INSEE>&tab=2 is the same for ways without numbered houses.

Another source for missing streets (and a way to get names but here the way types and possibly names are shortened).

http://osmose.openstreetmap.fr/en/map/#zoom=18&lat=47.810625&lon=-3.485805&item=7170&level=1%2C2%2C3

**Comment by vladaboitsik** [comment]
Hi @Bibi56 !
Already replied on this in related ticket, thank you!

**Comment by sonyahilchik** [comment]
Team finished reviewing Linters with the great results. The whole amount fixes is **5053**.

![Screenshot from 2021-07-07 16-04-22](https://user-images.githubusercontent.com/57490915/124763846-126c0400-df3d-11eb-9d5f-9cf9936d950d.png)

So, for now this project is finished.

**Comment by sonyahilchik** [comment]
France will be reviewed on permanent bases from the end of August. Once a week there'll be a upload of data and team will close these issues. As part of on-going work to improve the quality of OpenStreetMap data, our team is planning to review a subset of the detections to better understand the type of issues, and also fix any valid data issues directly in the OSM. Link to OSM Wiki.

**Comment by sonyahilchik** [comment]
For a month we reviewed 2322 items and fixed **1863** of them.

![Screenshot from 2021-10-05 13-52-58](https://user-images.githubusercontent.com/57490915/136009974-c7eae88f-3b30-4fe4-92b9-c78a68633950.png)

We'll continue our work and will update this ticket with metrics about our fixes.

**Comment by sonyahilchik** [comment]
For October the team reviewed **2467** items and fixed **66.75%** from them.

<img width="527" alt="Screenshot 2021-11-25 at 14 17 30" src="https://user-images.githubusercontent.com/57490915/143451332-b437158f-6ac9-4116-b0ad-651bc5a39b05.png">

We'll continue our work and will update this ticket with metrics about our fixes.

**Comment by sonyahilchik** [comment]
For November the team reviewed **1382** items and fixed **58.99%** from them.

<img width="526" alt="Screenshot 2021-12-07 at 14 16 20" src="https://user-images.githubusercontent.com/57490915/145541408-b3e041a1-ab20-47da-9de5-ef51df6ce244.png">
