### ISSUE TITLE
Can I translate this guide？

### ISSUE THREAD

**Issue by JOJOforshaun** [mapbox/mapping#376]
Can I translate this guide and eventually add the translation to the guide? Just like learnOSM

**Comment by vladaboitsik** [comment]
Hi @JOJOforshaun !
Generally why not, we just have some questions to be sure that translation will be suitable and correct.
1. What language would you like to translate into?
2. Are you a part of some OSM Community or what experience in mapping do you have? Mapping guide has lots of technical stuff so good experience is needed.
3. How this translation will be used?
