### ISSUE TITLE
Map issue in Singapore

### ISSUE THREAD

**Issue by Kseniya-Nekrasova** [mapbox/mapping#380]
## Background

As part of on-going work to improve the quality of OpenStreetMap data, our team found out a lack of some neighbourhoods and suburbs in Singapore or not correct tags, and we are going to fix this soon as an emergency project. There’s a [link](https://www.openstreetmap.org/#map=12/1.3314/103.7980) to the problem area.  Link to the [OSM Wiki page](https://wiki.openstreetmap.org/wiki/Organised_Editing/Activities/Mapping_Singapore_districts).

Currently, the following district names from the list are not displayed on the map on any zoom levels:
01 | Cecil (only a street is found), Marina, People's Park
02 | Anson (only a road is found)
04 | Telok Blangah (only a road is found)
05 | Pasir Panjang (only MRT station is found), Hong Leong Garden
07 | Golden Mile
09 | Cairnhill (only a road is found), River Valley(only a road is found)
10 | Ardmore
11 | Watten Estate (only a road is found)
13 | Macpherson(only a road is found), Braddell(only a road is found)
14 | Eunos (only MRT station is found)
15 | Katong, Joo Chiat (only a road is found)
16 | Eastwood(only a road is found)
21 | Ulu Pandan(only a road is found)
23 | Hillview(only a MRT station is found)
24 | Tengah
25 | Kranji(only a road is found), Woodgrove(only a road is found)
26 | Springleaf (only a road is found)

 

### Timeframe

We are going to start fixing this issue as soon as all preparation will be done, and we plan to finish this project till the end of the week.

  

### Tools

We are going to edit this area with the help of OSM ID using satellite images provided by Esri, Bing, Maxar and [List of Postal Districts](https://www.ura.gov.sg/realEstateIIWeb/resources/misc/list_of_postal_districts.htm). Hashtag **#mbx_singapore_districts** will be used to mark changeset associated with this project.

  

### Contact Person

We welcome feedback, suggestions, and insights from local mappers. If you have questions about this work, or a specific edits made by our team, please reach out to Kseniya at [kseniya.nekrasava@mapbox.com](mailto:kseniya.nekrasava@mapbox.com) or post a comment in a changeset.

**Edits**

Our edits will be introduced as set of changesets with creating or editing of suburbs and neighbourhoods. We will review each case of areas to be ensured that everything is as expected.

@Andygol @redsoull @maning @abrohood

**Comment by Andygol** [comment]
@jinalfoflia 🙏 may I ask you for help in this project as the one who may have local knowledge.

**Comment by Kseniya-Nekrasova** [comment]
As the result @wwunjo @leolark @limfortallo created missing suburbs with [List of Postal Districts](https://www.ura.gov.sg/realEstateIIWeb/resources/misc/list_of_postal_districts.htm) help and it was bypassed in Map Mender.
<details><summary>List of bypassed features</summary>

n8775761231, n8775726329, n8775792107, n8775806267, n8775818870, n8776630219, n8776648239, n8776085991, n8776103198, n8776302789, n4721482319, n8775971563, n6251479536, n8776720841, n8776769509, n8776490885, n8776515780, n8776529389, n8776533362, n8778535470, n8776547485, n8776547838, n8777036099, n8777045173, n8777049478, n8777126163, n8777129081, n6239123824, n8777160835

</details>

All contribution could be found through hashtag #mbx_singapore_districts
