### ISSUE TITLE
Mapping Protected Area in the US by Mapbox

### ISSUE THREAD

**Issue by vladaboitsik** [mapbox/mapping#384]
### **Background**

As part of on-going work to improve the quality of OpenStreetMap data, Mapbox is going to improve data quality in National Parks of the USA. Here is a link to the [OSM WIki page.](https://wiki.openstreetmap.org/wiki/Organised_Editing_/Activities/_Mapping_National_Parks_in_USA_by_Mapbox)

 Also during the step of establishing workflow and source research team started to map [Daniel Boone National Forest](https://www.fs.usda.gov/dbnf) in Kentucky, and [New River Gorge National Park and Preserve ](https://www.nps.gov/neri/index.htm)in Virginia

### **Details**

We’re interested in almost all natural properties like National Parks/Forests/Reserves and State parks/Recreation areas/Wildlife areas etc.

The team is going to map primarily roads and POIs according to official government sources like USDA ([link](https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/stelprdb5110485.pdf)) or US FS ([link](https://usfs-public.app.box.com/v/bdf-mvum-north))

A certain source will be mentioned in our comment.
  

### **Planning**

California state will be the first where we’ll start to improve OSM data and the first raw or parks are:

-   Ash Creek Wildlife Area
    
-   Red Rock Canyon State Park
    
-   Richardson Grove State Park
    
-   Samuel P. Taylor State Park
    
-   Colusa-Sacramento River State Recreation Area
    
-   George J. Hatfield State Recreation Area
    
-   Woodson Bridge State Recreation Area
    
-   Mountain Home State Forest
    
-   Angeles National Forest
    
-   Cleveland National Forest
    
-   Eldorado National Forest
    

After it is done we’ll make updates on this ticket.

### **Timeframe**

The team started to map in the middle of July

### **Tools**

We will use existing OpenStreetMap editing tools, we will use #hashtag for the project **#mbx_parks_usa**

Editor: iD or JOSM

Satellite Imagery: Bing, Maxar, Esri and any available on ID

### Contact Person

We welcome feedback, suggestions, and insights from local mappers. If you have questions about this work, or a specific edit by our team, please reach out to Vlada at vlada.boitsik@mapbox.com or post a comment in a changeset.

@Zetkun @Andygol @abrohood  @mikelmaron

**Comment by mvexel** [comment]
Do you have a strategy for dealing with trails that are mapped in OSM but do not appear on official NPS maps / materials?

**Comment by vladaboitsik** [comment]
Hi @mvexel !
Unfortunately it's difficult to build some strategy for already mapped roads, because we're not locals and in most cases we can't be sure and rely only on satellite. So we can just fix geometry if needed (dragged nodes for example) or delete if it will be very old import (as a Tiger 2007). But some of the official maps are more detailed and showing private zones, type of the road, what help us to tag roads right

**Comment by MikeTho16** [comment]
Hi @mvexel and @vladaboitsik 

My recommendation:
* If trail was created by something other than an old import, and is not in the official data, leave as is, or possibly tweak to match the Strava Global Heatmap.   
* If trail was created by an old import, and there is no evidence in the official data, overhead imagery, maps on the website for the protected area, or the Strava Global Heatmap, it might be ok to delete.   

Mike

**Comment by vladaboitsik** [comment]
Hi @MikeTho16 !
Yes, it's very similar to what we usually do, thanks!

**Comment by vladaboitsik** [comment]
This ticket is closed because this project was stopped in September and during that period  our team is enriched data for 27 Protected Areas, mostly it was State Parks in California. Almost 15,000 of road features were edited (added or fixed). Our team used an official maps for the areas mostly from National Park Service [website](https://www.nps.gov/index.htm) and from California Department of Parks and Recreation. All the edits could be found by #mbx_parks_usa in OSM
