### ISSUE TITLE
Please, make clear that notes are produced by Mapbox

### ISSUE THREAD

**Issue by matkoniecz** [mapbox/mapping#389]
Typical note: https://www.openstreetmap.org/note/2885624

> Could anyone check access this road please for drivers

Please, make clear that this notes are created by Mapbox employees. 

For example include "Note created based on an anonymous report send to Mapbox"

For comparison https://www.openstreetmap.org/note/2884433 :

> Forwarding anonymous report from #Mapy.cz user, please verify: Right address of Bank nowy is 'Tysiąclecia 3'.
> https://www.openstreetmap.org/way/180106997

PS Would it be possible to include context making this notes actually useful? For example report actual problem - is road fully gone? oneway? under construction? gated? All this situations would be handled in different way by mappers and different methods can be used to confirm note or close it as invalid. Or even include also a link to a photo of situation - that could allow remote fixing in many cases.

Right now usefulness of this notes is low, and amount of them is really large.

PPS Feel free to close this issue once new notes start being marked as coming from Mapbox, problem of missing detail can be discussed in a new issue if needed.

**Comment by vladaboitsik** [comment]
Hi @matkoniecz and @SomeoneElseOSM !
We agree that OSM Notes should have more detailed info to be more useful. Also we'll start to add our project hashtags (ex. #mbx_uk_editing)  for notes to make it more obvious that a note was written by Mapbox workers. As for multiple feedback in UK which is not useful, we'll reconsider our workflow and not leave a note without any useful details which can help to local mapper resolve an issue. 

Thanks for your feedback, we are always open for your comments.

**Comment by matkoniecz** [comment]
`mbx_uk_editing` 

Can you use something less cryptic and actually connecting notes with company? `mapbox` would be much better - editing is self obvious, uk is also obvious from location.

An `mbx` is rather about motorcycle than about Mapbox ( https://en.wikipedia.org/wiki/MBX ).

Please, use recognizable name not some cryptic form not understendable by typical person encountering it.
