### ISSUE TITLE
Please, switch #mbx to #mapbox in codes

### ISSUE THREAD

**Issue by matkoniecz** [mapbox/mapping#390]
Discovered in #389

An `mbx` is rather about motorcycle than about Mapbox ( https://en.wikipedia.org/wiki/MBX ).

People are not going to be able to connect `#mbx_uk_editing` with Mapbox company.

Such codes are cryptic without a good reason, there is no need for that.

It just obscures meaning without a good reason.

**Comment by vladaboitsik** [comment]
@matkoniecz  There's no any problems with tracking our hashtags by using OSM Wiki and it kind of easy thing to do ([example](https://wiki.openstreetmap.org/w/index.php?search=%23mbx_uk_editing&title=Special%3ASearch&go=Go))
