### ISSUE TITLE
Mapping in the Netherlands: use address nodes where appropriate

### ISSUE THREAD

**Issue by jdhoek** [mapbox/mapping#393]
Some of the Mapbox mappers are adding POI's in the Netherlands. Great!

Some important points of feedback:

## POI's should be added to their appropriate address nodes where applicable

In the Netherlands all address nodes are in the database and kept up to date. If you add a new POI, add its tags to the existing address node if it isn't used for something else.

If the address node is already used for another POI, check if that still exists. The POI you are adding may have replaced it.

If the POI already on the address node is still there (they are sharing an address), copy the four `addr:*` tags to your new POI.

## If you have a link to a POI's page on a website, add it

If you have a link to that POI's contact page (like user `KostyaZAyAc` noted in their changeset source), add it to the `website=*` key. This helps users and other mappers.

## Follow the wiki documentation

Don't tag a car dealer who does repairs as `shop=car;car_repair`. Choose the most appropriate one. See [`shop=car`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dcar) for more information.

## Examples

Three examples of Mapbox mappers not following conventions:

* https://www.openstreetmap.org/changeset/116017459
* https://www.openstreetmap.org/changeset/116017851
* https://www.openstreetmap.org/changeset/116053465

**Comment by antonmarkau** [comment]
Hi @jdhoek! This is a very valuable feedback. The team was notified and we will do mapping in the Netherlands according to the info you provided. The edits that were already made will be fixed shortly. 
Thank you for noticing this and sorry for the inconvenience.

**Comment by jdhoek** [comment]
Alright, thank you for your prompt action.

For any questions about mapping in the Netherlands, please use the Dutch subforum: https://forum.openstreetmap.org/viewforum.php?id=12

**Comment by jdhoek** [comment]
(Should you wish to contact the Dutch mapper community, using English on the subforum is not a problem. [This topic](https://forum.openstreetmap.org/viewtopic.php?pid=852061) may be used for any questions you might have.)
