### ISSUE TITLE
What is the license of materials in this repository?

### ISSUE THREAD

**Issue by matkoniecz** [mapbox/mapping#417]
Is it intentionally fully copyrighted?

In such case - is it accepting outside contributions at all, or only Mapbox employees are allowed to submit pull requests to mapping guides?

**Comment by 1ec5** [comment]
Mapbox has dedicated the content of these mapping guides to the public domain under a CC0 public domain dedication. If you click the ℹ️ button at the top of [the homepage](https://labs.mapbox.com/mapping/), a panel slides out with an introduction that mentions this dedication, linking to [this blog post](https://blog.mapbox.com/launching-the-redesigned-openstreetmap-mapping-guides-dc638b630a91) with more details:

![cc0](https://user-images.githubusercontent.com/1231218/171701746-ec345abe-df7a-4623-a2c8-ea8177cdc554.png)

Admittedly it isn’t the most obvious place for this information. The guides are published from the [publisher-production](https://github.com/mapbox/mapping/tree/publisher-production/) branch of this repository.

**Comment by matkoniecz** [comment]
Right, thanks for pointing this out! Such hidden buttons-not-looking-like-buttons are a bit hard to notice.

**Comment by 1ec5** [comment]
> I’m seeking clarification on whether the CC0 dedication also applies to the source code of this repository, e.g., the stylesheets and build scripts.

mapbox/mapping@4cef956c4b45c01e2143dfa85b98b9d25c6a4cc7 clarifies that the source code of this branch is also in the public domain.

**Comment by matkoniecz** [comment]
@1ec5 What about adding LICENSE/LICENCE/COPYING file in root of repo? It is displayed by Github and easy to find and standard way to show license.

See say https://github.com/streetcomplete/StreetComplete 

See #418 - alternative is to have full CC0 license code in COPYING
