### ISSUE TITLE
HOT Mapping: EAST SEPIK, PAPUA NEW GUINEA - 2024 EARTHQUAKE 

### ISSUE THREAD

**Issue by yuliyarazukevichus** [mapbox/mapping#423]
### Project description
As part of volunteer month, Mapbox is participating in the mapping of the HOTOsm project. Employees from across the company participate in this volunteer activity. We will provide training for all participants in this task.

A magnitude **6.9** earthquake struck western Papua New Guinea, causing extensive damage to approximately **1,000** homes in the East Sepik region. With the area already grappling with widespread flooding from earlier in March, urgent assistance is needed. We will be **mapping the buildings** in PNG as part of Humanitarian OpenStreetMap Teams'(HOT) disaster mapping efforts.

### Tasking Manager
[https://tasks.hotosm.org/projects/16593](https://tasks.hotosm.org/projects/16593)

### Mapping sources
- Bing imagery
- ESRI World Imagery

### Task Coverage
- Papua New Guinea, East Sepik Province

### Organization
Activity Organizer: @vladislavkanapliou | [Vladislav Konoplev](https://www.openstreetmap.org/user/Vladislav%20Konoplev)
Activity mapping OSM users: [Vladislav Konoplev](https://www.openstreetmap.org/user/Vladislav%20Konoplev), [jmty8](https://www.openstreetmap.org/user/jmty8), [Natasha_Zhovner](https://www.openstreetmap.org/user/Natasha_Zhovner), [Maryna Makarava](https://www.openstreetmap.org/user/Maryna%20Makarava), [Kate Karol](https://www.openstreetmap.org/user/Kate%20Karol), [SLKa](https://www.openstreetmap.org/user/SLKa), [mirikaaa](https://www.openstreetmap.org/user/mirikaaa), [ohsk](https://www.openstreetmap.org/user/ohsk), [wave9](https://www.openstreetmap.org/user/wave9), [nice2meetu](https://www.openstreetmap.org/user/nice2meetu), [greut-map](https://www.openstreetmap.org/user/greut-map), [StepanKuzmin](https://www.openstreetmap.org/user/StepanKuzmin), [satoe_mbx](https://www.openstreetmap.org/user/satoe_mbx), [chi5224](https://www.openstreetmap.org/user/chi5224),  [Akira Murao](https://www.openstreetmap.org/user/Akira%20Murao), [hidemapper](https://www.openstreetmap.org/user/hidemapper), [YoshiYazawa](https://www.openstreetmap.org/user/YoshiYazawa), [airkei](https://www.openstreetmap.org/user/airkei), [macoril](https://www.openstreetmap.org/user/macoril)

### Timeline
24 - 25 april training and mapping sessions

### Task status
![Screenshot 2024-04-23 101415](https://github.com/mapbox/mapping/assets/52424418/512452e4-ebe0-4dc4-ba5c-3aee5262e38a)
Right now, the task is 22% mapped and 6% validated. So let's help mapping even more buildings using Bing imagery.
![Screenshot 2024-04-23 101419](https://github.com/mapbox/mapping/assets/52424418/79edd0b0-0677-440a-80db-06f2dc490b2e)

### How to reach out
If you have remarks about a specific edit of ours, please drop a comment in the changeset, and we will do our best to respond thoughtfully. Or, you can also:
- email [osm-edit-escalations@mapbox.com](mailto:osm-edit-escalations@mapbox.com) for general questions about Mapbox mapping activities.

**Comment by vladislavkanapliou** [comment]
Due to the finishing of this project and the transition to the review stage, in the process it was decided to select another part of the same [project](https://tasks.hotosm.org/projects/16641)

**Comment by vladislavkanapliou** [comment]
During the 'Mapping Hour' volunteer initiative, a total of 3 dedicated volunteers participated actively in the mapping efforts for the affected area in East Sepik, Papua New Guinea, following the devastating earthquake in 2024.

The collective effort during this initiative resulted in the mapping of **176 buildings** within the earthquake-stricken region. This accomplishment reflects the commitment and hard work of our volunteers who have contributed their time and skills to aid in the disaster response efforts.

For detailed statistics and further insights into this activity, please refer to the corresponding [**dashboard**](https://app.mode.com/mapbox/reports/b1b5bb148cc6/runs/36422483e0a4).

<img width="1440" alt="image" src="https://github.com/mapbox/mapping/assets/43034572/11114886-e7e3-40d3-82f1-ea41ba78d5f9">

**Comment by vladislavkanapliou** [comment]
Thanks all for contribution 🎉
