### ISSUE TITLE
Salgar - validación

### ISSUE THREAD

**Issue by lxbarth** [mapbox/mapping#99]
@Rub21 @samely @calfarome @karitotp @ediyes @dannykath @luisalanya @RichRico @abel801 

Hubo un deslizamiento en Colombia y quiero que ayudemos con la validación.

## Validación en Salgar tareas 13 y 14

[![screen shot 2015-06-19 at 2 01 28 pm](https://cloud.githubusercontent.com/assets/98233/8259594/b206f762-168b-11e5-8a86-e51dd4e5c62a.png)](http://wiki.openstreetmap.org/wiki/2015_Salgar_Colombia_landslide)

http://wiki.openstreetmap.org/wiki/2015_Salgar_Colombia_landslide

**Comment by Rub21** [comment]
@lxbarth , El equipo de Peru ya ha iniciado con este trabajo. :)

**Comment by lxbarth** [comment]
@Rub21 - como vamos?

**Comment by Rub21** [comment]
@lxbarth , Por el momento hemos concluido las tareas, Humberto hara otra revision. En estos dias se estare agregando los numeros corespondientes al trabajo.

**Comment by Rub21** [comment]
Per voice:
@calfarome , podrias actualizar  el numero de objetos osm que el equipo ha decho en Salgar. 
Utilizan esta herrmienta https://github.com/Rub21/counter-edition,

**Comment by hyances** [comment]
Hola Rubén! Gracias, voy a probar el "counter-edition"!

Anexo envío las estadísticas preliminares del equipo Mapbox, entre el 18 de
mayo y 27 de junio usando el script de estadísicas de Pierzen

https://github.com/pierzen/osm-contributor-stats

Gracias por todo su apoyo, tengo pendiente abrir una nueva tarea para
finalizar el mapeo de hazard_type=landslides y realizar ajustes en los
offstes, será más fácil hacerlo así.

Saludos,

Humberto Yances

**Comment by lxbarth** [comment]
@rub21 - what's the status here?

**Comment by Rub21** [comment]
@lxbarth @calfarome @hyances : Estos son los numeros del trabajo en Colombia. 

User | Num OSM Objects | Num Changeset | Num nodes | Num ways | Num relation 
 ---|---|---|---|---|--- 
samely | 20,629 | 143 | 19,410 | 1,219 | 0
dannykath | 12,544 | 161 | 11,420 | 1,124 | 0
abel801 | 12,393 | 157 | 11,512 | 881 | 0
karitotp | 12,197 | 126 | 11,565 | 632 | 0
RichRico | 10,908 | 117 | 10,493 | 413 | 2
calfarome | 7,645 | 221 | 7,057 | 588 | 0
Luis36995 | 5,628 | 123 | 4,875 | 753 | 0
ediyes | 5,385 | 57 | 4,994 | 391 | 0
Rub21 | 3,235 | 38 | 3,024 | 211 | 0
**Total** | 90,564 | 1,143 | 84,350 | 6,212 | 2


Por el momento ya hemos terminado los trabajo en Salgar, si en el futuro  necesitan apoyo, podriamos trabajar un par de dias :)

**Comment by lxbarth** [comment]
:steam_locomotive: w00t!
